VulpesRender: el::LevelHelper Class Reference
el::LevelHelper Class Reference
Static class that contains helper functions for el::Level.
#include <easylogging++.h>
Static Public Member Functions
static base::type::EnumType castToInt (Level level)
Casts level to int, useful for iterating through enum.
static Level castFromInt (base::type::EnumType l)
Casts int(ushort) to level, useful for iterating through enum.
static const char * convertToString (Level level)
Converts level to associated const char*.
static Level convertFromString (const char *levelStr)
Converts from levelStr to Level.
static void forEachLevel (base::type::EnumType *startIndex, const std::function< bool(void)> &fn)
Applies specified function to each level starting from startIndex.
Static Public Attributes
static const base::type::EnumType kMinValid = static_cast<base::type::EnumType>(Level::Trace)
Represents minimum valid level. Useful when iterating through enum.
static const base::type::EnumType kMaxValid = static_cast<base::type::EnumType>(Level::Info)
Represents maximum valid level. This is used internally and you should not need it.
Detailed Description
Static class that contains helper functions for el::Level.
Definition at line 584 of file easylogging++.h.
Member Function Documentation
castFromInt()
static Level el::LevelHelper::castFromInt (base::type::EnumType l) inline static
Casts int(ushort) to level, useful for iterating through enum.
Definition at line 595 of file easylogging++.h.
Referenced by el::Logger::flush(), el::Configurations::hasConfiguration(), el::Logger::initUnflushedCount(), el::Logger::resolveLoggerFormatSpec(), el::Configurations::setGlobally(), and el::Configurations::unsafeSetGlobally().
{
     return static_cast<Level>(l);
   }
castToInt()
static base::type::EnumType el::LevelHelper::castToInt (Level level) inline static
Casts level to int, useful for iterating through enum.
Definition at line 591 of file easylogging++.h.
Referenced by el::base::Writer::initializeLogger().
{
     return static_cast<base::type::EnumType>(level);
   }
convertFromString()
Level el::LevelHelper::convertFromString (const char * levelStr) static
Converts from levelStr to Level.
Parameters
levelStr Upper case string based level. Lower case is also valid but providing upper case is recommended.
Definition at line 78 of file easylogging++.cc.
References el::base::utils::Str::cStringCaseEq(), and el::Unknown.
Referenced by el::Configurations::Parser::parseLine().
{
   for (auto& item : stringToLevelMap) {
     if (base::utils::Str::cStringCaseEq(levelStr, item.levelString)) {
       return item.level;
     }
   }
   return Level::Unknown;
 }
convertToString()
const char * el::LevelHelper::convertToString (Level level) static
Converts level to associated const char*.
Returns
Upper case string based level.
Definition at line 49 of file easylogging++.cc.
References el::Debug, el::Error, el::Fatal, el::Global, el::Info, el::Trace, el::Verbose, and el::Warning.
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), el::base::TypedConfigurations::insertFile(), el::Configuration::log(), el::base::TypedConfigurations::unsafeGetConfigByRef(), el::base::TypedConfigurations::unsafeGetConfigByVal(), and el::base::TypedConfigurations::unsafeValidateFileRolling().
{
   // Do not use switch over strongly typed enums because Intel C++ compilers dont support them yet.
   if (level == Level::Global) return "GLOBAL";
   if (level == Level::Debug) return "DEBUG";
   if (level == Level::Info) return "INFO";
   if (level == Level::Warning) return "WARNING";
   if (level == Level::Error) return "ERROR";
   if (level == Level::Fatal) return "FATAL";
   if (level == Level::Verbose) return "VERBOSE";
   if (level == Level::Trace) return "TRACE";
   return "UNKNOWN";
 }
forEachLevel()
void el::LevelHelper::forEachLevel (base::type::EnumType * startIndex, const std::function< bool(void)> & fn) static
Applies specified function to each level starting from startIndex.
Parameters
startIndex initial value to start the iteration from. This is passed as pointer and is left-shifted so this can be used inside function (fn) to represent current level.
fn function to apply with each level. This bool represent whether or not to stop iterating through levels.
Definition at line 87 of file easylogging++.cc.
References kMaxValid.
Referenced by el::Logger::flush(), el::Configurations::hasConfiguration(), el::Logger::initUnflushedCount(), el::Logger::resolveLoggerFormatSpec(), el::Configurations::setGlobally(), and el::Configurations::unsafeSetGlobally().
{
   base::type::EnumType lIndexMax = LevelHelper::kMaxValid;
   do {
     if (fn()) {
       break;
     }
     *startIndex = static_cast<base::type::EnumType>(*startIndex << 1);
   } while (*startIndex <= lIndexMax);
 }
Member Data Documentation
kMaxValid
const base::type::EnumType el::LevelHelper::kMaxValid = static_cast<base::type::EnumType>(Level::Info) static
Represents maximum valid level. This is used internally and you should not need it.
Definition at line 589 of file easylogging++.h.
Referenced by forEachLevel().
kMinValid
const base::type::EnumType el::LevelHelper::kMinValid = static_cast<base::type::EnumType>(Level::Trace) static
Represents minimum valid level. Useful when iterating through enum.
Definition at line 587 of file easylogging++.h.
Referenced by el::Logger::flush(), el::Configurations::hasConfiguration(), el::Logger::initUnflushedCount(), el::Logger::resolveLoggerFormatSpec(), el::Configurations::setGlobally(), and el::Configurations::unsafeSetGlobally().
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc