VulpesRender: vpr::Instance Class Reference
vpr::Instance Class Reference
Core
Instance is a wrapper around the base Vulkan object that must be initialized first.
#include <Instance.hpp>
Public Member Functions
Instance (bool enable_validation, const VkApplicationInfo *info, GLFWwindow *window)
Instance (bool enable_validation, const VkApplicationInfo *info, GLFWwindow *window, const VprExtensionPack *extensions, const char *const *layers=nullptr, const uint32_t layer_count=0)
~Instance ()
const VkInstance & vkHandle () const noexcept
const VkSurfaceKHR & vkSurface () const noexcept
const PhysicalDevice * GetPhysicalDevice () const noexcept
GLFWwindow * GetGLFWwindow () const noexcept
void CreateSurfaceKHR ()
void DestroySurfaceKHR ()
const bool & ValidationEnabled () const noexcept
Private Member Functions
Instance (const Instance &)=delete
Instance & operator= (const Instance &)=delete
void prepareValidation (const char *const *layers, const uint32_t layer_count)
bool checkValidationSupport (const char *const *layer_names, const uint32_t layer_count) const
void prepareValidationCallbacks ()
void extensionSetup (const VprExtensionPack *extensions)
void prepareRequiredExtensions (const VprExtensionPack *extensions, std::vector< const char *> &output) const
void prepareOptionalExtensions (const VprExtensionPack *extensions, std::vector< const char *> &output) const
void extensionCheck (std::vector< const char *> &extensions, bool throw_on_error) const
void checkOptionalExtensions (std::vector< const char *> &optional_extensions) const
void checkRequiredExtensions (std::vector< const char *> &required_extensions) const
void setupPhysicalDevice ()
Private Attributes
GLFWwindow * window
std::unique_ptr< PhysicalDevice > physicalDevice
std::unique_ptr< SurfaceKHR > surface
VkInstance handle
VkInstanceCreateInfo createInfo
bool validationEnabled
std::vector< const char * > enabledExtensions
VkDebugReportCallbackEXT debugCallback
Detailed Description
Instance is a wrapper around the base Vulkan object that must be initialized first.
The VkInstanceCreateInfo struct passed to the constructor contains information about the current layers enabled, and which Vulkan Instance extensions to enable. By default, this should/will contain extensions required to support the creation of a window surface (VkSurfaceKHR).
This class also contains a Window object, which it is responsible for creating and destroying as necessary, along with a PhysicalDevice object. These can both be retrieved through the relevant methods.
Definition at line 36 of file Instance.hpp.
Constructor & Destructor Documentation
Instance() [1/3]
vpr::Instance::Instance (const Instance &) private delete
Instance() [2/3]
vpr::Instance::Instance (bool enable_validation, const VkApplicationInfo * info, GLFWwindow * window)
Definition at line 13 of file Instance.cpp.
 : Instance(enable_validation, info, _window, nullptr) {}
Instance() [3/3]
vpr::Instance::Instance (bool enable_validation, const VkApplicationInfo * info, GLFWwindow * window, const VprExtensionPack * extensions, const char *const * layers = nullptr, const uint32_t layer_count = 0)
Definition at line 15 of file Instance.cpp.
References createInfo, CreateSurfaceKHR(), extensionSetup(), handle, prepareValidation(), prepareValidationCallbacks(), setupPhysicalDevice(), validationEnabled, and VkAssert.
                                                                                                                                                                                               :
         window(_window), validationEnabled(enable_validation), createInfo{ VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, nullptr, 0, info } {
         extensionSetup(extensions);
         prepareValidation(layers, layer_count);
         VkResult err = vkCreateInstance(&createInfo, nullptr, &handle);
         VkAssert(err);
         if (validationEnabled) {
             prepareValidationCallbacks();
         }
         setupPhysicalDevice();
         CreateSurfaceKHR();
     }
~Instance()
vpr::Instance::~Instance ()
Definition at line 32 of file Instance.cpp.
References debugCallback, DestroySurfaceKHR(), handle, and validationEnabled.
{
         if (debugCallback && validationEnabled) {
             auto func = (PFN_vkDestroyDebugReportCallbackEXT)vkGetInstanceProcAddr(handle, "vkDestroyDebugReportCallbackEXT");
             func(handle, debugCallback, nullptr);
         }
         DestroySurfaceKHR();
         vkDestroyInstance(handle, nullptr);
     }
Member Function Documentation
checkOptionalExtensions()
void vpr::Instance::checkOptionalExtensions (std::vector< const char *> & optional_extensions) const private
Definition at line 229 of file Instance.cpp.
References extensionCheck().
Referenced by prepareOptionalExtensions().
{
         extensionCheck(requested_extensions, false);
     }
checkRequiredExtensions()
void vpr::Instance::checkRequiredExtensions (std::vector< const char *> & required_extensions) const private
Definition at line 225 of file Instance.cpp.
References extensionCheck().
Referenced by prepareRequiredExtensions().
{
         extensionCheck(required_extensions, true);
     }
checkValidationSupport()
bool vpr::Instance::checkValidationSupport (const char *const * layer_names, const uint32_t layer_count) const private
Definition at line 99 of file Instance.cpp.
Referenced by prepareValidation().
{
         uint32_t queried_count = 0;
         vkEnumerateInstanceLayerProperties(&queried_count, nullptr);
         std::vector<VkLayerProperties> queried_layers(queried_count);
         vkEnumerateInstanceLayerProperties(&queried_count, queried_layers.data());
         std::vector<const char*> layers{ layer_names, layer_names + layer_count };
         for (const auto& layer_name : layers) {
             const auto has_layer = [queried_layers](const char* name) {
                 auto found_iter = std::find_if(queried_layers.cbegin(), queried_layers.cend(), [name](const VkLayerProperties& p) {
                     return strcmp(name, p.layerName) == 0;
                 });
                 return found_iter != queried_layers.cend();
             };
             if (!has_layer(layer_name)) {
                 return false;
             }
         }
         return true;
     }
CreateSurfaceKHR()
void vpr::Instance::CreateSurfaceKHR ()
Definition at line 41 of file Instance.cpp.
References LOG_IF, surface, and window.
Referenced by Instance(), and vpr::RecreateSwapchainAndSurface().
{
         LOG_IF(surface, WARNING) << "Attempting to create a SurfaceKHR when one might already exist: if it does, this will probably cause swapchain errors!";
         surface = std::make_unique<SurfaceKHR>(this, window);
     }
DestroySurfaceKHR()
void vpr::Instance::DestroySurfaceKHR ()
Definition at line 46 of file Instance.cpp.
References surface.
Referenced by vpr::RecreateSwapchainAndSurface(), and ~Instance().
{
         surface.reset();
     }
extensionCheck()
void vpr::Instance::extensionCheck (std::vector< const char *> & extensions, bool throw_on_error) const private
Definition at line 193 of file Instance.cpp.
References LOG.
Referenced by checkOptionalExtensions(), and checkRequiredExtensions().
{
         uint32_t queried_extension_count = 0;
         vkEnumerateInstanceExtensionProperties(nullptr, &queried_extension_count, nullptr);
         std::vector<VkExtensionProperties> queried_extensions(queried_extension_count);
         vkEnumerateInstanceExtensionProperties(nullptr, &queried_extension_count, queried_extensions.data());
         const auto has_extension = [queried_extensions](const char* name) {
             auto req_found = std::find_if(queried_extensions.cbegin(), queried_extensions.cend(), [name](const VkExtensionProperties& properties) {
                 return strcmp(properties.extensionName, name) == 0;
             });
             return req_found != queried_extensions.cend();
         };
         auto iter = extensions.begin();
         while (iter != extensions.end()) {
             if (!has_extension(*iter)) {
                 if (throw_on_error) {
                     LOG(ERROR) << "Required extension \"" << *iter << "\" not supported for instance in construction!";
                     throw std::runtime_error("Instance does not support a required extension!");
                 }
                 else {
                     LOG(WARNING) << "Extension with name \"" << *iter << "\" requested but isn't supported. Removing from list attached to Instance's creation info.";
                     extensions.erase(iter++);
                 }
             }
             else {
                 ++iter;
             }
         }
     }
extensionSetup()
void vpr::Instance::extensionSetup (const VprExtensionPack * extensions) private
Definition at line 137 of file Instance.cpp.
References createInfo, enabledExtensions, vpr::VprExtensionPack::OptionalExtensionNames, prepareOptionalExtensions(), and prepareRequiredExtensions().
Referenced by Instance().
{
         std::vector<const char*> all_extensions;
         prepareRequiredExtensions(extensions, all_extensions);
         if (extensions != nullptr) {
             if (extensions->OptionalExtensionNames != nullptr) {
                 prepareOptionalExtensions(extensions, all_extensions);
             }
         }
         enabledExtensions = all_extensions;
         createInfo.ppEnabledExtensionNames = enabledExtensions.data();
         createInfo.enabledExtensionCount = static_cast<uint32_t>(enabledExtensions.size());
     }
GetGLFWwindow()
GLFWwindow * vpr::Instance::GetGLFWwindow () const noexcept
Definition at line 66 of file Instance.cpp.
References window.
Referenced by vpr::Swapchain::setParameters().
{
         return window;
     }
GetPhysicalDevice()
const PhysicalDevice * vpr::Instance::GetPhysicalDevice () const noexcept
Definition at line 62 of file Instance.cpp.
References physicalDevice.
{
         return physicalDevice.get();
     }
operator=()
Instance& vpr::Instance::operator= (const Instance &) private delete
prepareOptionalExtensions()
void vpr::Instance::prepareOptionalExtensions (const VprExtensionPack * extensions, std::vector< const char *> & output) const private
Definition at line 181 of file Instance.cpp.
References checkOptionalExtensions(), vpr::VprExtensionPack::OptionalExtensionCount, and vpr::VprExtensionPack::OptionalExtensionNames.
Referenced by extensionSetup().
{
         std::vector<const char*> optional_extensions{ extensions->OptionalExtensionNames,
             extensions->OptionalExtensionNames + extensions->OptionalExtensionCount };
         checkOptionalExtensions(optional_extensions);
         for(auto&& elem : optional_extensions) {
             output.emplace_back(std::move(elem));
         }
     }
prepareRequiredExtensions()
void vpr::Instance::prepareRequiredExtensions (const VprExtensionPack * extensions, std::vector< const char *> & output) const private
Definition at line 152 of file Instance.cpp.
References checkRequiredExtensions(), vpr::VprExtensionPack::RequiredExtensionCount, vpr::VprExtensionPack::RequiredExtensionNames, and validationEnabled.
Referenced by extensionSetup().
{
         uint32_t req_ext_cnt = 0;
         const char** req_ext_names = nullptr;
         req_ext_names = glfwGetRequiredInstanceExtensions(&req_ext_cnt);
         std::vector<const char*> glfw_required_extensions{ req_ext_names, req_ext_names + req_ext_cnt };
         for (auto&& elem : glfw_required_extensions) {
             output.emplace_back(std::move(elem));
         }
         if (extensions != nullptr) {
             if (extensions->RequiredExtensionNames != nullptr) {
                 std::vector<const char*> input_required_extensions{ extensions->RequiredExtensionNames,
                     extensions->RequiredExtensionNames + extensions->RequiredExtensionCount };
                 for (auto&& elem : input_required_extensions) {
                     output.emplace_back(std::move(elem));
                 }
             }
         }
         if (validationEnabled) {
             output.emplace_back(VK_EXT_DEBUG_REPORT_EXTENSION_NAME);
         }
         checkRequiredExtensions(output);
     }
prepareValidation()
void vpr::Instance::prepareValidation (const char *const * layers, const uint32_t layer_count) private
Definition at line 77 of file Instance.cpp.
References checkValidationSupport(), createInfo, and validationEnabled.
Referenced by Instance().
{
         if (!validationEnabled) {
             assert(!layers && (layer_count == 0));
             createInfo.ppEnabledLayerNames = nullptr;
             createInfo.enabledLayerCount = 0;
         }
         else {
             if (layers && (layer_count != 0)) {
                 if (!checkValidationSupport(layers, layer_count)) {
                     throw std::runtime_error("Tried to enable Vulkan validation layers, but they're unsupported on the current system!");
                 }
                 createInfo.ppEnabledLayerNames = layers;
                 createInfo.enabledLayerCount = layer_count;
             }
             else {
                 constexpr static const char* const default_layer = "VK_LAYER_LUNARG_standard_validation";
                 createInfo.ppEnabledLayerNames = &default_layer;
                 createInfo.enabledLayerCount = 1;
             }
         }
     }
prepareValidationCallbacks()
void vpr::Instance::prepareValidationCallbacks () private
Definition at line 123 of file Instance.cpp.
References debugCallback, handle, VkAssert, and vpr::VkDebugCallbackFn().
Referenced by Instance().
{
         const VkDebugReportCallbackCreateInfoEXT create_info{
             VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT,
             nullptr,
             VK_DEBUG_REPORT_INFORMATION_BIT_EXT | VK_DEBUG_REPORT_ERROR_BIT_EXT | VK_DEBUG_REPORT_WARNING_BIT_EXT | VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT | VK_DEBUG_REPORT_DEBUG_BIT_EXT,
             VkDebugCallbackFn
         };
         auto func = (PFN_vkCreateDebugReportCallbackEXT)vkGetInstanceProcAddr(handle, "vkCreateDebugReportCallbackEXT");
         assert(func);
         VkResult result = func(handle, &create_info, nullptr, &debugCallback);
         VkAssert(result);
     }
setupPhysicalDevice()
void vpr::Instance::setupPhysicalDevice () private
Definition at line 233 of file Instance.cpp.
References physicalDevice, and vkHandle().
Referenced by Instance().
{
         physicalDevice = std::make_unique<PhysicalDevice>(vkHandle());
     }
ValidationEnabled()
const bool & vpr::Instance::ValidationEnabled () const noexcept
Definition at line 50 of file Instance.cpp.
References validationEnabled.
Referenced by vpr::Device::setupValidation().
{
         return validationEnabled;
     }
vkHandle()
const VkInstance & vpr::Instance::vkHandle () const noexcept
Definition at line 54 of file Instance.cpp.
References handle.
Referenced by setupPhysicalDevice(), vpr::SurfaceKHR::SurfaceKHR(), and vpr::SurfaceKHR::~SurfaceKHR().
{
         return handle;
     }
vkSurface()
const VkSurfaceKHR & vpr::Instance::vkSurface () const noexcept
Definition at line 58 of file Instance.cpp.
References surface.
Referenced by vpr::Swapchain::Recreate(), vpr::Swapchain::setupCreateInfo(), and vpr::Device::VerifyPresentationSupport().
{
         return surface->vkHandle();
     }
Member Data Documentation
createInfo
VkInstanceCreateInfo vpr::Instance::createInfo private
Definition at line 72 of file Instance.hpp.
Referenced by extensionSetup(), Instance(), and prepareValidation().
debugCallback
VkDebugReportCallbackEXT vpr::Instance::debugCallback private
Definition at line 77 of file Instance.hpp.
Referenced by prepareValidationCallbacks(), and ~Instance().
enabledExtensions
std::vector<const char*> vpr::Instance::enabledExtensions private
Definition at line 74 of file Instance.hpp.
Referenced by extensionSetup().
handle
VkInstance vpr::Instance::handle private
Definition at line 71 of file Instance.hpp.
Referenced by Instance(), prepareValidationCallbacks(), vkHandle(), and ~Instance().
physicalDevice
std::unique_ptr<PhysicalDevice> vpr::Instance::physicalDevice private
Definition at line 69 of file Instance.hpp.
Referenced by GetPhysicalDevice(), and setupPhysicalDevice().
surface
std::unique_ptr<SurfaceKHR> vpr::Instance::surface private
Definition at line 70 of file Instance.hpp.
Referenced by CreateSurfaceKHR(), DestroySurfaceKHR(), and vkSurface().
validationEnabled
bool vpr::Instance::validationEnabled private
Definition at line 73 of file Instance.hpp.
Referenced by Instance(), prepareRequiredExtensions(), prepareValidation(), ValidationEnabled(), and ~Instance().
window
GLFWwindow* vpr::Instance::window mutable private
Definition at line 68 of file Instance.hpp.
Referenced by CreateSurfaceKHR(), and GetGLFWwindow().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/core/Instance.hpp
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/core/Instance.cpp