VulpesRender: vpr::TransferPool Class Reference
vpr::TransferPool Class Reference
Command
Transfer pool is just a specialized command pool with certain flags pre-set, along with a fence protecting the transfer submission and a mutex for thread safety.
#include <TransferPool.hpp>
Public Member Functions
TransferPool (const Device *_parent)
TransferPool (const Device *_parent, const size_t &num_buffers)
~TransferPool ()
const VkCommandBuffer & Begin () const
Returns the command buffer associated with this pool, call VkBeginCommandBuffer before doing so.
const VkCommandBuffer * BeginAll () const
Begins all command buffers attached to this object.
void Submit () const
Calls VkEndCommandBuffer on this object's command buffer, then proceeds to submit it.
void SubmitWait (const VkSemaphore wait_semaphore, const VkPipelineStageFlags wait_flags) const
Submits but waits for the given semaphore to be signalled.
void SubmitAll () const
Submits all command buffers contained by this transfer pool.
void AllocateCmdBuffers (const uint32_t &num_buffers, const VkCommandBufferLevel &cmd_buffer_level)
void ResetCmdPool (const VkCommandPoolResetFlagBits &command_pool_reset_flag_bits=VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT)
Resets the entire command pool via a call to VkResetCommandPool.
void ResetCmdBuffer (const size_t &idx, const VkCommandBufferResetFlagBits &command_buffer_reset_flag_bits=VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT)
Resets the single command buffer at the given index.
void FreeCommandBuffers ()
Frees the memory used for all command buffers in this pool, which effectively "deletes" them, unlike resetting a single command buffer or even resetting the entire pool.
const VkCommandPool & vkHandle () const noexcept
VkCommandBuffer & operator[] (const size_t &idx)
VkCommandBuffer & GetCmdBuffer (const size_t &idx)
const VkCommandBuffer * GetCommandBuffers (const size_t &offset) const
Gets a range of command buffers, starting at the given offset.
VkCommandBuffer StartSingleCmdBuffer ()
void EndSingleCmdBuffer (VkCommandBuffer &cmd_buffer, const VkQueue &queue)
const size_t size () const noexcept
const VkCommandBuffer * Data () const noexcept
Protected Member Functions
void createPool ()
void createFence ()
void completeTransfer () const
Just a convienience method wrapping the command code required to reset the fence, reset the command buffer(s), and make sure to unlock the transfer mutex.
void destroy ()
Protected Attributes
std::mutex transferMutex
VkFence fence
VkQueue queue
std::vector< VkCommandBuffer > cmdBuffers
VkCommandPool handle
const Device * parent
Private Member Functions
TransferPool (TransferPool &&other)=delete
TransferPool & operator= (TransferPool &&other)=delete
Detailed Description
Transfer pool is just a specialized command pool with certain flags pre-set, along with a fence protecting the transfer submission and a mutex for thread safety.
This will be reset after each submission.
Definition at line 19 of file TransferPool.hpp.
Constructor & Destructor Documentation
TransferPool() [1/3]
vpr::TransferPool::TransferPool (TransferPool && other) private delete
TransferPool() [2/3]
vpr::TransferPool::TransferPool (const Device * _parent)
Definition at line 14 of file TransferPool.cpp.
References vpr::CommandPool::AllocateCmdBuffers(), createFence(), and createPool().
                                                      : CommandPool(_parent), queue(_parent->TransferQueue(0)) {
         createPool();
         AllocateCmdBuffers(1, VK_COMMAND_BUFFER_LEVEL_PRIMARY);
         createFence();
     }
TransferPool() [3/3]
vpr::TransferPool::TransferPool (const Device * _parent, const size_t & num_buffers)
Definition at line 20 of file TransferPool.cpp.
References vpr::CommandPool::AllocateCmdBuffers(), createFence(), and createPool().
                                                                                  : CommandPool(_parent), queue(_parent->TransferQueue(0)) {
         createPool();
         AllocateCmdBuffers(static_cast<uint32_t>(num_buffers), VK_COMMAND_BUFFER_LEVEL_PRIMARY);
         createFence();
     }
~TransferPool()
vpr::TransferPool::~TransferPool ()
Definition at line 26 of file TransferPool.cpp.
References fence, vpr::CommandPool::parent, and vpr::Device::vkHandle().
{
         if (fence != VK_NULL_HANDLE) {
             vkDestroyFence(parent->vkHandle(), fence, nullptr);
             fence = VK_NULL_HANDLE;
         }
     }
Member Function Documentation
AllocateCmdBuffers()
void vpr::CommandPool::AllocateCmdBuffers (const uint32_t & num_buffers, const VkCommandBufferLevel & cmd_buffer_level) inherited
Definition at line 51 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers, vpr::CommandPool::handle, LOG, vpr::CommandPool::parent, vpr::vk_command_buffer_allocate_info_base, VkAssert, and vpr::Device::vkHandle().
Referenced by TransferPool().
{
         if (!cmdBuffers.empty()) {
             return;
         }
         cmdBuffers.resize(num_buffers);
         VkCommandBufferAllocateInfo alloc_info = vk_command_buffer_allocate_info_base;
         alloc_info.commandPool = handle;
         alloc_info.commandBufferCount = num_buffers;
         alloc_info.level = cmd_buffer_level;
         VkResult result = vkAllocateCommandBuffers(parent->vkHandle(), &alloc_info, cmdBuffers.data());
         LOG(INFO) << std::to_string(num_buffers) << " command buffers allocated for command pool " << handle;
         VkAssert(result);
     }
Begin()
const VkCommandBuffer & vpr::TransferPool::Begin () const
Returns the command buffer associated with this pool, call VkBeginCommandBuffer before doing so.
Locks the mutex as well.
Definition at line 33 of file TransferPool.cpp.
References vpr::CommandPool::cmdBuffers, and transferMutex.
{
         transferMutex.lock();
         VkCommandBufferBeginInfo beginInfo = {};
         beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
         beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT | VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT;
         beginInfo.pInheritanceInfo = nullptr;
         vkBeginCommandBuffer(cmdBuffers.front(), &beginInfo);
         return cmdBuffers.front();
     }
BeginAll()
const VkCommandBuffer * vpr::TransferPool::BeginAll () const
Begins all command buffers attached to this object.
Intended for use when one plans to record transfer commands until multiple buffers in parallel, then submit all these transfers at once.
Definition at line 46 of file TransferPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         assert(cmdBuffers.size() > 1);
         constexpr static VkCommandBufferBeginInfo begin_info{
             VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
             nullptr,
             VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT | VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT,
             nullptr
         };
         for(auto& buff : cmdBuffers) {
             vkBeginCommandBuffer(buff, &begin_info);
         }
         return cmdBuffers.data();
     }
completeTransfer()
void vpr::TransferPool::completeTransfer () const protected
Just a convienience method wrapping the command code required to reset the fence, reset the command buffer(s), and make sure to unlock the transfer mutex.
Definition at line 141 of file TransferPool.cpp.
References fence, vpr::CommandPool::handle, vpr::CommandPool::parent, transferMutex, VkAssert, and vpr::Device::vkHandle().
Referenced by Submit(), SubmitAll(), and SubmitWait().
{
         VkResult result = vkWaitForFences(parent->vkHandle(), 1, &fence, VK_TRUE, static_cast<uint64_t>(2e9));
         VkAssert(result);
         result = vkResetFences(parent->vkHandle(), 1, &fence);
         vkResetCommandPool(parent->vkHandle(), handle, VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT);
         transferMutex.unlock();
     }
createFence()
void vpr::TransferPool::createFence () protected
Definition at line 136 of file TransferPool.cpp.
References fence, vpr::CommandPool::parent, vpr::vk_fence_create_info_base, VkAssert, and vpr::Device::vkHandle().
Referenced by TransferPool().
{
         VkResult result = vkCreateFence(parent->vkHandle(), &vk_fence_create_info_base, nullptr, &fence);
         VkAssert(result);
     }
createPool()
void vpr::TransferPool::createPool () protected
Definition at line 128 of file TransferPool.cpp.
References vpr::CommandPool::handle, vpr::CommandPool::parent, vpr::Device::QueueFamilyIndices, vpr::vkQueueFamilyIndices::Transfer, vpr::vk_command_pool_info_base, VkAssert, and vpr::Device::vkHandle().
Referenced by TransferPool().
{
         VkCommandPoolCreateInfo create_info = vk_command_pool_info_base;
         create_info.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT | VK_COMMAND_POOL_CREATE_TRANSIENT_BIT;
         create_info.queueFamilyIndex = parent->QueueFamilyIndices.Transfer;
         VkResult result = vkCreateCommandPool(parent->vkHandle(), &create_info, nullptr, &handle);
         VkAssert(result);
     }
Data()
const VkCommandBuffer * vpr::CommandPool::Data () const noexcept inherited
Definition at line 135 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         return cmdBuffers.data();
     }
destroy()
void vpr::CommandPool::destroy () protected inherited
Definition at line 40 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers, vpr::CommandPool::FreeCommandBuffers(), vpr::CommandPool::handle, LOG, vpr::CommandPool::parent, and vpr::Device::vkHandle().
Referenced by vpr::CommandPool::~CommandPool().
{
         if (!cmdBuffers.empty()) {
             FreeCommandBuffers();
         }
         if (handle != VK_NULL_HANDLE) {
             vkDestroyCommandPool(parent->vkHandle(), handle, nullptr);
             LOG(INFO) << "Command Pool " << handle << " destroyed.";
             handle = VK_NULL_HANDLE;
         }
     }
EndSingleCmdBuffer()
void vpr::CommandPool::EndSingleCmdBuffer (VkCommandBuffer & cmd_buffer, const VkQueue & queue) inherited
Definition at line 114 of file CommandPool.cpp.
References VkAssert.
Referenced by vpr::Buffer::CopyTo(), and vpr::Image::TransitionLayout().
{
         VkResult result = vkEndCommandBuffer(cmd_buffer);
         VkAssert(result);
         VkSubmitInfo submitInfo = {};
         submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
         submitInfo.commandBufferCount = 1;
         submitInfo.pCommandBuffers = &cmd_buffer;
         result = vkQueueSubmit(queue, 1, &submitInfo, VK_NULL_HANDLE);
         VkAssert(result);
         vkQueueWaitIdle(queue);
         result = vkResetCommandBuffer(cmd_buffer, VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT);
         VkAssert(result);
     }
FreeCommandBuffers()
void vpr::CommandPool::FreeCommandBuffers () inherited
Frees the memory used for all command buffers in this pool, which effectively "deletes" them, unlike resetting a single command buffer or even resetting the entire pool.
This will require calling AllocateCmdBuffers again, as it ultimately resets the object into its base state.
Definition at line 67 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers, vpr::CommandPool::handle, LOG, vpr::CommandPool::parent, and vpr::Device::vkHandle().
Referenced by vpr::CommandPool::destroy().
{
         vkFreeCommandBuffers(parent->vkHandle(), handle, static_cast<uint32_t>(cmdBuffers.size()), cmdBuffers.data());
         LOG(INFO) << std::to_string(cmdBuffers.size()) << " command buffers freed.";
         cmdBuffers.clear();
         cmdBuffers.shrink_to_fit();
     }
GetCmdBuffer()
VkCommandBuffer & vpr::CommandPool::GetCmdBuffer (const size_t & idx) inherited
Definition at line 90 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         return cmdBuffers[idx];
     }
GetCommandBuffers()
const VkCommandBuffer * vpr::CommandPool::GetCommandBuffers (const size_t & offset) const inherited
Gets a range of command buffers, starting at the given offset.
Definition at line 82 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         return &cmdBuffers[offset];
     }
operator=()
TransferPool& vpr::TransferPool::operator= (TransferPool && other) private delete
operator[]()
VkCommandBuffer & vpr::CommandPool::operator[] (const size_t & idx) inherited
Definition at line 86 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         return cmdBuffers[idx];
     }
ResetCmdBuffer()
void vpr::CommandPool::ResetCmdBuffer (const size_t & idx, const VkCommandBufferResetFlagBits & command_buffer_reset_flag_bits = VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT) inherited
Resets the single command buffer at the given index.
Uses VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT by default, which returns the resources allocated by the Vulkan implementation for this particular command buffer back to the parent pool. Be careful using this in a pool that doesn't have other buffers reset: this can cause memory fragmentation in the command buffer memory resources, which will increase the time it takes for the Vulkan implementation to find a suitable memory location to use (or it will have to allocate more memory).
Parameters
command_buffer_reset_flag_bits - Only current options are VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT, the default, or no flags (thus, no resources released)
Definition at line 74 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         vkResetCommandBuffer(cmdBuffers[idx], command_buffer_reset_flag_bits);
     }
ResetCmdPool()
void vpr::CommandPool::ResetCmdPool (const VkCommandPoolResetFlagBits & command_pool_reset_flag_bits = VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT) inherited
Resets the entire command pool via a call to VkResetCommandPool.
Uses VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT by default, which releases all resources that the Vulkan implementation internally allocates. This may take time, and may require re-allocation upon reinitialization but also prevents memory fragmentation when using command pools for quite some time.
Parameters
command_pool_reset_flag_bits - Only current options are VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT, the default, or no flags (thus, no resources released)
Definition at line 14 of file CommandPool.cpp.
References vpr::CommandPool::handle, vpr::CommandPool::parent, and vpr::Device::vkHandle().
{
         vkResetCommandPool(parent->vkHandle(), handle, command_pool_reset_flags);
     }
size()
const size_t vpr::CommandPool::size () const noexcept inherited
Definition at line 131 of file CommandPool.cpp.
References vpr::CommandPool::cmdBuffers.
{
         return cmdBuffers.size();
     }
StartSingleCmdBuffer()
VkCommandBuffer vpr::CommandPool::StartSingleCmdBuffer () inherited
Definition at line 94 of file CommandPool.cpp.
References vpr::CommandPool::handle, vpr::CommandPool::parent, and vpr::Device::vkHandle().
Referenced by vpr::Buffer::CopyTo(), and vpr::Image::TransitionLayout().
{
         VkCommandBufferAllocateInfo allocInfo = {};
         allocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
         allocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
         allocInfo.commandPool = handle;
         allocInfo.commandBufferCount = 1;
         VkCommandBuffer commandBuffer;
         vkAllocateCommandBuffers(parent->vkHandle(), &allocInfo, &commandBuffer);
         VkCommandBufferBeginInfo beginInfo = {};
         beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
         beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
         beginInfo.pInheritanceInfo = nullptr;
         vkBeginCommandBuffer(commandBuffer, &beginInfo);
         return commandBuffer;
     }
Submit()
void vpr::TransferPool::Submit () const
Calls VkEndCommandBuffer on this object's command buffer, then proceeds to submit it.
This transfer will wait on the VkFence object attached to this pool, resetting the owned command buffer once done and unlocks the mutex.
Definition at line 62 of file TransferPool.cpp.
References vpr::CommandPool::cmdBuffers, completeTransfer(), fence, queue, and VkAssert.
{
         VkResult result = vkEndCommandBuffer(cmdBuffers.front());
         VkAssert(result);
         VkSubmitInfo submitInfo = {};
         submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
         submitInfo.commandBufferCount = 1;
         submitInfo.pCommandBuffers = cmdBuffers.data();
         result = vkQueueSubmit(queue, 1, &submitInfo, fence);
         VkAssert(result);
         completeTransfer();
     }
SubmitAll()
void vpr::TransferPool::SubmitAll () const
Submits all command buffers contained by this transfer pool.
Waits on a fence and uses a mutex, just like the method for singular command buffers.
Definition at line 96 of file TransferPool.cpp.
References vpr::CommandPool::cmdBuffers, completeTransfer(), fence, queue, transferMutex, and VkAssert.
{
         // Unlike the other singular submit technique, we expect
         // that other threads have been accessing members of this
         // class (the retrieved buffers) up to this point, so we
         // delay locking the mutex until before we submit.
         transferMutex.lock();
         for(auto& buff : cmdBuffers) {
             vkEndCommandBuffer(buff);
         }
         const VkSubmitInfo submit_info{
             VK_STRUCTURE_TYPE_SUBMIT_INFO,
             nullptr,
             0,
             nullptr,
             nullptr,
             static_cast<uint32_t>(cmdBuffers.size()),
             cmdBuffers.data(),
             0,
             nullptr
         };
         VkResult result = vkQueueSubmit(queue, 1, &submit_info, fence);
         VkAssert(result);
         completeTransfer();
     }
SubmitWait()
void vpr::TransferPool::SubmitWait (const VkSemaphore wait_semaphore, const VkPipelineStageFlags wait_flags) const
Submits but waits for the given semaphore to be signalled.
Definition at line 79 of file TransferPool.cpp.
References vpr::CommandPool::cmdBuffers, completeTransfer(), fence, queue, and VkAssert.
{
         VkResult result = vkEndCommandBuffer(cmdBuffers.front());
         VkAssert(result);
         VkSubmitInfo submit_info{
             VK_STRUCTURE_TYPE_SUBMIT_INFO, nullptr,
             1, &semaphore, &wait_flags,
             1, &cmdBuffers.front(),
             0, nullptr };
         result = vkQueueSubmit(queue, 1, &submit_info, fence);
         VkAssert(result);
         completeTransfer();
     }
vkHandle()
const VkCommandPool & vpr::CommandPool::vkHandle () const noexcept inherited
Definition at line 78 of file CommandPool.cpp.
References vpr::CommandPool::handle.
{
         return handle;
     }
Member Data Documentation
cmdBuffers
std::vector<VkCommandBuffer> vpr::CommandPool::cmdBuffers protected inherited
Definition at line 77 of file CommandPool.hpp.
Referenced by vpr::CommandPool::AllocateCmdBuffers(), Begin(), BeginAll(), vpr::CommandPool::CommandPool(), vpr::CommandPool::Data(), vpr::CommandPool::destroy(), vpr::CommandPool::FreeCommandBuffers(), vpr::CommandPool::GetCmdBuffer(), vpr::CommandPool::GetCommandBuffers(), vpr::CommandPool::operator=(), vpr::CommandPool::operator[](), vpr::CommandPool::ResetCmdBuffer(), vpr::CommandPool::size(), Submit(), SubmitAll(), and SubmitWait().
fence
VkFence vpr::TransferPool::fence protected
Definition at line 64 of file TransferPool.hpp.
Referenced by completeTransfer(), createFence(), Submit(), SubmitAll(), SubmitWait(), and ~TransferPool().
handle
VkCommandPool vpr::CommandPool::handle protected inherited
Definition at line 78 of file CommandPool.hpp.
Referenced by vpr::CommandPool::AllocateCmdBuffers(), vpr::CommandPool::CommandPool(), completeTransfer(), createPool(), vpr::CommandPool::destroy(), vpr::CommandPool::FreeCommandBuffers(), vpr::CommandPool::operator=(), vpr::CommandPool::ResetCmdPool(), vpr::CommandPool::StartSingleCmdBuffer(), and vpr::CommandPool::vkHandle().
parent
const Device* vpr::CommandPool::parent protected inherited
Definition at line 79 of file CommandPool.hpp.
Referenced by vpr::CommandPool::AllocateCmdBuffers(), vpr::CommandPool::CommandPool(), completeTransfer(), createFence(), createPool(), vpr::CommandPool::destroy(), vpr::CommandPool::FreeCommandBuffers(), vpr::CommandPool::operator=(), vpr::CommandPool::ResetCmdPool(), vpr::CommandPool::StartSingleCmdBuffer(), and ~TransferPool().
queue
VkQueue vpr::TransferPool::queue protected
Definition at line 65 of file TransferPool.hpp.
Referenced by Submit(), SubmitAll(), and SubmitWait().
transferMutex
std::mutex vpr::TransferPool::transferMutex mutable protected
Definition at line 63 of file TransferPool.hpp.
Referenced by Begin(), completeTransfer(), and SubmitAll().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/command/TransferPool.hpp
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/command/TransferPool.cpp