VulpesRender: el::base::utils::DateTime Class Reference
el::base::utils::DateTime Class Reference
Contains utilities for cross-platform date/time. This class make use of el::base::utils::Str.
#include <easylogging++.h>
Static Public Member Functions
static void gettimeofday (struct timeval *tv)
Cross platform gettimeofday for Windows and unix platform.
static std::string getDateTime (const char *format, const base::SubsecondPrecision *ssPrec)
Gets current date and time with a subsecond part.
static std::string timevalToString (struct timeval tval, const char *format, const el::base::SubsecondPrecision *ssPrec)
Converts timeval (struct from ctime) to string using specified format and subsecond precision.
static base::type::string_t formatTime (unsigned long long time, base::TimestampUnit timestampUnit)
Formats time to get unit accordingly, units like second if > 1000 or minutes if > 60000 etc.
static unsigned long long getTimeDifference (const struct timeval &endTime, const struct timeval &startTime, base::TimestampUnit timestampUnit)
Gets time difference in milli/micro second depending on timestampUnit.
Static Private Member Functions
static struct ::tm * buildTimeInfo (struct timeval *currTime, struct ::tm *timeInfo)
static char * parseFormat (char *buf, std::size_t bufSz, const char *format, const struct tm *tInfo, std::size_t msec, const base::SubsecondPrecision *ssPrec)
Detailed Description
Contains utilities for cross-platform date/time. This class make use of el::base::utils::Str.
Definition at line 1234 of file easylogging++.h.
Member Function Documentation
buildTimeInfo()
struct::tm * el::base::utils::DateTime::buildTimeInfo (struct timeval * currTime, struct ::tm * timeInfo) static private
Definition at line 1148 of file easylogging++.cc.
References ELPP_UNUSED, elpptime, elpptime_r, and elpptime_s.
{
 #if ELPP_OS_UNIX
   time_t rawTime = currTime->tv_sec;
   ::elpptime_r(&rawTime, timeInfo);
   return timeInfo;
 #else
 #  if ELPP_COMPILER_MSVC
   ELPP_UNUSED(currTime);
   time_t t;
 #    if defined(_USE_32BIT_TIME_T)
   _time32(&t);
 #    else
   _time64(&t);
 #    endif
   elpptime_s(timeInfo, &t);
   return timeInfo;
 #  else
   // For any other compilers that don't have CRT warnings issue e.g, MinGW or TDM GCC- we use different method
   time_t rawTime = currTime->tv_sec;
   struct tm* tmInf = elpptime(&rawTime);
   *timeInfo = *tmInf;
   return timeInfo;
 #  endif  // ELPP_COMPILER_MSVC
 #endif  // ELPP_OS_UNIX
 }
formatTime()
base::type::string_t el::base::utils::DateTime::formatTime (unsigned long long time, base::TimestampUnit timestampUnit) static
Formats time to get unit accordingly, units like second if > 1000 or minutes if > 60000 etc.
Definition at line 1117 of file easylogging++.cc.
References el::base::consts::kTimeFormats, and el::base::consts::kTimeFormatsCount.
Referenced by el::base::PErrorWriter::~PErrorWriter().
{
   base::type::EnumType start = static_cast<base::type::EnumType>(timestampUnit);
   const base::type::char_t* unit = base::consts::kTimeFormats[start].unit;
   for (base::type::EnumType i = start; i < base::consts::kTimeFormatsCount - 1; ++i) {
     if (time <= base::consts::kTimeFormats[i].value) {
       break;
     }
     if (base::consts::kTimeFormats[i].value == 1000.0f && time / 1000.0f < 1.9f) {
       break;
     }
     time /= static_cast<decltype(time)>(base::consts::kTimeFormats[i].value);
     unit = base::consts::kTimeFormats[i + 1].unit;
   }
   base::type::stringstream_t ss;
   ss << time << " " << unit;
   return ss.str();
 }
getDateTime()
std::string el::base::utils::DateTime::getDateTime (const char * format, const base::SubsecondPrecision * ssPrec) static
Gets current date and time with a subsecond part.
Parameters
format User provided date/time format
ssPrec A pointer to base::SubsecondPrecision from configuration (non-null)
Returns
string based date time in specified format.
Definition at line 1100 of file easylogging++.cc.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::TypedConfigurations::resolveFilename().
{
   struct timeval currTime;
   gettimeofday(&currTime);
   return timevalToString(currTime, format, ssPrec);
 }
getTimeDifference()
unsigned long long el::base::utils::DateTime::getTimeDifference (const struct timeval & endTime, const struct timeval & startTime, base::TimestampUnit timestampUnit) static
Gets time difference in milli/micro second depending on timestampUnit.
Definition at line 1135 of file easylogging++.cc.
References el::base::Microsecond.
Referenced by el::base::PErrorWriter::~PErrorWriter().
{
   if (timestampUnit == base::TimestampUnit::Microsecond) {
     return static_cast<unsigned long long>(static_cast<unsigned long long>(1000000 * endTime.tv_sec + endTime.tv_usec) -
                                            static_cast<unsigned long long>(1000000 * startTime.tv_sec + startTime.tv_usec));
   }
   // milliseconds
   auto conv = [](const struct timeval& tim) {
     return static_cast<unsigned long long>((tim.tv_sec * 1000) + (tim.tv_usec / 1000));
   };
   return static_cast<unsigned long long>(conv(endTime) - conv(startTime));
 }
gettimeofday()
void el::base::utils::DateTime::gettimeofday (struct timeval * tv) static
Cross platform gettimeofday for Windows and unix platform.
This can be used to determine current microsecond.
For unix system it uses gettimeofday(timeval*, timezone*) and for Windows, a seperate implementation is provided
Parameters
[in,out] tv Pointer that gets updated
Definition at line 1073 of file easylogging++.cc.
Referenced by el::base::PErrorWriter::~PErrorWriter().
{
 #if ELPP_OS_WINDOWS
   if (tv != nullptr) {
 #  if ELPP_COMPILER_MSVC || defined(_MSC_EXTENSIONS)
     const unsigned __int64 delta_ = 11644473600000000Ui64;
 #  else
     const unsigned __int64 delta_ = 11644473600000000ULL;
 #  endif  // ELPP_COMPILER_MSVC || defined(_MSC_EXTENSIONS)
     const double secOffSet = 0.000001;
     const unsigned long usecOffSet = 1000000;
     FILETIME fileTime;
     GetSystemTimeAsFileTime(&fileTime);
     unsigned __int64 present = 0;
     present |= fileTime.dwHighDateTime;
     present = present << 32;
     present |= fileTime.dwLowDateTime;
     present /= 10;  // mic-sec
     // Subtract the difference
     present -= delta_;
     tv->tv_sec = static_cast<long>(present * secOffSet);
     tv->tv_usec = static_cast<long>(present % usecOffSet);
   }
 #else
   ::gettimeofday(tv, nullptr);
 #endif  // ELPP_OS_WINDOWS
 }
parseFormat()
char * el::base::utils::DateTime::parseFormat (char * buf, std::size_t bufSz, const char * format, const struct tm * tInfo, std::size_t msec, const base::SubsecondPrecision * ssPrec) static private
Definition at line 1174 of file easylogging++.cc.
References el::base::utils::Str::addToBuff(), el::base::utils::Str::convertAndAddToBuff(), el::base::consts::kAm, el::base::consts::kDays, el::base::consts::kDaysAbbrev, el::base::consts::kFormatSpecifierChar, el::base::consts::kMonths, el::base::consts::kMonthsAbbrev, el::base::consts::kPm, el::base::consts::kYearBase, and el::base::SubsecondPrecision::m_width.
{
   const char* bufLim = buf + bufSz;
   for (; *format; ++format) {
     if (*format == base::consts::kFormatSpecifierChar) {
       switch (*++format) {
       case base::consts::kFormatSpecifierChar:  // Escape
         break;
       case '\0':  // End
         --format;
         break;
       case 'd':  // Day
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_mday, 2, buf, bufLim);
         continue;
       case 'a':  // Day of week (short)
         buf = base::utils::Str::addToBuff(base::consts::kDaysAbbrev[tInfo->tm_wday], buf, bufLim);
         continue;
       case 'A':  // Day of week (long)
         buf = base::utils::Str::addToBuff(base::consts::kDays[tInfo->tm_wday], buf, bufLim);
         continue;
       case 'M':  // month
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_mon + 1, 2, buf, bufLim);
         continue;
       case 'b':  // month (short)
         buf = base::utils::Str::addToBuff(base::consts::kMonthsAbbrev[tInfo->tm_mon], buf, bufLim);
         continue;
       case 'B':  // month (long)
         buf = base::utils::Str::addToBuff(base::consts::kMonths[tInfo->tm_mon], buf, bufLim);
         continue;
       case 'y':  // year (two digits)
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_year + base::consts::kYearBase, 2, buf, bufLim);
         continue;
       case 'Y':  // year (four digits)
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_year + base::consts::kYearBase, 4, buf, bufLim);
         continue;
       case 'h':  // hour (12-hour)
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_hour % 12, 2, buf, bufLim);
         continue;
       case 'H':  // hour (24-hour)
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_hour, 2, buf, bufLim);
         continue;
       case 'm':  // minute
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_min, 2, buf, bufLim);
         continue;
       case 's':  // second
         buf = base::utils::Str::convertAndAddToBuff(tInfo->tm_sec, 2, buf, bufLim);
         continue;
       case 'z':  // subsecond part
       case 'g':
         buf = base::utils::Str::convertAndAddToBuff(msec, ssPrec->m_width, buf, bufLim);
         continue;
       case 'F':  // AM/PM
         buf = base::utils::Str::addToBuff((tInfo->tm_hour >= 12) ? base::consts::kPm : base::consts::kAm, buf, bufLim);
         continue;
       default:
         continue;
       }
     }
     if (buf == bufLim) break;
     *buf++ = *format;
   }
   return buf;
 }
timevalToString()
std::string el::base::utils::DateTime::timevalToString (struct timeval tval, const char * format, const el::base::SubsecondPrecision * ssPrec) static
Converts timeval (struct from ctime) to string using specified format and subsecond precision.
Definition at line 1106 of file easylogging++.cc.
References el::base::SubsecondPrecision::m_offset.
{
   struct ::tm timeInfo;
   buildTimeInfo(&tval, &timeInfo);
   const int kBuffSize = 30;
   char buff_[kBuffSize] = "";
   parseFormat(buff_, kBuffSize, format, &timeInfo, static_cast<std::size_t>(tval.tv_usec / ssPrec->m_offset),
               ssPrec);
   return std::string(buff_);
 }
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc