VulpesRender: vpr::PhysicalDeviceImpl Class Reference
vpr::PhysicalDeviceImpl Class Reference
Public Member Functions
PhysicalDeviceImpl (const VkInstance &instance)
PhysicalDeviceImpl (PhysicalDeviceImpl &&other) noexcept
PhysicalDeviceImpl & operator= (PhysicalDeviceImpl &&other) noexcept
~PhysicalDeviceImpl ()
uint32_t GetMemoryTypeIdx (const uint32_t &type_bitfield, const VkMemoryPropertyFlags &property_flags, VkBool32 *memory_type_found) const noexcept
void getAttributes () noexcept
void retrieveQueueFamilyProperties () noexcept
uint32_t GetQueueFamilyIndex (const VkQueueFlagBits &queue_bits) const noexcept
Public Attributes
VkPhysicalDeviceProperties Properties
VkPhysicalDeviceFeatures Features
VkPhysicalDeviceMemoryProperties MemoryProperties
VkPhysicalDeviceSubgroupProperties SubgroupProperties
std::vector< VkQueueFamilyProperties > queueFamilyProperties
VkPhysicalDevice handle
Private Member Functions
PhysicalDeviceImpl (const PhysicalDeviceImpl &)=delete
PhysicalDeviceImpl & operator= (const PhysicalDeviceImpl &)=delete
Detailed Description
Definition at line 99 of file PhysicalDevice.cpp.
Constructor & Destructor Documentation
PhysicalDeviceImpl() [1/3]
vpr::PhysicalDeviceImpl::PhysicalDeviceImpl (const PhysicalDeviceImpl &) private delete
PhysicalDeviceImpl() [2/3]
vpr::PhysicalDeviceImpl::PhysicalDeviceImpl (const VkInstance & instance)
Definition at line 124 of file PhysicalDevice.cpp.
References getAttributes(), vpr::GetBestAvailPhysicalDevice(), handle, vpr::PopulatePhysicalDeviceMap(), and retrieveQueueFamilyProperties().
{
         if (physicalDevices.empty()) {
             PopulatePhysicalDeviceMap(instance);
         }
         handle = GetBestAvailPhysicalDevice();
         getAttributes();
         retrieveQueueFamilyProperties();
     }
PhysicalDeviceImpl() [3/3]
vpr::PhysicalDeviceImpl::PhysicalDeviceImpl (PhysicalDeviceImpl && other) noexcept
Definition at line 136 of file PhysicalDevice.cpp.
                                                                                : Properties(std::move(other.Properties)), Features(std::move(other.Features)), MemoryProperties(std::move(other.MemoryProperties)),
         queueFamilyProperties(std::move(other.queueFamilyProperties)), SubgroupProperties(std::move(other.SubgroupProperties)),
         handle(std::move(other.handle)) { other.handle = VK_NULL_HANDLE; }
~PhysicalDeviceImpl()
vpr::PhysicalDeviceImpl::~PhysicalDeviceImpl ()
Definition at line 150 of file PhysicalDevice.cpp.
{
     }
Member Function Documentation
getAttributes()
void vpr::PhysicalDeviceImpl::getAttributes () noexcept
Definition at line 188 of file PhysicalDevice.cpp.
Referenced by PhysicalDeviceImpl().
{
         vkGetPhysicalDeviceProperties(handle, &Properties);
         vkGetPhysicalDeviceFeatures(handle, &Features);
         vkGetPhysicalDeviceMemoryProperties(handle, &MemoryProperties);
         /*
         SubgroupProperties = VkPhysicalDeviceSubgroupProperties{ VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES, nullptr };
         VkPhysicalDeviceProperties2 properties2{ VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2, &SubgroupProperties, Properties };
         vkGetPhysicalDeviceProperties2(handle, &properties2);
         */
     }
GetMemoryTypeIdx()
uint32_t vpr::PhysicalDeviceImpl::GetMemoryTypeIdx (const uint32_t & type_bitfield, const VkMemoryPropertyFlags & property_flags, VkBool32 * memory_type_found) const noexcept
Definition at line 153 of file PhysicalDevice.cpp.
References LOG, and MemoryProperties.
{
         auto bitfield = type_bitfield;
         const uint32_t num_memory_types = MemoryProperties.memoryTypeCount;
         for (uint32_t i = 0; i < num_memory_types; ++i) {
             if (bitfield & 1) {
                 // check if property flags match
                 if ((MemoryProperties.memoryTypes[i].propertyFlags & property_flags) == property_flags) {
                     if (memory_type_found) {
                         *memory_type_found = true;
                     }
                     return i;
                 }
             }
             bitfield >>= 1;
         }
         LOG(WARNING) << "Failed to find suitable memory type index.";
         return std::numeric_limits<uint32_t>::max();
     }
GetQueueFamilyIndex()
uint32_t vpr::PhysicalDeviceImpl::GetQueueFamilyIndex (const VkQueueFlagBits & queue_bits) const noexcept
Definition at line 211 of file PhysicalDevice.cpp.
References LOG.
{
         if (bitfield & VK_QUEUE_COMPUTE_BIT) {
             for (uint32_t i = 0; i < static_cast<uint32_t>(queueFamilyProperties.size()); ++i) {
                 if ((queueFamilyProperties[i].queueFlags & bitfield) && ((queueFamilyProperties[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) == 0)) {
                     return i;
                 }
             }
         }
         if (bitfield & VK_QUEUE_TRANSFER_BIT) {
             for (uint32_t i = 0; i < static_cast<uint32_t>(queueFamilyProperties.size()); ++i) {
                 if ((queueFamilyProperties[i].queueFlags & bitfield) && ((queueFamilyProperties[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) == 0) && ((queueFamilyProperties[i].queueFlags & VK_QUEUE_COMPUTE_BIT) == 0)) {
                     return i;
                 }
             }
         }
         for (uint32_t i = 0; i < static_cast<uint32_t>(queueFamilyProperties.size()); ++i) {
             if (queueFamilyProperties[i].queueFlags & bitfield) {
                 return i;
             }
         }
         LOG(WARNING) << "Failed to find desired queue family with given flags.";
         return std::numeric_limits<uint32_t>::max();
     }
operator=() [1/2]
PhysicalDeviceImpl& vpr::PhysicalDeviceImpl::operator= (const PhysicalDeviceImpl &) private delete
operator=() [2/2]
PhysicalDeviceImpl & vpr::PhysicalDeviceImpl::operator= (PhysicalDeviceImpl && other) noexcept
Definition at line 140 of file PhysicalDevice.cpp.
References Features, handle, MemoryProperties, Properties, queueFamilyProperties, and SubgroupProperties.
{
         Properties = std::move(other.Properties);
         Features = std::move(other.Features);
         MemoryProperties = std::move(other.MemoryProperties);
         queueFamilyProperties = std::move(other.queueFamilyProperties);
         SubgroupProperties = std::move(other.SubgroupProperties);
         handle = std::move(other.handle);
         return *this;
     }
retrieveQueueFamilyProperties()
void vpr::PhysicalDeviceImpl::retrieveQueueFamilyProperties () noexcept
Definition at line 199 of file PhysicalDevice.cpp.
Referenced by PhysicalDeviceImpl().
{
         uint32_t queue_family_cnt = 0;
         vkGetPhysicalDeviceQueueFamilyProperties(handle, &queue_family_cnt, nullptr);
         queueFamilyProperties.resize(queue_family_cnt);
         vkGetPhysicalDeviceQueueFamilyProperties(handle, &queue_family_cnt, queueFamilyProperties.data());
     }
Member Data Documentation
Features
VkPhysicalDeviceFeatures vpr::PhysicalDeviceImpl::Features
Definition at line 117 of file PhysicalDevice.cpp.
Referenced by operator=().
handle
VkPhysicalDevice vpr::PhysicalDeviceImpl::handle
Definition at line 121 of file PhysicalDevice.cpp.
Referenced by operator=(), and PhysicalDeviceImpl().
MemoryProperties
VkPhysicalDeviceMemoryProperties vpr::PhysicalDeviceImpl::MemoryProperties
Definition at line 118 of file PhysicalDevice.cpp.
Referenced by GetMemoryTypeIdx(), and operator=().
Properties
VkPhysicalDeviceProperties vpr::PhysicalDeviceImpl::Properties
Definition at line 116 of file PhysicalDevice.cpp.
Referenced by operator=().
queueFamilyProperties
std::vector<VkQueueFamilyProperties> vpr::PhysicalDeviceImpl::queueFamilyProperties
Definition at line 120 of file PhysicalDevice.cpp.
Referenced by operator=().
SubgroupProperties
VkPhysicalDeviceSubgroupProperties vpr::PhysicalDeviceImpl::SubgroupProperties
Definition at line 119 of file PhysicalDevice.cpp.
Referenced by operator=().
The documentation for this class was generated from the following file:
src/core/PhysicalDevice.cpp