VulpesRender: vpr::MemoryBlock Class Reference
vpr::MemoryBlock Class Reference
Allocation
A MemoryBlock is a large contiguous region of Vulkan memory of a uniform type (device local, host coherent, host visible, etc) that other objects bind to subregions of.
#include <MemoryBlock.hpp>
Public Member Functions
MemoryBlock (VkDevice parent_device)
~MemoryBlock ()
The object should be destroyed via the Destroy method before the destructor is called, but this will call the Destroy method if it hasn't been, and will log a warning that this was done.
void Init (VkDeviceMemory &new_memory, const VkDeviceSize &new_size)
void Destroy ()
Cleans up resources and prepares object to be safely destroyed.
bool operator< (const MemoryBlock &other)
VkDeviceSize AvailableMemory () const noexcept
const VkDeviceMemory & Memory () const noexcept
ValidationCode Validate () const
Verifies integrity of memory by checking all contained suballocations for integrity and correctness.
bool RequestSuballocation (const VkDeviceSize &buffer_image_granularity, const VkDeviceSize &allocation_size, const VkDeviceSize &allocation_alignment, SuballocationType allocation_type, SuballocationRequest *dest_request)
Fills the given SuballocationRequest struct with information about where to place the suballocation, and returns whether or not it succeeded in finding a spot to put the requested suballocation.
bool VerifySuballocation (const VkDeviceSize &buffer_image_granularity, const VkDeviceSize &allocation_size, const VkDeviceSize &allocation_alignment, SuballocationType allocation_type, const suballocationList::const_iterator &dest_suballocation_location, VkDeviceSize *dest_offset) const
Verifies that requested suballocation can be added to this object, and sets dest_offset to reflect offset of this now-inserted suballocation.
bool Empty () const
void Allocate (const SuballocationRequest &request, const SuballocationType &allocation_type, const VkDeviceSize &allocation_size)
Performs the actual allocation, once "request" has been checked and made valid.
void Free (const Allocation *memory_to_free)
Frees memory in region specified (i.e frees/destroys a suballocation)
void Map (const Allocation *alloc_being_mapped, const VkDeviceSize &size_of_map, const VkDeviceSize &offset_to_map_at, void **destination_address)
When we map a suballocation, we are mapping a sub-region of the larger memory object it is bound to.
void Unmap ()
As mentioned for the Map method, due to VkMapMemory functions we must make sure only one sub-region of an object is unmapped at a time, thus requiring the parent block to oversee the mapping/unmapping + using a mutex for thread safety.
VkDeviceSize LargestAvailRegion () const noexcept
suballocation_iterator_t begin ()
suballocation_iterator_t end ()
const_suballocation_iterator_t begin () const
const_suballocation_iterator_t end () const
const_suballocation_iterator_t cbegin () const
const_suballocation_iterator_t cend () const
avail_suballocation_iterator_t avail_begin ()
avail_suballocation_iterator_t avail_end ()
const_avail_suballocation_iterator_t avail_begin () const
const_avail_suballocation_iterator_t avail_end () const
const_avail_suballocation_iterator_t avail_cbegin () const
const_avail_suballocation_iterator_t avail_cend () const
Public Attributes
VkDeviceSize Size { std::numeric_limits<VkDeviceSize>::max() }
suballocationList Suballocations
uint32_t MemoryTypeIdx { std::numeric_limits<uint32_t>::max() }
Protected Member Functions
void freeSuballocation (const suballocationList::iterator &item_to_free)
Changes the item pointed to by the iterator to be a free type, then adds the now-available size to availSize and increments freeCount.
void mergeFreeWithNext (const suballocationList::iterator &item_to_merge)
Effectively reduces fragmentation by merging two free allocations that are adjacent in memory into one larger allocation.
void insertFreeSuballocation (const suballocationList::iterator &item_to_insert)
Registers a free suballocation, inserting it into the proper location to keep the sorting intact (via std::lower_bound)
void removeFreeSuballocation (const suballocationList::iterator &item_to_remove)
Removes a free suballocation, usually indicating that it is about to be made active and used by an object (or that it has been merged with another free suballocation)
Protected Attributes
VkDevice parentDevice
std::mutex guardMutex
VkDeviceSize availSize { std::numeric_limits<VkDeviceSize>::max() }
uint32_t freeCount { std::numeric_limits<uint32_t>::max() }
VkDeviceMemory memory { VK_NULL_HANDLE }
std::vector< suballocationList::iterator > availSuballocations
This vector stores iterators that can be used to locate suballocations in this object's suballocationList.
Private Member Functions
MemoryBlock (const MemoryBlock &)=delete
MemoryBlock & operator= (const MemoryBlock &)=delete
Friends
class DebugVisualization
struct DebugVisualizationImpl
Detailed Description
A MemoryBlock is a large contiguous region of Vulkan memory of a uniform type (device local, host coherent, host visible, etc) that other objects bind to subregions of.
This should never be directly accessed by any client code: it is managed and interfaced to by other objects, and several of these of each type can exist (occurs when a memory block is fully used, until no more memory available).
Definition at line 19 of file MemoryBlock.hpp.
Constructor & Destructor Documentation
MemoryBlock() [1/2]
vpr::MemoryBlock::MemoryBlock (const MemoryBlock &) private delete
MemoryBlock() [2/2]
vpr::MemoryBlock::MemoryBlock (VkDevice parent_device)
Definition at line 88 of file MemoryBlock.cpp.
 : parentDevice(parent), availSize(0), freeCount(0), memory(VK_NULL_HANDLE), Size(0) {}
~MemoryBlock()
vpr::MemoryBlock::~MemoryBlock ()
The object should be destroyed via the Destroy method before the destructor is called, but this will call the Destroy method if it hasn't been, and will log a warning that this was done.
Definition at line 90 of file MemoryBlock.cpp.
References Destroy(), and memory.
{
         if (memory != VK_NULL_HANDLE) {
             LOG(WARNING) << "Memory block destructor called before memory block's memory was destroyed.";
             Destroy();
         }
     }
Member Function Documentation
Allocate()
void vpr::MemoryBlock::Allocate (const SuballocationRequest & request, const SuballocationType & allocation_type, const VkDeviceSize & allocation_size)
Performs the actual allocation, once "request" has been checked and made valid.
Definition at line 354 of file MemoryBlock.cpp.
References availSize, vpr::Free, freeCount, vpr::SuballocationRequest::FreeSuballocation, insertFreeSuballocation(), vpr::SuballocationRequest::Offset, removeFreeSuballocation(), and Suballocations.
{
         assert(request.FreeSuballocation != Suballocations.cend());
         Suballocation& suballoc = *request.FreeSuballocation;
         assert(suballoc.Type == SuballocationType::Free);
         const VkDeviceSize padding_begin = request.Offset - suballoc.Offset;
         const VkDeviceSize padding_end = suballoc.Size - padding_begin - allocation_size;
         removeFreeSuballocation(request.FreeSuballocation);
         suballoc.Offset = request.Offset;
         suballoc.Size = allocation_size;
         suballoc.Type = allocation_type;
         // if there's any remaining memory after this allocation, register it
         if (padding_end) {
             Suballocation padding_suballoc{ request.Offset + allocation_size, padding_end, SuballocationType::Free };
             auto next_iter = request.FreeSuballocation;
             ++next_iter;
             {
                 const auto insert_iter = Suballocations.insert(next_iter, padding_suballoc);
                 // insert_iter returns iterator giving location of inserted item
                 insertFreeSuballocation(insert_iter);
             }
         }
         // if there's any remaining memory before the allocation, register it.
         if (padding_begin) {
             Suballocation padding_suballoc{ request.Offset - padding_begin, padding_begin, SuballocationType::Free };
             auto next_iter = request.FreeSuballocation;
             {
                 const auto insert_iter = Suballocations.insert(next_iter, padding_suballoc);
                 insertFreeSuballocation(insert_iter);
             }
         }
         --freeCount;
         if (padding_begin > 0) {
             ++freeCount;
         }
         if (padding_end > 0) {
             ++freeCount;
         }
         availSize -= allocation_size;
     }
avail_begin() [1/2]
avail_suballocation_iterator_t vpr::MemoryBlock::avail_begin ()
Definition at line 461 of file MemoryBlock.cpp.
References availSuballocations.
{
         return availSuballocations.begin();
     }
avail_begin() [2/2]
const_avail_suballocation_iterator_t vpr::MemoryBlock::avail_begin () const
Definition at line 469 of file MemoryBlock.cpp.
References availSuballocations.
{
         return availSuballocations.begin();
     }
avail_cbegin()
const_avail_suballocation_iterator_t vpr::MemoryBlock::avail_cbegin () const
Definition at line 477 of file MemoryBlock.cpp.
References availSuballocations.
{
         return availSuballocations.cbegin();
     }
avail_cend()
const_avail_suballocation_iterator_t vpr::MemoryBlock::avail_cend () const
Definition at line 481 of file MemoryBlock.cpp.
References availSuballocations.
{
         return availSuballocations.cend();;
     }
avail_end() [1/2]
avail_suballocation_iterator_t vpr::MemoryBlock::avail_end ()
Definition at line 465 of file MemoryBlock.cpp.
References availSuballocations.
{
         return availSuballocations.end();
     }
avail_end() [2/2]
const_avail_suballocation_iterator_t vpr::MemoryBlock::avail_end () const
Definition at line 473 of file MemoryBlock.cpp.
References availSuballocations.
{
         return availSuballocations.end();;
     }
AvailableMemory()
VkDeviceSize vpr::MemoryBlock::AvailableMemory () const noexcept
Definition at line 137 of file MemoryBlock.cpp.
References availSize.
{
         return availSize;
     }
begin() [1/2]
suballocation_iterator_t vpr::MemoryBlock::begin ()
Definition at line 437 of file MemoryBlock.cpp.
References Suballocations.
{
         return Suballocations.begin();
     }
begin() [2/2]
const_suballocation_iterator_t vpr::MemoryBlock::begin () const
Definition at line 445 of file MemoryBlock.cpp.
References Suballocations.
{
         return Suballocations.begin();
     }
cbegin()
const_suballocation_iterator_t vpr::MemoryBlock::cbegin () const
Definition at line 453 of file MemoryBlock.cpp.
References Suballocations.
{
         return Suballocations.cbegin();
     }
cend()
const_suballocation_iterator_t vpr::MemoryBlock::cend () const
Definition at line 457 of file MemoryBlock.cpp.
References Suballocations.
{
         return Suballocations.cend();
     }
Destroy()
void vpr::MemoryBlock::Destroy ()
Cleans up resources and prepares object to be safely destroyed.
Should be called before the destructor is called, but for safety's sake the destructor will also call this.
Definition at line 117 of file MemoryBlock.cpp.
References availSuballocations, memory, parentDevice, Size, Suballocations, and vpr::VERBOSE_LOGGING.
Referenced by ~MemoryBlock().
{
         if (!Suballocations.empty()) {
             Suballocations.clear();
         }
         if (!availSuballocations.empty()) {
             availSuballocations.clear();
         }
         LOG_IF(VERBOSE_LOGGING, INFO) << "MemoryBlock memory freed, memory handle was: " << memory << " and size was " << std::to_string(Size * 1e-6) << "mb";
         vkFreeMemory(parentDevice, memory, nullptr);
         memory = VK_NULL_HANDLE;
     }
Empty()
bool vpr::MemoryBlock::Empty () const
Definition at line 350 of file MemoryBlock.cpp.
References freeCount, and Suballocations.
{
         return (Suballocations.size() == 1) && (freeCount == 1);
     }
end() [1/2]
suballocation_iterator_t vpr::MemoryBlock::end ()
Definition at line 441 of file MemoryBlock.cpp.
References Suballocations.
{
         return Suballocations.end();
     }
end() [2/2]
const_suballocation_iterator_t vpr::MemoryBlock::end () const
Definition at line 449 of file MemoryBlock.cpp.
References Suballocations.
{
         return Suballocations.end();
     }
Free()
void vpr::MemoryBlock::Free (const Allocation * memory_to_free)
Frees memory in region specified (i.e frees/destroys a suballocation)
Definition at line 405 of file MemoryBlock.cpp.
References freeSuballocation(), vpr::Allocation::Offset(), Suballocations, Validate(), vpr::VALIDATE_MEMORY, and vpr::VALIDATION_PASSED.
{
         for (auto iter = Suballocations.begin(); iter != Suballocations.end(); ++iter) {
             auto& suballoc = *iter;
             if (suballoc.Offset == memory_to_free->Offset()) {
                 freeSuballocation(iter);
                 if (VALIDATE_MEMORY) {
                     auto vcode = Validate();
                     if (vcode != ValidationCode::VALIDATION_PASSED) {
                         LOG(ERROR) << "Validation of memory failed: " << vcode;
                         throw std::runtime_error("Validation of memory failed");
                     }
                 }
                 return;
             }
         }
     }
freeSuballocation()
void vpr::MemoryBlock::freeSuballocation (const suballocationList::iterator & item_to_free) protected
Changes the item pointed to by the iterator to be a free type, then adds the now-available size to availSize and increments freeCount.
This method may also call mergeFreeWithNext, insertFreeSuballocation, and removeFreeSuballocation if adjacent suballocations are free or can be merged with the now-free allocation passed in.
Definition at line 497 of file MemoryBlock.cpp.
References availSize, vpr::Free, freeCount, insertFreeSuballocation(), mergeFreeWithNext(), removeFreeSuballocation(), vpr::Suballocation::Size, Suballocations, and vpr::Suballocation::Type.
Referenced by Free().
{
         Suballocation& suballoc = *item_to_free;
         suballoc.Type = SuballocationType::Free;
         ++freeCount;
         availSize += suballoc.Size;
         bool merge_next = false, merge_prev = false;
         auto next_iter = item_to_free;
         ++next_iter;
         if ((next_iter != Suballocations.cend()) && (next_iter->Type == SuballocationType::Free)) {
             merge_next = true;
         }
         auto prev_iter = item_to_free;
         if (prev_iter != Suballocations.cbegin()) {
             --prev_iter;
             if (prev_iter->Type == SuballocationType::Free) {
                 merge_prev = true;
             }
         }
         if (merge_next) {
             removeFreeSuballocation(next_iter);
             mergeFreeWithNext(item_to_free);
         }
         if (merge_prev) {
             removeFreeSuballocation(prev_iter);
             mergeFreeWithNext(prev_iter);
             insertFreeSuballocation(prev_iter);
         }
         else {
             insertFreeSuballocation(item_to_free);
         }
     }
Init()
void vpr::MemoryBlock::Init (VkDeviceMemory & new_memory, const VkDeviceSize & new_size)
Parameters
new_memory This is the handle that this block will take ownership of.
new_size total size of this memory block.
Definition at line 97 of file MemoryBlock.cpp.
References availSize, availSuballocations, vpr::Free, freeCount, memory, Size, Suballocations, and vpr::VERBOSE_LOGGING.
{
         assert(memory == VK_NULL_HANDLE);
         memory = new_memory;
         Size = new_size;
         freeCount = 1;
         availSize = new_size;
         Suballocations.clear();
         availSuballocations.clear();
         // note/create suballocation defining our singular free region.
         Suballocations.emplace_back(Suballocation{ 0, new_size, SuballocationType::Free });
         // add location of that suballocation to mapping vector
         auto suballoc_iter = Suballocations.end();
         --suballoc_iter;
         availSuballocations.emplace_back(suballoc_iter);
         LOG_IF(VERBOSE_LOGGING, INFO) << "Created new MemoryBlock with size " << std::to_string(Size * 1e-6) << "mb ";
     }
insertFreeSuballocation()
void vpr::MemoryBlock::insertFreeSuballocation (const suballocationList::iterator & item_to_insert) protected
Registers a free suballocation, inserting it into the proper location to keep the sorting intact (via std::lower_bound)
Definition at line 536 of file MemoryBlock.cpp.
References availSuballocations, guardMutex, and vpr::MinSuballocationSizeToRegister.
Referenced by Allocate(), and freeSuballocation().
{
         std::lock_guard<std::mutex> alloc_guard(guardMutex);
         if (item_to_insert->Size >= MinSuballocationSizeToRegister) {
             if (availSuballocations.empty()) {
                 availSuballocations.emplace_back(item_to_insert);
             }
             else {
                 // find correct position ot insert "item_to_insert" and do so.
                 auto insert_iter = std::lower_bound(availSuballocations.begin(), availSuballocations.end(), item_to_insert, suballocIterCompare());
                 availSuballocations.insert(insert_iter, item_to_insert);
             }
         }
     }
LargestAvailRegion()
VkDeviceSize vpr::MemoryBlock::LargestAvailRegion () const noexcept
Definition at line 433 of file MemoryBlock.cpp.
References availSuballocations, and Size.
{
         return (*availSuballocations.front()).Size;
     }
Map()
void vpr::MemoryBlock::Map (const Allocation * alloc_being_mapped, const VkDeviceSize & size_of_map, const VkDeviceSize & offset_to_map_at, void ** destination_address)
When we map a suballocation, we are mapping a sub-region of the larger memory object it is bound to.
We cannot perform another map until this sub-region is unmapped. Thus, suballocations actually call their parent's mapping method. This lets us use a mutex to lock off access to this block's VkDeviceMemory object until the memory is unmapped.
Definition at line 422 of file MemoryBlock.cpp.
References guardMutex, memory, vpr::Allocation::Offset(), parentDevice, and VkAssert.
{
         std::lock_guard<std::mutex> mapping_lock(guardMutex);
         VkResult result = vkMapMemory(parentDevice, memory, alloc_being_mapped->Offset() + offset_to_map_at, size_of_map, 0, destination_address);
         VkAssert(result);
     }
Memory()
const VkDeviceMemory & vpr::MemoryBlock::Memory () const noexcept
Definition at line 141 of file MemoryBlock.cpp.
References memory.
{
         return memory;
     }
mergeFreeWithNext()
void vpr::MemoryBlock::mergeFreeWithNext (const suballocationList::iterator & item_to_merge) protected
Effectively reduces fragmentation by merging two free allocations that are adjacent in memory into one larger allocation.
Definition at line 485 of file MemoryBlock.cpp.
References vpr::Free, freeCount, guardMutex, and Suballocations.
Referenced by freeSuballocation().
{
         auto next_iter = item_to_merge;
         ++next_iter;
         assert(next_iter != Suballocations.cend());
         assert(next_iter->Type == SuballocationType::Free);
         // add item to merge's size to the size of the object after it
         item_to_merge->Size += next_iter->Size;
         --freeCount;
         std::lock_guard<std::mutex> alloc_guard(guardMutex);
         Suballocations.erase(next_iter);
     }
operator<()
bool vpr::MemoryBlock::operator< (const MemoryBlock & other)
Definition at line 133 of file MemoryBlock.cpp.
References availSize.
{
         return (availSize < other.availSize);
     }
operator=()
MemoryBlock& vpr::MemoryBlock::operator= (const MemoryBlock &) private delete
removeFreeSuballocation()
void vpr::MemoryBlock::removeFreeSuballocation (const suballocationList::iterator & item_to_remove) protected
Removes a free suballocation, usually indicating that it is about to be made active and used by an object (or that it has been merged with another free suballocation)
Definition at line 551 of file MemoryBlock.cpp.
References availSuballocations, guardMutex, and vpr::MinSuballocationSizeToRegister.
Referenced by Allocate(), and freeSuballocation().
{
         std::lock_guard<std::mutex> alloc_guard(guardMutex);
         if (item_to_remove->Size >= MinSuballocationSizeToRegister) {
             auto remove_iter = std::remove(availSuballocations.begin(), availSuballocations.end(), item_to_remove);
             assert(remove_iter != availSuballocations.cend());
             availSuballocations.erase(remove_iter);
         }
     }
RequestSuballocation()
bool vpr::MemoryBlock::RequestSuballocation (const VkDeviceSize & buffer_image_granularity, const VkDeviceSize & allocation_size, const VkDeviceSize & allocation_alignment, SuballocationType allocation_type, SuballocationRequest * dest_request)
Fills the given SuballocationRequest struct with information about where to place the suballocation, and returns whether or not it succeeded in finding a spot to put the requested suballocation.
Usually, a failure means we'll just try another memory block (and ultimately, consider creating a new one)
Definition at line 231 of file MemoryBlock.cpp.
References availSize, availSuballocations, vpr::SuballocationRequest::FreeSuballocation, vpr::SuballocationRequest::Offset, and VerifySuballocation().
{
         if ((availSize < allocation_size) || availSuballocations.empty()) {
             // not enough space in this allocation object
             return false;
         }
         const size_t numFreeSuballocs = availSuballocations.size();
         // use lower_bound to find location of avail suballocation
         size_t avail_idx = std::numeric_limits<size_t>::max();
         for (auto iter = availSuballocations.cbegin(); iter != availSuballocations.cend(); ++iter) {
             if ((*iter)->Size > allocation_size) {
                 avail_idx = iter - availSuballocations.cbegin();
                 break;
             }
         }
         if (avail_idx == std::numeric_limits<size_t>::max()) {
             return false;
         }
         for (size_t idx = avail_idx; idx < numFreeSuballocs; ++idx) {
             VkDeviceSize offset = 0;
             const auto iter = availSuballocations[idx];
             // Check allocation for validity
             bool allocation_valid = VerifySuballocation(buffer_image_granularity, allocation_size, allocation_alignment, allocation_type, iter, &offset);
             if (allocation_valid) {
                 dest_request->FreeSuballocation = iter;
                 dest_request->Offset = offset;
                 return true;
             }
         }
         return false;
     }
Unmap()
void vpr::MemoryBlock::Unmap ()
As mentioned for the Map method, due to VkMapMemory functions we must make sure only one sub-region of an object is unmapped at a time, thus requiring the parent block to oversee the mapping/unmapping + using a mutex for thread safety.
Definition at line 428 of file MemoryBlock.cpp.
References guardMutex, memory, and parentDevice.
{
         std::lock_guard<std::mutex> unmapping_lock(guardMutex);
         vkUnmapMemory(parentDevice, memory);
     }
Validate()
ValidationCode vpr::MemoryBlock::Validate () const
Verifies integrity of memory by checking all contained suballocations for integrity and correctness.
Definition at line 145 of file MemoryBlock.cpp.
References availSize, availSuballocations, vpr::FINAL_FREE_SIZE_MISMATCH, vpr::FINAL_SIZE_MISMATCH, vpr::Free, vpr::FREE_SUBALLOC_COUNT_MISMATCH, vpr::FREE_SUBALLOC_SORT_INCORRECT, freeCount, vpr::INCORRECT_SUBALLOC_OFFSET, memory, vpr::MinSuballocationSizeToRegister, vpr::NEED_MERGE_SUBALLOCS, vpr::NULL_MEMORY_HANDLE, vpr::Suballocation::Offset, vpr::Suballocation::Size, Size, Suballocations, vpr::Suballocation::Type, vpr::USED_SUBALLOC_IN_FREE_LIST, vpr::VALIDATION_PASSED, and vpr::ZERO_MEMORY_SIZE.
Referenced by Free().
{
         if (memory == VK_NULL_HANDLE) {
             return ValidationCode::NULL_MEMORY_HANDLE;
         }
         if (Size == 0 || Suballocations.empty()) {
             return ValidationCode::ZERO_MEMORY_SIZE;
         }
         // expected offset of newest suballocation compared to previous
         VkDeviceSize calculated_offset = 0;
         // expected number of free suballocations, from traversing that list
         uint32_t calculated_free_suballocs = 0;
         // available size, taken as sum of avail size of all free suballocations.
         VkDeviceSize calculated_free_size = 0;
         // number of free suballocations that need to be registered in the list for these objects
         uint32_t num_suballocs_to_register = 0;
         // set as we iterate, true when prev suballoc was free (used to sort/swap entries)
         bool prev_entry_free = false;
         for (auto iter = Suballocations.cbegin(); iter != Suballocations.cend(); ++iter) {
             const Suballocation& curr = *iter;
             // if offset of current suballoc is wrong, then this allocation is invalid
             if (curr.Offset != calculated_offset) {
                 return ValidationCode::INCORRECT_SUBALLOC_OFFSET;
             }
             // two adjacent free entries is invalid: should be merged.
             const bool curr_free = (curr.Type == SuballocationType::Free);
             if (curr_free && prev_entry_free) {
                 return ValidationCode::NEED_MERGE_SUBALLOCS;
             }
             // update prev free status
             prev_entry_free = curr_free;
             if (curr_free) {
                 calculated_free_size += curr.Size;
                 ++calculated_free_suballocs;
                 if (curr.Size >= MinSuballocationSizeToRegister) {
                     ++num_suballocs_to_register; // this suballocation should be registered in the free list.
                 }
             }
             calculated_offset += curr.Size;
         }
         // Number of free suballocations in objects list doesn't match what our calculated value says we should have
         if (availSuballocations.size() != num_suballocs_to_register) {
             return ValidationCode::FREE_SUBALLOC_COUNT_MISMATCH;
         }
         VkDeviceSize last_entry_size = 0;
         for (size_t i = 0; i < availSuballocations.size(); ++i) {
             auto curr_iter = availSuballocations[i];
             // non-free suballoc in free list
             if (curr_iter->Type != SuballocationType::Free) {
                 return ValidationCode::USED_SUBALLOC_IN_FREE_LIST;
             }
             // sorting of free list is incorrect
             if (curr_iter->Size < last_entry_size) {
                 return ValidationCode::FREE_SUBALLOC_SORT_INCORRECT;
             }
             last_entry_size = curr_iter->Size;
         }
         if (calculated_offset != Size) {
             return ValidationCode::FINAL_SIZE_MISMATCH;
         }
         if (calculated_free_size != availSize) {
             return ValidationCode::FINAL_FREE_SIZE_MISMATCH;
         }
         if (calculated_free_suballocs != freeCount) {
             return ValidationCode::FREE_SUBALLOC_COUNT_MISMATCH;
         }
         return ValidationCode::VALIDATION_PASSED;
     }
VerifySuballocation()
bool vpr::MemoryBlock::VerifySuballocation (const VkDeviceSize & buffer_image_granularity, const VkDeviceSize & allocation_size, const VkDeviceSize & allocation_alignment, SuballocationType allocation_type, const suballocationList::const_iterator & dest_suballocation_location, VkDeviceSize * dest_offset) const
Verifies that requested suballocation can be added to this object, and sets dest_offset to reflect offset of this now-inserted suballocation.
Definition at line 268 of file MemoryBlock.cpp.
References vpr::CheckBlocksOnSamePage(), vpr::CheckBufferImageGranularityConflict(), vpr::Free, vpr::Suballocation::Offset, vpr::Suballocation::Size, Suballocations, and vpr::Suballocation::Type.
Referenced by RequestSuballocation().
{
         assert(allocation_size > 0);
         assert(allocation_type != SuballocationType::Free);
         assert(dest_suballocation_location != Suballocations.cend());
         assert(dest_offset != nullptr);
         const Suballocation& suballoc = *dest_suballocation_location;
         assert(suballoc.Type == SuballocationType::Free);
         if (suballoc.Size < allocation_size) {
             return false;
         }
         *dest_offset = suballoc.Offset;
         // Apply alignment
         *dest_offset = AlignUp<VkDeviceSize>(*dest_offset, allocation_alignment);
         // check previous suballocations for conflicts with buffer-image granularity, change alignment as needed
         if (buffer_image_granularity > 1) {
             bool conflict_found = false;
             // iterate backwards, since we're checking previous suballoations for alignment conflicts
             auto prev_suballoc_iter = dest_suballocation_location;
             while (prev_suballoc_iter != Suballocations.cbegin()) {
                 --prev_suballoc_iter;
                 const Suballocation& prev_suballoc = *prev_suballoc_iter;
                 bool on_same_page = CheckBlocksOnSamePage(prev_suballoc.Offset, prev_suballoc.Size, *dest_offset, buffer_image_granularity);
                 if (on_same_page) {
                     conflict_found = CheckBufferImageGranularityConflict(prev_suballoc.Type, allocation_type);
                     if (conflict_found) {
                         LOG(WARNING) << "A buffer-image granularity conflict was identified in suballocation " << std::to_string(reinterpret_cast<size_t>(&prev_suballoc));
                         break;
                     }
                 }
                 else {
                     break;
                 }
             }
             if (conflict_found) {
                 // align up by a page size to get off the current page and remove the conflict.
                 *dest_offset = AlignUp<VkDeviceSize>(*dest_offset, buffer_image_granularity);
             }
         }
         // calculate padding at beginning from offset
         const VkDeviceSize padding_begin = *dest_offset - suballoc.Offset;
         // calculate required padding at end, assuming current suballoc isn't at end of memory object
         auto next_iter = dest_suballocation_location;
         ++next_iter;
         const VkDeviceSize padding_end = (next_iter != Suballocations.cend()) ? DEBUG_PADDING : 0;
         // Can't allocate if padding at begin and end is greater than requested size.
         if (padding_begin + padding_end + allocation_size > suballoc.Size) {
             LOG(WARNING) << "Suballocation verification failed as required padding for alignment + required size is greater than available space.";
             return false;
         }
         // We checked previous allocations for conflicts: now, we'll check next suballocations
         if(buffer_image_granularity > 1) {
             auto next_suballoc_iter = dest_suballocation_location;
             ++next_suballoc_iter;
             while (next_suballoc_iter != Suballocations.cend()) {
                 const auto& next_suballoc = *next_suballoc_iter;
                 bool on_same_page = CheckBlocksOnSamePage(*dest_offset, allocation_size, next_suballoc.Offset, buffer_image_granularity);
                 if (on_same_page) {
                     if (CheckBufferImageGranularityConflict(allocation_type, next_suballoc.Type)) {
                         LOG(WARNING) << "Suballocation verification failed as there were too many buffer-image granularity conflicts.";
                         return false;
                     }
                 }
                 else {
                     break;
                 }
                 ++next_suballoc_iter;
             }
         }
         return true;
     }
Friends And Related Function Documentation
DebugVisualization
friend class DebugVisualization friend
Definition at line 113 of file MemoryBlock.hpp.
DebugVisualizationImpl
friend struct DebugVisualizationImpl friend
Definition at line 114 of file MemoryBlock.hpp.
Member Data Documentation
availSize
VkDeviceSize vpr::MemoryBlock::availSize { std::numeric_limits<VkDeviceSize>::max() } protected
Definition at line 91 of file MemoryBlock.hpp.
Referenced by Allocate(), AvailableMemory(), freeSuballocation(), Init(), operator<(), RequestSuballocation(), and Validate().
availSuballocations
std::vector<suballocationList::iterator> vpr::MemoryBlock::availSuballocations protected
This vector stores iterators that can be used to locate suballocations in this object's suballocationList.
Using iterators avoids accidental duplication of objects, (akin to a pointer), but with more safety and extra convienience when it comes to retrieving, modifying, or even removing the object "pointed" to by the iterator.
Definition at line 111 of file MemoryBlock.hpp.
Referenced by avail_begin(), avail_cbegin(), avail_cend(), avail_end(), Destroy(), Init(), insertFreeSuballocation(), LargestAvailRegion(), removeFreeSuballocation(), RequestSuballocation(), and Validate().
freeCount
uint32_t vpr::MemoryBlock::freeCount { std::numeric_limits<uint32_t>::max() } protected
Definition at line 92 of file MemoryBlock.hpp.
Referenced by Allocate(), Empty(), freeSuballocation(), Init(), mergeFreeWithNext(), and Validate().
guardMutex
std::mutex vpr::MemoryBlock::guardMutex protected
Definition at line 90 of file MemoryBlock.hpp.
Referenced by insertFreeSuballocation(), Map(), mergeFreeWithNext(), removeFreeSuballocation(), and Unmap().
memory
VkDeviceMemory vpr::MemoryBlock::memory { VK_NULL_HANDLE } protected
Definition at line 93 of file MemoryBlock.hpp.
Referenced by Destroy(), Init(), Map(), Memory(), Unmap(), Validate(), and ~MemoryBlock().
MemoryTypeIdx
uint32_t vpr::MemoryBlock::MemoryTypeIdx { std::numeric_limits<uint32_t>::max() }
Definition at line 85 of file MemoryBlock.hpp.
parentDevice
VkDevice vpr::MemoryBlock::parentDevice protected
Definition at line 89 of file MemoryBlock.hpp.
Referenced by Destroy(), Map(), and Unmap().
Size
VkDeviceSize vpr::MemoryBlock::Size { std::numeric_limits<VkDeviceSize>::max() }
Definition at line 83 of file MemoryBlock.hpp.
Referenced by Destroy(), Init(), LargestAvailRegion(), and Validate().
Suballocations
suballocationList vpr::MemoryBlock::Suballocations
Definition at line 84 of file MemoryBlock.hpp.
Referenced by Allocate(), begin(), cbegin(), cend(), Destroy(), Empty(), end(), Free(), freeSuballocation(), Init(), mergeFreeWithNext(), Validate(), and VerifySuballocation().
The documentation for this class was generated from the following files:
alloc/src/MemoryBlock.hpp
alloc/src/MemoryBlock.cpp