VulpesRender: el::base::utils::Str Class Reference
el::base::utils::Str Class Reference
String utilities helper class used internally. You should not use it.
#include <easylogging++.h>
Static Public Member Functions
static bool isDigit (char c)
Checks if character is digit. Dont use libc implementation of it to prevent locale issues.
static bool wildCardMatch (const char *str, const char *pattern)
Matches wildcards, '*' and '?' only supported.
static std::string & ltrim (std::string &str)
static std::string & rtrim (std::string &str)
static std::string & trim (std::string &str)
static bool startsWith (const std::string &str, const std::string &start)
Determines whether or not str starts with specified string.
static bool endsWith (const std::string &str, const std::string &end)
Determines whether or not str ends with specified string.
static std::string & replaceAll (std::string &str, char replaceWhat, char replaceWith)
Replaces all instances of replaceWhat with 'replaceWith'.
static std::string & replaceAll (std::string &str, const std::string &replaceWhat, const std::string &replaceWith)
Replaces all instances of 'replaceWhat' with 'replaceWith'.
static void replaceFirstWithEscape (base::type::string_t &str, const base::type::string_t &replaceWhat, const base::type::string_t &replaceWith)
static std::string & toUpper (std::string &str)
Converts string to uppercase.
static bool cStringEq (const char *s1, const char *s2)
Compares cstring equality - uses strcmp.
static bool cStringCaseEq (const char *s1, const char *s2)
Compares cstring equality (case-insensitive) - uses toupper(char) Dont use strcasecmp because of CRT (VC++)
static bool contains (const char *str, char c)
Returns true if c exist in str.
static char * convertAndAddToBuff (std::size_t n, int len, char *buf, const char *bufLim, bool zeroPadded=true)
static char * addToBuff (const char *str, char *buf, const char *bufLim)
static char * clearBuff (char buff[], std::size_t lim)
static char * wcharPtrToCharPtr (const wchar_t *line)
Converst wchar* to char* NOTE: Need to free return value after use!
Detailed Description
String utilities helper class used internally. You should not use it.
Definition at line 1121 of file easylogging++.h.
Member Function Documentation
addToBuff()
char * el::base::utils::Str::addToBuff (const char * str, char * buf, const char * bufLim) static
Definition at line 924 of file easylogging++.cc.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::utils::DateTime::parseFormat().
{
   while ((buf < bufLim) && ((*buf = *str++) != '\0'))
     ++buf;
   return buf;
 }
clearBuff()
char * el::base::utils::Str::clearBuff (char buff[], std::size_t lim) static
Definition at line 930 of file easylogging++.cc.
References ELPP_UNUSED, and STRCPY.
Referenced by el::base::DefaultLogBuilder::build().
{
   STRCPY(buff, "", lim);
   ELPP_UNUSED(lim);  // For *nix we dont have anything using lim in above STRCPY macro
   return buff;
 }
contains()
bool el::base::utils::Str::contains (const char * str, char c) static
Returns true if c exist in str.
Definition at line 901 of file easylogging++.cc.
Referenced by el::Logger::isValidId().
{
   for (; *str; ++str) {
     if (*str == c)
       return true;
   }
   return false;
 }
convertAndAddToBuff()
char * el::base::utils::Str::convertAndAddToBuff (std::size_t n, int len, char * buf, const char * bufLim, bool zeroPadded = true) static
Definition at line 909 of file easylogging++.cc.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::utils::DateTime::parseFormat().
{
   char localBuff[10] = "";
   char* p = localBuff + sizeof(localBuff) - 2;
   if (n > 0) {
     for (; n > 0 && p > localBuff && len > 0; n /= 10, --len)
       *--p = static_cast<char>(n % 10 + '0');
   } else {
     *--p = '0';
     --len;
   }
   if (zeroPadded)
     while (p > localBuff && len-- > 0) *--p = static_cast<char>('0');
   return addToBuff(p, buf, bufLim);
 }
cStringCaseEq()
bool el::base::utils::Str::cStringCaseEq (const char * s1, const char * s2) static
Compares cstring equality (case-insensitive) - uses toupper(char) Dont use strcasecmp because of CRT (VC++)
Definition at line 882 of file easylogging++.cc.
Referenced by el::LevelHelper::convertFromString(), and el::ConfigurationTypeHelper::convertFromString().
{
   if (s1 == nullptr && s2 == nullptr) return true;
   if (s1 == nullptr || s2 == nullptr) return false;
   // With thanks to cygwin for this code
   int d = 0;
   while (true) {
     const int c1 = toupper(*s1++);
     const int c2 = toupper(*s2++);
     if (((d = c1 - c2) != 0) || (c2 == '\0')) {
       break;
     }
   }
   return d == 0;
 }
cStringEq()
bool el::base::utils::Str::cStringEq (const char * s1, const char * s2) static
Compares cstring equality - uses strcmp.
Definition at line 876 of file easylogging++.cc.
{
   if (s1 == nullptr && s2 == nullptr) return true;
   if (s1 == nullptr || s2 == nullptr) return false;
   return strcmp(s1, s2) == 0;
 }
endsWith()
bool el::base::utils::Str::endsWith (const std::string & str, const std::string & end) static
Determines whether or not str ends with specified string.
Parameters
str String to check
end String to check against
Returns
Returns true if ends with specified string, false otherwise
Definition at line 828 of file easylogging++.cc.
Referenced by el::base::VRegistry::setModules().
{
   return (str.length() >= end.length()) && (str.compare(str.length() - end.length(), end.length(), end) == 0);
 }
isDigit()
static bool el::base::utils::Str::isDigit (char c) inline static
Checks if character is digit. Dont use libc implementation of it to prevent locale issues.
Definition at line 1124 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::getULong().
{
     return c >= '0' && c <= '9';
   }
ltrim()
std::string & el::base::utils::Str::ltrim (std::string & str) static
Definition at line 806 of file easylogging++.cc.
{
   str.erase(str.begin(), std::find_if(str.begin(), str.end(), [](char c) {
     return !std::isspace(c);
   } ));
   return str;
 }
replaceAll() [1/2]
std::string & el::base::utils::Str::replaceAll (std::string & str, char replaceWhat, char replaceWith) static
Replaces all instances of replaceWhat with 'replaceWith'.
Original variable is changed for performance.
Parameters
[in,out] str String to replace from
replaceWhat Character to replace
replaceWith Character to replace with
Returns
Modified version of str
Definition at line 832 of file easylogging++.cc.
Referenced by el::base::TypedConfigurations::resolveFilename().
{
   std::replace(str.begin(), str.end(), replaceWhat, replaceWith);
   return str;
 }
replaceAll() [2/2]
std::string & el::base::utils::Str::replaceAll (std::string & str, const std::string & replaceWhat, const std::string & replaceWith) static
Replaces all instances of 'replaceWhat' with 'replaceWith'.
(String version) Replaces in place
Parameters
str String to replace from
replaceWhat Character to replace
replaceWith Character to replace with
Returns
Modified (original) str
Definition at line 837 of file easylogging++.cc.
{
   if (replaceWhat == replaceWith)
     return str;
   std::size_t foundAt = std::string::npos;
   while ((foundAt = str.find(replaceWhat, foundAt + 1)) != std::string::npos) {
     str.replace(foundAt, replaceWhat.length(), replaceWith);
   }
   return str;
 }
replaceFirstWithEscape()
void el::base::utils::Str::replaceFirstWithEscape (base::type::string_t & str, const base::type::string_t & replaceWhat, const base::type::string_t & replaceWith) static
Definition at line 848 of file easylogging++.cc.
References el::base::consts::kFormatSpecifierChar.
Referenced by el::base::DefaultLogBuilder::build(), el::Logger::resolveLoggerFormatSpec(), and el::base::LogFormat::updateFormatSpec().
{
   std::size_t foundAt = base::type::string_t::npos;
   while ((foundAt = str.find(replaceWhat, foundAt + 1)) != base::type::string_t::npos) {
     if (foundAt > 0 && str[foundAt - 1] == base::consts::kFormatSpecifierChar) {
       str.erase(foundAt > 0 ? foundAt - 1 : 0, 1);
       ++foundAt;
     } else {
       str.replace(foundAt, replaceWhat.length(), replaceWith);
       return;
     }
   }
 }
rtrim()
std::string & el::base::utils::Str::rtrim (std::string & str) static
Definition at line 813 of file easylogging++.cc.
{
   str.erase(std::find_if(str.rbegin(), str.rend(), [](char c) {
     return !std::isspace(c);
   }).base(), str.end());
   return str;
 }
startsWith()
bool el::base::utils::Str::startsWith (const std::string & str, const std::string & start) static
Determines whether or not str starts with specified string.
Parameters
str String to check
start String to check against
Returns
Returns true if starts with specified string, false otherwise
Definition at line 824 of file easylogging++.cc.
Referenced by el::Loggers::configureFromGlobal(), el::Configurations::Parser::isComment(), and el::Configurations::Parser::isLevel().
{
   return (str.length() >= start.length()) && (str.compare(0, start.length(), start) == 0);
 }
toUpper()
std::string & el::base::utils::Str::toUpper (std::string & str) static
Converts string to uppercase.
Parameters
str String to convert
Returns
Uppercase string
Definition at line 868 of file easylogging++.cc.
Referenced by el::Configurations::Parser::parseLine().
{
   std::transform(str.begin(), str.end(), str.begin(),
   [](char c) {
     return static_cast<char>(::toupper(c));
   });
   return str;
 }
trim()
std::string & el::base::utils::Str::trim (std::string & str) static
Definition at line 820 of file easylogging++.cc.
Referenced by el::base::TypedConfigurations::build(), el::Loggers::configureFromGlobal(), el::base::TypedConfigurations::getULong(), and el::Configurations::Parser::parseLine().
{
   return ltrim(rtrim(str));
 }
wcharPtrToCharPtr()
char * el::base::utils::Str::wcharPtrToCharPtr (const wchar_t * line) static
Converst wchar* to char* NOTE: Need to free return value after use!
Definition at line 938 of file easylogging++.cc.
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), and el::base::MessageBuilder::operator<<().
{
   std::size_t len_ = wcslen(line) + 1;
   char* buff_ = static_cast<char*>(malloc(len_ + 1));
 #      if ELPP_OS_UNIX || (ELPP_OS_WINDOWS && !ELPP_CRT_DBG_WARNINGS)
   std::wcstombs(buff_, line, len_);
 #      elif ELPP_OS_WINDOWS
   std::size_t convCount_ = 0;
   mbstate_t mbState_;
   ::memset(static_cast<void*>(&mbState_), 0, sizeof(mbState_));
   wcsrtombs_s(&convCount_, buff_, len_, &line, len_, &mbState_);
 #      endif  // ELPP_OS_UNIX || (ELPP_OS_WINDOWS && !ELPP_CRT_DBG_WARNINGS)
   return buff_;
 }
wildCardMatch()
bool el::base::utils::Str::wildCardMatch (const char * str, const char * pattern) static
Matches wildcards, '*' and '?' only supported.
Definition at line 782 of file easylogging++.cc.
Referenced by el::base::VRegistry::allowed().
{
   while (*pattern) {
     switch (*pattern) {
     case '?':
       if (!*str)
         return false;
       ++str;
       ++pattern;
       break;
     case '*':
       if (wildCardMatch(str, pattern + 1))
         return true;
       if (*str && wildCardMatch(str + 1, pattern))
         return true;
       return false;
     default:
       if (*str++ != *pattern++)
         return false;
       break;
     }
   }
   return !*str && !*pattern;
 }
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc