VulpesRender: el::Configurations::Parser Class Reference
el::Configurations::Parser Class Reference
Parser used internally to parse configurations from file or text.
#include <easylogging++.h>
Static Public Member Functions
static bool parseFromFile (const std::string &configurationFile, Configurations *sender, Configurations *base=nullptr)
Parses configuration from file.
static bool parseFromText (const std::string &configurationsString, Configurations *sender, Configurations *base=nullptr)
Parse configurations from configuration string.
Static Private Member Functions
static void ignoreComments (std::string *line)
static bool isLevel (const std::string &line)
static bool isComment (const std::string &line)
static bool isConfig (const std::string &line)
static bool parseLine (std::string *line, std::string *currConfigStr, std::string *currLevelStr, Level *currLevel, Configurations *conf)
Friends
class el::Loggers
Detailed Description
Parser used internally to parse configurations from file or text.
This class makes use of base::utils::Str. You should not need this unless you are working on some tool for Easylogging++
Definition at line 1894 of file easylogging++.h.
Member Function Documentation
ignoreComments()
void el::Configurations::Parser::ignoreComments (std::string * line) static private
Definition at line 364 of file easylogging++.cc.
References el::base::consts::kConfigurationComment.
Referenced by el::Loggers::configureFromGlobal().
{
   std::size_t foundAt = 0;
   std::size_t quotesStart = line->find("\"");
   std::size_t quotesEnd = std::string::npos;
   if (quotesStart != std::string::npos) {
     quotesEnd = line->find("\"", quotesStart + 1);
     while (quotesEnd != std::string::npos && line->at(quotesEnd - 1) == '\\') {
       // Do not erase slash yet - we will erase it in parseLine(..) while loop
       quotesEnd = line->find("\"", quotesEnd + 2);
     }
   }
   if ((foundAt = line->find(base::consts::kConfigurationComment)) != std::string::npos) {
     if (foundAt < quotesEnd) {
       foundAt = line->find(base::consts::kConfigurationComment, quotesEnd + 1);
     }
     *line = line->substr(0, foundAt);
   }
 }
isComment()
bool el::Configurations::Parser::isComment (const std::string & line) static private
Definition at line 387 of file easylogging++.cc.
References el::base::consts::kConfigurationComment, and el::base::utils::Str::startsWith().
Referenced by el::Loggers::configureFromGlobal().
{
   return base::utils::Str::startsWith(line, std::string(base::consts::kConfigurationComment));
 }
isConfig()
bool el::Configurations::Parser::isConfig (const std::string & line) inline static private
Definition at line 391 of file easylogging++.cc.
{
   std::size_t assignment = line.find('=');
   return line != "" &&
          ((line[0] >= 'A' && line[0] <= 'Z') || (line[0] >= 'a' && line[0] <= 'z')) &&
          (assignment != std::string::npos) &&
          (line.size() > assignment);
 }
isLevel()
bool el::Configurations::Parser::isLevel (const std::string & line) static private
Definition at line 383 of file easylogging++.cc.
References el::base::consts::kConfigurationLevel, and el::base::utils::Str::startsWith().
{
   return base::utils::Str::startsWith(line, std::string(base::consts::kConfigurationLevel));
 }
parseFromFile()
bool el::Configurations::Parser::parseFromFile (const std::string & configurationFile, Configurations * sender, Configurations * base = nullptr) static
Parses configuration from file.
Parameters
configurationFile Full path to configuration file
sender Sender configurations pointer. Usually 'this' is used from calling class
base Configurations to base new configuration repository off. This value is used when you want to use existing Configurations to base all the values and then set rest of configuration via configuration file.
Returns
True if successfully parsed, false otherwise. You may define '_STOP_ON_FIRSTELPP_ASSERTION' to make sure you do not proceed without successful parse.
Definition at line 330 of file easylogging++.cc.
References ELPP_ASSERT, el::Configurations::setFromBase(), and el::Unknown.
Referenced by el::Configurations::parseFromFile().
{
   sender->setFromBase(base);
   std::ifstream fileStream_(configurationFile.c_str(), std::ifstream::in);
   ELPP_ASSERT(fileStream_.is_open(), "Unable to open configuration file [" << configurationFile << "] for parsing.");
   bool parsedSuccessfully = false;
   std::string line = std::string();
   Level currLevel = Level::Unknown;
   std::string currConfigStr = std::string();
   std::string currLevelStr = std::string();
   while (fileStream_.good()) {
     std::getline(fileStream_, line);
     parsedSuccessfully = parseLine(&line, &currConfigStr, &currLevelStr, &currLevel, sender);
     ELPP_ASSERT(parsedSuccessfully, "Unable to parse configuration line: " << line);
   }
   return parsedSuccessfully;
 }
parseFromText()
bool el::Configurations::Parser::parseFromText (const std::string & configurationsString, Configurations * sender, Configurations * base = nullptr) static
Parse configurations from configuration string.
This configuration string has same syntax as configuration file contents. Make sure all the necessary new line characters are provided. You may define '_STOP_ON_FIRSTELPP_ASSERTION' to make sure you do not proceed without successful parse (This is recommended)
Parameters
configurationsString the configuration in plain text format
sender Sender configurations pointer. Usually 'this' is used from calling class
base Configurations to base new configuration repository off. This value is used when you want to use existing Configurations to base all the values and then set rest of configuration via configuration text.
Returns
True if successfully parsed, false otherwise.
Definition at line 348 of file easylogging++.cc.
References ELPP_ASSERT, el::Configurations::setFromBase(), and el::Unknown.
Referenced by el::Configurations::parseFromText().
{
   sender->setFromBase(base);
   bool parsedSuccessfully = false;
   std::stringstream ss(configurationsString);
   std::string line = std::string();
   Level currLevel = Level::Unknown;
   std::string currConfigStr = std::string();
   std::string currLevelStr = std::string();
   while (std::getline(ss, line)) {
     parsedSuccessfully = parseLine(&line, &currConfigStr, &currLevelStr, &currLevel, sender);
     ELPP_ASSERT(parsedSuccessfully, "Unable to parse configuration line: " << line);
   }
   return parsedSuccessfully;
 }
parseLine()
bool el::Configurations::Parser::parseLine (std::string * line, std::string * currConfigStr, std::string * currLevelStr, Level * currLevel, Configurations * conf) static private
Definition at line 399 of file easylogging++.cc.
References el::LevelHelper::convertFromString(), el::ConfigurationTypeHelper::convertFromString(), ELPP_ASSERT, el::Configurations::set(), el::base::utils::Str::toUpper(), el::base::utils::Str::trim(), and el::Unknown.
{
   ConfigurationType currConfig = ConfigurationType::Unknown;
   std::string currValue = std::string();
   *line = base::utils::Str::trim(*line);
   if (isComment(*line)) return true;
   ignoreComments(line);
   *line = base::utils::Str::trim(*line);
   if (line->empty()) {
     // Comment ignored
     return true;
   }
   if (isLevel(*line)) {
     if (line->size() <= 2) {
       return true;
     }
     *currLevelStr = line->substr(1, line->size() - 2);
     *currLevelStr = base::utils::Str::toUpper(*currLevelStr);
     *currLevelStr = base::utils::Str::trim(*currLevelStr);
     *currLevel = LevelHelper::convertFromString(currLevelStr->c_str());
     return true;
   }
   if (isConfig(*line)) {
     std::size_t assignment = line->find('=');
     *currConfigStr = line->substr(0, assignment);
     *currConfigStr = base::utils::Str::toUpper(*currConfigStr);
     *currConfigStr = base::utils::Str::trim(*currConfigStr);
     currConfig = ConfigurationTypeHelper::convertFromString(currConfigStr->c_str());
     currValue = line->substr(assignment + 1);
     currValue = base::utils::Str::trim(currValue);
     std::size_t quotesStart = currValue.find("\"", 0);
     std::size_t quotesEnd = std::string::npos;
     if (quotesStart != std::string::npos) {
       quotesEnd = currValue.find("\"", quotesStart + 1);
       while (quotesEnd != std::string::npos && currValue.at(quotesEnd - 1) == '\\') {
         currValue = currValue.erase(quotesEnd - 1, 1);
         quotesEnd = currValue.find("\"", quotesEnd + 2);
       }
     }
     if (quotesStart != std::string::npos && quotesEnd != std::string::npos) {
       // Quote provided - check and strip if valid
       ELPP_ASSERT((quotesStart < quotesEnd), "Configuration error - No ending quote found in ["
                   << currConfigStr << "]");
       ELPP_ASSERT((quotesStart + 1 != quotesEnd), "Empty configuration value for [" << currConfigStr << "]");
       if ((quotesStart != quotesEnd) && (quotesStart + 1 != quotesEnd)) {
         // Explicit check in case if assertion is disabled
         currValue = currValue.substr(quotesStart + 1, quotesEnd - 1);
       }
     }
   }
   ELPP_ASSERT(*currLevel != Level::Unknown, "Unrecognized severity level [" << *currLevelStr << "]");
   ELPP_ASSERT(currConfig != ConfigurationType::Unknown, "Unrecognized configuration [" << *currConfigStr << "]");
   if (*currLevel == Level::Unknown || currConfig == ConfigurationType::Unknown) {
     return false;  // unrecognizable level or config
   }
   conf->set(*currLevel, currConfig, currValue);
   return true;
 }
Friends And Related Function Documentation
el::Loggers
friend class el::Loggers friend
Definition at line 1920 of file easylogging++.h.
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc