VulpesRender: el::ConfigurationTypeHelper Class Reference
el::ConfigurationTypeHelper Class Reference
Static class that contains helper functions for el::ConfigurationType.
#include <easylogging++.h>
Static Public Member Functions
static base::type::EnumType castToInt (ConfigurationType configurationType)
Casts configuration type to int, useful for iterating through enum.
static ConfigurationType castFromInt (base::type::EnumType c)
Casts int(ushort) to configurationt type, useful for iterating through enum.
static const char * convertToString (ConfigurationType configurationType)
Converts configuration type to associated const char*.
static ConfigurationType convertFromString (const char *configStr)
Converts from configStr to ConfigurationType.
static void forEachConfigType (base::type::EnumType *startIndex, const std::function< bool(void)> &fn)
Applies specified function to each configuration type starting from startIndex.
Static Public Attributes
static const base::type::EnumType kMinValid = static_cast<base::type::EnumType>(ConfigurationType::Enabled)
Represents minimum valid configuration type. Useful when iterating through enum.
static const base::type::EnumType kMaxValid = static_cast<base::type::EnumType>(ConfigurationType::MaxLogFileSize)
Represents maximum valid configuration type. This is used internally and you should not need it.
Detailed Description
Static class that contains helper functions for el::ConfigurationType.
Definition at line 645 of file easylogging++.h.
Member Function Documentation
castFromInt()
static ConfigurationType el::ConfigurationTypeHelper::castFromInt (base::type::EnumType c) inline static
Casts int(ushort) to configurationt type, useful for iterating through enum.
Definition at line 656 of file easylogging++.h.
{
     return static_cast<ConfigurationType>(c);
   }
castToInt()
static base::type::EnumType el::ConfigurationTypeHelper::castToInt (ConfigurationType configurationType) inline static
Casts configuration type to int, useful for iterating through enum.
Definition at line 652 of file easylogging++.h.
{
     return static_cast<base::type::EnumType>(configurationType);
   }
convertFromString()
ConfigurationType el::ConfigurationTypeHelper::convertFromString (const char * configStr) static
Converts from configStr to ConfigurationType.
Parameters
configStr Upper case string based configuration type. Lower case is also valid but providing upper case is recommended.
Definition at line 131 of file easylogging++.cc.
References el::base::utils::Str::cStringCaseEq(), and el::Unknown.
Referenced by el::Configurations::Parser::parseLine().
{
   for (auto& item : configStringToTypeMap) {
     if (base::utils::Str::cStringCaseEq(configStr, item.configString)) {
       return item.configType;
     }
   }
   return ConfigurationType::Unknown;
 }
convertToString()
const char * el::ConfigurationTypeHelper::convertToString (ConfigurationType configurationType) static
Converts configuration type to associated const char*.
Returns
Upper case string based configuration type.
Definition at line 99 of file easylogging++.cc.
References el::Enabled, el::Filename, el::Format, el::LogFlushThreshold, el::MaxLogFileSize, el::PerformanceTracking, el::SubsecondPrecision, el::ToFile, and el::ToStandardOutput.
Referenced by el::Configuration::log().
{
   // Do not use switch over strongly typed enums because Intel C++ compilers dont support them yet.
   if (configurationType == ConfigurationType::Enabled) return "ENABLED";
   if (configurationType == ConfigurationType::Filename) return "FILENAME";
   if (configurationType == ConfigurationType::Format) return "FORMAT";
   if (configurationType == ConfigurationType::ToFile) return "TO_FILE";
   if (configurationType == ConfigurationType::ToStandardOutput) return "TO_STANDARD_OUTPUT";
   if (configurationType == ConfigurationType::SubsecondPrecision) return "SUBSECOND_PRECISION";
   if (configurationType == ConfigurationType::PerformanceTracking) return "PERFORMANCE_TRACKING";
   if (configurationType == ConfigurationType::MaxLogFileSize) return "MAX_LOG_FILE_SIZE";
   if (configurationType == ConfigurationType::LogFlushThreshold) return "LOG_FLUSH_THRESHOLD";
   return "UNKNOWN";
 }
forEachConfigType()
void el::ConfigurationTypeHelper::forEachConfigType (base::type::EnumType * startIndex, const std::function< bool(void)> & fn) inline static
Applies specified function to each configuration type starting from startIndex.
Parameters
startIndex initial value to start the iteration from. This is passed by pointer and is left-shifted so this can be used inside function (fn) to represent current configuration type.
fn function to apply with each configuration type. This bool represent whether or not to stop iterating through configurations.
Definition at line 140 of file easylogging++.cc.
References kMaxValid.
{
   base::type::EnumType cIndexMax = ConfigurationTypeHelper::kMaxValid;
   do {
     if (fn()) {
       break;
     }
     *startIndex = static_cast<base::type::EnumType>(*startIndex << 1);
   } while (*startIndex <= cIndexMax);
 }
Member Data Documentation
kMaxValid
const base::type::EnumType el::ConfigurationTypeHelper::kMaxValid = static_cast<base::type::EnumType>(ConfigurationType::MaxLogFileSize) static
Represents maximum valid configuration type. This is used internally and you should not need it.
Definition at line 650 of file easylogging++.h.
Referenced by forEachConfigType().
kMinValid
const base::type::EnumType el::ConfigurationTypeHelper::kMinValid = static_cast<base::type::EnumType>(ConfigurationType::Enabled) static
Represents minimum valid configuration type. Useful when iterating through enum.
Definition at line 648 of file easylogging++.h.
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc