VulpesRender: vpr::PipelineLayout Class Reference
vpr::PipelineLayout Class Reference
Resources
PipelineLayout is an RAII wrapper around a VkPipelineLayout object that also simplifies setting what resources the pipeline layout will have bound to it.
#include <PipelineLayout.hpp>
Public Member Functions
PipelineLayout (const Device *device)
~PipelineLayout ()
PipelineLayout (PipelineLayout &&other) noexcept
PipelineLayout & operator= (PipelineLayout &&other) noexcept
void Destroy ()
void Create (const VkPushConstantRange *push_constants, const size_t num_push_constants)
Creates a pipeline layout that will only use push constants for setting data in shaders.
void Create (const VkDescriptorSetLayout *set_layouts, const size_t num_layouts)
Creates a pipeline layout that will only use descriptors (of whatever type is in the layout) for data reads/writes in shaders.
void Create (const VkPushConstantRange *push_constants, const size_t num_push_constants, const VkDescriptorSetLayout *set_layouts, const size_t num_layouts)
Creates a pipeline layout that will utilize both push constants and descriptors in the shaders.
const VkPipelineLayout & vkHandle () const noexcept
Private Member Functions
PipelineLayout (const PipelineLayout &)=delete
PipelineLayout & operator= (const PipelineLayout &)=delete
Private Attributes
const Device * device
VkPipelineLayoutCreateInfo createInfo
VkPipelineLayout handle
Detailed Description
PipelineLayout is an RAII wrapper around a VkPipelineLayout object that also simplifies setting what resources the pipeline layout will have bound to it.
Definition at line 13 of file PipelineLayout.hpp.
Constructor & Destructor Documentation
PipelineLayout() [1/3]
vpr::PipelineLayout::PipelineLayout (const PipelineLayout &) private delete
PipelineLayout() [2/3]
vpr::PipelineLayout::PipelineLayout (const Device * device)
Definition at line 7 of file PipelineLayout.cpp.
 : device(_device), handle(VK_NULL_HANDLE) { }
~PipelineLayout()
vpr::PipelineLayout::~PipelineLayout ()
Definition at line 9 of file PipelineLayout.cpp.
References Destroy().
{
         Destroy();
     }
PipelineLayout() [3/3]
vpr::PipelineLayout::PipelineLayout (PipelineLayout && other) noexcept
Definition at line 13 of file PipelineLayout.cpp.
                                                                    : device(other.device), handle(std::move(other.handle)), createInfo(std::move(other.createInfo)) {
         other.handle = VK_NULL_HANDLE;
     }
Member Function Documentation
Create() [1/3]
void vpr::PipelineLayout::Create (const VkPushConstantRange * push_constants, const size_t num_push_constants)
Creates a pipeline layout that will only use push constants for setting data in shaders.
Definition at line 32 of file PipelineLayout.cpp.
Referenced by Create().
{
         Create(push_constants, num_push_constants, nullptr, 0);
     }
Create() [2/3]
void vpr::PipelineLayout::Create (const VkDescriptorSetLayout * set_layouts, const size_t num_layouts)
Creates a pipeline layout that will only use descriptors (of whatever type is in the layout) for data reads/writes in shaders.
Definition at line 36 of file PipelineLayout.cpp.
References Create().
{
         Create(nullptr, 0, set_layouts, num_layouts);
     }
Create() [3/3]
void vpr::PipelineLayout::Create (const VkPushConstantRange * push_constants, const size_t num_push_constants, const VkDescriptorSetLayout * set_layouts, const size_t num_layouts)
Creates a pipeline layout that will utilize both push constants and descriptors in the shaders.
Definition at line 40 of file PipelineLayout.cpp.
References createInfo, device, handle, vpr::vk_pipeline_layout_create_info_base, VkAssert, and vpr::Device::vkHandle().
{
         createInfo = vk_pipeline_layout_create_info_base;
         createInfo.setLayoutCount = static_cast<uint32_t>(num_layouts);
         createInfo.pSetLayouts = set_layouts;
         createInfo.pushConstantRangeCount = static_cast<uint32_t>(num_ranges);
         createInfo.pPushConstantRanges = ranges;
         VkResult result = vkCreatePipelineLayout(device->vkHandle(), &createInfo, nullptr, &handle);
         VkAssert(result);
     }
Destroy()
void vpr::PipelineLayout::Destroy ()
Definition at line 25 of file PipelineLayout.cpp.
References device, handle, and vpr::Device::vkHandle().
Referenced by ~PipelineLayout().
{
         if (handle != VK_NULL_HANDLE) {
             vkDestroyPipelineLayout(device->vkHandle(), handle, nullptr);
             handle = VK_NULL_HANDLE;
         }
     }
operator=() [1/2]
PipelineLayout& vpr::PipelineLayout::operator= (const PipelineLayout &) private delete
operator=() [2/2]
PipelineLayout & vpr::PipelineLayout::operator= (PipelineLayout && other) noexcept
Definition at line 17 of file PipelineLayout.cpp.
References createInfo, device, and handle.
{
         device = other.device;
         handle = std::move(other.handle);
         createInfo = std::move(other.createInfo);
         other.handle = VK_NULL_HANDLE;
         return *this;
     }
vkHandle()
const VkPipelineLayout & vpr::PipelineLayout::vkHandle () const noexcept
Definition at line 53 of file PipelineLayout.cpp.
References handle.
{
         return handle;
     }
Member Data Documentation
createInfo
VkPipelineLayoutCreateInfo vpr::PipelineLayout::createInfo private
Definition at line 39 of file PipelineLayout.hpp.
Referenced by Create(), and operator=().
device
const Device* vpr::PipelineLayout::device private
Definition at line 38 of file PipelineLayout.hpp.
Referenced by Create(), Destroy(), and operator=().
handle
VkPipelineLayout vpr::PipelineLayout::handle private
Definition at line 40 of file PipelineLayout.hpp.
Referenced by Create(), Destroy(), operator=(), and vkHandle().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/resource/PipelineLayout.hpp
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/resource/PipelineLayout.cpp