VulpesRender: el::Callback< T > Class Template Reference
el::Callback< T > Class Template Reference abstract
#include <easylogging++.h>
Public Member Functions
Callback (void)
bool enabled (void) const
void setEnabled (bool enabled)
Protected Member Functions
virtual void handle (const T *handlePtr)=0
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Attributes
bool m_enabled
Detailed Description
template<typename T>
class el::Callback< T >
Definition at line 466 of file easylogging++.h.
Constructor & Destructor Documentation
Callback()
template<typename T> el::Callback< T >::Callback (void) inline
Definition at line 2199 of file easylogging++.h.
 : m_enabled(true) {}
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
enabled()
template<typename T> bool el::Callback< T >::enabled (void) const inline
Definition at line 2200 of file easylogging++.h.
Referenced by el::base::LogDispatcher::dispatch(), el::base::RegisteredLoggers::get(), and el::base::PErrorWriter::~PErrorWriter().
{
     return m_enabled;
   }
handle()
template<typename T> virtual void el::Callback< T >::handle (const T * handlePtr) protected pure virtual
Implemented in el::base::DefaultLogDispatchCallback.
Referenced by el::base::LogDispatcher::dispatch(), el::base::RegisteredLoggers::get(), and el::base::PErrorWriter::~PErrorWriter().
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
setEnabled()
template<typename T> void el::Callback< T >::setEnabled (bool enabled) inline
Definition at line 2203 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     m_enabled = enabled;
   }
Member Data Documentation
m_enabled
template<typename T> bool el::Callback< T >::m_enabled private
Definition at line 2210 of file easylogging++.h.
The documentation for this class was generated from the following file:
include/util/easylogging++.h