VulpesRender: el::Configurations Class Reference
el::Configurations Class Reference abstract
Thread-safe Configuration repository.
#include <easylogging++.h>
Classes
class Parser
Parser used internally to parse configurations from file or text.
Public Types
typedef RegistryWithPred< Configuration, Configuration::Predicate >::iterator iterator
typedef RegistryWithPred< Configuration, Configuration::Predicate >::const_iterator const_iterator
Public Member Functions
Configurations (void)
Default constructor with empty repository.
Configurations (const std::string &configurationFile, bool useDefaultsForRemaining=true, Configurations *base=nullptr)
Constructor used to set configurations using configuration file.
virtual ~Configurations (void)
bool parseFromFile (const std::string &configurationFile, Configurations *base=nullptr)
Parses configuration from file.
bool parseFromText (const std::string &configurationsString, Configurations *base=nullptr)
Parse configurations from configuration string.
void setFromBase (Configurations *base)
Sets configuration based-off an existing configurations.
bool hasConfiguration (ConfigurationType configurationType)
Determines whether or not specified configuration type exists in the repository.
bool hasConfiguration (Level level, ConfigurationType configurationType)
Determines whether or not specified configuration type exists for specified level.
void set (Level level, ConfigurationType configurationType, const std::string &value)
Sets value of configuration for specified level.
void set (Configuration *conf)
Sets single configuration based on other single configuration.
Configuration * get (Level level, ConfigurationType configurationType)
void setGlobally (ConfigurationType configurationType, const std::string &value)
Sets configuration for all levels.
void clear (void)
Clears repository so that all the configurations are unset.
const std::string & configurationFile (void) const
Gets configuration file used in parsing this configurations.
void setToDefault (void)
Sets configurations to "factory based" configurations.
void setRemainingToDefault (void)
Lets you set the remaining configurations to default.
bool operator== (const AbstractRegistry< Configuration, std::vector< Configuration * > > &other)
bool operator!= (const AbstractRegistry< Configuration, std::vector< Configuration * > > &other)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual std::vector< Configuration * > & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const std::vector< Configuration * > & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void unregister (Configuration *&ptr) ELPP_FINAL
virtual void registerNew (Configuration *ptr) ELPP_FINAL
Configuration * get (const T &arg1, const T2 arg2)
Gets pointer from repository with speicifed arguments.
virtual void deepCopy (const AbstractRegistry< Configuration, std::vector< Configuration * > > &)=0
void reinitDeepCopy (const AbstractRegistry< Configuration, std::vector< Configuration * > > &sr)
Private Member Functions
void unsafeSetIfNotExist (Level level, ConfigurationType configurationType, const std::string &value)
Unsafely sets configuration if does not already exist.
void unsafeSet (Level level, ConfigurationType configurationType, const std::string &value)
Thread unsafe set.
void setGlobally (ConfigurationType configurationType, const std::string &value, bool includeGlobalLevel)
Sets configurations for all levels including Level::Global if includeGlobalLevel is true.
void unsafeSetGlobally (ConfigurationType configurationType, const std::string &value, bool includeGlobalLevel)
Sets configurations (Unsafely) for all levels including Level::Global if includeGlobalLevel is true.
Private Attributes
std::string m_configurationFile
bool m_isFromFile
Friends
class el::Loggers
Detailed Description
Thread-safe Configuration repository.
This repository represents configurations for all the levels and configuration type mapped to a value.
Definition at line 1784 of file easylogging++.h.
Member Typedef Documentation
const_iterator
typedef RegistryWithPred<Configuration , Configuration::Predicate >::const_iterator el::base::utils::RegistryWithPred< Configuration , Configuration::Predicate >::const_iterator inherited
Definition at line 1504 of file easylogging++.h.
iterator
typedef RegistryWithPred<Configuration , Configuration::Predicate >::iterator el::base::utils::RegistryWithPred< Configuration , Configuration::Predicate >::iterator inherited
Definition at line 1503 of file easylogging++.h.
Constructor & Destructor Documentation
Configurations() [1/2]
el::Configurations::Configurations (void)
Default constructor with empty repository.
Definition at line 192 of file easylogging++.cc.
                                    :
   m_configurationFile(std::string()),
   m_isFromFile(false) {
 }
Configurations() [2/2]
el::Configurations::Configurations (const std::string & configurationFile, bool useDefaultsForRemaining = true, Configurations * base = nullptr)
Constructor used to set configurations using configuration file.
Parameters
configurationFile Full path to configuration file
useDefaultsForRemaining Lets you set the remaining configurations to default.
base If provided, this configuration will be based off existing repository that this argument is pointing to.
See also
parseFromFile(const std::string&, Configurations* base)
setRemainingToDefault()
Definition at line 197 of file easylogging++.cc.
References parseFromFile(), and setRemainingToDefault().
                                                      :
   m_configurationFile(configurationFile),
   m_isFromFile(false) {
   parseFromFile(configurationFile, base);
   if (useDefaultsForRemaining) {
     setRemainingToDefault();
   }
 }
~Configurations()
virtual el::Configurations::~Configurations (void) inline virtual
Definition at line 1798 of file easylogging++.h.
{
   }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
begin()
virtual iterator el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::begin (void) inline virtual inherited
Returns
Iterator pointer from start of repository
Definition at line 1365 of file easylogging++.h.
{
     return m_list.begin();
   }
cbegin()
virtual const_iterator el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::cbegin (void) const inline virtual inherited
Returns
Constant iterator pointer from start of repository
Definition at line 1376 of file easylogging++.h.
{
     return m_list.cbegin();
   }
cend()
virtual const_iterator el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::cend (void) const inline virtual inherited
Returns
End of repository
Definition at line 1381 of file easylogging++.h.
{
     return m_list.cend();
   }
clear()
void el::Configurations::clear (void) inline
Clears repository so that all the configurations are unset.
Definition at line 1866 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     unregisterAll();
   }
configurationFile()
const std::string& el::Configurations::configurationFile (void) const inline
Gets configuration file used in parsing this configurations.
If this repository was set manually or by text this returns empty string.
Definition at line 1874 of file easylogging++.h.
{
     return m_configurationFile;
   }
deepCopy()
virtual void el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::deepCopy (const AbstractRegistry< Configuration , std::vector< Configuration *> > &) protected pure virtual inherited
empty()
virtual bool el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::empty (void) const inline virtual inherited
Returns
Whether or not repository is empty
Definition at line 1386 of file easylogging++.h.
{
     return m_list.empty();
   }
end()
virtual iterator el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::end (void) inline virtual inherited
Returns
Iterator pointer from end of repository
Definition at line 1370 of file easylogging++.h.
{
     return m_list.end();
   }
get() [1/2]
Configuration * el::base::utils::RegistryWithPred< Configuration , Configuration::Predicate >::get (const T & arg1, const T2 arg2) inline protected inherited
Gets pointer from repository with speicifed arguments.
Arguments are passed to predicate in order to validate pointer.
Definition at line 1571 of file easylogging++.h.
Referenced by get(), hasConfiguration(), unsafeSet(), and unsafeSetIfNotExist().
{
     iterator iter = std::find_if(this->list().begin(), this->list().end(), Pred(arg1, arg2));
     if (iter != this->list().end() && *iter != nullptr) {
       return *iter;
     }
     return nullptr;
   }
get() [2/2]
Configuration* el::Configurations::get (Level level, ConfigurationType configurationType) inline
Definition at line 1852 of file easylogging++.h.
References el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >::get().
{
     base::threading::ScopedLock scopedLock(lock());
     return RegistryWithPred<Configuration, Configuration::Predicate>::get(level, configurationType);
   }
hasConfiguration() [1/2]
bool el::Configurations::hasConfiguration (ConfigurationType configurationType)
Determines whether or not specified configuration type exists in the repository.
Returns as soon as first level is found.
Parameters
configurationType Type of configuration to check existence for.
Definition at line 239 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), el::LevelHelper::forEachLevel(), and el::LevelHelper::kMinValid.
Referenced by el::Logger::configure().
{
   base::type::EnumType lIndex = LevelHelper::kMinValid;
   bool result = false;
   LevelHelper::forEachLevel(&lIndex, [&](void) -> bool {
     if (hasConfiguration(LevelHelper::castFromInt(lIndex), configurationType)) {
       result = true;
     }
     return result;
   });
   return result;
 }
hasConfiguration() [2/2]
bool el::Configurations::hasConfiguration (Level level, ConfigurationType configurationType)
Determines whether or not specified configuration type exists for specified level.
Parameters
level Level to check
configurationType Type of configuration to check existence for.
Definition at line 251 of file easylogging++.cc.
References el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >::get(), and el::base::threading::ThreadSafe::lock().
{
   base::threading::ScopedLock scopedLock(lock());
 #if ELPP_COMPILER_INTEL
   // We cant specify template types here, Intel C++ throws compilation error
   // "error: type name is not allowed"
   return RegistryWithPred::get(level, configurationType) != nullptr;
 #else
   return RegistryWithPred<Configuration, Configuration::Predicate>::get(level, configurationType) != nullptr;
 #endif  // ELPP_COMPILER_INTEL
 }
list() [1/2]
virtual std::vector< Configuration *> & el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::list (void) inline virtual inherited
Returns underlying container by reference.
Definition at line 1396 of file easylogging++.h.
{
     return m_list;
   }
list() [2/2]
virtual const std::vector< Configuration *> & el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::list (void) const inline virtual inherited
Returns underlying container by constant reference.
Definition at line 1401 of file easylogging++.h.
{
     return m_list;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), set(), setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
operator!=()
bool el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::operator!= (const AbstractRegistry< Configuration , std::vector< Configuration *> > & other) inline inherited
Definition at line 1339 of file easylogging++.h.
{
     if (size() != other.size()) {
       return true;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return true;
       }
     }
     return false;
   }
operator==()
bool el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::operator== (const AbstractRegistry< Configuration , std::vector< Configuration *> > & other) inline inherited
Definition at line 1327 of file easylogging++.h.
{
     if (size() != other.size()) {
       return false;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return false;
       }
     }
     return true;
   }
parseFromFile()
bool el::Configurations::parseFromFile (const std::string & configurationFile, Configurations * base = nullptr)
Parses configuration from file.
Parameters
configurationFile Full path to configuration file
base Configurations to base new configuration repository off. This value is used when you want to use existing Configurations to base all the values and then set rest of configuration via configuration file.
Returns
True if successfully parsed, false otherwise. You may define 'ELPP_DEBUG_ASSERT_FAILURE' to make sure you do not proceed without successful parse.
Definition at line 207 of file easylogging++.cc.
References ELPP_ASSERT, m_isFromFile, el::Configurations::Parser::parseFromFile(), and el::base::utils::File::pathExists().
Referenced by Configurations().
{
   // We initial assertion with true because if we have assertion diabled, we want to pass this
   // check and if assertion is enabled we will have values re-assigned any way.
   bool assertionPassed = true;
   ELPP_ASSERT((assertionPassed = base::utils::File::pathExists(configurationFile.c_str(), true)) == true,
               "Configuration file [" << configurationFile << "] does not exist!");
   if (!assertionPassed) {
     return false;
   }
   bool success = Parser::parseFromFile(configurationFile, this, base);
   m_isFromFile = success;
   return success;
 }
parseFromText()
bool el::Configurations::parseFromText (const std::string & configurationsString, Configurations * base = nullptr)
Parse configurations from configuration string.
This configuration string has same syntax as configuration file contents. Make sure all the necessary new line characters are provided.
Parameters
base Configurations to base new configuration repository off. This value is used when you want to use existing Configurations to base all the values and then set rest of configuration via configuration text.
Returns
True if successfully parsed, false otherwise. You may define 'ELPP_DEBUG_ASSERT_FAILURE' to make sure you do not proceed without successful parse.
Definition at line 221 of file easylogging++.cc.
References m_isFromFile, and el::Configurations::Parser::parseFromText().
Referenced by el::Loggers::configureFromGlobal().
{
   bool success = Parser::parseFromText(configurationsString, this, base);
   if (success) {
     m_isFromFile = false;
   }
   return success;
 }
registerNew()
virtual void el::base::utils::RegistryWithPred< Configuration , Configuration::Predicate >::registerNew (Configuration * ptr) inline protected virtual inherited
Definition at line 1564 of file easylogging++.h.
Referenced by unsafeSet().
{
     this->list().push_back(ptr);
   }
reinitDeepCopy()
void el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::reinitDeepCopy (const AbstractRegistry< Configuration , std::vector< Configuration *> > & sr) inline protected inherited
Definition at line 1410 of file easylogging++.h.
{
     unregisterAll();
     deepCopy(sr);
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
set() [1/2]
void el::Configurations::set (Level level, ConfigurationType configurationType, const std::string & value)
Sets value of configuration for specified level.
Any existing configuration for specified level will be replaced. Also note that configuration types ConfigurationType::SubsecondPrecision and ConfigurationType::PerformanceTracking will be ignored if not set for Level::Global because these configurations are not dependant on level.
Parameters
level Level to set configuration for (el::Level).
configurationType Type of configuration (el::ConfigurationType)
value A string based value. Regardless of what the data type of configuration is, it will always be string from users' point of view. This is then parsed later to be used internally.
See also
Configuration::setValue(const std::string& value)
el::Level
el::ConfigurationType
Definition at line 262 of file easylogging++.cc.
References el::Global, el::base::threading::ThreadSafe::lock(), unsafeSet(), and unsafeSetGlobally().
Referenced by el::Configurations::Parser::parseLine(), el::Loggers::reconfigureAllLoggers(), and el::Loggers::reconfigureLogger().
{
   base::threading::ScopedLock scopedLock(lock());
   unsafeSet(level, configurationType, value);  // This is not unsafe anymore as we have locked mutex
   if (level == Level::Global) {
     unsafeSetGlobally(configurationType, value, false);  // Again this is not unsafe either
   }
 }
set() [2/2]
void el::Configurations::set (Configuration * conf)
Sets single configuration based on other single configuration.
See also
set(Level level, ConfigurationType configurationType, const std::string& value)
Definition at line 270 of file easylogging++.cc.
References el::Configuration::configurationType(), el::Configuration::level(), and el::Configuration::value().
{
   if (conf == nullptr) {
     return;
   }
   set(conf->level(), conf->configurationType(), conf->value());
 }
setFromBase()
void el::Configurations::setFromBase (Configurations * base)
Sets configuration based-off an existing configurations.
Parameters
base Pointer to existing configurations.
Definition at line 229 of file easylogging++.cc.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::list(), and el::base::threading::ThreadSafe::lock().
Referenced by el::Logger::configure(), el::Configurations::Parser::parseFromFile(), and el::Configurations::Parser::parseFromText().
{
   if (base == nullptr || base == this) {
     return;
   }
   base::threading::ScopedLock scopedLock(base->lock());
   for (Configuration*& conf : base->list()) {
     set(conf);
   }
 }
setGlobally() [1/2]
void el::Configurations::setGlobally (ConfigurationType configurationType, const std::string & value) inline
Sets configuration for all levels.
Parameters
configurationType Type of configuration
value String based value
See also
Configurations::set(Level level, ConfigurationType configurationType, const std::string& value)
Definition at line 1861 of file easylogging++.h.
Referenced by el::base::Storage::setApplicationArguments(), setToDefault(), and el::base::Storage::Storage().
{
     setGlobally(configurationType, value, false);
   }
setGlobally() [2/2]
void el::Configurations::setGlobally (ConfigurationType configurationType, const std::string & value, bool includeGlobalLevel) private
Sets configurations for all levels including Level::Global if includeGlobalLevel is true.
See also
Configurations::setGlobally(ConfigurationType configurationType, const std::string& value)
Definition at line 478 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), el::LevelHelper::forEachLevel(), el::Global, and el::LevelHelper::kMinValid.
{
   if (includeGlobalLevel) {
     set(Level::Global, configurationType, value);
   }
   base::type::EnumType lIndex = LevelHelper::kMinValid;
   LevelHelper::forEachLevel(&lIndex, [&](void) -> bool {
     set(LevelHelper::castFromInt(lIndex), configurationType, value);
     return false;  // Do not break lambda function yet as we need to set all levels regardless
   });
 }
setRemainingToDefault()
void el::Configurations::setRemainingToDefault (void)
Lets you set the remaining configurations to default.
By remaining, it means that the level/type a configuration does not exist for. This function is useful when you want to minimize chances of failures, e.g, if you have a configuration file that sets configuration for all the configurations except for Enabled or not, we use this so that ENABLED is set to default i.e, true. If you dont do this explicitly (either by calling this function or by using second param in Constructor and try to access a value, an error is thrown
Definition at line 305 of file easylogging++.cc.
References el::Debug, el::Enabled, el::Error, el::Fatal, el::Filename, el::Format, el::Global, el::base::threading::ThreadSafe::lock(), el::MaxLogFileSize, el::PerformanceTracking, el::SubsecondPrecision, el::ToStandardOutput, el::Trace, unsafeSetIfNotExist(), and el::Verbose.
Referenced by Configurations().
{
   base::threading::ScopedLock scopedLock(lock());
 #if defined(ELPP_NO_LOG_TO_FILE)
   unsafeSetIfNotExist(Level::Global, ConfigurationType::Enabled, std::string("false"));
 #else
   unsafeSetIfNotExist(Level::Global, ConfigurationType::Enabled, std::string("true"));
 #endif // defined(ELPP_NO_LOG_TO_FILE)
 #if !defined(ELPP_NO_DEFAULT_LOG_FILE)
   unsafeSetIfNotExist(Level::Global, ConfigurationType::Filename, std::string(base::consts::kDefaultLogFile));
 #endif  // !defined(ELPP_NO_DEFAULT_LOG_FILE)
   unsafeSetIfNotExist(Level::Global, ConfigurationType::ToStandardOutput, std::string("true"));
   unsafeSetIfNotExist(Level::Global, ConfigurationType::SubsecondPrecision, std::string("3"));
   unsafeSetIfNotExist(Level::Global, ConfigurationType::PerformanceTracking, std::string("true"));
   unsafeSetIfNotExist(Level::Global, ConfigurationType::MaxLogFileSize, std::string("0"));
   unsafeSetIfNotExist(Level::Global, ConfigurationType::Format, std::string("%datetime %level [%logger] %msg"));
   unsafeSetIfNotExist(Level::Debug, ConfigurationType::Format,
                       std::string("%datetime %level [%logger] [%user@%host] [%func] [%loc] %msg"));
   // INFO and WARNING are set to default by Level::Global
   unsafeSetIfNotExist(Level::Error, ConfigurationType::Format, std::string("%datetime %level [%logger] %msg"));
   unsafeSetIfNotExist(Level::Fatal, ConfigurationType::Format, std::string("%datetime %level [%logger] %msg"));
   unsafeSetIfNotExist(Level::Verbose, ConfigurationType::Format, std::string("%datetime %level-%vlevel [%logger] %msg"));
   unsafeSetIfNotExist(Level::Trace, ConfigurationType::Format,
                       std::string("%datetime %level [%logger] [%func] [%loc] %msg"));
 }
setToDefault()
void el::Configurations::setToDefault (void)
Sets configurations to "factory based" configurations.
Definition at line 277 of file easylogging++.cc.
References el::Debug, ELPP_UNUSED, el::Enabled, el::Error, el::Fatal, el::Filename, el::Format, el::LogFlushThreshold, el::MaxLogFileSize, el::PerformanceTracking, setGlobally(), el::SubsecondPrecision, el::ToFile, el::ToStandardOutput, el::Trace, and el::Verbose.
Referenced by el::base::RegisteredLoggers::RegisteredLoggers().
{
   setGlobally(ConfigurationType::Enabled, std::string("true"), true);
 #if !defined(ELPP_NO_DEFAULT_LOG_FILE)
   setGlobally(ConfigurationType::Filename, std::string(base::consts::kDefaultLogFile), true);
 #else
   ELPP_UNUSED(base::consts::kDefaultLogFile);
 #endif  // !defined(ELPP_NO_DEFAULT_LOG_FILE)
 #if defined(ELPP_NO_LOG_TO_FILE)
   setGlobally(ConfigurationType::ToFile, std::string("false"), true);
 #else
   setGlobally(ConfigurationType::ToFile, std::string("true"), true);
 #endif // defined(ELPP_NO_LOG_TO_FILE)
   setGlobally(ConfigurationType::ToStandardOutput, std::string("true"), true);
   setGlobally(ConfigurationType::SubsecondPrecision, std::string("3"), true);
   setGlobally(ConfigurationType::PerformanceTracking, std::string("true"), true);
   setGlobally(ConfigurationType::MaxLogFileSize, std::string("0"), true);
   setGlobally(ConfigurationType::LogFlushThreshold, std::string("0"), true);
   setGlobally(ConfigurationType::Format, std::string("%datetime %level [%logger] %msg"), true);
   set(Level::Debug, ConfigurationType::Format,
       std::string("%datetime %level [%logger] [%user@%host] [%func] [%loc] %msg"));
   // INFO and WARNING are set to default by Level::Global
   set(Level::Error, ConfigurationType::Format, std::string("%datetime %level [%logger] %msg"));
   set(Level::Fatal, ConfigurationType::Format, std::string("%datetime %level [%logger] %msg"));
   set(Level::Verbose, ConfigurationType::Format, std::string("%datetime %level-%vlevel [%logger] %msg"));
   set(Level::Trace, ConfigurationType::Format, std::string("%datetime %level [%logger] [%func] [%loc] %msg"));
 }
size()
virtual std::size_t el::base::utils::AbstractRegistry< Configuration , std::vector< Configuration *> >::size (void) const inline virtual inherited
Returns
Size of repository
Definition at line 1391 of file easylogging++.h.
{
     return m_list.size();
   }
unregister()
virtual void el::base::utils::RegistryWithPred< Configuration , Configuration::Predicate >::unregister (Configuration *& ptr) inline protected virtual inherited
Definition at line 1549 of file easylogging++.h.
{
     if (ptr) {
       iterator iter = this->begin();
       for (; iter != this->end(); ++iter) {
         if (ptr == *iter) {
           break;
         }
       }
       if (iter != this->end() && *iter != nullptr) {
         this->list().erase(iter);
         base::utils::safeDelete(*iter);
       }
     }
   }
unregisterAll()
virtual void el::base::utils::RegistryWithPred< Configuration , Configuration::Predicate >::unregisterAll (void) inline protected virtual inherited
Unregisters all the pointers from current repository.
Implements el::base::utils::AbstractRegistry< Configuration, std::vector< Configuration *> >.
Definition at line 1540 of file easylogging++.h.
{
     if (!this->empty()) {
       for (auto&& curr : this->list()) {
         base::utils::safeDelete(curr);
       }
       this->list().clear();
     }
   }
unsafeSet()
void el::Configurations::unsafeSet (Level level, ConfigurationType configurationType, const std::string & value) private
Thread unsafe set.
Definition at line 466 of file easylogging++.cc.
References el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >::get(), el::Global, el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >::registerNew(), el::Configuration::setValue(), and unsafeSetGlobally().
Referenced by set(), unsafeSetGlobally(), and unsafeSetIfNotExist().
{
   Configuration* conf = RegistryWithPred<Configuration, Configuration::Predicate>::get(level, configurationType);
   if (conf == nullptr) {
     registerNew(new Configuration(level, configurationType, value));
   } else {
     conf->setValue(value);
   }
   if (level == Level::Global) {
     unsafeSetGlobally(configurationType, value, false);
   }
 }
unsafeSetGlobally()
void el::Configurations::unsafeSetGlobally (ConfigurationType configurationType, const std::string & value, bool includeGlobalLevel) private
Sets configurations (Unsafely) for all levels including Level::Global if includeGlobalLevel is true.
See also
Configurations::setGlobally(ConfigurationType configurationType, const std::string& value)
Definition at line 490 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), el::LevelHelper::forEachLevel(), el::Global, el::LevelHelper::kMinValid, and unsafeSet().
Referenced by set(), and unsafeSet().
{
   if (includeGlobalLevel) {
     unsafeSet(Level::Global, configurationType, value);
   }
   base::type::EnumType lIndex = LevelHelper::kMinValid;
   LevelHelper::forEachLevel(&lIndex, [&](void) -> bool  {
     unsafeSet(LevelHelper::castFromInt(lIndex), configurationType, value);
     return false;  // Do not break lambda function yet as we need to set all levels regardless
   });
 }
unsafeSetIfNotExist()
void el::Configurations::unsafeSetIfNotExist (Level level, ConfigurationType configurationType, const std::string & value) private
Unsafely sets configuration if does not already exist.
Definition at line 459 of file easylogging++.cc.
References el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >::get(), and unsafeSet().
Referenced by setRemainingToDefault().
{
   Configuration* conf = RegistryWithPred<Configuration, Configuration::Predicate>::get(level, configurationType);
   if (conf == nullptr) {
     unsafeSet(level, configurationType, value);
   }
 }
Friends And Related Function Documentation
el::Loggers
friend class el::Loggers friend
Definition at line 1932 of file easylogging++.h.
Member Data Documentation
m_configurationFile
std::string el::Configurations::m_configurationFile private
Definition at line 1930 of file easylogging++.h.
m_isFromFile
bool el::Configurations::m_isFromFile private
Definition at line 1931 of file easylogging++.h.
Referenced by parseFromFile(), and parseFromText().
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc