VulpesRender: el::base::PErrorWriter Class Reference
el::base::PErrorWriter Class Reference
#include <easylogging++.h>
Public Member Functions
PErrorWriter (Level level, const char *file, base::type::LineNumber line, const char *func, base::DispatchAction dispatchAction=base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel=0)
virtual ~PErrorWriter (void)
template<typename T >
Writer & operator<< (const T &log)
Writer & operator<< (std::ostream &(*log)(std::ostream &))
operator bool ()
Writer & construct (Logger *logger, bool needLock=true)
Writer & construct (int count, const char *loggerIds,...)
Protected Member Functions
void initializeLogger (const std::string &loggerId, bool lookup=true, bool needLock=true)
void processDispatch ()
void triggerDispatch (void)
Protected Attributes
Level m_level
const char * m_file
const base::type::LineNumber m_line
const char * m_func
base::type::VerboseLevel m_verboseLevel
Logger * m_logger
bool m_proceed
base::MessageBuilder m_messageBuilder
base::DispatchAction m_dispatchAction
std::vector< std::string > m_loggerIds
Detailed Description
Definition at line 3286 of file easylogging++.h.
Constructor & Destructor Documentation
PErrorWriter()
el::base::PErrorWriter::PErrorWriter (Level level, const char * file, base::type::LineNumber line, const char * func, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel = 0) inline
Definition at line 3288 of file easylogging++.h.
References el::base::Writer::construct(), el::Debug, ELPP, ELPP_INTERNAL_ERROR, ELPP_LITERAL, el::Error, el::Fatal, el::Info, el::base::MessageBuilder::initialize(), el::base::consts::kFormatSpecifierChar, el::Logger::log(), el::base::NormalLog, el::Trace, el::Verbose, and el::Warning.
                                                       :
     base::Writer(level, file, line, func, dispatchAction, verboseLevel) {
   }
~PErrorWriter()
el::base::PErrorWriter::~PErrorWriter (void) virtual
Definition at line 2535 of file easylogging++.cc.
References el::base::utils::abort(), ELPP, ELPP_INTERNAL_INFO, ELPP_LITERAL, ELPP_UNUSED, ELPP_WRITE_LOG, el::Callback< T >::enabled(), el::Fatal, el::FixedTimeFormat, el::base::utils::DateTime::formatTime(), el::base::utils::DateTime::getTimeDifference(), el::base::utils::DateTime::gettimeofday(), el::Callback< T >::handle(), el::base::consts::kCrashSignals, el::base::consts::kCrashSignalsCount, el::base::consts::kDefaultLoggerId, el::base::consts::kTimeFormats, el::base::VRegistry::level(), el::base::threading::ThreadSafe::lock(), el::LogDetailedCrashReason, el::base::VRegistry::m_level, el::Logger::m_typedConfigurations, el::base::NormalLog, el::base::utils::operator<<(), and el::base::TypedConfigurations::performanceTracking().
{
   if (m_proceed) {
 #if ELPP_COMPILER_MSVC
     char buff[256];
     strerror_s(buff, 256, errno);
     m_logger->stream() << ": " << buff << " [" << errno << "]";
 #else
     m_logger->stream() << ": " << strerror(errno) << " [" << errno << "]";
 #endif
   }
 }
Member Function Documentation
construct() [1/2]
Writer & el::base::Writer::construct (Logger * logger, bool needLock = true) inherited
Definition at line 2417 of file easylogging++.cc.
References el::Logger::id().
Referenced by el::base::Writer::initializeLogger(), PErrorWriter(), and el::base::Writer::triggerDispatch().
{
   m_logger = logger;
   initializeLogger(logger->id(), false, needLock);
   m_messageBuilder.initialize(m_logger);
   return *this;
 }
construct() [2/2]
Writer & el::base::Writer::construct (int count, const char * loggerIds, ...) inherited
Definition at line 2424 of file easylogging++.cc.
References ELPP, and el::MultiLoggerSupport.
{
   if (ELPP->hasFlag(LoggingFlag::MultiLoggerSupport)) {
     va_list loggersList;
     va_start(loggersList, loggerIds);
     const char* id = loggerIds;
     for (int i = 0; i < count; ++i) {
       m_loggerIds.push_back(std::string(id));
       id = va_arg(loggersList, const char*);
     }
     va_end(loggersList);
     initializeLogger(m_loggerIds.at(0));
   } else {
     initializeLogger(std::string(loggerIds));
   }
   m_messageBuilder.initialize(m_logger);
   return *this;
 }
initializeLogger()
void el::base::Writer::initializeLogger (const std::string & loggerId, bool lookup = true, bool needLock = true) protected inherited
Definition at line 2442 of file easylogging++.cc.
References el::LevelHelper::castToInt(), el::base::Writer::construct(), el::CreateLoggerAutomatically, el::Debug, ELPP, el::HierarchicalLogging, el::base::consts::kDefaultLoggerId, el::base::VRegistry::m_level, and el::Verbose.
{
   if (lookup) {
     m_logger = ELPP->registeredLoggers()->get(loggerId, ELPP->hasFlag(LoggingFlag::CreateLoggerAutomatically));
   }
   if (m_logger == nullptr) {
     ELPP->acquireLock();
     if (!ELPP->registeredLoggers()->has(std::string(base::consts::kDefaultLoggerId))) {
       // Somehow default logger has been unregistered. Not good! Register again
       ELPP->registeredLoggers()->get(std::string(base::consts::kDefaultLoggerId));
     }
     ELPP->releaseLock();  // Need to unlock it for next writer
     Writer(Level::Debug, m_file, m_line, m_func).construct(1, base::consts::kDefaultLoggerId)
         << "Logger [" << loggerId << "] is not registered yet!";
     m_proceed = false;
   } else {
     if (needLock) {
       m_logger->acquireLock();  // This should not be unlocked by checking m_proceed because
       // m_proceed can be changed by lines below
     }
     if (ELPP->hasFlag(LoggingFlag::HierarchicalLogging)) {
       m_proceed = m_level == Level::Verbose ? m_logger->enabled(m_level) :
                   LevelHelper::castToInt(m_level) >= LevelHelper::castToInt(ELPP->m_loggingLevel);
     } else {
       m_proceed = m_logger->enabled(m_level);
     }
   }
 }
operator bool()
el::base::Writer::operator bool () inline inherited
Definition at line 3263 of file easylogging++.h.
{
     return true;
   }
operator<<() [1/2]
template<typename T > Writer& el::base::Writer::operator<< (const T & log) inline inherited
Definition at line 3245 of file easylogging++.h.
{
 #if ELPP_LOGGING_ENABLED
     if (m_proceed) {
       m_messageBuilder << log;
     }
 #endif  // ELPP_LOGGING_ENABLED
     return *this;
   }
operator<<() [2/2]
Writer& el::base::Writer::operator<< (std::ostream &(*)(std::ostream &) log) inline inherited
Definition at line 3254 of file easylogging++.h.
{
 #if ELPP_LOGGING_ENABLED
     if (m_proceed) {
       m_messageBuilder << log;
     }
 #endif  // ELPP_LOGGING_ENABLED
     return *this;
   }
processDispatch()
void el::base::Writer::processDispatch () protected inherited
Definition at line 2470 of file easylogging++.cc.
References ELPP, ELPP_LITERAL, and el::MultiLoggerSupport.
{
 #if ELPP_LOGGING_ENABLED
   if (ELPP->hasFlag(LoggingFlag::MultiLoggerSupport)) {
     bool firstDispatched = false;
     base::type::string_t logMessage;
     std::size_t i = 0;
     do {
       if (m_proceed) {
         if (firstDispatched) {
           m_logger->stream() << logMessage;
         } else {
           firstDispatched = true;
           if (m_loggerIds.size() > 1) {
             logMessage = m_logger->stream().str();
           }
         }
         triggerDispatch();
       } else if (m_logger != nullptr) {
         m_logger->stream().str(ELPP_LITERAL(""));
         m_logger->releaseLock();
       }
       if (i + 1 < m_loggerIds.size()) {
         initializeLogger(m_loggerIds.at(i + 1));
       }
     } while (++i < m_loggerIds.size());
   } else {
     if (m_proceed) {
       triggerDispatch();
     } else if (m_logger != nullptr) {
       m_logger->stream().str(ELPP_LITERAL(""));
       m_logger->releaseLock();
     }
   }
 #else
   if (m_logger != nullptr) {
     m_logger->stream().str(ELPP_LITERAL(""));
     m_logger->releaseLock();
   }
 #endif // ELPP_LOGGING_ENABLED
 }
triggerDispatch()
void el::base::Writer::triggerDispatch (void) protected inherited
Definition at line 2511 of file easylogging++.cc.
References el::base::utils::abort(), el::base::Writer::construct(), el::DisableApplicationAbortOnFatalLog, el::base::LogDispatcher::dispatch(), ELPP, ELPP_LITERAL, el::Fatal, el::base::consts::kDefaultLoggerId, el::base::LogMessage, el::base::VRegistry::m_level, and el::Warning.
{
   if (m_proceed) {
     base::LogDispatcher(m_proceed, LogMessage(m_level, m_file, m_line, m_func, m_verboseLevel,
                         m_logger), m_dispatchAction).dispatch();
   }
   if (m_logger != nullptr) {
     m_logger->stream().str(ELPP_LITERAL(""));
     m_logger->releaseLock();
   }
   if (m_proceed && m_level == Level::Fatal
       && !ELPP->hasFlag(LoggingFlag::DisableApplicationAbortOnFatalLog)) {
     base::Writer(Level::Warning, m_file, m_line, m_func).construct(1, base::consts::kDefaultLoggerId)
         << "Aborting application. Reason: Fatal log at [" << m_file << ":" << m_line << "]";
     std::stringstream reasonStream;
     reasonStream << "Fatal log at [" << m_file << ":" << m_line << "]"
                  << " If you wish to disable 'abort on fatal log' please use "
                  << "el::Helpers::addFlag(el::LoggingFlag::DisableApplicationAbortOnFatalLog)";
     base::utils::abort(1, reasonStream.str());
   }
   m_proceed = false;
 }
Member Data Documentation
m_dispatchAction
base::DispatchAction el::base::Writer::m_dispatchAction protected inherited
Definition at line 3278 of file easylogging++.h.
m_file
const char* el::base::Writer::m_file protected inherited
Definition at line 3271 of file easylogging++.h.
m_func
const char* el::base::Writer::m_func protected inherited
Definition at line 3273 of file easylogging++.h.
m_level
Level el::base::Writer::m_level protected inherited
Definition at line 3270 of file easylogging++.h.
m_line
const base::type::LineNumber el::base::Writer::m_line protected inherited
Definition at line 3272 of file easylogging++.h.
m_logger
Logger* el::base::Writer::m_logger protected inherited
Definition at line 3275 of file easylogging++.h.
m_loggerIds
std::vector<std::string> el::base::Writer::m_loggerIds protected inherited
Definition at line 3279 of file easylogging++.h.
m_messageBuilder
base::MessageBuilder el::base::Writer::m_messageBuilder protected inherited
Definition at line 3277 of file easylogging++.h.
m_proceed
bool el::base::Writer::m_proceed protected inherited
Definition at line 3276 of file easylogging++.h.
m_verboseLevel
base::type::VerboseLevel el::base::Writer::m_verboseLevel protected inherited
Definition at line 3274 of file easylogging++.h.
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc