VulpesRender: vpr::Swapchain Class Reference
vpr::Swapchain Class Reference
Rendering
This class abstracts away much of the detailed work and boilerplate code required to setup a swapchain in Vulkan.
#include <Swapchain.hpp>
Classes
struct SwapchainInfo
SwapchainInfo takes care of hiding away much of the setup work required to create a swapchain.
Public Member Functions
Swapchain (const Instance *_instance, const Device *_device)
~Swapchain ()
void Recreate ()
void Destroy ()
const VkSwapchainKHR & vkHandle () const noexcept
const VkExtent2D & Extent () const noexcept
const uint32_t & ImageCount () const noexcept
const VkColorSpaceKHR & ColorSpace () const noexcept
const VkFormat & ColorFormat () const noexcept
const VkImage & Image (const size_t &idx) const
const VkImageView & ImageView (const size_t &idx) const
Private Member Functions
Swapchain (const Swapchain &)=delete
Swapchain & operator= (const Swapchain &)=delete
void create ()
void setParameters ()
void setupCreateInfo ()
void setupSwapImages ()
void setupImageViews ()
Private Attributes
struct vpr::Swapchain::SwapchainInfo info
VkFormat colorFormat
uint32_t imageCount
VkColorSpaceKHR colorSpace
VkExtent2D extent
std::vector< VkImage > images
std::vector< VkImageView > imageViews
VkPresentModeKHR presentMode
VkSurfaceFormatKHR surfaceFormat
VkSwapchainCreateInfoKHR createInfo
VkSwapchainKHR handle = VK_NULL_HANDLE
const Instance * instance
const PhysicalDevice * phys_device
const Device * device
Detailed Description
This class abstracts away much of the detailed work and boilerplate code required to setup a swapchain in Vulkan.
Init() only needs to be called once during runtime: recreating the swapchain is easily accomplished using the appropriate recreation method.
Definition at line 13 of file Swapchain.hpp.
Constructor & Destructor Documentation
Swapchain() [1/2]
vpr::Swapchain::Swapchain (const Swapchain &) private delete
Swapchain() [2/2]
vpr::Swapchain::Swapchain (const Instance * _instance, const Device * _device)
Definition at line 81 of file Swapchain.cpp.
References create().
                                                                            : instance(_instance), device(_device), info(_device->GetPhysicalDevice().vkHandle(), _instance->vkSurface()) {
         create();
     }
~Swapchain()
vpr::Swapchain::~Swapchain ()
Definition at line 85 of file Swapchain.cpp.
References Destroy().
{
         Destroy();
     }
Member Function Documentation
ColorFormat()
const VkFormat & vpr::Swapchain::ColorFormat () const noexcept
Definition at line 198 of file Swapchain.cpp.
References colorFormat.
{
         return colorFormat;
     }
ColorSpace()
const VkColorSpaceKHR & vpr::Swapchain::ColorSpace () const noexcept
Definition at line 194 of file Swapchain.cpp.
References colorSpace.
{
         return colorSpace;
     }
create()
void vpr::Swapchain::create () private
Definition at line 210 of file Swapchain.cpp.
References createInfo, device, handle, setParameters(), setupCreateInfo(), setupImageViews(), setupSwapImages(), VkAssert, and vpr::Device::vkHandle().
Referenced by Recreate(), and Swapchain().
{
         setParameters();
         setupCreateInfo();
         VkResult result = vkCreateSwapchainKHR(device->vkHandle(), &createInfo, nullptr, &handle);
         VkAssert(result);
         setupSwapImages();
         setupImageViews();
     }
Destroy()
void vpr::Swapchain::Destroy ()
Definition at line 171 of file Swapchain.cpp.
References device, handle, imageViews, and vpr::Device::vkHandle().
Referenced by vpr::RecreateSwapchainAndSurface(), and ~Swapchain().
{
         for (const auto& view : imageViews) {
             if (view != VK_NULL_HANDLE) {
                 vkDestroyImageView(device->vkHandle(), view, nullptr);
             }
         }
         if (handle != VK_NULL_HANDLE) {
             vkDestroySwapchainKHR(device->vkHandle(), handle, nullptr);
         }
     }
Extent()
const VkExtent2D & vpr::Swapchain::Extent () const noexcept
Definition at line 186 of file Swapchain.cpp.
References extent.
{
         return extent;
     }
Image()
const VkImage & vpr::Swapchain::Image (const size_t & idx) const
Definition at line 202 of file Swapchain.cpp.
References images.
{
         return images[idx];
     }
ImageCount()
const uint32_t & vpr::Swapchain::ImageCount () const noexcept
Definition at line 190 of file Swapchain.cpp.
References imageCount.
{
         return imageCount;
     }
ImageView()
const VkImageView & vpr::Swapchain::ImageView (const size_t & idx) const
Definition at line 206 of file Swapchain.cpp.
References imageViews.
{
         return imageViews[idx];
     }
operator=()
Swapchain& vpr::Swapchain::operator= (const Swapchain &) private delete
Recreate()
void vpr::Swapchain::Recreate ()
Definition at line 89 of file Swapchain.cpp.
References create(), device, vpr::Device::GetPhysicalDevice(), imageCount, info, instance, vpr::PhysicalDevice::vkHandle(), and vpr::Instance::vkSurface().
Referenced by vpr::RecreateSwapchainAndSurface().
{
         imageCount = 0;
         info = SwapchainInfo(device->GetPhysicalDevice().vkHandle(), instance->vkSurface());
         create();
     }
setParameters()
void vpr::Swapchain::setParameters () private
Definition at line 95 of file Swapchain.cpp.
References vpr::Swapchain::SwapchainInfo::Capabilities, vpr::Swapchain::SwapchainInfo::ChooseSwapchainExtent(), colorFormat, extent, vpr::Swapchain::SwapchainInfo::GetBestFormat(), vpr::Swapchain::SwapchainInfo::GetBestPresentMode(), vpr::Instance::GetGLFWwindow(), imageCount, info, instance, presentMode, and surfaceFormat.
Referenced by create().
{
         surfaceFormat = info.GetBestFormat();
         colorFormat = surfaceFormat.format;
         presentMode = info.GetBestPresentMode();
         extent = info.ChooseSwapchainExtent(instance->GetGLFWwindow());
         // Create one more image than minspec to implement triple buffering (in hope we got mailbox present mode)
         imageCount = info.Capabilities.minImageCount + 1;
         if (info.Capabilities.maxImageCount > 0 && imageCount > info.Capabilities.maxImageCount) {
             imageCount = info.Capabilities.maxImageCount;
         }
     }
setupCreateInfo()
void vpr::Swapchain::setupCreateInfo () private
Definition at line 110 of file Swapchain.cpp.
References vpr::Swapchain::SwapchainInfo::Capabilities, createInfo, device, extent, vpr::vkQueueFamilyIndices::Graphics, imageCount, info, instance, vpr::vkQueueFamilyIndices::Present, presentMode, vpr::Device::QueueFamilyIndices, surfaceFormat, vpr::vk_swapchain_create_info_base, and vpr::Instance::vkSurface().
Referenced by create().
{
         createInfo = vk_swapchain_create_info_base;
         createInfo.surface = instance->vkSurface();
         createInfo.imageFormat = surfaceFormat.format;
         createInfo.imageColorSpace = surfaceFormat.colorSpace;
         createInfo.imageExtent = extent;
         createInfo.imageArrayLayers = 1;
         createInfo.minImageCount = imageCount;
         createInfo.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
         const uint32_t indices[2] = { static_cast<uint32_t>(device->QueueFamilyIndices.Present), static_cast<uint32_t>(device->QueueFamilyIndices.Graphics) };
         if (device->QueueFamilyIndices.Present != device->QueueFamilyIndices.Graphics) {
             createInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
             createInfo.queueFamilyIndexCount = 2;
             createInfo.pQueueFamilyIndices = indices;
         }
         else {
             createInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
             createInfo.queueFamilyIndexCount = 0;
             createInfo.pQueueFamilyIndices = nullptr;
         }
         createInfo.preTransform = info.Capabilities.currentTransform;
         createInfo.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
         createInfo.presentMode = presentMode;
         createInfo.clipped = VK_TRUE;
         createInfo.oldSwapchain = VK_NULL_HANDLE;
     }
setupImageViews()
void vpr::Swapchain::setupImageViews () private
Definition at line 150 of file Swapchain.cpp.
References colorFormat, device, imageCount, images, imageViews, vpr::vk_image_view_create_info_base, VkAssert, and vpr::Device::vkHandle().
Referenced by create().
{
         // Setup image views
         imageViews.resize(imageCount);
         for (uint32_t i = 0; i < imageCount; ++i) {
             VkImageViewCreateInfo iv_info = vk_image_view_create_info_base;
             iv_info.image = images[i];
             iv_info.viewType = VK_IMAGE_VIEW_TYPE_2D;
             iv_info.format = colorFormat;
             iv_info.components = { VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY };
             iv_info.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
             iv_info.subresourceRange.baseMipLevel = 0;
             iv_info.subresourceRange.levelCount = 1;
             iv_info.subresourceRange.baseArrayLayer = 0;
             iv_info.subresourceRange.layerCount = 1;
             VkResult result = vkCreateImageView(device->vkHandle(), &iv_info, nullptr, &imageViews[i]);
             VkAssert(result);
         }
     }
setupSwapImages()
void vpr::Swapchain::setupSwapImages () private
Definition at line 141 of file Swapchain.cpp.
References device, handle, imageCount, images, and vpr::Device::vkHandle().
Referenced by create().
{
         // Setup swap images
         vkGetSwapchainImagesKHR(device->vkHandle(), handle, &imageCount, nullptr);
         images.resize(imageCount);
         vkGetSwapchainImagesKHR(device->vkHandle(), handle, &imageCount, images.data());
     }
vkHandle()
const VkSwapchainKHR & vpr::Swapchain::vkHandle () const noexcept
Definition at line 182 of file Swapchain.cpp.
References handle.
{
         return handle;
     }
Member Data Documentation
colorFormat
VkFormat vpr::Swapchain::colorFormat private
Definition at line 50 of file Swapchain.hpp.
Referenced by ColorFormat(), setParameters(), and setupImageViews().
colorSpace
VkColorSpaceKHR vpr::Swapchain::colorSpace private
Definition at line 52 of file Swapchain.hpp.
Referenced by ColorSpace().
createInfo
VkSwapchainCreateInfoKHR vpr::Swapchain::createInfo private
Definition at line 64 of file Swapchain.hpp.
Referenced by create(), and setupCreateInfo().
device
const Device* vpr::Swapchain::device private
Definition at line 68 of file Swapchain.hpp.
Referenced by create(), Destroy(), Recreate(), setupCreateInfo(), setupImageViews(), and setupSwapImages().
extent
VkExtent2D vpr::Swapchain::extent private
Definition at line 53 of file Swapchain.hpp.
Referenced by Extent(), setParameters(), and setupCreateInfo().
handle
VkSwapchainKHR vpr::Swapchain::handle = VK_NULL_HANDLE private
Definition at line 65 of file Swapchain.hpp.
Referenced by create(), Destroy(), setupSwapImages(), and vkHandle().
imageCount
uint32_t vpr::Swapchain::imageCount private
Definition at line 51 of file Swapchain.hpp.
Referenced by ImageCount(), Recreate(), setParameters(), setupCreateInfo(), setupImageViews(), and setupSwapImages().
images
std::vector<VkImage> vpr::Swapchain::images private
Definition at line 55 of file Swapchain.hpp.
Referenced by Image(), setupImageViews(), and setupSwapImages().
imageViews
std::vector<VkImageView> vpr::Swapchain::imageViews private
Definition at line 56 of file Swapchain.hpp.
Referenced by Destroy(), ImageView(), and setupImageViews().
instance
const Instance* vpr::Swapchain::instance private
Definition at line 66 of file Swapchain.hpp.
Referenced by Recreate(), setParameters(), and setupCreateInfo().
phys_device
const PhysicalDevice* vpr::Swapchain::phys_device private
Definition at line 67 of file Swapchain.hpp.
presentMode
VkPresentModeKHR vpr::Swapchain::presentMode private
Definition at line 62 of file Swapchain.hpp.
Referenced by setParameters(), and setupCreateInfo().
surfaceFormat
VkSurfaceFormatKHR vpr::Swapchain::surfaceFormat private
Definition at line 63 of file Swapchain.hpp.
Referenced by setParameters(), and setupCreateInfo().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/render/Swapchain.hpp
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/render/Swapchain.cpp