VulpesRender: vpr::Allocation Class Reference
vpr::Allocation Class Reference
Allocation
Allocation class represents a singular allocation: can be a private allocation (i.e, only user of attached DeviceMemory) or a block allocation (bound to sub-region of device memory)
#include <Allocation.hpp>
Public Member Functions
Allocation ()
If this is an allocation bound to a smaller region of a larger object, it is a block allocation.
~Allocation ()
Allocation (const Allocation &)
Allocation & operator= (const Allocation &)
Allocation (Allocation &&other) noexcept
Allocation & operator= (Allocation &&other) noexcept
void Init (MemoryBlock *parent_block, const VkDeviceSize &offset, const VkDeviceSize &alignment, const VkDeviceSize &alloc_size, void *user_data=nullptr)
void Update (MemoryBlock *new_parent_block, const VkDeviceSize &new_offset)
void InitPrivate (const uint32_t &type_idx, VkDeviceMemory &dvc_memory, bool persistently_mapped, void *mapped_data, const VkDeviceSize &data_size, void *user_data=nullptr)
void Map (const VkDeviceSize &size_to_map, const VkDeviceSize &offset_to_map_at, void **address_to_map_to) const
void Unmap () const noexcept
const VkDeviceMemory & Memory () const
VkDeviceSize Offset () const noexcept
uint32_t MemoryTypeIdx () const
void SetUserData (void *data) const
void * GetUserData () const
bool IsPrivateAllocation () const noexcept
bool operator== (const Allocation &other) const noexcept
Public Attributes
VkDeviceSize Size
VkDeviceSize Alignment
Private Attributes
std::unique_ptr< AllocationImpl > impl
void * userData { nullptr }
Detailed Description
Allocation class represents a singular allocation: can be a private allocation (i.e, only user of attached DeviceMemory) or a block allocation (bound to sub-region of device memory)
Definition at line 17 of file Allocation.hpp.
Constructor & Destructor Documentation
Allocation() [1/3]
vpr::Allocation::Allocation ()
If this is an allocation bound to a smaller region of a larger object, it is a block allocation.
Otherwise, it has it's own VkDeviceMemory object and is a "PRIVATE_ALLOCATION" type.
Definition at line 32 of file Allocation.cpp.
 : Size(0), Alignment(0), impl(std::make_unique<AllocationImpl>()) {}
~Allocation()
vpr::Allocation::~Allocation ()
Definition at line 34 of file Allocation.cpp.
References impl.
{
         impl.reset();
     }
Allocation() [2/3]
vpr::Allocation::Allocation (const Allocation & other)
Definition at line 38 of file Allocation.cpp.
 : Size(other.Size), Alignment(other.Alignment), impl(std::make_unique<AllocationImpl>(*other.impl)) {}
Allocation() [3/3]
vpr::Allocation::Allocation (Allocation && other) noexcept
Definition at line 47 of file Allocation.cpp.
                                                        : Size(std::move(other.Size)), Alignment(std::move(other.Alignment)),
         impl(std::move(other.impl)) {}
Member Function Documentation
GetUserData()
void* vpr::Allocation::GetUserData () const
Init()
void vpr::Allocation::Init (MemoryBlock * parent_block, const VkDeviceSize & offset, const VkDeviceSize & alignment, const VkDeviceSize & alloc_size, void * user_data = nullptr)
Definition at line 57 of file Allocation.cpp.
References Alignment, impl, vpr::AllocationImpl::blockAllocation::Offset, vpr::AllocationImpl::blockAllocation::ParentBlock, and Size.
Referenced by vpr::AllocatorImpl::allocateMemoryType().
{
         AllocationImpl::blockAllocation alloc;
         alloc.ParentBlock = parent_block;
         alloc.Offset = offset;
         Size = alloc_size;
         Alignment = alignment;
         impl->typeData = std::move(alloc);
         impl->userData = user_data;
     }
InitPrivate()
void vpr::Allocation::InitPrivate (const uint32_t & type_idx, VkDeviceMemory & dvc_memory, bool persistently_mapped, void * mapped_data, const VkDeviceSize & data_size, void * user_data = nullptr)
Parameters
persistently_mapped If set, this object will be considered to be always mapped. This will remove any worries about mapping/unmapping the object.
Definition at line 77 of file Allocation.cpp.
References vpr::AllocationImpl::privateAllocation::DvcMemory, impl, vpr::AllocationImpl::privateAllocation::MappedData, vpr::AllocationImpl::privateAllocation::MemoryTypeIdx, vpr::AllocationImpl::privateAllocation::PersistentlyMapped, and Size.
Referenced by vpr::AllocatorImpl::allocatePrivateMemory().
{
         Size = data_size;
         AllocationImpl::privateAllocation p_alloc;
         p_alloc.DvcMemory = dvc_memory;
         p_alloc.MemoryTypeIdx = type_idx;
         p_alloc.PersistentlyMapped = persistently_mapped;
         p_alloc.MappedData = mapped_data;
         impl->typeData = std::move(p_alloc);
         impl->userData = user_data;
     }
IsPrivateAllocation()
bool vpr::Allocation::IsPrivateAllocation () const noexcept
Definition at line 205 of file Allocation.cpp.
References impl.
Referenced by vpr::Allocator::FreeMemory(), vpr::AllocatorImpl::freePrivateMemory(), and operator==().
{
 #ifdef __APPLE_CC__
         switch(impl->typeData.which()){
         case 0:
             return false;
         case 1:
             return true;
         default:
             return false;
         };
 #else
         return std::holds_alternative<AllocationImpl::privateAllocation>(impl->typeData);
 #endif
     }
Map()
void vpr::Allocation::Map (const VkDeviceSize & size_to_map, const VkDeviceSize & offset_to_map_at, void ** address_to_map_to) const
Definition at line 88 of file Allocation.cpp.
References impl, and vpr::VERBOSE_LOGGING.
{
 #if __APPLE_CC__
         auto map_private_alloc = [&](AllocationImpl::privateAllocation& alloc) {
             if (alloc.PersistentlyMapped) {
                 *address_to_map_to = alloc.MappedData;
             }
             else {
                 throw std::runtime_error("Private allocation cannot be mapped!");
             }
         };
         switch (impl->typeData.which()) {
         case 0:
             boost::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->Map(this, size_to_map, offset_to_map_at, address_to_map_to);
             break;
         case 1:
             map_private_alloc(boost::get<AllocationImpl::privateAllocation>(impl->typeData));
             break;
         };
 #else
         if (std::holds_alternative<AllocationImpl::blockAllocation>(impl->typeData)) {
             std::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->Map(this, size_to_map, offset_to_map_at, address_to_map_to);
         }
         else if (std::holds_alternative<AllocationImpl::privateAllocation>(impl->typeData)) {
             auto& p_alloc = std::get<AllocationImpl::privateAllocation>(impl->typeData);
             if (p_alloc.PersistentlyMapped) {
                 LOG_IF(VERBOSE_LOGGING, INFO) << "Attempted to map private allocation, setting given address_to_map_to to permanently mapped address.";
                 *address_to_map_to = std::get<AllocationImpl::privateAllocation>(impl->typeData).MappedData;
             }
             else {
                 throw std::runtime_error("Given private allocation is not mapped.");
             }
         }
 #endif
     }
Memory()
const VkDeviceMemory & vpr::Allocation::Memory () const
Definition at line 139 of file Allocation.cpp.
References impl.
Referenced by vpr::Allocator::AllocateForBuffer(), vpr::Allocator::AllocateForImage(), vpr::Buffer::CopyTo(), vpr::Buffer::Map(), operator==(), vpr::Buffer::setMappedMemoryRange(), and vpr::Buffer::Unmap().
{
 #ifdef __APPLE_CC__
         switch (impl->typeData.which()) {
         case 0:
             return boost::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->Memory();
         case 1:
             return boost::get<AllocationImpl::privateAllocation>(impl->typeData).DvcMemory;
         default:
             throw std::runtime_error("Allocation had invalid type!");
         };
 #else
         if (std::holds_alternative<AllocationImpl::blockAllocation>(impl->typeData)) {
             return std::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->Memory();
         }
         else if (std::holds_alternative<AllocationImpl::privateAllocation>(impl->typeData)) {
             return std::get<AllocationImpl::privateAllocation>(impl->typeData).DvcMemory;
         }
         else {
             throw std::runtime_error("Allocation had invalid type or was improperly initialized!");
         }
 #endif
     }
MemoryTypeIdx()
uint32_t vpr::Allocation::MemoryTypeIdx () const
Definition at line 182 of file Allocation.cpp.
References impl.
Referenced by vpr::Allocator::FreeMemory(), and operator==().
{
 #ifdef __APPLE_CC__
         switch (impl->typeData.which()) {
         case 0:
             return boost::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->MemoryTypeIdx;
         case 1:
             return boost::get<AllocationImpl::privateAllocation>(impl->typeData).MemoryTypeIdx;
         default:
             throw std::runtime_error("Allocation had invalid type!");
         };
 #else
         if (std::holds_alternative<AllocationImpl::blockAllocation>(impl->typeData)) {
             return std::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->MemoryTypeIdx;
         }
         else if (std::holds_alternative<AllocationImpl::privateAllocation>(impl->typeData)) {
             return std::get<AllocationImpl::privateAllocation>(impl->typeData).MemoryTypeIdx;
         }
         else {
             throw std::runtime_error("Allocation had invalid type, or was improperly initialized!");
         }
 #endif
     }
Offset()
VkDeviceSize vpr::Allocation::Offset () const noexcept
Definition at line 162 of file Allocation.cpp.
References impl.
Referenced by vpr::Allocator::AllocateForBuffer(), vpr::Allocator::AllocateForImage(), vpr::Buffer::CopyTo(), vpr::Buffer::CreateMemoryBarrier(), vpr::MemoryBlock::Free(), vpr::MemoryBlock::Map(), vpr::Buffer::Map(), operator==(), and vpr::Buffer::setMappedMemoryRange().
{
 #ifdef __APPLE_CC__
         switch (impl->typeData.which()) {
         case 0:
             return boost::get<AllocationImpl::blockAllocation>(impl->typeData).Offset;
         case 1:
             return VkDeviceSize(0);
         default:
             throw std::runtime_error("Allocation had invalid type!");
         };
 #else
         if (std::holds_alternative<AllocationImpl::blockAllocation>(impl->typeData)) {
             return std::get<AllocationImpl::blockAllocation>(impl->typeData).Offset;
         }
         else {
             return VkDeviceSize(0);
         }
 #endif
     }
operator=() [1/2]
Allocation & vpr::Allocation::operator= (const Allocation & other)
Definition at line 40 of file Allocation.cpp.
References Alignment, impl, and Size.
{
         Size = other.Size;
         Alignment = other.Alignment;
         impl = std::make_unique<AllocationImpl>(*other.impl);
         return *this;
     }
operator=() [2/2]
Allocation & vpr::Allocation::operator= (Allocation && other) noexcept
Definition at line 50 of file Allocation.cpp.
References Alignment, impl, and Size.
{
         Size = std::move(other.Size);
         Alignment = std::move(other.Alignment);
         impl = std::move(other.impl);
         return *this;
     }
operator==()
bool vpr::Allocation::operator== (const Allocation & other) const noexcept
Definition at line 220 of file Allocation.cpp.
References Alignment, IsPrivateAllocation(), Memory(), MemoryTypeIdx(), Offset(), and Size.
{
         return (Memory() == other.Memory()) && (MemoryTypeIdx() == other.MemoryTypeIdx()) &&
             (Offset() == other.Offset()) && (Size == other.Size) && (Alignment == other.Alignment) &&
             (IsPrivateAllocation() == other.IsPrivateAllocation());
     }
SetUserData()
void vpr::Allocation::SetUserData (void * data) const
Unmap()
void vpr::Allocation::Unmap () const noexcept
Definition at line 123 of file Allocation.cpp.
References impl.
{
 #ifdef __APPLE_CC__
         switch (impl->typeData.which()) {
         case 0:
             boost::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->Unmap();
             break;
         default:
             break;
         };
 #else
         if (std::holds_alternative<AllocationImpl::blockAllocation>(impl->typeData)) {
             std::get<AllocationImpl::blockAllocation>(impl->typeData).ParentBlock->Unmap();
         }
 #endif
     }
Update()
void vpr::Allocation::Update (MemoryBlock * new_parent_block, const VkDeviceSize & new_offset)
Definition at line 67 of file Allocation.cpp.
References impl.
{
 #ifdef __APPLE_CC__
         auto& alloc = boost::get<AllocationImpl::blockAllocation>(impl->typeData);
 #else
         auto& alloc = std::get<AllocationImpl::blockAllocation>(impl->typeData);
 #endif
         alloc.ParentBlock = new_parent_block;
         alloc.Offset = new_offset;
     }
Member Data Documentation
Alignment
VkDeviceSize vpr::Allocation::Alignment
Definition at line 47 of file Allocation.hpp.
Referenced by Init(), operator=(), and operator==().
impl
std::unique_ptr<AllocationImpl> vpr::Allocation::impl private
Definition at line 49 of file Allocation.hpp.
Referenced by Init(), InitPrivate(), IsPrivateAllocation(), Map(), Memory(), MemoryTypeIdx(), Offset(), operator=(), Unmap(), Update(), and ~Allocation().
Size
VkDeviceSize vpr::Allocation::Size
Definition at line 46 of file Allocation.hpp.
Referenced by vpr::Buffer::CreateBuffer(), vpr::Allocator::FreeMemory(), Init(), InitPrivate(), vpr::Buffer::Map(), operator=(), operator==(), and vpr::Buffer::setMappedMemoryRange().
userData
void* vpr::Allocation::userData { nullptr } private
Definition at line 50 of file Allocation.hpp.
The documentation for this class was generated from the following files:
alloc/include/Allocation.hpp
alloc/src/Allocation.cpp