VulpesRender: vpr::PhysicalDevice Class Reference
vpr::PhysicalDevice Class Reference
Core
! PhysicalDevice is a wrapper around a VkPhysicalDevice object, which is itself merely a handle representing a Vulkan-compatible hardware device in a user's system.
#include <PhysicalDevice.hpp>
Public Member Functions
PhysicalDevice (const VkInstance &instance_handle)
PhysicalDevice (PhysicalDevice &&other) noexcept
PhysicalDevice & operator= (PhysicalDevice &&other) noexcept
~PhysicalDevice ()
const VkPhysicalDevice & vkHandle () const noexcept
uint32_t GetMemoryTypeIdx (const uint32_t &type_bitfield, const VkMemoryPropertyFlags &property_flags, VkBool32 *memory_type_found=nullptr) const noexcept
! Attempts to find the hardware-appropriate index of a memory type that meets the flags given.
uint32_t GetQueueFamilyIndex (const VkQueueFlagBits &bitfield) const noexcept
! Attempts to find a Queue family that supports the full bitfield given: this can be multiple types, so graphics + compute options or compute + transfer bitfields can be passed to the method.
VkQueueFamilyProperties GetQueueFamilyProperties (const VkQueueFlagBits &bitfield) const
const VkPhysicalDeviceProperties & GetProperties () const noexcept
const VkPhysicalDeviceFeatures & GetFeatures () const noexcept
const VkPhysicalDeviceMemoryProperties & GetMemoryProperties () const noexcept
const VkPhysicalDeviceSubgroupProperties & GetSubgroupProperties () const noexcept
Private Member Functions
PhysicalDevice (const PhysicalDevice &other)=delete
PhysicalDevice & operator= (const PhysicalDevice &other)=delete
Private Attributes
std::unique_ptr< PhysicalDeviceImpl > impl
Detailed Description
! PhysicalDevice is a wrapper around a VkPhysicalDevice object, which is itself merely a handle representing a Vulkan-compatible hardware device in a user's system.
This class stores the relevant VkPhysicalDeviceProperties, VkPhysicalDeviceFeatures, and VkPhysicalDeviceMemoryProperties that can be freely queried from anywhere in the program. This can/should be used to check for limits on things like texture and buffer size, supported memory types, supported rendering modes, and supported texture types like cubemaps.
As each computer can have multiple physical devices, the class uses a simplistic scoring system to find the "best" hardware on the current system.
Definition at line 18 of file PhysicalDevice.hpp.
Constructor & Destructor Documentation
PhysicalDevice() [1/3]
vpr::PhysicalDevice::PhysicalDevice (const PhysicalDevice & other) private delete
PhysicalDevice() [2/3]
vpr::PhysicalDevice::PhysicalDevice (const VkInstance & instance_handle)
Definition at line 174 of file PhysicalDevice.cpp.
 : impl(std::make_unique<PhysicalDeviceImpl>(handle)) {}
PhysicalDevice() [3/3]
vpr::PhysicalDevice::PhysicalDevice (PhysicalDevice && other) noexcept
Definition at line 176 of file PhysicalDevice.cpp.
                                                                    : impl(std::move(other.impl)) {
         other.impl.reset();
     }
~PhysicalDevice()
vpr::PhysicalDevice::~PhysicalDevice ()
Definition at line 186 of file PhysicalDevice.cpp.
 { }
Member Function Documentation
GetFeatures()
const VkPhysicalDeviceFeatures & vpr::PhysicalDevice::GetFeatures () const noexcept
Definition at line 259 of file PhysicalDevice.cpp.
References impl.
Referenced by vpr::Device::create().
{
         return impl->Features;
     }
GetMemoryProperties()
const VkPhysicalDeviceMemoryProperties & vpr::PhysicalDevice::GetMemoryProperties () const noexcept
Definition at line 263 of file PhysicalDevice.cpp.
References impl.
Referenced by vpr::Device::GetPhysicalDeviceMemoryProperties().
{
         return impl->MemoryProperties;
     }
GetMemoryTypeIdx()
uint32_t vpr::PhysicalDevice::GetMemoryTypeIdx (const uint32_t & type_bitfield, const VkMemoryPropertyFlags & property_flags, VkBool32 * memory_type_found = nullptr) const noexcept
! Attempts to find the hardware-appropriate index of a memory type that meets the flags given.
Parameters
type_bitfield - the memoryTypeBits field of a VkMemoryRequirements struct, retrieved from a vkGetImageMemoryRequirements/vkGetBufferMemoryRequirements call.
property_flags - the type of memory requested by the user, commonly device-local or host-coherent memory.
Returns
Index of the requested memory type on success, std::numeric_limits<uint32_t>::max() on failure.
Definition at line 207 of file PhysicalDevice.cpp.
References impl.
Referenced by vpr::Device::GetMemoryTypeIdx().
{
         return impl->GetMemoryTypeIdx(type_bitfield, property_flags, memory_type_found);
     }
GetProperties()
const VkPhysicalDeviceProperties & vpr::PhysicalDevice::GetProperties () const noexcept
Definition at line 255 of file PhysicalDevice.cpp.
References impl.
Referenced by vpr::Device::GetPhysicalDeviceID(), and vpr::Device::GetPhysicalDeviceProperties().
{
         return impl->Properties;
     }
GetQueueFamilyIndex()
uint32_t vpr::PhysicalDevice::GetQueueFamilyIndex (const VkQueueFlagBits & bitfield) const noexcept
! Attempts to find a Queue family that supports the full bitfield given: this can be multiple types, so graphics + compute options or compute + transfer bitfields can be passed to the method.
Returns
Index of the queue meeting all of the flags specified, or std::numeric_limits<uint32_t>::max() on failure.
Definition at line 238 of file PhysicalDevice.cpp.
References impl.
Referenced by vpr::Device::GeneralQueue(), GetQueueFamilyProperties(), vpr::Device::setupComputeQueues(), vpr::Device::setupGraphicsQueues(), vpr::Device::setupSparseBindingQueues(), and vpr::Device::setupTransferQueues().
{
         return impl->GetQueueFamilyIndex(bitfield);
     }
GetQueueFamilyProperties()
VkQueueFamilyProperties vpr::PhysicalDevice::GetQueueFamilyProperties (const VkQueueFlagBits & bitfield) const
Definition at line 242 of file PhysicalDevice.cpp.
References GetQueueFamilyIndex(), impl, and LOG.
Referenced by vpr::Device::setupComputeQueues(), vpr::Device::setupGraphicsQueues(), vpr::Device::setupSparseBindingQueues(), and vpr::Device::setupTransferQueues().
{
         uint32_t idx = GetQueueFamilyIndex(bitfield);
         if (idx == std::numeric_limits<uint32_t>::max()) {
             LOG(WARNING) << "Failed to retrieve queue family properties: couldn't find queue family with given bitfield.";
             return VkQueueFamilyProperties();
         }
         else {
             return impl->queueFamilyProperties[idx];
         }
     }
GetSubgroupProperties()
const VkPhysicalDeviceSubgroupProperties & vpr::PhysicalDevice::GetSubgroupProperties () const noexcept
Definition at line 267 of file PhysicalDevice.cpp.
References impl.
{
         return impl->SubgroupProperties;
     }
operator=() [1/2]
PhysicalDevice& vpr::PhysicalDevice::operator= (const PhysicalDevice & other) private delete
operator=() [2/2]
PhysicalDevice & vpr::PhysicalDevice::operator= (PhysicalDevice && other) noexcept
Definition at line 180 of file PhysicalDevice.cpp.
References impl.
{
         impl = std::move(other.impl);
         other.impl.reset();
         return *this;
     }
vkHandle()
const VkPhysicalDevice & vpr::PhysicalDevice::vkHandle () const noexcept
Definition at line 271 of file PhysicalDevice.cpp.
References impl.
Referenced by vpr::Device::checkExtensions(), vpr::Device::CheckSurfaceSupport(), vpr::Device::create(), vpr::Device::FindSupportedFormat(), vpr::Device::GetFormatTiling(), vpr::Swapchain::Recreate(), and vpr::Device::VerifyPresentationSupport().
{
         return impl->handle;
     }
Member Data Documentation
impl
std::unique_ptr<PhysicalDeviceImpl> vpr::PhysicalDevice::impl private
Definition at line 51 of file PhysicalDevice.hpp.
Referenced by GetFeatures(), GetMemoryProperties(), GetMemoryTypeIdx(), GetProperties(), GetQueueFamilyIndex(), GetQueueFamilyProperties(), GetSubgroupProperties(), operator=(), and vkHandle().
The documentation for this class was generated from the following files:
include/core/PhysicalDevice.hpp
src/core/PhysicalDevice.cpp