VulpesRender: el::LogMessage Class Reference
el::LogMessage Class Reference
#include <easylogging++.h>
Public Member Functions
LogMessage (Level level, const std::string &file, base::type::LineNumber line, const std::string &func, base::type::VerboseLevel verboseLevel, Logger *logger)
Level level (void) const
const std::string & file (void) const
base::type::LineNumber line (void) const
const std::string & func (void) const
base::type::VerboseLevel verboseLevel (void) const
Logger * logger (void) const
const base::type::string_t & message (void) const
Private Attributes
Level m_level
std::string m_file
base::type::LineNumber m_line
std::string m_func
base::type::VerboseLevel m_verboseLevel
Logger * m_logger
base::type::string_t m_message
Detailed Description
Definition at line 2502 of file easylogging++.h.
Constructor & Destructor Documentation
LogMessage()
el::LogMessage::LogMessage (Level level, const std::string & file, base::type::LineNumber line, const std::string & func, base::type::VerboseLevel verboseLevel, Logger * logger) inline
Definition at line 2504 of file easylogging++.h.
                                                                 :
     m_level(level), m_file(file), m_line(line), m_func(func),
     m_verboseLevel(verboseLevel), m_logger(logger), m_message(logger->stream().str()) {
   }
Member Function Documentation
file()
const std::string& el::LogMessage::file (void) const inline
Definition at line 2512 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_file;
   }
func()
const std::string& el::LogMessage::func (void) const inline
Definition at line 2518 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_func;
   }
level()
Level el::LogMessage::level (void) const inline
Definition at line 2509 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::DefaultLogDispatchCallback::dispatch().
{
     return m_level;
   }
line()
base::type::LineNumber el::LogMessage::line (void) const inline
Definition at line 2515 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_line;
   }
logger()
Logger* el::LogMessage::logger (void) const inline
Definition at line 2524 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::DefaultLogDispatchCallback::dispatch().
{
     return m_logger;
   }
message()
const base::type::string_t& el::LogMessage::message (void) const inline
Definition at line 2527 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_message;
   }
verboseLevel()
base::type::VerboseLevel el::LogMessage::verboseLevel (void) const inline
Definition at line 2521 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_verboseLevel;
   }
Member Data Documentation
m_file
std::string el::LogMessage::m_file private
Definition at line 2532 of file easylogging++.h.
m_func
std::string el::LogMessage::m_func private
Definition at line 2534 of file easylogging++.h.
m_level
Level el::LogMessage::m_level private
Definition at line 2531 of file easylogging++.h.
m_line
base::type::LineNumber el::LogMessage::m_line private
Definition at line 2533 of file easylogging++.h.
m_logger
Logger* el::LogMessage::m_logger private
Definition at line 2536 of file easylogging++.h.
m_message
base::type::string_t el::LogMessage::m_message private
Definition at line 2537 of file easylogging++.h.
m_verboseLevel
base::type::VerboseLevel el::LogMessage::m_verboseLevel private
Definition at line 2535 of file easylogging++.h.
The documentation for this class was generated from the following file:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h