VulpesRender: el::base::MessageBuilder Class Reference
el::base::MessageBuilder Class Reference
#include <easylogging++.h>
Public Member Functions
MessageBuilder (void)
void initialize (Logger *logger)
MessageBuilder & operator<< (const std::string &msg)
MessageBuilder & operator<< (const std::wstring &msg)
MessageBuilder & operator<< (const wchar_t *msg)
MessageBuilder & operator<< (std::ostream &(*OStreamMani)(std::ostream &))
Private Member Functions
template<class Iterator >
MessageBuilder & writeIterator (Iterator begin_, Iterator end_, std::size_t size_)
Private Attributes
template<class Class >
Logger * m_logger
const base::type::char_t * m_containerLogSeperator
Detailed Description
Definition at line 2903 of file easylogging++.h.
Constructor & Destructor Documentation
MessageBuilder()
el::base::MessageBuilder::MessageBuilder (void) inline
Definition at line 2905 of file easylogging++.h.
 : m_logger(nullptr), m_containerLogSeperator(ELPP_LITERAL("")) {}
Member Function Documentation
initialize()
void el::base::MessageBuilder::initialize (Logger * logger)
Definition at line 2391 of file easylogging++.cc.
References ELPP, ELPP_LITERAL, and el::NewLineForContainer.
Referenced by el::Helpers::convertTemplateToStdString(), and el::base::PErrorWriter::PErrorWriter().
{
   m_logger = logger;
   m_containerLogSeperator = ELPP->hasFlag(LoggingFlag::NewLineForContainer) ?
                             ELPP_LITERAL("\n    ") : ELPP_LITERAL(", ");
 }
operator<<() [1/4]
MessageBuilder& el::base::MessageBuilder::operator<< (const std::string & msg) inline
Definition at line 2917 of file easylogging++.h.
References ELPP_SIMPLE_LOG, and vpr::operator<<().
{
     return operator<<(msg.c_str());
   }
operator<<() [2/4]
MessageBuilder& el::base::MessageBuilder::operator<< (const std::wstring & msg) inline
Definition at line 2934 of file easylogging++.h.
References vpr::operator<<().
{
     return operator<<(msg.c_str());
   }
operator<<() [3/4]
MessageBuilder & el::base::MessageBuilder::operator<< (const wchar_t * msg)
Definition at line 2397 of file easylogging++.cc.
References el::AutoSpacing, ELPP, el::base::consts::kNullPointer, and el::base::utils::Str::wcharPtrToCharPtr().
{
   if (msg == nullptr) {
     m_logger->stream() << base::consts::kNullPointer;
     return *this;
   }
 #  if defined(ELPP_UNICODE)
   m_logger->stream() << msg;
 #  else
   char* buff_ = base::utils::Str::wcharPtrToCharPtr(msg);
   m_logger->stream() << buff_;
   free(buff_);
 #  endif
   if (ELPP->hasFlag(LoggingFlag::AutoSpacing)) {
     m_logger->stream() << " ";
   }
   return *this;
 }
operator<<() [4/4]
MessageBuilder& el::base::MessageBuilder::operator<< (std::ostream &(*)(std::ostream &) OStreamMani) inline
Definition at line 2939 of file easylogging++.h.
{
     m_logger->stream() << OStreamMani;
     return *this;
   }
writeIterator()
template<class Iterator > MessageBuilder& el::base::MessageBuilder::writeIterator (Iterator begin_, Iterator end_, std::size_t size_) inline private
Definition at line 3195 of file easylogging++.h.
References el::AutoSpacing, ELPP, ELPP_LITERAL, el::base::consts::kMaxLogPerContainer, vpr::operator<<(), and el::Logger::stream().
{
     m_logger->stream() << ELPP_LITERAL("[");
     for (std::size_t i = 0; begin_ != end_ && i < base::consts::kMaxLogPerContainer; ++i, ++begin_) {
       operator << (*begin_);
       m_logger->stream() << ((i < size_ - 1) ? m_containerLogSeperator : ELPP_LITERAL(""));
     }
     if (begin_ != end_) {
       m_logger->stream() << ELPP_LITERAL("...");
     }
     m_logger->stream() << ELPP_LITERAL("]");
     if (ELPP->hasFlag(LoggingFlag::AutoSpacing)) {
       m_logger->stream() << " ";
     }
     return *this;
   }
Member Data Documentation
m_containerLogSeperator
const base::type::char_t* el::base::MessageBuilder::m_containerLogSeperator private
Definition at line 3192 of file easylogging++.h.
m_logger
template<class Class > Logger* el::base::MessageBuilder::m_logger private
Definition at line 3191 of file easylogging++.h.
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc