VulpesRender: vpr::DescriptorSet Class Reference
vpr::DescriptorSet Class Reference
Resources
RAII wrapper around a descriptor set, simplifying adding individual descriptor bindings for whatever stage they're required at.
#include <DescriptorSet.hpp>
Public Member Functions
DescriptorSet (const VkDevice &parent)
~DescriptorSet ()
DescriptorSet (DescriptorSet &&other) noexcept
DescriptorSet & operator= (DescriptorSet &&other) noexcept
void AddDescriptorInfo (VkDescriptorImageInfo info, const VkDescriptorType &type, const size_t &item_binding_idx)
Sets the required image info for the descriptor at the given index.
void AddDescriptorInfo (VkDescriptorBufferInfo info, const VkDescriptorType &descr_type, const size_t &item_binding_idx)
Functionally the same as AddDescriptorInfo with VkDescriptorImageInfo.
void AddDescriptorInfo (VkDescriptorBufferInfo info, const VkBufferView &view, const VkDescriptorType &type, const size_t &idx)
void Init (const VkDescriptorPool &parent_pool, const VkDescriptorSetLayout &set_layout)
Call after all descriptor bindings and infos required have been added, and make sure you have enough space in the given pool for all of these resources.
const VkDescriptorSet & vkHandle () const noexcept
void Update () const
void Reset ()
Private Member Functions
DescriptorSet (const DescriptorSet &)=delete
DescriptorSet & operator= (const DescriptorSet &)=delete
void allocate (const VkDescriptorPool &parent_pool, const VkDescriptorSetLayout &set_layout) const
void update () const
Private Attributes
VkDevice device { VK_NULL_HANDLE }
VkDescriptorSet handle { VK_NULL_HANDLE }
std::unique_ptr< DescriptorSetImpl > impl { nullptr }
Detailed Description
RAII wrapper around a descriptor set, simplifying adding individual descriptor bindings for whatever stage they're required at.
Definition at line 14 of file DescriptorSet.hpp.
Constructor & Destructor Documentation
DescriptorSet() [1/3]
vpr::DescriptorSet::DescriptorSet (const DescriptorSet &) private delete
DescriptorSet() [2/3]
vpr::DescriptorSet::DescriptorSet (const VkDevice & parent)
Definition at line 23 of file DescriptorSet.cpp.
 : device(parent), handle(VK_NULL_HANDLE), impl(std::make_unique<DescriptorSetImpl>()) { }
~DescriptorSet()
vpr::DescriptorSet::~DescriptorSet ()
Definition at line 25 of file DescriptorSet.cpp.
References device, handle, and impl.
{
         if (handle != VK_NULL_HANDLE) {
             vkFreeDescriptorSets(device, impl->pool, 1, &handle);
         }
     }
DescriptorSet() [3/3]
vpr::DescriptorSet::DescriptorSet (DescriptorSet && other) noexcept
Definition at line 31 of file DescriptorSet.cpp.
                                                                : device(std::move(other.device)), handle(std::move(other.handle)),
         impl(std::move(other.impl)) { other.handle = VK_NULL_HANDLE; }
Member Function Documentation
AddDescriptorInfo() [1/3]
void vpr::DescriptorSet::AddDescriptorInfo (VkDescriptorImageInfo info, const VkDescriptorType & type, const size_t & item_binding_idx)
Sets the required image info for the descriptor at the given index.
Definition at line 42 of file DescriptorSet.cpp.
References handle, and impl.
{
         impl->imageInfos.emplace(item_binding_idx, std::move(info));
         impl->writeDescriptors.emplace(item_binding_idx, VkWriteDescriptorSet{
             VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             nullptr,
             handle,
             static_cast<uint32_t>(item_binding_idx),
             0,
             1,
             type,
             &impl->imageInfos.at(item_binding_idx),
             nullptr,
             nullptr,
         });
     }
AddDescriptorInfo() [2/3]
void vpr::DescriptorSet::AddDescriptorInfo (VkDescriptorBufferInfo info, const VkDescriptorType & descr_type, const size_t & item_binding_idx)
Functionally the same as AddDescriptorInfo with VkDescriptorImageInfo.
Definition at line 59 of file DescriptorSet.cpp.
References handle, and impl.
{
         impl->bufferInfos.emplace(item_binding_idx, std::move(info));
         impl->writeDescriptors.emplace(item_binding_idx, VkWriteDescriptorSet{
             VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             nullptr,
             handle,
             static_cast<uint32_t>(item_binding_idx),
             0,
             1,
             descr_type,
             nullptr,
             &impl->bufferInfos.at(item_binding_idx),
             nullptr,
         });
     }
AddDescriptorInfo() [3/3]
void vpr::DescriptorSet::AddDescriptorInfo (VkDescriptorBufferInfo info, const VkBufferView & view, const VkDescriptorType & type, const size_t & idx)
Definition at line 75 of file DescriptorSet.cpp.
References handle, and impl.
{
         impl->bufferInfos.emplace(idx, std::move(info));
         impl->bufferViews.emplace(idx, view);
         impl->writeDescriptors.emplace(idx, VkWriteDescriptorSet{
             VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
             nullptr,
             handle,
             static_cast<uint32_t>(idx),
             0,
             1,
             type,
             nullptr,
             &impl->bufferInfos.at(idx),
             &impl->bufferViews.at(idx)
         });
     }
allocate()
void vpr::DescriptorSet::allocate (const VkDescriptorPool & parent_pool, const VkDescriptorSetLayout & set_layout) const private
Definition at line 97 of file DescriptorSet.cpp.
References device, handle, impl, vpr::vk_descriptor_set_alloc_info_base, and VkAssert.
Referenced by Init(), and vkHandle().
{
         impl->pool = parent_pool;
         impl->setLayout = set_layout;
         VkDescriptorSetAllocateInfo alloc_info = vk_descriptor_set_alloc_info_base;
         alloc_info.descriptorPool = impl->pool;
         alloc_info.descriptorSetCount = 1;
         alloc_info.pSetLayouts = &impl->setLayout;
         VkResult result = vkAllocateDescriptorSets(device, &alloc_info, &handle);
         VkAssert(result);
         impl->allocated = true;
     }
Init()
void vpr::DescriptorSet::Init (const VkDescriptorPool & parent_pool, const VkDescriptorSetLayout & set_layout)
Call after all descriptor bindings and infos required have been added, and make sure you have enough space in the given pool for all of these resources.
Definition at line 92 of file DescriptorSet.cpp.
References allocate(), and update().
{
         allocate(parent_pool, set_layout);
         update();
     }
operator=() [1/2]
DescriptorSet& vpr::DescriptorSet::operator= (const DescriptorSet &) private delete
operator=() [2/2]
DescriptorSet & vpr::DescriptorSet::operator= (DescriptorSet && other) noexcept
Definition at line 34 of file DescriptorSet.cpp.
References device, handle, and impl.
{
         device = std::move(other.device);
         handle = std::move(other.handle);
         impl = std::move(other.impl);
         other.handle = VK_NULL_HANDLE;
         return *this;
     }
Reset()
void vpr::DescriptorSet::Reset ()
Definition at line 153 of file DescriptorSet.cpp.
References impl.
{
         VkDescriptorPool pool = impl->pool;
         VkDescriptorSetLayout layout = impl->setLayout;
         impl.reset();
         impl = std::make_unique<DescriptorSetImpl>();
         impl->pool = pool;
         impl->setLayout = layout;
     }
Update()
void vpr::DescriptorSet::Update () const
Definition at line 113 of file DescriptorSet.cpp.
References update().
{
         update();
     }
update()
void vpr::DescriptorSet::update () const private
Definition at line 117 of file DescriptorSet.cpp.
References device, handle, and impl.
Referenced by Init(), Update(), and vkHandle().
{
         assert(impl->pool && impl->allocated && !impl->writeDescriptors.empty());
         std::vector<VkWriteDescriptorSet> write_descriptors;
         for (const auto& entry : impl->writeDescriptors) {
             write_descriptors.emplace_back(entry.second);
             write_descriptors.back().dstSet = handle;
             if (entry.second.pBufferInfo != nullptr) {
                 write_descriptors.back().pBufferInfo = entry.second.pBufferInfo;
             }
             if (entry.second.pImageInfo != nullptr) {
                 write_descriptors.back().pImageInfo = entry.second.pImageInfo;
             }
             if (entry.second.pTexelBufferView != nullptr) {
                 write_descriptors.back().pTexelBufferView = entry.second.pTexelBufferView;
             }
         }
         vkUpdateDescriptorSets(device, static_cast<uint32_t>(write_descriptors.size()), write_descriptors.data(), 0, nullptr);
         impl->updated = true;
     }
vkHandle()
const VkDescriptorSet & vpr::DescriptorSet::vkHandle () const noexcept
Definition at line 143 of file DescriptorSet.cpp.
References allocate(), handle, impl, and update().
{
         if (!impl->allocated) {
             allocate(impl->pool, impl->setLayout);
         }
         if (!impl->updated) {
             update();
         }
         return handle;
     }
Member Data Documentation
device
VkDevice vpr::DescriptorSet::device { VK_NULL_HANDLE } private
Definition at line 49 of file DescriptorSet.hpp.
Referenced by allocate(), operator=(), update(), and ~DescriptorSet().
handle
VkDescriptorSet vpr::DescriptorSet::handle { VK_NULL_HANDLE } mutable private
Definition at line 50 of file DescriptorSet.hpp.
Referenced by AddDescriptorInfo(), allocate(), operator=(), update(), vkHandle(), and ~DescriptorSet().
impl
std::unique_ptr<DescriptorSetImpl> vpr::DescriptorSet::impl { nullptr } mutable private
Definition at line 51 of file DescriptorSet.hpp.
Referenced by AddDescriptorInfo(), allocate(), operator=(), Reset(), update(), vkHandle(), and ~DescriptorSet().
The documentation for this class was generated from the following files:
resource/include/DescriptorSet.hpp
resource/src/DescriptorSet.cpp