VulpesRender: el::base::LogFormat Class Reference
el::base::LogFormat Class Reference
Represents log format containing flags and date format. This is used internally to start initial log.
#include <easylogging++.h>
Public Member Functions
LogFormat (void)
LogFormat (Level level, const base::type::string_t &format)
LogFormat (const LogFormat &logFormat)
LogFormat (LogFormat &&logFormat)
LogFormat & operator= (const LogFormat &logFormat)
virtual ~LogFormat (void)
bool operator== (const LogFormat &other)
void parseFromFormat (const base::type::string_t &userFormat)
Updates format to be used while logging.
Level level (void) const
const base::type::string_t & userFormat (void) const
const base::type::string_t & format (void) const
const std::string & dateTimeFormat (void) const
base::type::EnumType flags (void) const
bool hasFlag (base::FormatFlags flag) const
virtual void log (el::base::type::ostream_t &os) const
Protected Member Functions
virtual void updateDateFormat (std::size_t index, base::type::string_t &currFormat) ELPP_FINAL
Updates date time format if available in currFormat.
virtual void updateFormatSpec (void) ELPP_FINAL
Updates level from format. This is so that we dont have to do it at log-writing-time. It uses m_format and m_level.
void addFlag (base::FormatFlags flag)
Private Attributes
Level m_level
base::type::string_t m_userFormat
base::type::string_t m_format
std::string m_dateTimeFormat
base::type::EnumType m_flags
std::string m_currentUser
std::string m_currentHost
Friends
class el::Logger
Detailed Description
Represents log format containing flags and date format. This is used internally to start initial log.
Definition at line 1630 of file easylogging++.h.
Constructor & Destructor Documentation
LogFormat() [1/4]
el::base::LogFormat::LogFormat (void)
Definition at line 1353 of file easylogging++.cc.
                          :
   m_level(Level::Unknown),
   m_userFormat(base::type::string_t()),
   m_format(base::type::string_t()),
   m_dateTimeFormat(std::string()),
   m_flags(0x0),
   m_currentUser(base::utils::OS::currentUser()),
   m_currentHost(base::utils::OS::currentHost()) {
 }
LogFormat() [2/4]
el::base::LogFormat::LogFormat (Level level, const base::type::string_t & format)
Definition at line 1363 of file easylogging++.cc.
References m_userFormat, and parseFromFormat().
   : m_level(level), m_userFormat(format), m_currentUser(base::utils::OS::currentUser()),
     m_currentHost(base::utils::OS::currentHost()) {
   parseFromFormat(m_userFormat);
 }
LogFormat() [3/4]
el::base::LogFormat::LogFormat (const LogFormat & logFormat)
Definition at line 1369 of file easylogging++.cc.
                                               :
   m_level(logFormat.m_level),
   m_userFormat(logFormat.m_userFormat),
   m_format(logFormat.m_format),
   m_dateTimeFormat(logFormat.m_dateTimeFormat),
   m_flags(logFormat.m_flags),
   m_currentUser(logFormat.m_currentUser),
   m_currentHost(logFormat.m_currentHost) {
 }
LogFormat() [4/4]
el::base::LogFormat::LogFormat (LogFormat && logFormat)
Definition at line 1379 of file easylogging++.cc.
References m_currentHost, m_currentUser, m_dateTimeFormat, m_flags, m_format, m_level, and m_userFormat.
{
   m_level = std::move(logFormat.m_level);
   m_userFormat = std::move(logFormat.m_userFormat);
   m_format = std::move(logFormat.m_format);
   m_dateTimeFormat = std::move(logFormat.m_dateTimeFormat);
   m_flags = std::move(logFormat.m_flags);
   m_currentUser = std::move(logFormat.m_currentUser);
   m_currentHost = std::move(logFormat.m_currentHost);
 }
~LogFormat()
virtual el::base::LogFormat::~LogFormat (void) inline virtual
Definition at line 1637 of file easylogging++.h.
 {}
Member Function Documentation
addFlag()
void el::base::LogFormat::addFlag (base::FormatFlags flag) inline protected
Definition at line 1681 of file easylogging++.h.
References el::base::utils::addFlag().
Referenced by parseFromFormat().
{
     base::utils::addFlag(flag, &m_flags);
   }
dateTimeFormat()
const std::string& el::base::LogFormat::dateTimeFormat (void) const inline
Definition at line 1656 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_dateTimeFormat;
   }
flags()
base::type::EnumType el::base::LogFormat::flags (void) const inline
Definition at line 1660 of file easylogging++.h.
{
     return m_flags;
   }
format()
const base::type::string_t& el::base::LogFormat::format (void) const inline
Definition at line 1652 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_format;
   }
hasFlag()
bool el::base::LogFormat::hasFlag (base::FormatFlags flag) const inline
Definition at line 1664 of file easylogging++.h.
References el::base::utils::hasFlag().
Referenced by el::base::DefaultLogBuilder::build(), parseFromFormat(), updateDateFormat(), and updateFormatSpec().
{
     return base::utils::hasFlag(flag, m_flags);
   }
level()
Level el::base::LogFormat::level (void) const inline
Definition at line 1644 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::enabled(), el::base::TypedConfigurations::filename(), el::base::TypedConfigurations::fileStream(), el::base::TypedConfigurations::insertFile(), el::base::TypedConfigurations::logFlushThreshold(), el::base::TypedConfigurations::logFormat(), el::base::TypedConfigurations::maxLogFileSize(), el::base::TypedConfigurations::millisecondsWidth(), el::base::TypedConfigurations::performanceTracking(), el::base::TypedConfigurations::subsecondPrecision(), el::base::TypedConfigurations::toFile(), and el::base::TypedConfigurations::toStandardOutput().
{
     return m_level;
   }
log()
virtual void el::base::LogFormat::log (el::base::type::ostream_t & os) const inline virtual
Implements el::Loggable.
Definition at line 1668 of file easylogging++.h.
References ELPP_FINAL.
{
     os << m_format;
   }
operator=()
LogFormat & el::base::LogFormat::operator= (const LogFormat & logFormat)
Definition at line 1389 of file easylogging++.cc.
References m_currentHost, m_currentUser, m_dateTimeFormat, m_flags, m_level, and m_userFormat.
{
   if (&logFormat != this) {
     m_level = logFormat.m_level;
     m_userFormat = logFormat.m_userFormat;
     m_dateTimeFormat = logFormat.m_dateTimeFormat;
     m_flags = logFormat.m_flags;
     m_currentUser = logFormat.m_currentUser;
     m_currentHost = logFormat.m_currentHost;
   }
   return *this;
 }
operator==()
bool el::base::LogFormat::operator== (const LogFormat & other)
Definition at line 1401 of file easylogging++.cc.
References m_dateTimeFormat, m_flags, m_format, m_level, and m_userFormat.
{
   return m_level == other.m_level && m_userFormat == other.m_userFormat && m_format == other.m_format &&
          m_dateTimeFormat == other.m_dateTimeFormat && m_flags == other.m_flags;
 }
parseFromFormat()
void el::base::LogFormat::parseFromFormat (const base::type::string_t & userFormat)
Updates format to be used while logging.
Parameters
userFormat User provided format
Definition at line 1408 of file easylogging++.cc.
References addFlag(), el::base::AppName, el::base::DateTime, el::base::File, el::base::FileBase, el::base::Function, hasFlag(), el::base::Host, el::base::consts::kAppNameFormatSpecifier, el::base::consts::kCurrentHostFormatSpecifier, el::base::consts::kCurrentUserFormatSpecifier, el::base::consts::kDateTimeFormatSpecifier, el::base::consts::kFormatSpecifierChar, el::base::consts::kLogFileBaseFormatSpecifier, el::base::consts::kLogFileFormatSpecifier, el::base::consts::kLogFunctionFormatSpecifier, el::base::consts::kLoggerIdFormatSpecifier, el::base::consts::kLogLineFormatSpecifier, el::base::consts::kLogLocationFormatSpecifier, el::base::consts::kMessageFormatSpecifier, el::base::consts::kSeverityLevelFormatSpecifier, el::base::consts::kSeverityLevelShortFormatSpecifier, el::base::consts::kThreadIdFormatSpecifier, el::base::consts::kVerboseLevelFormatSpecifier, el::base::Level, el::base::LevelShort, el::base::Line, el::base::Location, el::base::LoggerId, el::base::LogMessage, m_flags, m_format, el::base::ThreadId, updateDateFormat(), updateFormatSpec(), el::base::User, userFormat(), and el::base::VerboseLevel.
Referenced by LogFormat().
{
   // We make copy because we will be changing the format
   // i.e, removing user provided date format from original format
   // and then storing it.
   base::type::string_t formatCopy = userFormat;
   m_flags = 0x0;
   auto conditionalAddFlag = [&](const base::type::char_t* specifier, base::FormatFlags flag) {
     std::size_t foundAt = base::type::string_t::npos;
     while ((foundAt = formatCopy.find(specifier, foundAt + 1)) != base::type::string_t::npos) {
       if (foundAt > 0 && formatCopy[foundAt - 1] == base::consts::kFormatSpecifierChar) {
         if (hasFlag(flag)) {
           // If we already have flag we remove the escape chars so that '%%' is turned to '%'
           // even after specifier resolution - this is because we only replaceFirst specifier
           formatCopy.erase(foundAt > 0 ? foundAt - 1 : 0, 1);
           ++foundAt;
         }
       } else {
         if (!hasFlag(flag)) addFlag(flag);
       }
     }
   };
   conditionalAddFlag(base::consts::kAppNameFormatSpecifier, base::FormatFlags::AppName);
   conditionalAddFlag(base::consts::kSeverityLevelFormatSpecifier, base::FormatFlags::Level);
   conditionalAddFlag(base::consts::kSeverityLevelShortFormatSpecifier, base::FormatFlags::LevelShort);
   conditionalAddFlag(base::consts::kLoggerIdFormatSpecifier, base::FormatFlags::LoggerId);
   conditionalAddFlag(base::consts::kThreadIdFormatSpecifier, base::FormatFlags::ThreadId);
   conditionalAddFlag(base::consts::kLogFileFormatSpecifier, base::FormatFlags::File);
   conditionalAddFlag(base::consts::kLogFileBaseFormatSpecifier, base::FormatFlags::FileBase);
   conditionalAddFlag(base::consts::kLogLineFormatSpecifier, base::FormatFlags::Line);
   conditionalAddFlag(base::consts::kLogLocationFormatSpecifier, base::FormatFlags::Location);
   conditionalAddFlag(base::consts::kLogFunctionFormatSpecifier, base::FormatFlags::Function);
   conditionalAddFlag(base::consts::kCurrentUserFormatSpecifier, base::FormatFlags::User);
   conditionalAddFlag(base::consts::kCurrentHostFormatSpecifier, base::FormatFlags::Host);
   conditionalAddFlag(base::consts::kMessageFormatSpecifier, base::FormatFlags::LogMessage);
   conditionalAddFlag(base::consts::kVerboseLevelFormatSpecifier, base::FormatFlags::VerboseLevel);
   // For date/time we need to extract user's date format first
   std::size_t dateIndex = std::string::npos;
   if ((dateIndex = formatCopy.find(base::consts::kDateTimeFormatSpecifier)) != std::string::npos) {
     while (dateIndex > 0 && formatCopy[dateIndex - 1] == base::consts::kFormatSpecifierChar) {
       dateIndex = formatCopy.find(base::consts::kDateTimeFormatSpecifier, dateIndex + 1);
     }
     if (dateIndex != std::string::npos) {
       addFlag(base::FormatFlags::DateTime);
       updateDateFormat(dateIndex, formatCopy);
     }
   }
   m_format = formatCopy;
   updateFormatSpec();
 }
updateDateFormat()
void el::base::LogFormat::updateDateFormat (std::size_t index, base::type::string_t & currFormat) protected virtual
Updates date time format if available in currFormat.
Parameters
index Index where datetime, date or time was found
[in,out] currFormat current format that is being used to format
Definition at line 1458 of file easylogging++.cc.
References el::base::DateTime, ELPP_STRLEN, hasFlag(), el::base::consts::kDateTimeFormatSpecifier, el::base::consts::kDefaultDateTimeFormat, and m_dateTimeFormat.
Referenced by parseFromFormat().
{
   if (hasFlag(base::FormatFlags::DateTime)) {
     index += ELPP_STRLEN(base::consts::kDateTimeFormatSpecifier);
   }
   const base::type::char_t* ptr = currFormat.c_str() + index;
   if ((currFormat.size() > index) && (ptr[0] == '{')) {
     // User has provided format for date/time
     ++ptr;
     int count = 1;  // Start by 1 in order to remove starting brace
     std::stringstream ss;
     for (; *ptr; ++ptr, ++count) {
       if (*ptr == '}') {
         ++count;  // In order to remove ending brace
         break;
       }
       ss << static_cast<char>(*ptr);
     }
     currFormat.erase(index, count);
     m_dateTimeFormat = ss.str();
   } else {
     // No format provided, use default
     if (hasFlag(base::FormatFlags::DateTime)) {
       m_dateTimeFormat = std::string(base::consts::kDefaultDateTimeFormat);
     }
   }
 }
updateFormatSpec()
void el::base::LogFormat::updateFormatSpec (void) protected virtual
Updates level from format. This is so that we dont have to do it at log-writing-time. It uses m_format and m_level.
Definition at line 1485 of file easylogging++.cc.
References el::Debug, el::Error, el::Fatal, hasFlag(), el::base::Host, el::Info, el::base::consts::kCurrentHostFormatSpecifier, el::base::consts::kCurrentUserFormatSpecifier, el::base::consts::kDebugLevelLogValue, el::base::consts::kDebugLevelShortLogValue, el::base::consts::kErrorLevelLogValue, el::base::consts::kErrorLevelShortLogValue, el::base::consts::kFatalLevelLogValue, el::base::consts::kFatalLevelShortLogValue, el::base::consts::kInfoLevelLogValue, el::base::consts::kInfoLevelShortLogValue, el::base::consts::kSeverityLevelFormatSpecifier, el::base::consts::kSeverityLevelShortFormatSpecifier, el::base::consts::kTraceLevelLogValue, el::base::consts::kTraceLevelShortLogValue, el::base::consts::kVerboseLevelLogValue, el::base::consts::kVerboseLevelShortLogValue, el::base::consts::kWarningLevelLogValue, el::base::consts::kWarningLevelShortLogValue, m_currentHost, m_currentUser, m_format, m_level, el::base::utils::Str::replaceFirstWithEscape(), el::Trace, el::base::User, el::Verbose, and el::Warning.
Referenced by parseFromFormat().
{
   // Do not use switch over strongly typed enums because Intel C++ compilers dont support them yet.
   if (m_level == Level::Debug) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kDebugLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kDebugLevelShortLogValue);
   } else if (m_level == Level::Info) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kInfoLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kInfoLevelShortLogValue);
   } else if (m_level == Level::Warning) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kWarningLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kWarningLevelShortLogValue);
   } else if (m_level == Level::Error) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kErrorLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kErrorLevelShortLogValue);
   } else if (m_level == Level::Fatal) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kFatalLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kFatalLevelShortLogValue);
   } else if (m_level == Level::Verbose) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kVerboseLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kVerboseLevelShortLogValue);
   } else if (m_level == Level::Trace) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelFormatSpecifier,
         base::consts::kTraceLevelLogValue);
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kSeverityLevelShortFormatSpecifier,
         base::consts::kTraceLevelShortLogValue);
   }
   if (hasFlag(base::FormatFlags::User)) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kCurrentUserFormatSpecifier,
         m_currentUser);
   }
   if (hasFlag(base::FormatFlags::Host)) {
     base::utils::Str::replaceFirstWithEscape(m_format, base::consts::kCurrentHostFormatSpecifier,
         m_currentHost);
   }
   // Ignore Level::Global and Level::Unknown
 }
userFormat()
const base::type::string_t& el::base::LogFormat::userFormat (void) const inline
Definition at line 1648 of file easylogging++.h.
Referenced by parseFromFormat().
{
     return m_userFormat;
   }
Friends And Related Function Documentation
el::Logger
friend class el::Logger friend
Definition at line 1693 of file easylogging++.h.
Member Data Documentation
m_currentHost
std::string el::base::LogFormat::m_currentHost private
Definition at line 1692 of file easylogging++.h.
Referenced by LogFormat(), operator=(), and updateFormatSpec().
m_currentUser
std::string el::base::LogFormat::m_currentUser private
Definition at line 1691 of file easylogging++.h.
Referenced by LogFormat(), operator=(), and updateFormatSpec().
m_dateTimeFormat
std::string el::base::LogFormat::m_dateTimeFormat private
Definition at line 1689 of file easylogging++.h.
Referenced by LogFormat(), operator=(), operator==(), and updateDateFormat().
m_flags
base::type::EnumType el::base::LogFormat::m_flags private
Definition at line 1690 of file easylogging++.h.
Referenced by LogFormat(), operator=(), operator==(), and parseFromFormat().
m_format
base::type::string_t el::base::LogFormat::m_format private
Definition at line 1688 of file easylogging++.h.
Referenced by LogFormat(), operator==(), parseFromFormat(), el::Logger::resolveLoggerFormatSpec(), and updateFormatSpec().
m_level
Level el::base::LogFormat::m_level private
Definition at line 1686 of file easylogging++.h.
Referenced by LogFormat(), operator=(), operator==(), and updateFormatSpec().
m_userFormat
base::type::string_t el::base::LogFormat::m_userFormat private
Definition at line 1687 of file easylogging++.h.
Referenced by LogFormat(), operator=(), and operator==().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc