VulpesRender: el::base::TypedConfigurations Class Reference
el::base::TypedConfigurations Class Reference
Configurations with data types.
#include <easylogging++.h>
Public Member Functions
TypedConfigurations (Configurations *configurations, base::LogStreamsReferenceMap *logStreamsReference)
Constructor to initialize (construct) the object off el::Configurations.
TypedConfigurations (const TypedConfigurations &other)
virtual ~TypedConfigurations (void)
const Configurations * configurations (void) const
bool enabled (Level level)
bool toFile (Level level)
const std::string & filename (Level level)
bool toStandardOutput (Level level)
const base::LogFormat & logFormat (Level level)
const base::SubsecondPrecision & subsecondPrecision (Level level=Level::Global)
const base::MillisecondsWidth & millisecondsWidth (Level level=Level::Global)
bool performanceTracking (Level level=Level::Global)
base::type::fstream_t * fileStream (Level level)
std::size_t maxLogFileSize (Level level)
std::size_t logFlushThreshold (Level level)
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
template<typename Conf_T >
Conf_T getConfigByVal (Level level, const std::map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T & getConfigByRef (Level level, std::map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T unsafeGetConfigByVal (Level level, const std::map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T & unsafeGetConfigByRef (Level level, std::map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
void setValue (Level level, const Conf_T &value, std::map< Level, Conf_T > *confMap, bool includeGlobalLevel=true)
void build (Configurations *configurations)
unsigned long getULong (std::string confVal)
std::string resolveFilename (const std::string &filename)
void insertFile (Level level, const std::string &fullFilename)
bool unsafeValidateFileRolling (Level level, const PreRollOutCallback &preRollOutCallback)
bool validateFileRolling (Level level, const PreRollOutCallback &preRollOutCallback)
Private Attributes
Configurations * m_configurations
std::map< Level, bool > m_enabledMap
std::map< Level, bool > m_toFileMap
std::map< Level, std::string > m_filenameMap
std::map< Level, bool > m_toStandardOutputMap
std::map< Level, base::LogFormat > m_logFormatMap
std::map< Level, base::SubsecondPrecision > m_subsecondPrecisionMap
std::map< Level, bool > m_performanceTrackingMap
std::map< Level, base::FileStreamPtr > m_fileStreamMap
std::map< Level, std::size_t > m_maxLogFileSizeMap
std::map< Level, std::size_t > m_logFlushThresholdMap
base::LogStreamsReferenceMap * m_logStreamsReference
Friends
class el::Helpers
class el::base::MessageBuilder
class el::base::Writer
class el::base::DefaultLogDispatchCallback
class el::base::LogDispatcher
Detailed Description
Configurations with data types.
el::Configurations have string based values. This is whats used internally in order to read correct configurations. This is to perform faster while writing logs using correct configurations.
This is thread safe and final class containing non-virtual destructor (means nothing should inherit this class)
Definition at line 1958 of file easylogging++.h.
Constructor & Destructor Documentation
TypedConfigurations() [1/2]
el::base::TypedConfigurations::TypedConfigurations (Configurations * configurations, base::LogStreamsReferenceMap * logStreamsReference)
Constructor to initialize (construct) the object off el::Configurations.
Parameters
configurations Configurations pointer/reference to base this typed configurations off.
logStreamsReference Use ELPP->registeredLoggers()->logStreamsReference()
Definition at line 1536 of file easylogging++.cc.
{
   m_configurations = configurations;
   m_logStreamsReference = logStreamsReference;
   build(m_configurations);
 }
TypedConfigurations() [2/2]
el::base::TypedConfigurations::TypedConfigurations (const TypedConfigurations & other)
Definition at line 1543 of file easylogging++.cc.
References m_configurations, and m_logStreamsReference.
{
   this->m_configurations = other.m_configurations;
   this->m_logStreamsReference = other.m_logStreamsReference;
   build(m_configurations);
 }
~TypedConfigurations()
virtual el::base::TypedConfigurations::~TypedConfigurations (void) inline virtual
Definition at line 1967 of file easylogging++.h.
{
   }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
build()
void el::base::TypedConfigurations::build (Configurations * configurations) private
Definition at line 1593 of file easylogging++.cc.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::begin(), el::Configuration::configurationType(), el::base::defaultPreRollOutCallback(), el::Enabled, el::base::utils::AbstractRegistry< T_Ptr, Container >::end(), el::Filename, el::Format, el::Global, el::Configuration::level(), el::LogFlushThreshold, el::MaxLogFileSize, el::PerformanceTracking, el::SubsecondPrecision, el::ToFile, el::ToStandardOutput, el::base::utils::Str::trim(), and el::Configuration::value().
{
   base::threading::ScopedLock scopedLock(lock());
   auto getBool = [] (std::string boolStr) -> bool {  // Pass by value for trimming
     base::utils::Str::trim(boolStr);
     return (boolStr == "TRUE" || boolStr == "true" || boolStr == "1");
   };
   std::vector<Configuration*> withFileSizeLimit;
   for (Configurations::const_iterator it = configurations->begin(); it != configurations->end(); ++it) {
     Configuration* conf = *it;
     // We cannot use switch on strong enums because Intel C++ dont support them yet
     if (conf->configurationType() == ConfigurationType::Enabled) {
       setValue(conf->level(), getBool(conf->value()), &m_enabledMap);
     } else if (conf->configurationType() == ConfigurationType::ToFile) {
       setValue(conf->level(), getBool(conf->value()), &m_toFileMap);
     } else if (conf->configurationType() == ConfigurationType::ToStandardOutput) {
       setValue(conf->level(), getBool(conf->value()), &m_toStandardOutputMap);
     } else if (conf->configurationType() == ConfigurationType::Filename) {
       // We do not yet configure filename but we will configure in another
       // loop. This is because if file cannot be created, we will force ToFile
       // to be false. Because configuring logger is not necessarily performance
       // sensative operation, we can live with another loop; (by the way this loop
       // is not very heavy either)
     } else if (conf->configurationType() == ConfigurationType::Format) {
       setValue(conf->level(), base::LogFormat(conf->level(),
                                               base::type::string_t(conf->value().begin(), conf->value().end())), &m_logFormatMap);
     } else if (conf->configurationType() == ConfigurationType::SubsecondPrecision) {
       setValue(Level::Global,
                base::SubsecondPrecision(static_cast<int>(getULong(conf->value()))), &m_subsecondPrecisionMap);
     } else if (conf->configurationType() == ConfigurationType::PerformanceTracking) {
       setValue(Level::Global, getBool(conf->value()), &m_performanceTrackingMap);
     } else if (conf->configurationType() == ConfigurationType::MaxLogFileSize) {
       setValue(conf->level(), static_cast<std::size_t>(getULong(conf->value())), &m_maxLogFileSizeMap);
 #if !defined(ELPP_NO_DEFAULT_LOG_FILE)
       withFileSizeLimit.push_back(conf);
 #endif  // !defined(ELPP_NO_DEFAULT_LOG_FILE)
     } else if (conf->configurationType() == ConfigurationType::LogFlushThreshold) {
       setValue(conf->level(), static_cast<std::size_t>(getULong(conf->value())), &m_logFlushThresholdMap);
     }
   }
   // As mentioned earlier, we will now set filename configuration in separate loop to deal with non-existent files
   for (Configurations::const_iterator it = configurations->begin(); it != configurations->end(); ++it) {
     Configuration* conf = *it;
     if (conf->configurationType() == ConfigurationType::Filename) {
       insertFile(conf->level(), conf->value());
     }
   }
   for (std::vector<Configuration*>::iterator conf = withFileSizeLimit.begin();
        conf != withFileSizeLimit.end(); ++conf) {
     // This is not unsafe as mutex is locked in currect scope
     unsafeValidateFileRolling((*conf)->level(), base::defaultPreRollOutCallback);
   }
 }
configurations()
const Configurations* el::base::TypedConfigurations::configurations (void) const inline
Definition at line 1970 of file easylogging++.h.
References el::Global.
Referenced by el::Logger::configure().
{
     return m_configurations;
   }
enabled()
bool el::base::TypedConfigurations::enabled (Level level)
Definition at line 1549 of file easylogging++.cc.
References el::base::LogFormat::level().
{
   return getConfigByVal<bool>(level, &m_enabledMap, "enabled");
 }
filename()
const std::string & el::base::TypedConfigurations::filename (Level level)
Definition at line 1557 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
   return getConfigByRef<std::string>(level, &m_filenameMap, "filename");
 }
fileStream()
base::type::fstream_t * el::base::TypedConfigurations::fileStream (Level level)
Definition at line 1581 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), and el::Logger::flush().
{
   return getConfigByRef<base::FileStreamPtr>(level, &m_fileStreamMap, "fileStream").get();
 }
getConfigByRef()
template<typename Conf_T > Conf_T& el::base::TypedConfigurations::getConfigByRef (Level level, std::map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 2013 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     return unsafeGetConfigByRef(level, confMap, confName);  // This is not unsafe anymore - mutex locked in scope
   }
getConfigByVal()
template<typename Conf_T > Conf_T el::base::TypedConfigurations::getConfigByVal (Level level, const std::map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 2007 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     return unsafeGetConfigByVal(level, confMap, confName);  // This is not unsafe anymore - mutex locked in scope
   }
getULong()
unsigned long el::base::TypedConfigurations::getULong (std::string confVal) private
Definition at line 1646 of file easylogging++.cc.
References ELPP_ASSERT, el::base::utils::Str::isDigit(), and el::base::utils::Str::trim().
{
   bool valid = true;
   base::utils::Str::trim(confVal);
   valid = !confVal.empty() && std::find_if(confVal.begin(), confVal.end(),
   [](char c) {
     return !base::utils::Str::isDigit(c);
   }) == confVal.end();
   if (!valid) {
     valid = false;
     ELPP_ASSERT(valid, "Configuration value not a valid integer [" << confVal << "]");
     return 0;
   }
   return atol(confVal.c_str());
 }
insertFile()
void el::base::TypedConfigurations::insertFile (Level level, const std::string & fullFilename) private
Definition at line 1700 of file easylogging++.cc.
References el::LevelHelper::convertToString(), el::base::utils::File::createPath(), ELPP_INTERNAL_ERROR, ELPP_UNUSED, el::base::utils::File::extractPathFromFilename(), el::Global, el::base::consts::kFilePathSeperator, el::base::LogFormat::level(), and el::base::utils::File::newFileStream().
{
 #if defined(ELPP_NO_LOG_TO_FILE)
   setValue(level, false, &m_toFileMap);
   ELPP_UNUSED(fullFilename);
   m_fileStreamMap.insert(std::make_pair(level, base::FileStreamPtr(nullptr)));
   return;
 #endif
   std::string resolvedFilename = resolveFilename(fullFilename);
   if (resolvedFilename.empty()) {
     std::cerr << "Could not load empty file for logging, please re-check your configurations for level ["
               << LevelHelper::convertToString(level) << "]";
   }
   std::string filePath = base::utils::File::extractPathFromFilename(resolvedFilename, base::consts::kFilePathSeperator);
   if (filePath.size() < resolvedFilename.size()) {
     base::utils::File::createPath(filePath);
   }
   auto create = [&](Level level) {
     base::LogStreamsReferenceMap::iterator filestreamIter = m_logStreamsReference->find(resolvedFilename);
     base::type::fstream_t* fs = nullptr;
     if (filestreamIter == m_logStreamsReference->end()) {
       // We need a completely new stream, nothing to share with
       fs = base::utils::File::newFileStream(resolvedFilename);
       m_filenameMap.insert(std::make_pair(level, resolvedFilename));
       m_fileStreamMap.insert(std::make_pair(level, base::FileStreamPtr(fs)));
       m_logStreamsReference->insert(std::make_pair(resolvedFilename, base::FileStreamPtr(m_fileStreamMap.at(level))));
     } else {
       // Woops! we have an existing one, share it!
       m_filenameMap.insert(std::make_pair(level, filestreamIter->first));
       m_fileStreamMap.insert(std::make_pair(level, base::FileStreamPtr(filestreamIter->second)));
       fs = filestreamIter->second.get();
     }
     if (fs == nullptr) {
       // We display bad file error from newFileStream()
       ELPP_INTERNAL_ERROR("Setting [TO_FILE] of ["
                           << LevelHelper::convertToString(level) << "] to FALSE", false);
       setValue(level, false, &m_toFileMap);
     }
   };
   // If we dont have file conf for any level, create it for Level::Global first
   // otherwise create for specified level
   create(m_filenameMap.empty() && m_fileStreamMap.empty() ? Level::Global : level);
 }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
logFlushThreshold()
std::size_t el::base::TypedConfigurations::logFlushThreshold (Level level)
Definition at line 1589 of file easylogging++.cc.
References el::base::LogFormat::level().
{
   return getConfigByVal<std::size_t>(level, &m_logFlushThresholdMap, "logFlushThreshold");
 }
logFormat()
const base::LogFormat & el::base::TypedConfigurations::logFormat (Level level)
Definition at line 1565 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogBuilder::build(), and el::Logger::resolveLoggerFormatSpec().
{
   return getConfigByRef<base::LogFormat>(level, &m_logFormatMap, "logFormat");
 }
maxLogFileSize()
std::size_t el::base::TypedConfigurations::maxLogFileSize (Level level)
Definition at line 1585 of file easylogging++.cc.
References el::base::LogFormat::level().
{
   return getConfigByVal<std::size_t>(level, &m_maxLogFileSizeMap, "maxLogFileSize");
 }
millisecondsWidth()
const base::MillisecondsWidth & el::base::TypedConfigurations::millisecondsWidth (Level level = Level::Global)
Definition at line 1573 of file easylogging++.cc.
References el::base::LogFormat::level().
{
   return getConfigByRef<base::MillisecondsWidth>(level, &m_subsecondPrecisionMap, "millisecondsWidth");
 }
performanceTracking()
bool el::base::TypedConfigurations::performanceTracking (Level level = Level::Global)
Definition at line 1577 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::PErrorWriter::~PErrorWriter().
{
   return getConfigByVal<bool>(level, &m_performanceTrackingMap, "performanceTracking");
 }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
resolveFilename()
std::string el::base::TypedConfigurations::resolveFilename (const std::string & filename) private
Definition at line 1661 of file easylogging++.cc.
References el::base::utils::DateTime::getDateTime(), el::base::consts::kDateTimeFormatSpecifierForFilename, el::base::consts::kDefaultDateTimeFormatInFilename, el::base::consts::kFormatSpecifierChar, and el::base::utils::Str::replaceAll().
{
   std::string resultingFilename = filename;
   std::size_t dateIndex = std::string::npos;
   std::string dateTimeFormatSpecifierStr = std::string(base::consts::kDateTimeFormatSpecifierForFilename);
   if ((dateIndex = resultingFilename.find(dateTimeFormatSpecifierStr.c_str())) != std::string::npos) {
     while (dateIndex > 0 && resultingFilename[dateIndex - 1] == base::consts::kFormatSpecifierChar) {
       dateIndex = resultingFilename.find(dateTimeFormatSpecifierStr.c_str(), dateIndex + 1);
     }
     if (dateIndex != std::string::npos) {
       const char* ptr = resultingFilename.c_str() + dateIndex;
       // Goto end of specifier
       ptr += dateTimeFormatSpecifierStr.size();
       std::string fmt;
       if ((resultingFilename.size() > dateIndex) && (ptr[0] == '{')) {
         // User has provided format for date/time
         ++ptr;
         int count = 1;  // Start by 1 in order to remove starting brace
         std::stringstream ss;
         for (; *ptr; ++ptr, ++count) {
           if (*ptr == '}') {
             ++count;  // In order to remove ending brace
             break;
           }
           ss << *ptr;
         }
         resultingFilename.erase(dateIndex + dateTimeFormatSpecifierStr.size(), count);
         fmt = ss.str();
       } else {
         fmt = std::string(base::consts::kDefaultDateTimeFormatInFilename);
       }
       base::SubsecondPrecision ssPrec(3);
       std::string now = base::utils::DateTime::getDateTime(fmt.c_str(), &ssPrec);
       base::utils::Str::replaceAll(now, '/', '-'); // Replace path element since we are dealing with filename
       base::utils::Str::replaceAll(resultingFilename, dateTimeFormatSpecifierStr, now);
     }
   }
   return resultingFilename;
 }
setValue()
template<typename Conf_T > void el::base::TypedConfigurations::setValue (Level level, const Conf_T & value, std::map< Level, Conf_T > * confMap, bool includeGlobalLevel = true) inline private
Definition at line 2052 of file easylogging++.h.
References el::Global.
{
     // If map is empty and we are allowed to add into generic level (Level::Global), do it!
     if (confMap->empty() && includeGlobalLevel) {
       confMap->insert(std::make_pair(Level::Global, value));
       return;
     }
     // If same value exist in generic level already, dont add it to explicit level
     typename std::map<Level, Conf_T>::iterator it = confMap->find(Level::Global);
     if (it != confMap->end() && it->second == value) {
       return;
     }
     // Now make sure we dont double up values if we really need to add it to explicit level
     it = confMap->find(level);
     if (it == confMap->end()) {
       // Value not found for level, add new
       confMap->insert(std::make_pair(level, value));
     } else {
       // Value found, just update value
       confMap->at(level) = value;
     }
   }
subsecondPrecision()
const base::SubsecondPrecision & el::base::TypedConfigurations::subsecondPrecision (Level level = Level::Global)
Definition at line 1569 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogBuilder::build().
{
   return getConfigByRef<base::SubsecondPrecision>(level, &m_subsecondPrecisionMap, "subsecondPrecision");
 }
toFile()
bool el::base::TypedConfigurations::toFile (Level level)
Definition at line 1553 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), and el::Logger::flush().
{
   return getConfigByVal<bool>(level, &m_toFileMap, "toFile");
 }
toStandardOutput()
bool el::base::TypedConfigurations::toStandardOutput (Level level)
Definition at line 1561 of file easylogging++.cc.
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
   return getConfigByVal<bool>(level, &m_toStandardOutputMap, "toStandardOutput");
 }
unsafeGetConfigByRef()
template<typename Conf_T > Conf_T& el::base::TypedConfigurations::unsafeGetConfigByRef (Level level, std::map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 2036 of file easylogging++.h.
References el::LevelHelper::convertToString(), ELPP_INTERNAL_ERROR, ELPP_UNUSED, and el::Global.
{
     ELPP_UNUSED(confName);
     typename std::map<Level, Conf_T>::iterator it = confMap->find(level);
     if (it == confMap->end()) {
       try {
         return confMap->at(Level::Global);
       } catch (...) {
         ELPP_INTERNAL_ERROR("Unable to get configuration [" << confName << "] for level ["
                             << LevelHelper::convertToString(level) << "]"
                             << std::endl << "Please ensure you have properly configured logger.", false);
       }
     }
     return it->second;
   }
unsafeGetConfigByVal()
template<typename Conf_T > Conf_T el::base::TypedConfigurations::unsafeGetConfigByVal (Level level, const std::map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 2019 of file easylogging++.h.
References el::LevelHelper::convertToString(), ELPP_INTERNAL_ERROR, ELPP_UNUSED, and el::Global.
{
     ELPP_UNUSED(confName);
     typename std::map<Level, Conf_T>::const_iterator it = confMap->find(level);
     if (it == confMap->end()) {
       try {
         return confMap->at(Level::Global);
       } catch (...) {
         ELPP_INTERNAL_ERROR("Unable to get configuration [" << confName << "] for level ["
                             << LevelHelper::convertToString(level) << "]"
                             << std::endl << "Please ensure you have properly configured logger.", false);
         return Conf_T();
       }
     }
     return it->second;
   }
unsafeValidateFileRolling()
bool el::base::TypedConfigurations::unsafeValidateFileRolling (Level level, const PreRollOutCallback & preRollOutCallback) private
Definition at line 1743 of file easylogging++.cc.
References el::LevelHelper::convertToString(), ELPP_INTERNAL_INFO, and el::base::utils::File::getSizeOfFile().
{
   base::type::fstream_t* fs = unsafeGetConfigByRef(level, &m_fileStreamMap, "fileStream").get();
   if (fs == nullptr) {
     return true;
   }
   std::size_t maxLogFileSize = unsafeGetConfigByVal(level, &m_maxLogFileSizeMap, "maxLogFileSize");
   std::size_t currFileSize = base::utils::File::getSizeOfFile(fs);
   if (maxLogFileSize != 0 && currFileSize >= maxLogFileSize) {
     std::string fname = unsafeGetConfigByRef(level, &m_filenameMap, "filename");
     ELPP_INTERNAL_INFO(1, "Truncating log file [" << fname << "] as a result of configurations for level ["
                        << LevelHelper::convertToString(level) << "]");
     fs->close();
     preRollOutCallback(fname.c_str(), currFileSize);
     fs->open(fname, std::fstream::out | std::fstream::trunc);
     return true;
   }
   return false;
 }
validateFileRolling()
bool el::base::TypedConfigurations::validateFileRolling (Level level, const PreRollOutCallback & preRollOutCallback) inline private
Definition at line 2080 of file easylogging++.h.
Referenced by el::base::LogDispatcher::dispatch(), and el::Helpers::validateFileRolling().
{
     base::threading::ScopedLock scopedLock(lock());
     return unsafeValidateFileRolling(level, preRollOutCallback);
   }
Friends And Related Function Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
Definition at line 2003 of file easylogging++.h.
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
Definition at line 2004 of file easylogging++.h.
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
Definition at line 2001 of file easylogging++.h.
el::base::Writer
friend class el::base::Writer friend
Definition at line 2002 of file easylogging++.h.
el::Helpers
friend class el::Helpers friend
Definition at line 2000 of file easylogging++.h.
Member Data Documentation
m_configurations
Configurations* el::base::TypedConfigurations::m_configurations private
Definition at line 1987 of file easylogging++.h.
Referenced by TypedConfigurations().
m_enabledMap
std::map<Level, bool> el::base::TypedConfigurations::m_enabledMap private
Definition at line 1988 of file easylogging++.h.
m_filenameMap
std::map<Level, std::string> el::base::TypedConfigurations::m_filenameMap private
Definition at line 1990 of file easylogging++.h.
m_fileStreamMap
std::map<Level, base::FileStreamPtr> el::base::TypedConfigurations::m_fileStreamMap private
Definition at line 1995 of file easylogging++.h.
m_logFlushThresholdMap
std::map<Level, std::size_t> el::base::TypedConfigurations::m_logFlushThresholdMap private
Definition at line 1997 of file easylogging++.h.
m_logFormatMap
std::map<Level, base::LogFormat> el::base::TypedConfigurations::m_logFormatMap private
Definition at line 1992 of file easylogging++.h.
m_logStreamsReference
base::LogStreamsReferenceMap* el::base::TypedConfigurations::m_logStreamsReference private
Definition at line 1998 of file easylogging++.h.
Referenced by TypedConfigurations().
m_maxLogFileSizeMap
std::map<Level, std::size_t> el::base::TypedConfigurations::m_maxLogFileSizeMap private
Definition at line 1996 of file easylogging++.h.
m_performanceTrackingMap
std::map<Level, bool> el::base::TypedConfigurations::m_performanceTrackingMap private
Definition at line 1994 of file easylogging++.h.
m_subsecondPrecisionMap
std::map<Level, base::SubsecondPrecision> el::base::TypedConfigurations::m_subsecondPrecisionMap private
Definition at line 1993 of file easylogging++.h.
m_toFileMap
std::map<Level, bool> el::base::TypedConfigurations::m_toFileMap private
Definition at line 1989 of file easylogging++.h.
m_toStandardOutputMap
std::map<Level, bool> el::base::TypedConfigurations::m_toStandardOutputMap private
Definition at line 1991 of file easylogging++.h.
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc