VulpesRender: el::Configuration Class Reference
el::Configuration Class Reference
Represents single configuration that has representing level, configuration type and a string based value.
#include <easylogging++.h>
Classes
class Predicate
Used to find configuration from configuration (pointers) repository. Avoid using it.
Public Member Functions
Configuration (const Configuration &c)
Configuration & operator= (const Configuration &c)
virtual ~Configuration (void)
Configuration (Level level, ConfigurationType configurationType, const std::string &value)
Full constructor used to sets value of configuration.
Level level (void) const
Gets level of current configuration.
ConfigurationType configurationType (void) const
Gets configuration type of current configuration.
const std::string & value (void) const
Gets string based configuration value.
void setValue (const std::string &value)
Set string based configuration value.
virtual void log (el::base::type::ostream_t &os) const
Private Attributes
Level m_level
ConfigurationType m_configurationType
std::string m_value
Detailed Description
Represents single configuration that has representing level, configuration type and a string based value.
String based value means any value either its boolean, integer or string itself, it will be embedded inside quotes and will be parsed later.
Consider some examples below:
el::Configuration confEnabledInfo(el::Level::Info, el::ConfigurationType::Enabled, "true");
el::Configuration confMaxLogFileSizeInfo(el::Level::Info, el::ConfigurationType::MaxLogFileSize, "2048");
el::Configuration confFilenameInfo(el::Level::Info, el::ConfigurationType::Filename, "/var/log/my.log");
Definition at line 1728 of file easylogging++.h.
Constructor & Destructor Documentation
Configuration() [1/2]
el::Configuration::Configuration (const Configuration & c)
Definition at line 152 of file easylogging++.cc.
                                                    :
   m_level(c.m_level),
   m_configurationType(c.m_configurationType),
   m_value(c.m_value) {
 }
~Configuration()
virtual el::Configuration::~Configuration (void) inline virtual
Definition at line 1733 of file easylogging++.h.
{
   }
Configuration() [2/2]
el::Configuration::Configuration (Level level, ConfigurationType configurationType, const std::string & value)
Full constructor used to sets value of configuration.
Definition at line 168 of file easylogging++.cc.
                                                                                                      :
   m_level(level),
   m_configurationType(configurationType),
   m_value(value) {
 }
Member Function Documentation
configurationType()
ConfigurationType el::Configuration::configurationType (void) const inline
Gets configuration type of current configuration.
Definition at line 1745 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::build(), el::Configuration::Predicate::operator()(), and el::Configurations::set().
{
     return m_configurationType;
   }
level()
Level el::Configuration::level (void) const inline
Gets level of current configuration.
Definition at line 1740 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::build(), el::Configuration::Predicate::operator()(), and el::Configurations::set().
{
     return m_level;
   }
log()
void el::Configuration::log (el::base::type::ostream_t & os) const virtual
Implements el::Loggable.
Definition at line 174 of file easylogging++.cc.
References el::LevelHelper::convertToString(), el::ConfigurationTypeHelper::convertToString(), ELPP_LITERAL, m_configurationType, m_level, and m_value.
{
   os << LevelHelper::convertToString(m_level)
      << ELPP_LITERAL(" ") << ConfigurationTypeHelper::convertToString(m_configurationType)
      << ELPP_LITERAL(" = ") << m_value.c_str();
 }
operator=()
Configuration & el::Configuration::operator= (const Configuration & c)
Definition at line 158 of file easylogging++.cc.
References m_configurationType, m_level, and m_value.
{
   if (&c != this) {
     m_level = c.m_level;
     m_configurationType = c.m_configurationType;
     m_value = c.m_value;
   }
   return *this;
 }
setValue()
void el::Configuration::setValue (const std::string & value) inline
Set string based configuration value.
Parameters
value Value to set. Values have to be std::string; For boolean values use "true", "false", for any integral values use them in quotes. They will be parsed when configuring
Definition at line 1757 of file easylogging++.h.
Referenced by el::Configurations::unsafeSet().
{
     m_value = value;
   }
value()
const std::string& el::Configuration::value (void) const inline
Gets string based configuration value.
Definition at line 1750 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::build(), and el::Configurations::set().
{
     return m_value;
   }
Member Data Documentation
m_configurationType
ConfigurationType el::Configuration::m_configurationType private
Definition at line 1777 of file easylogging++.h.
Referenced by log(), and operator=().
m_level
Level el::Configuration::m_level private
Definition at line 1776 of file easylogging++.h.
Referenced by log(), and operator=().
m_value
std::string el::Configuration::m_value private
Definition at line 1778 of file easylogging++.h.
Referenced by log(), and operator=().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc