VulpesRender: el::Helpers Class Reference
el::Helpers Class Reference
Static helpers for developers.
#include <easylogging++.h>
Static Public Member Functions
static void setStorage (base::type::StoragePointer storage)
Shares logging repository (base::Storage)
static base::type::StoragePointer storage ()
static void setArgs (int argc, char **argv)
Sets application arguments and figures out whats active for logging and whats not.
static void setArgs (int argc, const char **argv)
Sets application arguments and figures out whats active for logging and whats not.
static void setThreadName (const std::string &name)
Sets thread name for current thread. Requires std::thread.
static std::string getThreadName ()
static void installPreRollOutCallback (const PreRollOutCallback &callback)
Installs pre rollout callback, this callback is triggered when log file is about to be rolled out (can be useful for backing up)
static void uninstallPreRollOutCallback (void)
Uninstalls pre rollout callback.
template<typename T >
static bool installLogDispatchCallback (const std::string &id)
Installs post log dispatch callback, this callback is triggered when log is dispatched.
template<typename T >
static void uninstallLogDispatchCallback (const std::string &id)
Uninstalls log dispatch callback.
template<typename T >
static T * logDispatchCallback (const std::string &id)
template<typename T >
static std::string convertTemplateToStdString (const T &templ)
Converts template to std::string - useful for loggable classes to log containers within log(std::ostream&) const.
static const el::base::utils::CommandLineArgs * commandLineArgs (void)
Returns command line arguments (pointer) provided to easylogging++.
static void installCustomFormatSpecifier (const CustomFormatSpecifier &customFormatSpecifier)
Installs user defined format specifier and handler.
static bool uninstallCustomFormatSpecifier (const char *formatSpecifier)
Uninstalls user defined format specifier and handler.
static bool hasCustomFormatSpecifier (const char *formatSpecifier)
Returns true if custom format specifier is installed.
static void validateFileRolling (Logger *logger, Level level)
Detailed Description
Static helpers for developers.
Definition at line 3685 of file easylogging++.h.
Member Function Documentation
commandLineArgs()
static const el::base::utils::CommandLineArgs* el::Helpers::commandLineArgs (void) inline static
Returns command line arguments (pointer) provided to easylogging++.
Definition at line 3789 of file easylogging++.h.
References ELPP.
Referenced by el::Loggers::configureFromArg().
{
     return ELPP->commandLineArgs();
   }
convertTemplateToStdString()
template<typename T > static std::string el::Helpers::convertTemplateToStdString (const T & templ) inline static
Converts template to std::string - useful for loggable classes to log containers within log(std::ostream&) const.
Definition at line 3769 of file easylogging++.h.
References el::base::threading::ThreadSafe::acquireLock(), ELPP, ELPP_LITERAL, el::base::MessageBuilder::initialize(), el::base::consts::kDefaultLoggerId, el::base::threading::ThreadSafe::releaseLock(), and el::Logger::stream().
{
     el::Logger* logger =
       ELPP->registeredLoggers()->get(el::base::consts::kDefaultLoggerId);
     if (logger == nullptr) {
       return std::string();
     }
     base::MessageBuilder b;
     b.initialize(logger);
     logger->acquireLock();
     b << templ;
 #if defined(ELPP_UNICODE)
     std::string s = std::string(logger->stream().str().begin(), logger->stream().str().end());
 #else
     std::string s = logger->stream().str();
 #endif  // defined(ELPP_UNICODE)
     logger->stream().str(ELPP_LITERAL(""));
     logger->releaseLock();
     return s;
   }
getThreadName()
static std::string el::Helpers::getThreadName () inline static
Definition at line 3707 of file easylogging++.h.
References el::elCrashHandler, ELPP, el::Fatal, el::base::threading::getCurrentThreadId(), and el::base::consts::kDefaultLoggerId.
{
     return ELPP->getThreadName(base::threading::getCurrentThreadId());
   }
hasCustomFormatSpecifier()
static bool el::Helpers::hasCustomFormatSpecifier (const char * formatSpecifier) inline static
Returns true if custom format specifier is installed.
Definition at line 3801 of file easylogging++.h.
References ELPP.
{
     return ELPP->hasCustomFormatSpecifier(formatSpecifier);
   }
installCustomFormatSpecifier()
static void el::Helpers::installCustomFormatSpecifier (const CustomFormatSpecifier & customFormatSpecifier) inline static
Installs user defined format specifier and handler.
Definition at line 3793 of file easylogging++.h.
References ELPP.
{
     ELPP->installCustomFormatSpecifier(customFormatSpecifier);
   }
installLogDispatchCallback()
template<typename T > static bool el::Helpers::installLogDispatchCallback (const std::string & id) inline static
Installs post log dispatch callback, this callback is triggered when log is dispatched.
Definition at line 3739 of file easylogging++.h.
References ELPP.
{
     return ELPP->installLogDispatchCallback<T>(id);
   }
installPreRollOutCallback()
static void el::Helpers::installPreRollOutCallback (const PreRollOutCallback & callback) inline static
Installs pre rollout callback, this callback is triggered when log file is about to be rolled out (can be useful for backing up)
Definition at line 3730 of file easylogging++.h.
{
     ELPP->setPreRollOutCallback(callback);
   }
logDispatchCallback()
template<typename T > static T* el::Helpers::logDispatchCallback (const std::string & id) inline static
Definition at line 3748 of file easylogging++.h.
References ELPP.
{
     return ELPP->logDispatchCallback<T>(id);
   }
setArgs() [1/2]
static void el::Helpers::setArgs (int argc, char ** argv) inline static
Sets application arguments and figures out whats active for logging and whats not.
Definition at line 3696 of file easylogging++.h.
References ELPP.
{
     ELPP->setApplicationArguments(argc, argv);
   }
setArgs() [2/2]
static void el::Helpers::setArgs (int argc, const char ** argv) inline static
Sets application arguments and figures out whats active for logging and whats not.
Definition at line 3700 of file easylogging++.h.
References ELPP.
{
     ELPP->setApplicationArguments(argc, const_cast<char**>(argv));
   }
setStorage()
static void el::Helpers::setStorage (base::type::StoragePointer storage) inline static
Shares logging repository (base::Storage)
Definition at line 3688 of file easylogging++.h.
References ELPP.
{
     ELPP = storage;
   }
setThreadName()
static void el::Helpers::setThreadName (const std::string & name) inline static
Sets thread name for current thread. Requires std::thread.
Definition at line 3704 of file easylogging++.h.
References ELPP.
{
     ELPP->setThreadName(name);
   }
storage()
static base::type::StoragePointer el::Helpers::storage () inline static
Returns
Main storage repository
Definition at line 3692 of file easylogging++.h.
References ELPP.
{
     return ELPP;
   }
uninstallCustomFormatSpecifier()
static bool el::Helpers::uninstallCustomFormatSpecifier (const char * formatSpecifier) inline static
Uninstalls user defined format specifier and handler.
Definition at line 3797 of file easylogging++.h.
References ELPP.
{
     return ELPP->uninstallCustomFormatSpecifier(formatSpecifier);
   }
uninstallLogDispatchCallback()
template<typename T > static void el::Helpers::uninstallLogDispatchCallback (const std::string & id) inline static
Uninstalls log dispatch callback.
Definition at line 3744 of file easylogging++.h.
References ELPP.
{
     ELPP->uninstallLogDispatchCallback<T>(id);
   }
uninstallPreRollOutCallback()
static void el::Helpers::uninstallPreRollOutCallback (void) inline static
Uninstalls pre rollout callback.
Definition at line 3734 of file easylogging++.h.
References ELPP.
{
     ELPP->unsetPreRollOutCallback();
   }
validateFileRolling()
static void el::Helpers::validateFileRolling (Logger * logger, Level level) inline static
Definition at line 3804 of file easylogging++.h.
References ELPP, el::Logger::m_typedConfigurations, and el::base::TypedConfigurations::validateFileRolling().
{
     if (logger == nullptr) return;
     logger->m_typedConfigurations->validateFileRolling(level, ELPP->preRollOutCallback());
   }
The documentation for this class was generated from the following file:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h