VulpesRender: el::base::DefaultLogBuilder Class Reference
el::base::DefaultLogBuilder Class Reference
#include <easylogging++.h>
Public Member Functions
base::type::string_t build (const LogMessage *logMessage, bool appendNewLine) const
void convertToColoredOutput (base::type::string_t *logLine, Level level)
Detailed Description
Definition at line 2806 of file easylogging++.h.
Member Function Documentation
build()
base::type::string_t el::base::DefaultLogBuilder::build (const LogMessage * logMessage, bool appendNewLine) const virtual
Implements el::LogBuilder.
Definition at line 2285 of file easylogging++.cc.
References el::base::utils::Str::addToBuff(), el::base::AppName, el::base::utils::File::buildBaseFilename(), el::base::utils::File::buildStrippedFilename(), el::base::utils::Str::clearBuff(), el::base::utils::Str::convertAndAddToBuff(), el::base::DateTime, el::base::LogFormat::dateTimeFormat(), ELPP, ELPP_LITERAL, el::base::File, el::LogMessage::file(), el::base::FileBase, el::base::LogFormat::format(), el::LogMessage::func(), el::base::Function, el::base::threading::getCurrentThreadId(), el::base::utils::DateTime::getDateTime(), el::base::LogFormat::hasFlag(), el::base::consts::kAppNameFormatSpecifier, el::base::consts::kDateTimeFormatSpecifier, el::base::consts::kLogFileBaseFormatSpecifier, el::base::consts::kLogFileFormatSpecifier, el::base::consts::kLogFunctionFormatSpecifier, el::base::consts::kLogLineFormatSpecifier, el::base::consts::kLogLocationFormatSpecifier, el::base::consts::kMessageFormatSpecifier, el::base::consts::kSourceFilenameMaxLength, el::base::consts::kSourceLineMaxLength, el::base::consts::kThreadIdFormatSpecifier, el::base::consts::kVerboseLevelFormatSpecifier, el::LogMessage::level(), el::base::Line, el::LogMessage::line(), el::base::Location, el::base::TypedConfigurations::logFormat(), el::LogMessage::logger(), el::base::LogMessage, el::LogMessage::message(), el::Logger::parentApplicationName(), el::base::utils::Str::replaceFirstWithEscape(), el::base::TypedConfigurations::subsecondPrecision(), el::base::ThreadId, el::Logger::typedConfigurations(), el::Verbose, el::base::VerboseLevel, and el::LogMessage::verboseLevel().
{
   base::TypedConfigurations* tc = logMessage->logger()->typedConfigurations();
   const base::LogFormat* logFormat = &tc->logFormat(logMessage->level());
   base::type::string_t logLine = logFormat->format();
   char buff[base::consts::kSourceFilenameMaxLength + base::consts::kSourceLineMaxLength] = "";
   const char* bufLim = buff + sizeof(buff);
   if (logFormat->hasFlag(base::FormatFlags::AppName)) {
     // App name
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kAppNameFormatSpecifier,
         logMessage->logger()->parentApplicationName());
   }
   if (logFormat->hasFlag(base::FormatFlags::ThreadId)) {
     // Thread ID
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kThreadIdFormatSpecifier,
         ELPP->getThreadName(base::threading::getCurrentThreadId()));
   }
   if (logFormat->hasFlag(base::FormatFlags::DateTime)) {
     // DateTime
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kDateTimeFormatSpecifier,
         base::utils::DateTime::getDateTime(logFormat->dateTimeFormat().c_str(),
                                            &tc->subsecondPrecision(logMessage->level())));
   }
   if (logFormat->hasFlag(base::FormatFlags::Function)) {
     // Function
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kLogFunctionFormatSpecifier, logMessage->func());
   }
   if (logFormat->hasFlag(base::FormatFlags::File)) {
     // File
     base::utils::Str::clearBuff(buff, base::consts::kSourceFilenameMaxLength);
     base::utils::File::buildStrippedFilename(logMessage->file().c_str(), buff);
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kLogFileFormatSpecifier, std::string(buff));
   }
   if (logFormat->hasFlag(base::FormatFlags::FileBase)) {
     // FileBase
     base::utils::Str::clearBuff(buff, base::consts::kSourceFilenameMaxLength);
     base::utils::File::buildBaseFilename(logMessage->file(), buff);
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kLogFileBaseFormatSpecifier, std::string(buff));
   }
   if (logFormat->hasFlag(base::FormatFlags::Line)) {
     // Line
     char* buf = base::utils::Str::clearBuff(buff, base::consts::kSourceLineMaxLength);
     buf = base::utils::Str::convertAndAddToBuff(logMessage->line(), base::consts::kSourceLineMaxLength, buf, bufLim, false);
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kLogLineFormatSpecifier, std::string(buff));
   }
   if (logFormat->hasFlag(base::FormatFlags::Location)) {
     // Location
     char* buf = base::utils::Str::clearBuff(buff,
                                             base::consts::kSourceFilenameMaxLength + base::consts::kSourceLineMaxLength);
     base::utils::File::buildStrippedFilename(logMessage->file().c_str(), buff);
     buf = base::utils::Str::addToBuff(buff, buf, bufLim);
     buf = base::utils::Str::addToBuff(":", buf, bufLim);
     buf = base::utils::Str::convertAndAddToBuff(logMessage->line(),  base::consts::kSourceLineMaxLength, buf, bufLim,
           false);
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kLogLocationFormatSpecifier, std::string(buff));
   }
   if (logMessage->level() == Level::Verbose && logFormat->hasFlag(base::FormatFlags::VerboseLevel)) {
     // Verbose level
     char* buf = base::utils::Str::clearBuff(buff, 1);
     buf = base::utils::Str::convertAndAddToBuff(logMessage->verboseLevel(), 1, buf, bufLim, false);
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kVerboseLevelFormatSpecifier, std::string(buff));
   }
   if (logFormat->hasFlag(base::FormatFlags::LogMessage)) {
     // Log message
     base::utils::Str::replaceFirstWithEscape(logLine, base::consts::kMessageFormatSpecifier, logMessage->message());
   }
 #if !defined(ELPP_DISABLE_CUSTOM_FORMAT_SPECIFIERS)
   for (std::vector<CustomFormatSpecifier>::const_iterator it = ELPP->customFormatSpecifiers()->begin();
        it != ELPP->customFormatSpecifiers()->end(); ++it) {
     std::string fs(it->formatSpecifier());
     base::type::string_t wcsFormatSpecifier(fs.begin(), fs.end());
     base::utils::Str::replaceFirstWithEscape(logLine, wcsFormatSpecifier, it->resolver()(logMessage));
   }
 #endif  // !defined(ELPP_DISABLE_CUSTOM_FORMAT_SPECIFIERS)
   if (appendNewLine) logLine += ELPP_LITERAL("\n");
   return logLine;
 }
convertToColoredOutput()
void el::LogBuilder::convertToColoredOutput (base::type::string_t * logLine, Level level) inherited
Definition at line 504 of file easylogging++.cc.
References el::Debug, ELPP_LITERAL, el::Error, el::Fatal, el::Info, el::Trace, and el::Warning.
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
   if (!m_termSupportsColor) return;
   const base::type::char_t* resetColor = ELPP_LITERAL("\x1b[0m");
   if (level == Level::Error || level == Level::Fatal)
     *logLine = ELPP_LITERAL("\x1b[31m") + *logLine + resetColor;
   else if (level == Level::Warning)
     *logLine = ELPP_LITERAL("\x1b[33m") + *logLine + resetColor;
   else if (level == Level::Debug)
     *logLine = ELPP_LITERAL("\x1b[32m") + *logLine + resetColor;
   else if (level == Level::Info)
     *logLine = ELPP_LITERAL("\x1b[36m") + *logLine + resetColor;
   else if (level == Level::Trace)
     *logLine = ELPP_LITERAL("\x1b[35m") + *logLine + resetColor;
 }
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc