VulpesRender: el::base::Storage Class Reference
el::base::Storage Class Reference
Easylogging++ management storage.
#include <easylogging++.h>
Public Member Functions
Storage (const LogBuilderPtr &defaultLogBuilder)
virtual ~Storage (void)
bool validateEveryNCounter (const char *filename, base::type::LineNumber lineNumber, std::size_t occasion)
bool validateAfterNCounter (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
bool validateNTimesCounter (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
base::RegisteredHitCounters * hitCounters (void) const
base::RegisteredLoggers * registeredLoggers (void) const
base::VRegistry * vRegistry (void) const
const base::utils::CommandLineArgs * commandLineArgs (void) const
void addFlag (LoggingFlag flag)
void removeFlag (LoggingFlag flag)
bool hasFlag (LoggingFlag flag) const
base::type::EnumType flags (void) const
void setFlags (base::type::EnumType flags)
void setPreRollOutCallback (const PreRollOutCallback &callback)
void unsetPreRollOutCallback (void)
PreRollOutCallback & preRollOutCallback (void)
bool hasCustomFormatSpecifier (const char *formatSpecifier)
void installCustomFormatSpecifier (const CustomFormatSpecifier &customFormatSpecifier)
bool uninstallCustomFormatSpecifier (const char *formatSpecifier)
const std::vector< CustomFormatSpecifier > * customFormatSpecifiers (void) const
void setLoggingLevel (Level level)
template<typename T >
bool installLogDispatchCallback (const std::string &id)
template<typename T >
void uninstallLogDispatchCallback (const std::string &id)
template<typename T >
T * logDispatchCallback (const std::string &id)
void setThreadName (const std::string &name)
Sets thread name for current thread. Requires std::thread.
std::string getThreadName (const std::string &threadId)
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
void setApplicationArguments (int argc, char **argv)
void setApplicationArguments (int argc, const char **argv)
Private Attributes
base::RegisteredHitCounters * m_registeredHitCounters
base::RegisteredLoggers * m_registeredLoggers
base::type::EnumType m_flags
base::VRegistry * m_vRegistry
base::utils::CommandLineArgs m_commandLineArgs
PreRollOutCallback m_preRollOutCallback
std::map< std::string, base::type::LogDispatchCallbackPtr > m_logDispatchCallbacks
std::map< std::string, base::type::PerformanceTrackingCallbackPtr > m_performanceTrackingCallbacks
std::map< std::string, std::string > m_threadNames
std::vector< CustomFormatSpecifier > m_customFormatSpecifiers
Level m_loggingLevel
Friends
class el::Helpers
class el::base::DefaultLogDispatchCallback
class el::LogBuilder
class el::base::MessageBuilder
class el::base::Writer
class el::base::PerformanceTracker
class el::base::LogDispatcher
Detailed Description
Easylogging++ management storage.
Definition at line 2599 of file easylogging++.h.
Constructor & Destructor Documentation
Storage()
el::base::Storage::Storage (const LogBuilderPtr & defaultLogBuilder) explicit
Definition at line 1986 of file easylogging++.cc.
References el::base::utils::addFlag(), el::AllowVerboseIfModuleNotSpecified, el::Logger::configurations(), ELPP_INTERNAL_INFO, el::Format, el::base::consts::kDefaultLoggerId, el::base::consts::kPerformanceLoggerId, el::Logger::reconfigure(), and el::Configurations::setGlobally().
                                                        :
 #endif  // ELPP_ASYNC_LOGGING
   m_registeredHitCounters(new base::RegisteredHitCounters()),
   m_registeredLoggers(new base::RegisteredLoggers(defaultLogBuilder)),
   m_flags(ELPP_DEFAULT_LOGGING_FLAGS),
   m_vRegistry(new base::VRegistry(0, &m_flags)),
 #if ELPP_ASYNC_LOGGING
   m_asyncLogQueue(new base::AsyncLogQueue()),
   m_asyncDispatchWorker(asyncDispatchWorker),
 #endif  // ELPP_ASYNC_LOGGING
   m_preRollOutCallback(base::defaultPreRollOutCallback) {
   // Register default logger
   m_registeredLoggers->get(std::string(base::consts::kDefaultLoggerId));
   // We register default logger anyway (worse case it's not going to register) just in case
   m_registeredLoggers->get("default");
   // Register performance logger and reconfigure format
   Logger* performanceLogger = m_registeredLoggers->get(std::string(base::consts::kPerformanceLoggerId));
   m_registeredLoggers->get("performance");
   performanceLogger->configurations()->setGlobally(ConfigurationType::Format, std::string("%datetime %level %msg"));
   performanceLogger->reconfigure();
 #if defined(ELPP_SYSLOG)
   // Register syslog logger and reconfigure format
   Logger* sysLogLogger = m_registeredLoggers->get(std::string(base::consts::kSysLogLoggerId));
   sysLogLogger->configurations()->setGlobally(ConfigurationType::Format, std::string("%level: %msg"));
   sysLogLogger->reconfigure();
 #endif //  defined(ELPP_SYSLOG)
   addFlag(LoggingFlag::AllowVerboseIfModuleNotSpecified);
 #if ELPP_ASYNC_LOGGING
   installLogDispatchCallback<base::AsyncLogDispatchCallback>(std::string("AsyncLogDispatchCallback"));
 #else
   installLogDispatchCallback<base::DefaultLogDispatchCallback>(std::string("DefaultLogDispatchCallback"));
 #endif  // ELPP_ASYNC_LOGGING
 #if defined(ELPP_FEATURE_ALL) || defined(ELPP_FEATURE_PERFORMANCE_TRACKING)
   installPerformanceTrackingCallback<base::DefaultPerformanceTrackingCallback>
   (std::string("DefaultPerformanceTrackingCallback"));
 #endif // defined(ELPP_FEATURE_ALL) || defined(ELPP_FEATURE_PERFORMANCE_TRACKING)
   ELPP_INTERNAL_INFO(1, "Easylogging++ has been initialized");
 #if ELPP_ASYNC_LOGGING
   m_asyncDispatchWorker->start();
 #endif  // ELPP_ASYNC_LOGGING
 }
~Storage()
el::base::Storage::~Storage (void) virtual
Definition at line 2028 of file easylogging++.cc.
References ELPP_INTERNAL_INFO, and el::base::utils::safeDelete().
                       {
   ELPP_INTERNAL_INFO(4, "Destroying storage");
 #if ELPP_ASYNC_LOGGING
   ELPP_INTERNAL_INFO(5, "Replacing log dispatch callback to synchronous");
   uninstallLogDispatchCallback<base::AsyncLogDispatchCallback>(std::string("AsyncLogDispatchCallback"));
   installLogDispatchCallback<base::DefaultLogDispatchCallback>(std::string("DefaultLogDispatchCallback"));
   ELPP_INTERNAL_INFO(5, "Destroying asyncDispatchWorker");
   base::utils::safeDelete(m_asyncDispatchWorker);
   ELPP_INTERNAL_INFO(5, "Destroying asyncLogQueue");
   base::utils::safeDelete(m_asyncLogQueue);
 #endif  // ELPP_ASYNC_LOGGING
   ELPP_INTERNAL_INFO(5, "Destroying registeredHitCounters");
   base::utils::safeDelete(m_registeredHitCounters);
   ELPP_INTERNAL_INFO(5, "Destroying registeredLoggers");
   base::utils::safeDelete(m_registeredLoggers);
   ELPP_INTERNAL_INFO(5, "Destroying vRegistry");
   base::utils::safeDelete(m_vRegistry);
 }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
addFlag()
void el::base::Storage::addFlag (LoggingFlag flag) inline
Definition at line 2643 of file easylogging++.h.
References el::base::utils::addFlag().
{
     base::utils::addFlag(flag, &m_flags);
   }
commandLineArgs()
const base::utils::CommandLineArgs* el::base::Storage::commandLineArgs (void) const inline
Definition at line 2639 of file easylogging++.h.
{
     return &m_commandLineArgs;
   }
customFormatSpecifiers()
const std::vector<CustomFormatSpecifier>* el::base::Storage::customFormatSpecifiers (void) const inline
Definition at line 2679 of file easylogging++.h.
{
     return &m_customFormatSpecifiers;
   }
flags()
base::type::EnumType el::base::Storage::flags (void) const inline
Definition at line 2655 of file easylogging++.h.
{
     return m_flags;
   }
getThreadName()
std::string el::base::Storage::getThreadName (const std::string & threadId) inline
Definition at line 2727 of file easylogging++.h.
{
     std::map<std::string, std::string>::const_iterator it = m_threadNames.find(threadId);
     if (it == m_threadNames.end()) {
       return threadId;
     }
     return it->second;
   }
hasCustomFormatSpecifier()
bool el::base::Storage::hasCustomFormatSpecifier (const char * formatSpecifier)
Definition at line 2047 of file easylogging++.cc.
References el::base::threading::ThreadSafe::lock().
{
   base::threading::ScopedLock scopedLock(lock());
   return std::find(m_customFormatSpecifiers.begin(), m_customFormatSpecifiers.end(),
                    formatSpecifier) != m_customFormatSpecifiers.end();
 }
hasFlag()
bool el::base::Storage::hasFlag (LoggingFlag flag) const inline
Definition at line 2651 of file easylogging++.h.
References el::base::utils::hasFlag().
{
     return base::utils::hasFlag(flag, m_flags);
   }
hitCounters()
base::RegisteredHitCounters* el::base::Storage::hitCounters (void) const inline
Definition at line 2621 of file easylogging++.h.
{
     return m_registeredHitCounters;
   }
installCustomFormatSpecifier()
void el::base::Storage::installCustomFormatSpecifier (const CustomFormatSpecifier & customFormatSpecifier)
Definition at line 2053 of file easylogging++.cc.
References el::CustomFormatSpecifier::formatSpecifier(), and el::base::threading::ThreadSafe::lock().
{
   if (hasCustomFormatSpecifier(customFormatSpecifier.formatSpecifier())) {
     return;
   }
   base::threading::ScopedLock scopedLock(lock());
   m_customFormatSpecifiers.push_back(customFormatSpecifier);
 }
installLogDispatchCallback()
template<typename T > bool el::base::Storage::installLogDispatchCallback (const std::string & id) inline
Definition at line 2688 of file easylogging++.h.
{
     return base::utils::Utils::installCallback<T, base::type::LogDispatchCallbackPtr>(id, &m_logDispatchCallbacks);
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), hasCustomFormatSpecifier(), installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
logDispatchCallback()
template<typename T > T* el::base::Storage::logDispatchCallback (const std::string & id) inline
Definition at line 2697 of file easylogging++.h.
{
     return base::utils::Utils::callback<T, base::type::LogDispatchCallbackPtr>(id, &m_logDispatchCallbacks);
   }
preRollOutCallback()
PreRollOutCallback& el::base::Storage::preRollOutCallback (void) inline
Definition at line 2671 of file easylogging++.h.
{
     return m_preRollOutCallback;
   }
registeredLoggers()
base::RegisteredLoggers* el::base::Storage::registeredLoggers (void) const inline
Definition at line 2625 of file easylogging++.h.
{
     return m_registeredLoggers;
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
removeFlag()
void el::base::Storage::removeFlag (LoggingFlag flag) inline
Definition at line 2647 of file easylogging++.h.
References el::base::utils::removeFlag().
{
     base::utils::removeFlag(flag, &m_flags);
   }
setApplicationArguments() [1/2]
void el::base::Storage::setApplicationArguments (int argc, char ** argv) private
Definition at line 2072 of file easylogging++.cc.
References ELPP_DEFAULT_LOGGING_FLAGS, el::Filename, el::base::consts::kDefaultLogFileParam, and el::Configurations::setGlobally().
{
   m_commandLineArgs.setArgs(argc, argv);
   m_vRegistry->setFromArgs(commandLineArgs());
   // default log file
 #if !defined(ELPP_DISABLE_LOG_FILE_FROM_ARG)
   if (m_commandLineArgs.hasParamWithValue(base::consts::kDefaultLogFileParam)) {
     Configurations c;
     c.setGlobally(ConfigurationType::Filename,
                   std::string(m_commandLineArgs.getParamValue(base::consts::kDefaultLogFileParam)));
     registeredLoggers()->setDefaultConfigurations(c);
     for (base::RegisteredLoggers::iterator it = registeredLoggers()->begin();
          it != registeredLoggers()->end(); ++it) {
       it->second->configure(c);
     }
   }
 #endif  // !defined(ELPP_DISABLE_LOG_FILE_FROM_ARG)
 #if defined(ELPP_LOGGING_FLAGS_FROM_ARG)
   if (m_commandLineArgs.hasParamWithValue(base::consts::kLoggingFlagsParam)) {
     int userInput = atoi(m_commandLineArgs.getParamValue(base::consts::kLoggingFlagsParam));
     if (ELPP_DEFAULT_LOGGING_FLAGS == 0x0) {
       m_flags = userInput;
     } else {
       base::utils::addFlag<base::type::EnumType>(userInput, &m_flags);
     }
   }
 #endif  // defined(ELPP_LOGGING_FLAGS_FROM_ARG)
 }
setApplicationArguments() [2/2]
void el::base::Storage::setApplicationArguments (int argc, const char ** argv) inline private
Definition at line 2761 of file easylogging++.h.
References ELPP_EXPORT, and el::base::elStorage.
{
     setApplicationArguments(argc, const_cast<char**>(argv));
   }
setFlags()
void el::base::Storage::setFlags (base::type::EnumType flags) inline
Definition at line 2659 of file easylogging++.h.
{
     m_flags = flags;
   }
setLoggingLevel()
void el::base::Storage::setLoggingLevel (Level level) inline
Definition at line 2683 of file easylogging++.h.
{
     m_loggingLevel = level;
   }
setPreRollOutCallback()
void el::base::Storage::setPreRollOutCallback (const PreRollOutCallback & callback) inline
Definition at line 2663 of file easylogging++.h.
{
     m_preRollOutCallback = callback;
   }
setThreadName()
void el::base::Storage::setThreadName (const std::string & name) inline
Sets thread name for current thread. Requires std::thread.
Definition at line 2721 of file easylogging++.h.
References el::base::threading::getCurrentThreadId().
{
     if (name.empty()) return;
     base::threading::ScopedLock scopedLock(lock());
     m_threadNames[base::threading::getCurrentThreadId()] = name;
   }
uninstallCustomFormatSpecifier()
bool el::base::Storage::uninstallCustomFormatSpecifier (const char * formatSpecifier)
Definition at line 2061 of file easylogging++.cc.
References el::base::threading::ThreadSafe::lock().
{
   base::threading::ScopedLock scopedLock(lock());
   std::vector<CustomFormatSpecifier>::iterator it = std::find(m_customFormatSpecifiers.begin(),
       m_customFormatSpecifiers.end(), formatSpecifier);
   if (it != m_customFormatSpecifiers.end() && strcmp(formatSpecifier, it->formatSpecifier()) == 0) {
     m_customFormatSpecifiers.erase(it);
     return true;
   }
   return false;
 }
uninstallLogDispatchCallback()
template<typename T > void el::base::Storage::uninstallLogDispatchCallback (const std::string & id) inline
Definition at line 2693 of file easylogging++.h.
{
     base::utils::Utils::uninstallCallback<T, base::type::LogDispatchCallbackPtr>(id, &m_logDispatchCallbacks);
   }
unsetPreRollOutCallback()
void el::base::Storage::unsetPreRollOutCallback (void) inline
Definition at line 2667 of file easylogging++.h.
References el::base::defaultPreRollOutCallback().
{
     m_preRollOutCallback = base::defaultPreRollOutCallback;
   }
validateAfterNCounter()
bool el::base::Storage::validateAfterNCounter (const char * filename, base::type::LineNumber lineNumber, std::size_t n) inline
Definition at line 2613 of file easylogging++.h.
{
     return hitCounters()->validateAfterN(filename, lineNumber, n);
   }
validateEveryNCounter()
bool el::base::Storage::validateEveryNCounter (const char * filename, base::type::LineNumber lineNumber, std::size_t occasion) inline
Definition at line 2609 of file easylogging++.h.
{
     return hitCounters()->validateEveryN(filename, lineNumber, occasion);
   }
validateNTimesCounter()
bool el::base::Storage::validateNTimesCounter (const char * filename, base::type::LineNumber lineNumber, std::size_t n) inline
Definition at line 2617 of file easylogging++.h.
{
     return hitCounters()->validateNTimes(filename, lineNumber, n);
   }
vRegistry()
base::VRegistry* el::base::Storage::vRegistry (void) const inline
Definition at line 2629 of file easylogging++.h.
{
     return m_vRegistry;
   }
Friends And Related Function Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
Definition at line 2752 of file easylogging++.h.
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
Definition at line 2757 of file easylogging++.h.
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
Definition at line 2754 of file easylogging++.h.
el::base::PerformanceTracker
friend class el::base::PerformanceTracker friend
Definition at line 2756 of file easylogging++.h.
el::base::Writer
friend class el::base::Writer friend
Definition at line 2755 of file easylogging++.h.
el::Helpers
friend class el::Helpers friend
Definition at line 2751 of file easylogging++.h.
el::LogBuilder
friend class el::LogBuilder friend
Definition at line 2753 of file easylogging++.h.
Member Data Documentation
m_commandLineArgs
base::utils::CommandLineArgs el::base::Storage::m_commandLineArgs private
Definition at line 2743 of file easylogging++.h.
m_customFormatSpecifiers
std::vector<CustomFormatSpecifier> el::base::Storage::m_customFormatSpecifiers private
Definition at line 2748 of file easylogging++.h.
m_flags
base::type::EnumType el::base::Storage::m_flags private
Definition at line 2737 of file easylogging++.h.
m_logDispatchCallbacks
std::map<std::string, base::type::LogDispatchCallbackPtr> el::base::Storage::m_logDispatchCallbacks private
Definition at line 2745 of file easylogging++.h.
m_loggingLevel
Level el::base::Storage::m_loggingLevel private
Definition at line 2749 of file easylogging++.h.
m_performanceTrackingCallbacks
std::map<std::string, base::type::PerformanceTrackingCallbackPtr> el::base::Storage::m_performanceTrackingCallbacks private
Definition at line 2746 of file easylogging++.h.
m_preRollOutCallback
PreRollOutCallback el::base::Storage::m_preRollOutCallback private
Definition at line 2744 of file easylogging++.h.
m_registeredHitCounters
base::RegisteredHitCounters* el::base::Storage::m_registeredHitCounters private
Definition at line 2735 of file easylogging++.h.
m_registeredLoggers
base::RegisteredLoggers* el::base::Storage::m_registeredLoggers private
Definition at line 2736 of file easylogging++.h.
m_threadNames
std::map<std::string, std::string> el::base::Storage::m_threadNames private
Definition at line 2747 of file easylogging++.h.
m_vRegistry
base::VRegistry* el::base::Storage::m_vRegistry private
Definition at line 2738 of file easylogging++.h.
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc