VulpesRender: el::base::utils::File Class Reference
el::base::utils::File Class Reference
#include <easylogging++.h>
Static Public Member Functions
static base::type::fstream_t * newFileStream (const std::string &filename)
Creates new out file stream for specified filename.
static std::size_t getSizeOfFile (base::type::fstream_t *fs)
Gets size of file provided in stream.
static bool pathExists (const char *path, bool considerFile=false)
Determines whether or not provided path exist in current file system.
static bool createPath (const std::string &path)
Creates specified path on file system.
static std::string extractPathFromFilename (const std::string &fullPath, const char *seperator=base::consts::kFilePathSeperator)
Extracts path of filename with leading slash.
static void buildStrippedFilename (const char *filename, char buff[], std::size_t limit=base::consts::kSourceFilenameMaxLength)
builds stripped filename and puts it in buff
static void buildBaseFilename (const std::string &fullPath, char buff[], std::size_t limit=base::consts::kSourceFilenameMaxLength, const char *seperator=base::consts::kFilePathSeperator)
builds base filename and puts it in buff
Detailed Description
Definition at line 1094 of file easylogging++.h.
Member Function Documentation
buildBaseFilename()
void el::base::utils::File::buildBaseFilename (const std::string & fullPath, char buff[], std::size_t limit = base::consts::kSourceFilenameMaxLength, const char * seperator = base::consts::kFilePathSeperator) static
builds base filename and puts it in buff
Definition at line 765 of file easylogging++.cc.
References STRCAT.
Referenced by el::base::VRegistry::allowed(), and el::base::DefaultLogBuilder::build().
{
   const char *filename = fullPath.c_str();
   std::size_t lastSlashAt = fullPath.find_last_of(separator);
   filename += lastSlashAt ? lastSlashAt+1 : 0;
   std::size_t sizeOfFilename = strlen(filename);
   if (sizeOfFilename >= limit) {
     filename += (sizeOfFilename - limit);
     if (filename[0] != '.' && filename[1] != '.') {  // prepend if not already
       filename += 3;  // 3 = '..'
       STRCAT(buff, "..", limit);
     }
   }
   STRCAT(buff, filename, limit);
 }
buildStrippedFilename()
void el::base::utils::File::buildStrippedFilename (const char * filename, char buff[], std::size_t limit = base::consts::kSourceFilenameMaxLength) static
builds stripped filename and puts it in buff
Definition at line 753 of file easylogging++.cc.
References STRCAT.
Referenced by el::base::DefaultLogBuilder::build().
{
   std::size_t sizeOfFilename = strlen(filename);
   if (sizeOfFilename >= limit) {
     filename += (sizeOfFilename - limit);
     if (filename[0] != '.' && filename[1] != '.') {  // prepend if not already
       filename += 3;  // 3 = '..'
       STRCAT(buff, "..", limit);
     }
   }
   STRCAT(buff, filename, limit);
 }
createPath()
bool el::base::utils::File::createPath (const std::string & path) static
Creates specified path on file system.
Parameters
path Path to create.
Definition at line 702 of file easylogging++.cc.
References ELPP_INTERNAL_ERROR, ELPP_UNUSED, el::base::consts::kFilePathSeperator, pathExists(), and STRTOK.
Referenced by el::base::TypedConfigurations::insertFile().
{
   if (path.empty()) {
     return false;
   }
   if (base::utils::File::pathExists(path.c_str())) {
     return true;
   }
   int status = -1;
   char* currPath = const_cast<char*>(path.c_str());
   std::string builtPath = std::string();
 #if ELPP_OS_UNIX
   if (path[0] == '/') {
     builtPath = "/";
   }
   currPath = STRTOK(currPath, base::consts::kFilePathSeperator, 0);
 #elif ELPP_OS_WINDOWS
   // Use secure functions API
   char* nextTok_ = nullptr;
   currPath = STRTOK(currPath, base::consts::kFilePathSeperator, &nextTok_);
   ELPP_UNUSED(nextTok_);
 #endif  // ELPP_OS_UNIX
   while (currPath != nullptr) {
     builtPath.append(currPath);
     builtPath.append(base::consts::kFilePathSeperator);
 #if ELPP_OS_UNIX
     status = mkdir(builtPath.c_str(), ELPP_LOG_PERMS);
     currPath = STRTOK(nullptr, base::consts::kFilePathSeperator, 0);
 #elif ELPP_OS_WINDOWS
     status = _mkdir(builtPath.c_str());
     currPath = STRTOK(nullptr, base::consts::kFilePathSeperator, &nextTok_);
 #endif  // ELPP_OS_UNIX
   }
   if (status == -1) {
     ELPP_INTERNAL_ERROR("Error while creating path [" << path << "]", true);
     return false;
   }
   return true;
 }
extractPathFromFilename()
std::string el::base::utils::File::extractPathFromFilename (const std::string & fullPath, const char * seperator = base::consts::kFilePathSeperator) static
Extracts path of filename with leading slash.
Definition at line 742 of file easylogging++.cc.
Referenced by el::base::TypedConfigurations::insertFile().
{
   if ((fullPath == "") || (fullPath.find(separator) == std::string::npos)) {
     return fullPath;
   }
   std::size_t lastSlashAt = fullPath.find_last_of(separator);
   if (lastSlashAt == 0) {
     return std::string(separator);
   }
   return fullPath.substr(0, lastSlashAt + 1);
 }
getSizeOfFile()
std::size_t el::base::utils::File::getSizeOfFile (base::type::fstream_t * fs) static
Gets size of file provided in stream.
Definition at line 674 of file easylogging++.cc.
Referenced by el::base::TypedConfigurations::unsafeValidateFileRolling().
{
   if (fs == nullptr) {
     return 0;
   }
   std::streampos currPos = fs->tellg();
   fs->seekg(0, fs->end);
   std::size_t size = static_cast<std::size_t>(fs->tellg());
   fs->seekg(currPos);
   return size;
 }
newFileStream()
base::type::fstream_t * el::base::utils::File::newFileStream (const std::string & filename) static
Creates new out file stream for specified filename.
Returns
Pointer to newly created fstream or nullptr
Definition at line 650 of file easylogging++.cc.
References ELPP_INTERNAL_ERROR, and el::base::utils::safeDelete().
Referenced by el::base::TypedConfigurations::insertFile().
{
   base::type::fstream_t *fs = new base::type::fstream_t(filename.c_str(),
       base::type::fstream_t::out
 #if !defined(ELPP_FRESH_LOG_FILE)
       | base::type::fstream_t::app
 #endif
                                                        );
 #if defined(ELPP_UNICODE)
   std::locale elppUnicodeLocale("");
 #  if ELPP_OS_WINDOWS
   std::locale elppUnicodeLocaleWindows(elppUnicodeLocale, new std::codecvt_utf8_utf16<wchar_t>);
   elppUnicodeLocale = elppUnicodeLocaleWindows;
 #  endif // ELPP_OS_WINDOWS
   fs->imbue(elppUnicodeLocale);
 #endif  // defined(ELPP_UNICODE)
   if (fs->is_open()) {
     fs->flush();
   } else {
     base::utils::safeDelete(fs);
     ELPP_INTERNAL_ERROR("Bad file [" << filename << "]", true);
   }
   return fs;
 }
pathExists()
bool el::base::utils::File::pathExists (const char * path, bool considerFile = false) static
Determines whether or not provided path exist in current file system.
Definition at line 685 of file easylogging++.cc.
References ELPP_UNUSED.
Referenced by createPath(), and el::Configurations::parseFromFile().
{
   if (path == nullptr) {
     return false;
   }
 #if ELPP_OS_UNIX
   ELPP_UNUSED(considerFile);
   struct stat st;
   return (stat(path, &st) == 0);
 #elif ELPP_OS_WINDOWS
   DWORD fileType = GetFileAttributesA(path);
   if (fileType == INVALID_FILE_ATTRIBUTES) {
     return false;
   }
   return considerFile ? true : ((fileType & FILE_ATTRIBUTE_DIRECTORY) == 0 ? false : true);
 #endif  // ELPP_OS_UNIX
 }
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc