VulpesRender: vpr::SurfaceKHR Class Reference
vpr::SurfaceKHR Class Reference
Core
The bare-minimum required to wrap a VkSurfaceKHR object.
#include <SurfaceKHR.hpp>
Public Member Functions
SurfaceKHR (const Instance *_parent, VkPhysicalDevice physical_device, GLFWwindow *window)
SurfaceKHR (SurfaceKHR &&other) noexcept
SurfaceKHR & operator= (SurfaceKHR &&other) noexcept
~SurfaceKHR ()
void Recreate ()
const VkSurfaceKHR & vkHandle () const noexcept
Static Public Member Functions
static VkBool32 VerifyPresentationSupport (VkPhysicalDevice physical_device, VkSurfaceKHR surface)
Private Member Functions
SurfaceKHR (const SurfaceKHR &)=delete
SurfaceKHR & operator= (const SurfaceKHR &)=delete
void create ()
void destroy ()
Private Attributes
GLFWwindow * window
const Instance * parent
VkPhysicalDevice device
VkSurfaceKHR handle
Detailed Description
The bare-minimum required to wrap a VkSurfaceKHR object.
Uses the glfwCreateWindowSurface function to handle the various platform-specific details that would change otherwise.
Definition at line 15 of file SurfaceKHR.hpp.
Constructor & Destructor Documentation
SurfaceKHR() [1/3]
vpr::SurfaceKHR::SurfaceKHR (const SurfaceKHR &) private delete
SurfaceKHR() [2/3]
vpr::SurfaceKHR::SurfaceKHR (const Instance * _parent, VkPhysicalDevice physical_device, GLFWwindow * window)
Definition at line 10 of file SurfaceKHR.cpp.
References create().
                                                                                                  : parent(_parent), window(_window), device(_device), handle(VK_NULL_HANDLE) {
         create();
     }
SurfaceKHR() [3/3]
vpr::SurfaceKHR::SurfaceKHR (SurfaceKHR && other) noexcept
Definition at line 14 of file SurfaceKHR.cpp.
                                                       : parent(std::move(other.parent)), handle(std::move(other.handle)) {
         other.handle = VK_NULL_HANDLE;
     }
~SurfaceKHR()
vpr::SurfaceKHR::~SurfaceKHR ()
Definition at line 25 of file SurfaceKHR.cpp.
References destroy().
{
         destroy();
     }
Member Function Documentation
create()
void vpr::SurfaceKHR::create () private
Definition at line 38 of file SurfaceKHR.cpp.
References device, handle, parent, VerifyPresentationSupport(), VkAssert, vpr::Instance::vkHandle(), and window.
Referenced by Recreate(), and SurfaceKHR().
{
         VkResult err = glfwCreateWindowSurface(parent->vkHandle(), window, nullptr, &handle);
         VkAssert(err);
         if (!VerifyPresentationSupport(device, handle)) {
             throw std::runtime_error("Surfaces are not supported on current physical device!");
         }
     }
destroy()
void vpr::SurfaceKHR::destroy () private
Definition at line 46 of file SurfaceKHR.cpp.
References handle, parent, and vpr::Instance::vkHandle().
Referenced by Recreate(), and ~SurfaceKHR().
{
         if (handle != VK_NULL_HANDLE) {
             vkDestroySurfaceKHR(parent->vkHandle(), handle, nullptr);
             handle = VK_NULL_HANDLE;
         }
     }
operator=() [1/2]
SurfaceKHR& vpr::SurfaceKHR::operator= (const SurfaceKHR &) private delete
operator=() [2/2]
SurfaceKHR & vpr::SurfaceKHR::operator= (SurfaceKHR && other) noexcept
Definition at line 18 of file SurfaceKHR.cpp.
References handle, and parent.
{
         parent = std::move(other.parent);
         handle = std::move(other.handle);
         other.handle = VK_NULL_HANDLE;
         return *this;
     }
Recreate()
void vpr::SurfaceKHR::Recreate ()
Definition at line 29 of file SurfaceKHR.cpp.
References create(), and destroy().
Referenced by vpr::RecreateSwapchainAndSurface().
{
         destroy();
         create();
     }
VerifyPresentationSupport()
VkBool32 vpr::SurfaceKHR::VerifyPresentationSupport (VkPhysicalDevice physical_device, VkSurfaceKHR surface) static
Definition at line 53 of file SurfaceKHR.cpp.
Referenced by create().
{
         // Check presentation support
         VkBool32 present_support = VK_FALSE;
         for (uint32_t i = 0; i < 3; ++i) {
             vkGetPhysicalDeviceSurfaceSupportKHR(physical_device, i, surface, &present_support);
             if (present_support) {
                 break;
             }
         }
         return present_support;
     }
vkHandle()
const VkSurfaceKHR & vpr::SurfaceKHR::vkHandle () const noexcept
Definition at line 34 of file SurfaceKHR.cpp.
References handle.
Referenced by vpr::RecreateSwapchainAndSurface().
{
         return handle;
     }
Member Data Documentation
device
VkPhysicalDevice vpr::SurfaceKHR::device private
Definition at line 37 of file SurfaceKHR.hpp.
Referenced by create().
handle
VkSurfaceKHR vpr::SurfaceKHR::handle private
Definition at line 38 of file SurfaceKHR.hpp.
Referenced by create(), destroy(), operator=(), and vkHandle().
parent
const Instance* vpr::SurfaceKHR::parent private
Definition at line 36 of file SurfaceKHR.hpp.
Referenced by create(), destroy(), and operator=().
window
GLFWwindow* vpr::SurfaceKHR::window private
Definition at line 35 of file SurfaceKHR.hpp.
Referenced by create().
The documentation for this class was generated from the following files:
core/include/SurfaceKHR.hpp
core/src/SurfaceKHR.cpp