VulpesRender: el::base::HitCounter Class Reference
el::base::HitCounter Class Reference
Class that keeps record of current line hit for occasional logging.
#include <easylogging++.h>
Classes
class Predicate
Public Member Functions
HitCounter (void)
HitCounter (const char *filename, base::type::LineNumber lineNumber)
HitCounter (const HitCounter &hitCounter)
HitCounter & operator= (const HitCounter &hitCounter)
virtual ~HitCounter (void)
void resetLocation (const char *filename, base::type::LineNumber lineNumber)
Resets location of current hit counter.
void validateHitCounts (std::size_t n)
Validates hit counts and resets it if necessary.
const char * filename (void) const
base::type::LineNumber lineNumber (void) const
std::size_t hitCounts (void) const
void increment (void)
Private Attributes
const char * m_filename
base::type::LineNumber m_lineNumber
std::size_t m_hitCounts
Detailed Description
Class that keeps record of current line hit for occasional logging.
Definition at line 2086 of file easylogging++.h.
Constructor & Destructor Documentation
HitCounter() [1/3]
el::base::HitCounter::HitCounter (void) inline
Definition at line 2088 of file easylogging++.h.
                    :
     m_filename(""),
     m_lineNumber(0),
     m_hitCounts(0) {
   }
HitCounter() [2/3]
el::base::HitCounter::HitCounter (const char * filename, base::type::LineNumber lineNumber) inline
Definition at line 2094 of file easylogging++.h.
                                                                   :
     m_filename(filename),
     m_lineNumber(lineNumber),
     m_hitCounts(0) {
   }
HitCounter() [3/3]
el::base::HitCounter::HitCounter (const HitCounter & hitCounter) inline
Definition at line 2100 of file easylogging++.h.
                                            :
     m_filename(hitCounter.m_filename),
     m_lineNumber(hitCounter.m_lineNumber),
     m_hitCounts(hitCounter.m_hitCounts) {
   }
~HitCounter()
virtual el::base::HitCounter::~HitCounter (void) inline virtual
Definition at line 2115 of file easylogging++.h.
{
   }
Member Function Documentation
filename()
const char* el::base::HitCounter::filename (void) const inline
Definition at line 2132 of file easylogging++.h.
{
     return m_filename;
   }
hitCounts()
std::size_t el::base::HitCounter::hitCounts (void) const inline
Definition at line 2140 of file easylogging++.h.
Referenced by el::base::RegisteredHitCounters::validateAfterN(), el::base::RegisteredHitCounters::validateEveryN(), and el::base::RegisteredHitCounters::validateNTimes().
{
     return m_hitCounts;
   }
increment()
void el::base::HitCounter::increment (void) inline
Definition at line 2144 of file easylogging++.h.
Referenced by el::base::RegisteredHitCounters::validateAfterN(), and el::base::RegisteredHitCounters::validateNTimes().
{
     ++m_hitCounts;
   }
lineNumber()
base::type::LineNumber el::base::HitCounter::lineNumber (void) const inline
Definition at line 2136 of file easylogging++.h.
{
     return m_lineNumber;
   }
operator=()
HitCounter& el::base::HitCounter::operator= (const HitCounter & hitCounter) inline
Definition at line 2106 of file easylogging++.h.
References m_filename, m_hitCounts, and m_lineNumber.
{
     if (&hitCounter != this) {
       m_filename = hitCounter.m_filename;
       m_lineNumber = hitCounter.m_lineNumber;
       m_hitCounts = hitCounter.m_hitCounts;
     }
     return *this;
   }
resetLocation()
void el::base::HitCounter::resetLocation (const char * filename, base::type::LineNumber lineNumber) inline
Resets location of current hit counter.
Definition at line 2119 of file easylogging++.h.
{
     m_filename = filename;
     m_lineNumber = lineNumber;
   }
validateHitCounts()
void el::base::HitCounter::validateHitCounts (std::size_t n) inline
Validates hit counts and resets it if necessary.
Definition at line 2125 of file easylogging++.h.
References el::base::consts::kMaxLogPerCounter.
Referenced by el::base::RegisteredHitCounters::validateEveryN().
{
     if (m_hitCounts >= base::consts::kMaxLogPerCounter) {
       m_hitCounts = (n >= 1 ? base::consts::kMaxLogPerCounter % n : 0);
     }
     ++m_hitCounts;
   }
Member Data Documentation
m_filename
const char* el::base::HitCounter::m_filename private
Definition at line 2166 of file easylogging++.h.
Referenced by el::base::HitCounter::Predicate::operator()(), and operator=().
m_hitCounts
std::size_t el::base::HitCounter::m_hitCounts private
Definition at line 2168 of file easylogging++.h.
Referenced by operator=().
m_lineNumber
base::type::LineNumber el::base::HitCounter::m_lineNumber private
Definition at line 2167 of file easylogging++.h.
Referenced by el::base::HitCounter::Predicate::operator()(), and operator=().
The documentation for this class was generated from the following file:
include/util/easylogging++.h