VulpesRender: el::base::VRegistry Class Reference
el::base::VRegistry Class Reference
Represents registries for verbose logging.
#include <easylogging++.h>
Public Member Functions
VRegistry (base::type::VerboseLevel level, base::type::EnumType *pFlags)
void setLevel (base::type::VerboseLevel level)
Sets verbose level. Accepted range is 0-9.
base::type::VerboseLevel level (void) const
void clearModules (void)
void setModules (const char *modules)
bool allowed (base::type::VerboseLevel vlevel, const char *file)
const std::map< std::string, base::type::VerboseLevel > & modules (void) const
void setFromArgs (const base::utils::CommandLineArgs *commandLineArgs)
bool vModulesEnabled (void)
Whether or not vModules enabled.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Attributes
base::type::VerboseLevel m_level
base::type::EnumType * m_pFlags
std::map< std::string, base::type::VerboseLevel > m_modules
Detailed Description
Represents registries for verbose logging.
Definition at line 2465 of file easylogging++.h.
Constructor & Destructor Documentation
VRegistry()
el::base::VRegistry::VRegistry (base::type::VerboseLevel level, base::type::EnumType * pFlags) explicit
Definition at line 1860 of file easylogging++.cc.
                                                                          : m_level(level), m_pFlags(pFlags) {
 }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
allowed()
bool el::base::VRegistry::allowed (base::type::VerboseLevel vlevel, const char * file)
Definition at line 1944 of file easylogging++.cc.
References el::AllowVerboseIfModuleNotSpecified, el::base::utils::File::buildBaseFilename(), el::base::utils::hasFlag(), el::base::consts::kSourceFilenameMaxLength, el::base::threading::ThreadSafe::lock(), m_level, m_modules, m_pFlags, and el::base::utils::Str::wildCardMatch().
{
   base::threading::ScopedLock scopedLock(lock());
   if (m_modules.empty() || file == nullptr) {
     return vlevel <= m_level;
   } else {
     char baseFilename[base::consts::kSourceFilenameMaxLength] = "";
     base::utils::File::buildBaseFilename(file, baseFilename);
     std::map<std::string, base::type::VerboseLevel>::iterator it = m_modules.begin();
     for (; it != m_modules.end(); ++it) {
       if (base::utils::Str::wildCardMatch(baseFilename, it->first.c_str())) {
         return vlevel <= it->second;
       }
     }
     if (base::utils::hasFlag(LoggingFlag::AllowVerboseIfModuleNotSpecified, *m_pFlags)) {
       return true;
     }
     return false;
   }
 }
clearModules()
void el::base::VRegistry::clearModules (void) inline
Definition at line 2476 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     m_modules.clear();
   }
level()
base::type::VerboseLevel el::base::VRegistry::level (void) const inline
Definition at line 2472 of file easylogging++.h.
Referenced by setLevel(), setModules(), and el::base::PErrorWriter::~PErrorWriter().
{
     return m_level;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), setLevel(), setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
modules()
const std::map<std::string, base::type::VerboseLevel>& el::base::VRegistry::modules (void) const inline
Definition at line 2485 of file easylogging++.h.
Referenced by setModules().
{
     return m_modules;
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
setFromArgs()
void el::base::VRegistry::setFromArgs (const base::utils::CommandLineArgs * commandLineArgs)
Definition at line 1964 of file easylogging++.cc.
References el::base::utils::CommandLineArgs::getParamValue(), el::base::utils::CommandLineArgs::hasParam(), el::base::utils::CommandLineArgs::hasParamWithValue(), el::base::consts::kMaxVerboseLevel, setLevel(), setModules(), and vModulesEnabled().
{
   if (commandLineArgs->hasParam("-v") || commandLineArgs->hasParam("--verbose") ||
       commandLineArgs->hasParam("-V") || commandLineArgs->hasParam("--VERBOSE")) {
     setLevel(base::consts::kMaxVerboseLevel);
   } else if (commandLineArgs->hasParamWithValue("--v")) {
     setLevel(static_cast<base::type::VerboseLevel>(atoi(commandLineArgs->getParamValue("--v"))));
   } else if (commandLineArgs->hasParamWithValue("--V")) {
     setLevel(static_cast<base::type::VerboseLevel>(atoi(commandLineArgs->getParamValue("--V"))));
   } else if ((commandLineArgs->hasParamWithValue("-vmodule")) && vModulesEnabled()) {
     setModules(commandLineArgs->getParamValue("-vmodule"));
   } else if (commandLineArgs->hasParamWithValue("-VMODULE") && vModulesEnabled()) {
     setModules(commandLineArgs->getParamValue("-VMODULE"));
   }
 }
setLevel()
void el::base::VRegistry::setLevel (base::type::VerboseLevel level)
Sets verbose level. Accepted range is 0-9.
Definition at line 1864 of file easylogging++.cc.
References el::base::consts::kMaxVerboseLevel, level(), el::base::threading::ThreadSafe::lock(), and m_level.
Referenced by setFromArgs().
{
   base::threading::ScopedLock scopedLock(lock());
   if (level > 9)
     m_level = base::consts::kMaxVerboseLevel;
   else
     m_level = level;
 }
setModules()
void el::base::VRegistry::setModules (const char * modules)
Definition at line 1872 of file easylogging++.cc.
References el::DisableVModulesExtensions, el::base::utils::Str::endsWith(), el::base::utils::hasFlag(), level(), el::base::threading::ThreadSafe::lock(), m_modules, m_pFlags, and modules().
Referenced by setFromArgs().
{
   base::threading::ScopedLock scopedLock(lock());
   auto addSuffix = [](std::stringstream& ss, const char* sfx, const char* prev) {
     if (prev != nullptr && base::utils::Str::endsWith(ss.str(), std::string(prev))) {
       std::string chr(ss.str().substr(0, ss.str().size() - strlen(prev)));
       ss.str(std::string(""));
       ss << chr;
     }
     if (base::utils::Str::endsWith(ss.str(), std::string(sfx))) {
       std::string chr(ss.str().substr(0, ss.str().size() - strlen(sfx)));
       ss.str(std::string(""));
       ss << chr;
     }
     ss << sfx;
   };
   auto insert = [&](std::stringstream& ss, base::type::VerboseLevel level) {
     if (!base::utils::hasFlag(LoggingFlag::DisableVModulesExtensions, *m_pFlags)) {
       addSuffix(ss, ".h", nullptr);
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".c", ".h");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".cpp", ".c");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".cc", ".cpp");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".cxx", ".cc");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".-inl.h", ".cxx");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".hxx", ".-inl.h");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".hpp", ".hxx");
       m_modules.insert(std::make_pair(ss.str(), level));
       addSuffix(ss, ".hh", ".hpp");
     }
     m_modules.insert(std::make_pair(ss.str(), level));
   };
   bool isMod = true;
   bool isLevel = false;
   std::stringstream ss;
   int level = -1;
   for (; *modules; ++modules) {
     switch (*modules) {
     case '=':
       isLevel = true;
       isMod = false;
       break;
     case ',':
       isLevel = false;
       isMod = true;
       if (!ss.str().empty() && level != -1) {
         insert(ss, static_cast<base::type::VerboseLevel>(level));
         ss.str(std::string(""));
         level = -1;
       }
       break;
     default:
       if (isMod) {
         ss << *modules;
       } else if (isLevel) {
         if (isdigit(*modules)) {
           level = static_cast<base::type::VerboseLevel>(*modules) - 48;
         }
       }
       break;
     }
   }
   if (!ss.str().empty() && level != -1) {
     insert(ss, static_cast<base::type::VerboseLevel>(level));
   }
 }
vModulesEnabled()
bool el::base::VRegistry::vModulesEnabled (void) inline
Whether or not vModules enabled.
Definition at line 2492 of file easylogging++.h.
References el::DisableVModules, and el::base::utils::hasFlag().
Referenced by setFromArgs().
{
     return !base::utils::hasFlag(LoggingFlag::DisableVModules, *m_pFlags);
   }
Member Data Documentation
m_level
base::type::VerboseLevel el::base::VRegistry::m_level private
Definition at line 2497 of file easylogging++.h.
Referenced by allowed(), el::base::Writer::initializeLogger(), setLevel(), el::base::Writer::triggerDispatch(), and el::base::PErrorWriter::~PErrorWriter().
m_modules
std::map<std::string, base::type::VerboseLevel> el::base::VRegistry::m_modules private
Definition at line 2499 of file easylogging++.h.
Referenced by allowed(), and setModules().
m_pFlags
base::type::EnumType* el::base::VRegistry::m_pFlags private
Definition at line 2498 of file easylogging++.h.
Referenced by allowed(), and setModules().
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc