VulpesRender: el::LogDispatchData Class Reference
el::LogDispatchData Class Reference
#include <easylogging++.h>
Public Member Functions
LogDispatchData ()
const LogMessage * logMessage (void) const
base::DispatchAction dispatchAction (void) const
Private Member Functions
void setLogMessage (LogMessage *logMessage)
void setDispatchAction (base::DispatchAction dispatchAction)
Private Attributes
LogMessage * m_logMessage
base::DispatchAction m_dispatchAction
Friends
class base::LogDispatcher
Detailed Description
Definition at line 2212 of file easylogging++.h.
Constructor & Destructor Documentation
LogDispatchData()
el::LogDispatchData::LogDispatchData () inline
Definition at line 2214 of file easylogging++.h.
 : m_logMessage(nullptr), m_dispatchAction(base::DispatchAction::None) {}
Member Function Documentation
dispatchAction()
base::DispatchAction el::LogDispatchData::dispatchAction (void) const inline
Definition at line 2218 of file easylogging++.h.
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
     return m_dispatchAction;
   }
logMessage()
const LogMessage* el::LogDispatchData::logMessage (void) const inline
Definition at line 2215 of file easylogging++.h.
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
     return m_logMessage;
   }
setDispatchAction()
void el::LogDispatchData::setDispatchAction (base::DispatchAction dispatchAction) inline private
Definition at line 2229 of file easylogging++.h.
Referenced by el::base::LogDispatcher::dispatch().
{
     m_dispatchAction = dispatchAction;
   }
setLogMessage()
void el::LogDispatchData::setLogMessage (LogMessage * logMessage) inline private
Definition at line 2226 of file easylogging++.h.
Referenced by el::base::LogDispatcher::dispatch().
{
     m_logMessage = logMessage;
   }
Friends And Related Function Documentation
base::LogDispatcher
friend class base::LogDispatcher friend
Definition at line 2224 of file easylogging++.h.
Member Data Documentation
m_dispatchAction
base::DispatchAction el::LogDispatchData::m_dispatchAction private
Definition at line 2223 of file easylogging++.h.
m_logMessage
LogMessage* el::LogDispatchData::m_logMessage private
Definition at line 2222 of file easylogging++.h.
The documentation for this class was generated from the following file:
include/util/easylogging++.h