VulpesRender: vpr::Device Class Reference
vpr::Device Class Reference
Core
!The Device class is a wrapper around the vkLogicalDevice object.
#include <LogicalDevice.hpp>
Public Member Functions
Device (const Instance *instance, const PhysicalDevice *p_device, VkSurfaceKHR surface=VK_NULL_HANDLE, const VprExtensionPack *extensions=nullptr, const char *const *layer_names=nullptr, const uint32_t layer_count=0)
~Device ()
const VkDevice & vkHandle () const
bool HasDedicatedComputeQueues () const
! Returns whether or not the currently active physical device, along with the logical device, supports/has queues dedicated compute operations
bool DedicatedAllocationExtensionsEnabled () const noexcept
bool HasExtension (const char *name) const noexcept
void GetEnabledExtensions (size_t *num_extensions, char **extensions) const
void UpdateSurface (VkSurfaceKHR new_surface)
VkQueue GeneralQueue (const uint32_t &idx=0) const
! Returns queue that has support for most operation types.
VkQueue GraphicsQueue (const uint32_t &idx=0) const
VkQueue TransferQueue (const uint32_t &idx=0) const
VkQueue ComputeQueue (const uint32_t &idx=0) const
VkQueue SparseBindingQueue (const uint32_t &idx=0) const
VkImageTiling GetFormatTiling (const VkFormat &format, const VkFormatFeatureFlags &flags) const
! Checks whether or not the given format along with the specified flags supports optimal or linear tiling.
VkFormat FindSupportedFormat (const VkFormat *formats, const size_t num_formats, const VkImageTiling &tiling, const VkFormatFeatureFlags &flags) const
! Checks a collection of possible formats, returning the one that supports the given tiling and feature flags.
VkFormat FindDepthFormat () const
! Finds a Vulkan image format suitable for use in the depth buffer
uint32_t GetMemoryTypeIdx (const uint32_t &type_bitfield, const VkMemoryPropertyFlags &property_flags, VkBool32 *memory_type_found=nullptr) const
const PhysicalDevice & GetPhysicalDevice () const noexcept
const VkPhysicalDeviceProperties & GetPhysicalDeviceProperties () const noexcept
const VkPhysicalDeviceMemoryProperties & GetPhysicalDeviceMemoryProperties () const noexcept
const VkDebugUtilsFunctions & DebugUtilsHandler () const
const uint32_t & NumGraphicsQueues () const noexcept
const uint32_t & NumComputeQueues () const noexcept
const uint32_t & NumTransferQueues () const noexcept
const uint32_t & NumSparseBindingQueues () const noexcept
const vkQueueFamilyIndices & QueueFamilyIndices () const noexcept
Private Member Functions
Device (const Device &)=delete
Device (Device &&)=delete
Device & operator= (const Device &)=delete
Device & operator= (Device &&)=delete
void verifyPresentationSupport ()
void checkSurfaceSupport (const VkSurfaceKHR &surf)
VkDeviceQueueCreateInfo setupQueueFamily (const VkQueueFamilyProperties &family_properties)
void create (const VprExtensionPack *extensions, const char *const *layers, const uint32_t layer_count)
void setupQueues ()
void setupValidation (const char *const *layers, const uint32_t layer_count)
void setupExtensions (const VprExtensionPack *extensions)
void setupGraphicsQueues ()
void setupComputeQueues ()
void setupTransferQueues ()
void setupSparseBindingQueues ()
void setupDebugUtilsHandler ()
Private Attributes
uint32_t numGraphicsQueues { 0 }
uint32_t numComputeQueues { 0 }
uint32_t numTransferQueues { 0 }
uint32_t numSparseBindingQueues { 0 }
vkQueueFamilyIndices queueFamilyIndices
VkDevice handle { VK_NULL_HANDLE }
VkDeviceCreateInfo createInfo { }
VkDebugUtilsFunctions * debugUtilsHandler { nullptr }
const PhysicalDevice * parent { nullptr }
const Instance * parentInstance { nullptr }
VkSurfaceKHR surface
DeviceDataMembers * dataMembers
Detailed Description
!The Device class is a wrapper around the vkLogicalDevice object.
This object is what most Vulkan resources and objects are spawned from, and is then responsible for managing these resources. Most Vulkan functions relating to resource creation, binding, or updating will take a VkDevice reference as a parameter. This is considered to be a "Logical device" as it represents a non-physical device and each physical device can actually store and handle multiple logical devices.
The vast majority of classes in this codebase contain a private const Device pointer, for use in their internal functions requiring this object's handle.
Definition at line 34 of file LogicalDevice.hpp.
Constructor & Destructor Documentation
Device() [1/3]
vpr::Device::Device (const Device &) private delete
Device() [2/3]
vpr::Device::Device (Device &&) private delete
Device() [3/3]
vpr::Device::Device (const Instance * instance, const PhysicalDevice * p_device, VkSurfaceKHR surface = VK_NULL_HANDLE, const VprExtensionPack * extensions = nullptr, const char *const * layer_names = nullptr, const uint32_t layer_count = 0)
Definition at line 54 of file LogicalDevice.cpp.
References create(), and vpr::RECOMMENDED_EXTENSIONS.
                                     : parent(dvc), parentInstance(instance), debugUtilsHandler(nullptr), dataMembers(nullptr), surface(_surface) {
         if (extensions != nullptr) {
             create(extensions, layer_names, layer_count);
         }
         else {
             create(&RECOMMENDED_EXTENSIONS, nullptr, 0);
         }
     }
~Device()
vpr::Device::~Device ()
Definition at line 64 of file LogicalDevice.cpp.
References dataMembers, debugUtilsHandler, and handle.
                    {
         if (dataMembers) {
             delete dataMembers;
         }
         if (debugUtilsHandler) {
             delete debugUtilsHandler;
         }
         vkDestroyDevice(handle, nullptr);
     }
Member Function Documentation
checkSurfaceSupport()
void vpr::Device::checkSurfaceSupport (const VkSurfaceKHR & surf) private
Definition at line 119 of file LogicalDevice.cpp.
References parent, vpr::vkQueueFamilyIndices::Present, queueFamilyIndices, and vpr::PhysicalDevice::vkHandle().
{
         VkBool32 supported;
         vkGetPhysicalDeviceSurfaceSupportKHR(parent->vkHandle(), queueFamilyIndices.Present, surf, &supported);
         assert(supported);
     }
ComputeQueue()
VkQueue vpr::Device::ComputeQueue (const uint32_t & idx = 0) const
Definition at line 144 of file LogicalDevice.cpp.
References vpr::vkQueueFamilyIndices::Compute, vpr::vkQueueFamilyIndices::Graphics, queueFamilyIndices, and vkHandle().
{
         static bool logged_warning = false;
         if ((queueFamilyIndices.Compute == queueFamilyIndices.Graphics) && !logged_warning) {
             LOG(WARNING) << "Retrieving queue that supports compute ops, but isn't dedicated compute queue. This warning is only issued once - but retrieval is likely occuring multiple times.";
             logged_warning = true;
         }
         VkQueue result;
         vkGetDeviceQueue(vkHandle(), queueFamilyIndices.Compute, idx, &result);
         return result;
     }
create()
void vpr::Device::create (const VprExtensionPack * extensions, const char *const * layers, const uint32_t layer_count) private
Definition at line 271 of file LogicalDevice.cpp.
References createInfo, dataMembers, vpr::PhysicalDevice::GetFeatures(), handle, parent, vpr::DeviceDataMembers::queueInfos, setupDebugUtilsHandler(), setupExtensions(), setupQueues(), setupValidation(), surface, verifyPresentationSupport(), vpr::vk_device_create_info_base, VkAssert, and vpr::PhysicalDevice::vkHandle().
Referenced by Device().
{
         createInfo = vk_device_create_info_base;
         dataMembers = new DeviceDataMembers(this);
         if (surface != VK_NULL_HANDLE) {
             verifyPresentationSupport();
         }
         setupQueues();
         setupValidation(layers, layer_count);
         setupExtensions(extensions);
         // This has to be here so that the queue_infos vector persists through device creation.
         std::vector<VkDeviceQueueCreateInfo> queue_infos;
         for (const auto& queue_info_entry : dataMembers->queueInfos) {
             queue_infos.emplace_back(queue_info_entry.second);
         }
         createInfo.queueCreateInfoCount = static_cast<uint32_t>(queue_infos.size());
         createInfo.pQueueCreateInfos = queue_infos.data();
         createInfo.pEnabledFeatures = &parent->GetFeatures();
         VkResult result = vkCreateDevice(parent->vkHandle(), &createInfo, nullptr, &handle);
         VkAssert(result);
         setupDebugUtilsHandler();
     }
DebugUtilsHandler()
const VkDebugUtilsFunctions & vpr::Device::DebugUtilsHandler () const
Definition at line 222 of file LogicalDevice.cpp.
References debugUtilsHandler.
{
         // In case we don't have member to return, return fully empty struct
         static const VkDebugUtilsFunctions fallback{ nullptr };
         if (debugUtilsHandler) {
             return *debugUtilsHandler;
         }
         else {
             return fallback;
         }
     }
DedicatedAllocationExtensionsEnabled()
bool vpr::Device::DedicatedAllocationExtensionsEnabled () const noexcept
Definition at line 85 of file LogicalDevice.cpp.
References dataMembers, and vpr::DeviceDataMembers::enableDedicatedAllocations.
{
         return dataMembers->enableDedicatedAllocations;
     }
FindDepthFormat()
VkFormat vpr::Device::FindDepthFormat () const
! Finds a Vulkan image format suitable for use in the depth buffer
Definition at line 201 of file LogicalDevice.cpp.
References FindSupportedFormat().
{
         static const std::vector<VkFormat> format_options{ VK_FORMAT_D32_SFLOAT, VK_FORMAT_D32_SFLOAT_S8_UINT, VK_FORMAT_D24_UNORM_S8_UINT };
         return FindSupportedFormat(format_options.data(), format_options.size(), VK_IMAGE_TILING_OPTIMAL, VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT);
     }
FindSupportedFormat()
VkFormat vpr::Device::FindSupportedFormat (const VkFormat * formats, const size_t num_formats, const VkImageTiling & tiling, const VkFormatFeatureFlags & flags) const
! Checks a collection of possible formats, returning the one that supports the given tiling and feature flags.
Parameters
options - vector of formats that are usable for the desired task.
tiling - required image tiling setting.
flags - features required, commonly related to intended use for the image.
Returns
Returns found format if successful, otherwise returns VK_FORMAT_UNDEFINED and logs a detailed error.
Definition at line 186 of file LogicalDevice.cpp.
References parent, and vpr::PhysicalDevice::vkHandle().
Referenced by FindDepthFormat().
{
         for (size_t i = 0; i < num_formats; ++i) {
             VkFormatProperties properties;
             vkGetPhysicalDeviceFormatProperties(parent->vkHandle(), formats[i], &properties);
             if (tiling == VK_IMAGE_TILING_LINEAR && (properties.linearTilingFeatures & flags) == flags) {
                 return formats[i];
             }
             else if (tiling == VK_IMAGE_TILING_OPTIMAL && (properties.optimalTilingFeatures & flags) == flags) {
                 return formats[i];
             }
         }
         LOG(ERROR) << "Could not find texture format that supports requested tiling and feature flags: ( " << std::to_string(tiling) << " , " << std::to_string(flags) << " )";
         throw std::runtime_error("Could not find valid texture format.");
     }
GeneralQueue()
VkQueue vpr::Device::GeneralQueue (const uint32_t & idx = 0) const
! Returns queue that has support for most operation types.
First checks for graphics, compute, and transfer. Then proceeds to graphics and compute. Lastly, it will just return a graphics-only queue and log a warning.
Parameters
idx - in the case of a device with several "generalized" queues, selects which queue to return.
Definition at line 233 of file LogicalDevice.cpp.
References vpr::PhysicalDevice::GetQueueFamilyIndex(), vpr::vkQueueFamilyIndices::Graphics, parent, queueFamilyIndices, and vkHandle().
{
         uint32_t idx = parent->GetQueueFamilyIndex(VkQueueFlagBits(VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_TRANSFER_BIT | VK_QUEUE_COMPUTE_BIT));
         if (idx == std::numeric_limits<uint32_t>::max()) {
             LOG(WARNING) << "Couldn't find a generalized queue supporting compute, graphics, and transfer: trying graphics and transfer.";
             idx = parent->GetQueueFamilyIndex(VkQueueFlagBits(VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_TRANSFER_BIT));
             if (idx == std::numeric_limits<uint32_t>::max()) {
                 LOG(WARNING) << "Couldn't find a generalized queue supporting transfer and graphics operations: just returning a graphics queue.";
                 idx = queueFamilyIndices.Graphics;
             }
         }
         VkQueue result;
         vkGetDeviceQueue(vkHandle(), idx, desired_idx, &result);
         return result;
     }
GetEnabledExtensions()
void vpr::Device::GetEnabledExtensions (size_t * num_extensions, char ** extensions) const
Definition at line 101 of file LogicalDevice.cpp.
References dataMembers, and vpr::DeviceDataMembers::enabledExtensions.
{
         *num_extensions = dataMembers->enabledExtensions.size();
         if (extensions != nullptr) {
             for (size_t i = 0; i < *num_extensions; ++i) {
 #ifdef __APPLE_CC__
                 extensions[i] = strdup(dataMembers->enabledExtensions[i]);
 #else
                 extensions[i] = _strdup(dataMembers->enabledExtensions[i]);
 #endif
             }
         }
     }
GetFormatTiling()
VkImageTiling vpr::Device::GetFormatTiling (const VkFormat & format, const VkFormatFeatureFlags & flags) const
! Checks whether or not the given format along with the specified flags supports optimal or linear tiling.
Parameters
format - Vulkan format enum specifying the type of image data
flags - flags specifying features of format: commonly what it is being used for, e.g cube map, sampled image, storage image, etc
Definition at line 170 of file LogicalDevice.cpp.
References parent, and vpr::PhysicalDevice::vkHandle().
{
         VkFormatProperties properties;
         vkGetPhysicalDeviceFormatProperties(parent->vkHandle(), format, &properties);
         if (properties.optimalTilingFeatures & flags) {
             return VK_IMAGE_TILING_OPTIMAL;
         }
         else {
             // Check that the device at least supports the desired features for linear tiling
             if (!(properties.linearTilingFeatures & flags)) {
                 LOG(ERROR) << "Could not retrieve VkImageTiling mode for format, indicating that the format is probably not supported on the current device!";
                 throw std::runtime_error("Requested format is likely not supported on current device!");
             }
             return VK_IMAGE_TILING_LINEAR;
         }
     }
GetMemoryTypeIdx()
uint32_t vpr::Device::GetMemoryTypeIdx (const uint32_t & type_bitfield, const VkMemoryPropertyFlags & property_flags, VkBool32 * memory_type_found = nullptr) const
Definition at line 206 of file LogicalDevice.cpp.
References vpr::PhysicalDevice::GetMemoryTypeIdx(), and parent.
{
         return parent->GetMemoryTypeIdx(type_bitfield, property_flags, memory_type_found);
     }
GetPhysicalDevice()
const PhysicalDevice & vpr::Device::GetPhysicalDevice () const noexcept
Definition at line 210 of file LogicalDevice.cpp.
References parent.
Referenced by vpr::Swapchain::Recreate().
{
         return *parent;
     }
GetPhysicalDeviceMemoryProperties()
const VkPhysicalDeviceMemoryProperties & vpr::Device::GetPhysicalDeviceMemoryProperties () const noexcept
Definition at line 218 of file LogicalDevice.cpp.
References vpr::PhysicalDevice::GetMemoryProperties(), and parent.
{
         return parent->GetMemoryProperties();
     }
GetPhysicalDeviceProperties()
const VkPhysicalDeviceProperties & vpr::Device::GetPhysicalDeviceProperties () const noexcept
Definition at line 214 of file LogicalDevice.cpp.
References vpr::PhysicalDevice::GetProperties(), and parent.
{
         return parent->GetProperties();
     }
GraphicsQueue()
VkQueue vpr::Device::GraphicsQueue (const uint32_t & idx = 0) const
Definition at line 125 of file LogicalDevice.cpp.
References vpr::vkQueueFamilyIndices::Graphics, numGraphicsQueues, queueFamilyIndices, and vkHandle().
{
         assert(idx < numGraphicsQueues);
         VkQueue result;
         vkGetDeviceQueue(vkHandle(), queueFamilyIndices.Graphics, idx, &result);
         return result;
     }
HasDedicatedComputeQueues()
bool vpr::Device::HasDedicatedComputeQueues () const
! Returns whether or not the currently active physical device, along with the logical device, supports/has queues dedicated compute operations
Definition at line 78 of file LogicalDevice.cpp.
References vpr::vkQueueFamilyIndices::Compute, vpr::vkQueueFamilyIndices::Graphics, and queueFamilyIndices.
{
         if (queueFamilyIndices.Compute != queueFamilyIndices.Graphics) {
             return true;
         }
         return false;
     }
HasExtension()
bool vpr::Device::HasExtension (const char * name) const noexcept
Definition at line 89 of file LogicalDevice.cpp.
References dataMembers, and vpr::DeviceDataMembers::enabledExtensions.
{
         auto iter = std::find_if(std::cbegin(dataMembers->enabledExtensions), std::cend(dataMembers->enabledExtensions), [name](const char* str) {
             return strcmp(name, str) == 0;
         });
         if (iter != std::cend(dataMembers->enabledExtensions)) {
             return true;
         }
         else {
             return false;
         }
     }
NumComputeQueues()
const uint32_t & vpr::Device::NumComputeQueues () const noexcept
Definition at line 255 of file LogicalDevice.cpp.
References numComputeQueues.
{
         return numComputeQueues;
     }
NumGraphicsQueues()
const uint32_t & vpr::Device::NumGraphicsQueues () const noexcept
Definition at line 251 of file LogicalDevice.cpp.
References numGraphicsQueues.
{
         return numGraphicsQueues;
     }
NumSparseBindingQueues()
const uint32_t & vpr::Device::NumSparseBindingQueues () const noexcept
Definition at line 263 of file LogicalDevice.cpp.
References numSparseBindingQueues.
{
         return numSparseBindingQueues;
     }
NumTransferQueues()
const uint32_t & vpr::Device::NumTransferQueues () const noexcept
Definition at line 259 of file LogicalDevice.cpp.
References numTransferQueues.
{
         return numTransferQueues;
     }
operator=() [1/2]
Device& vpr::Device::operator= (const Device &) private delete
operator=() [2/2]
Device& vpr::Device::operator= (Device &&) private delete
QueueFamilyIndices()
const vkQueueFamilyIndices & vpr::Device::QueueFamilyIndices () const noexcept
Definition at line 267 of file LogicalDevice.cpp.
References queueFamilyIndices.
{
         return queueFamilyIndices;
     }
setupComputeQueues()
void vpr::Device::setupComputeQueues () private
Definition at line 354 of file LogicalDevice.cpp.
References vpr::vkQueueFamilyIndices::Compute, vpr::queue_priorities_t::compute, dataMembers, vpr::PhysicalDevice::GetQueueFamilyIndex(), vpr::PhysicalDevice::GetQueueFamilyProperties(), vpr::vkQueueFamilyIndices::Graphics, numComputeQueues, numGraphicsQueues, parent, vpr::queue_priorities, queueFamilyIndices, vpr::DeviceDataMembers::queueInfos, and setupQueueFamily().
Referenced by setupQueues().
{
         queueFamilyIndices.Compute = parent->GetQueueFamilyIndex(VK_QUEUE_COMPUTE_BIT);
         if (queueFamilyIndices.Compute != queueFamilyIndices.Graphics) {
             auto compute_info = setupQueueFamily(parent->GetQueueFamilyProperties(VK_QUEUE_COMPUTE_BIT));
             compute_info.queueFamilyIndex = queueFamilyIndices.Compute;
             numComputeQueues = compute_info.queueCount;
             compute_info.queueCount = numComputeQueues;
             queue_priorities.compute = std::vector<float>(numComputeQueues, 1.0f);
             compute_info.pQueuePriorities = queue_priorities.compute.data();
             dataMembers->queueInfos.insert(std::make_pair(VK_QUEUE_COMPUTE_BIT, compute_info));
         }
         else {
             auto queue_properties = parent->GetQueueFamilyProperties(VK_QUEUE_COMPUTE_BIT);
             if (queue_properties.queueFlags & VK_QUEUE_GRAPHICS_BIT) {
                 queueFamilyIndices.Compute = queueFamilyIndices.Graphics;
                 numComputeQueues = numGraphicsQueues;
             }
         }
     }
setupDebugUtilsHandler()
void vpr::Device::setupDebugUtilsHandler () private
Definition at line 512 of file LogicalDevice.cpp.
References debugUtilsHandler, handle, vpr::Instance::HasExtension(), parentInstance, vpr::Instance::ValidationEnabled(), vpr::VkDebugUtilsFunctions::vkCmdBeginDebugUtilsLabel, vpr::VkDebugUtilsFunctions::vkCmdEndDebugUtilsLabel, vpr::VkDebugUtilsFunctions::vkCmdInsertDebugUtilsLabel, vpr::VkDebugUtilsFunctions::vkCreateDebugUtilsMessenger, vpr::VkDebugUtilsFunctions::vkDestroyDebugUtilsMessenger, vpr::VkDebugUtilsFunctions::vkQueueBeginDebugUtilsLabel, vpr::VkDebugUtilsFunctions::vkQueueEndDebugUtilsLabel, vpr::VkDebugUtilsFunctions::vkSetDebugUtilsObjectName, vpr::VkDebugUtilsFunctions::vkSetDebugUtilsObjectTag, and vpr::VkDebugUtilsFunctions::vkSubmitDebugUtilsMessage.
Referenced by create().
{
         auto check_loaded_pfn = [](const void* ptr, const char* fname) {
             if (!ptr) {
                 LOG(ERROR) << "Failed to load function pointer " << fname << "for debug utils extension!";
             }
         };
         if (!parentInstance->ValidationEnabled()) {
             LOG(WARNING) << "Cannot load requested VkDebugUtils function pointers, as validation layers are not enabled!";
             return;
         }
         if (parentInstance->HasExtension(VK_EXT_DEBUG_UTILS_EXTENSION_NAME)) {
             debugUtilsHandler = new VkDebugUtilsFunctions();
             debugUtilsHandler->vkSetDebugUtilsObjectName =
                 reinterpret_cast<PFN_vkSetDebugUtilsObjectNameEXT>(vkGetDeviceProcAddr(handle, "vkSetDebugUtilsObjectNameEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkSetDebugUtilsObjectName, "vkSetDebugUtilsObjectName");
             debugUtilsHandler->vkSetDebugUtilsObjectTag =
                 reinterpret_cast<PFN_vkSetDebugUtilsObjectTagEXT>(vkGetDeviceProcAddr(handle, "vkSetDebugUtilsObjectTagEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkSetDebugUtilsObjectTag, "vkSetDebugUtilsObjectTag");
             debugUtilsHandler->vkQueueBeginDebugUtilsLabel =
                 reinterpret_cast<PFN_vkQueueBeginDebugUtilsLabelEXT>(vkGetDeviceProcAddr(handle, "vkQueueBeginDebugUtilsLabelEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkQueueBeginDebugUtilsLabel, "vkQueueBeginDebugUtilsLabel");
             debugUtilsHandler->vkQueueEndDebugUtilsLabel =
                 reinterpret_cast<PFN_vkQueueEndDebugUtilsLabelEXT>(vkGetDeviceProcAddr(handle, "vkQueueEndDebugUtilsLabelEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkQueueEndDebugUtilsLabel, "vkQueueEndDebugUtilsLabel");
             debugUtilsHandler->vkCmdBeginDebugUtilsLabel =
                 reinterpret_cast<PFN_vkCmdBeginDebugUtilsLabelEXT>(vkGetDeviceProcAddr(handle, "vkCmdBeginDebugUtilsLabelEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkCmdBeginDebugUtilsLabel, "vkCmdBeginDebugUtilsLabel");
             debugUtilsHandler->vkCmdEndDebugUtilsLabel =
                 reinterpret_cast<PFN_vkCmdEndDebugUtilsLabelEXT>(vkGetDeviceProcAddr(handle, "vkCmdEndDebugUtilsLabelEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkCmdEndDebugUtilsLabel, "vkCmdEndDebugUtilsLabel");
             debugUtilsHandler->vkCmdInsertDebugUtilsLabel =
                 reinterpret_cast<PFN_vkCmdInsertDebugUtilsLabelEXT>(vkGetDeviceProcAddr(handle, "vkCmdInsertDebugUtilsLabelEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkCmdInsertDebugUtilsLabel, "vkCmdInsertDebugUtilsLabel");
             debugUtilsHandler->vkCreateDebugUtilsMessenger =
                 reinterpret_cast<PFN_vkCreateDebugUtilsMessengerEXT>(vkGetDeviceProcAddr(handle, "vkCreateDebugUtilsMessengerEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkCreateDebugUtilsMessenger, "vkCreateDebugUtilsMessenger");
             debugUtilsHandler->vkDestroyDebugUtilsMessenger =
                 reinterpret_cast<PFN_vkDestroyDebugUtilsMessengerEXT>(vkGetDeviceProcAddr(handle, "vkDestroyDebugUtilsMessengerEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkDestroyDebugUtilsMessenger, "vkDestroyDebugUtilsMessenger");
             debugUtilsHandler->vkSubmitDebugUtilsMessage =
                 reinterpret_cast<PFN_vkSubmitDebugUtilsMessageEXT>(vkGetDeviceProcAddr(handle, "vkSubmitDebugUtilsMessageEXT"));
             check_loaded_pfn((void*)debugUtilsHandler->vkSubmitDebugUtilsMessage, "vkSubmitDebugUtilsMessage");
         }
     }
setupExtensions()
void vpr::Device::setupExtensions (const VprExtensionPack * extensions) private
Definition at line 324 of file LogicalDevice.cpp.
References vpr::DeviceDataMembers::checkDedicatedAllocExtensions(), createInfo, dataMembers, vpr::DeviceDataMembers::enableDedicatedAllocations, vpr::DeviceDataMembers::enabledExtensions, vpr::DeviceDataMembers::prepareOptionalExtensions(), and vpr::DeviceDataMembers::prepareRequiredExtensions().
Referenced by create().
{
         if (extensions) {
             std::vector<const char*> all_extensions;
             dataMembers->prepareRequiredExtensions(extensions, all_extensions);
             dataMembers->prepareOptionalExtensions(extensions, all_extensions);
             dataMembers->checkDedicatedAllocExtensions(all_extensions);
             dataMembers->enabledExtensions = all_extensions;
             createInfo.enabledExtensionCount = static_cast<uint32_t>(dataMembers->enabledExtensions.size());
             createInfo.ppEnabledExtensionNames = dataMembers->enabledExtensions.data();
         }
         else {
             createInfo.enabledExtensionCount = 0;
             createInfo.ppEnabledExtensionNames = nullptr;
             dataMembers->enableDedicatedAllocations = false;
         }
     }
setupGraphicsQueues()
void vpr::Device::setupGraphicsQueues () private
Definition at line 343 of file LogicalDevice.cpp.
References dataMembers, vpr::PhysicalDevice::GetQueueFamilyIndex(), vpr::PhysicalDevice::GetQueueFamilyProperties(), vpr::vkQueueFamilyIndices::Graphics, vpr::queue_priorities_t::graphics, numGraphicsQueues, parent, vpr::queue_priorities, queueFamilyIndices, vpr::DeviceDataMembers::queueInfos, and setupQueueFamily().
Referenced by setupQueues().
{
         queueFamilyIndices.Graphics = parent->GetQueueFamilyIndex(VK_QUEUE_GRAPHICS_BIT);
         auto create_info = setupQueueFamily(parent->GetQueueFamilyProperties(VK_QUEUE_GRAPHICS_BIT));
         create_info.queueFamilyIndex = queueFamilyIndices.Graphics;
         numGraphicsQueues = 1;
         create_info.queueCount = numGraphicsQueues;
         queue_priorities.graphics = std::vector<float>(numGraphicsQueues, 1.0f);
         create_info.pQueuePriorities = queue_priorities.graphics.data();
         dataMembers->queueInfos.insert(std::make_pair(VK_QUEUE_GRAPHICS_BIT, create_info));
     }
setupQueueFamily()
VkDeviceQueueCreateInfo vpr::Device::setupQueueFamily (const VkQueueFamilyProperties & family_properties) private
Definition at line 432 of file LogicalDevice.cpp.
References vpr::vk_device_queue_create_info_base.
Referenced by setupComputeQueues(), setupGraphicsQueues(), setupSparseBindingQueues(), and setupTransferQueues().
{
         VkDeviceQueueCreateInfo result = vk_device_queue_create_info_base;
         result.queueCount = family_properties.queueCount;
         return result;
     }
setupQueues()
void vpr::Device::setupQueues () private
Definition at line 299 of file LogicalDevice.cpp.
References setupComputeQueues(), setupGraphicsQueues(), setupSparseBindingQueues(), and setupTransferQueues().
Referenced by create().
{
         setupGraphicsQueues();
         setupComputeQueues();
         setupTransferQueues();
         setupSparseBindingQueues();
     }
setupSparseBindingQueues()
void vpr::Device::setupSparseBindingQueues () private
Definition at line 394 of file LogicalDevice.cpp.
References dataMembers, vpr::PhysicalDevice::GetQueueFamilyIndex(), vpr::PhysicalDevice::GetQueueFamilyProperties(), vpr::vkQueueFamilyIndices::Graphics, numGraphicsQueues, numSparseBindingQueues, parent, vpr::queue_priorities, queueFamilyIndices, vpr::DeviceDataMembers::queueInfos, setupQueueFamily(), vpr::queue_priorities_t::sparse_binding, and vpr::vkQueueFamilyIndices::SparseBinding.
Referenced by setupQueues().
{
         queueFamilyIndices.SparseBinding = parent->GetQueueFamilyIndex(VK_QUEUE_SPARSE_BINDING_BIT);
         if ((queueFamilyIndices.SparseBinding != queueFamilyIndices.Graphics) && (queueFamilyIndices.SparseBinding != std::numeric_limits<uint32_t>::max())) {
             auto sparse_info = setupQueueFamily(parent->GetQueueFamilyProperties(VK_QUEUE_SPARSE_BINDING_BIT));
             sparse_info.queueFamilyIndex = queueFamilyIndices.SparseBinding;
             numSparseBindingQueues = sparse_info.queueCount;
             queue_priorities.sparse_binding = std::vector<float>(numSparseBindingQueues, 1.0f);
             sparse_info.pQueuePriorities = queue_priorities.sparse_binding.data();
             dataMembers->queueInfos.insert(std::make_pair(VK_QUEUE_SPARSE_BINDING_BIT, sparse_info));
         }
         else {
             auto queue_properties = parent->GetQueueFamilyProperties(VK_QUEUE_SPARSE_BINDING_BIT);
             if (queue_properties.queueFlags & VK_QUEUE_GRAPHICS_BIT) {
                 queueFamilyIndices.SparseBinding = queueFamilyIndices.Graphics;
                 numSparseBindingQueues = numGraphicsQueues;
             }
         }
     }
setupTransferQueues()
void vpr::Device::setupTransferQueues () private
Definition at line 375 of file LogicalDevice.cpp.
References dataMembers, vpr::PhysicalDevice::GetQueueFamilyIndex(), vpr::PhysicalDevice::GetQueueFamilyProperties(), vpr::vkQueueFamilyIndices::Graphics, numGraphicsQueues, numTransferQueues, parent, vpr::queue_priorities, queueFamilyIndices, vpr::DeviceDataMembers::queueInfos, setupQueueFamily(), vpr::vkQueueFamilyIndices::Transfer, and vpr::queue_priorities_t::transfer.
Referenced by setupQueues().
{
         queueFamilyIndices.Transfer = parent->GetQueueFamilyIndex(VK_QUEUE_TRANSFER_BIT);
         if (queueFamilyIndices.Transfer != queueFamilyIndices.Graphics) {
             auto transfer_info = setupQueueFamily(parent->GetQueueFamilyProperties(VK_QUEUE_TRANSFER_BIT));
             transfer_info.queueFamilyIndex = queueFamilyIndices.Transfer;
             numTransferQueues = transfer_info.queueCount;
             queue_priorities.transfer = std::vector<float>(numTransferQueues, 1.0f);
             transfer_info.pQueuePriorities = queue_priorities.transfer.data();
             dataMembers->queueInfos.insert(std::make_pair(VK_QUEUE_TRANSFER_BIT, transfer_info));
         }
         else {
             auto queue_properties = parent->GetQueueFamilyProperties(VK_QUEUE_TRANSFER_BIT);
             if (queue_properties.queueFlags & VK_QUEUE_GRAPHICS_BIT) {
                 queueFamilyIndices.Transfer = queueFamilyIndices.Graphics;
                 numTransferQueues = numGraphicsQueues;
             }
         }
     }
setupValidation()
void vpr::Device::setupValidation (const char *const * layers, const uint32_t layer_count) private
Definition at line 308 of file LogicalDevice.cpp.
References createInfo, parentInstance, and vpr::Instance::ValidationEnabled().
Referenced by create().
{
         if (parentInstance->ValidationEnabled()) {
             if ((layer_count == 0) && (layers == nullptr)) {
                 constexpr static const char* const default_layer = "VK_LAYER_LUNARG_standard_validation";
                 createInfo.enabledLayerCount = 1;
                 createInfo.ppEnabledLayerNames = &default_layer;
             }
             else {
                 createInfo.enabledLayerCount = layer_count;
                 createInfo.ppEnabledLayerNames = layers;
             }
         }
     }
SparseBindingQueue()
VkQueue vpr::Device::SparseBindingQueue (const uint32_t & idx = 0) const
Definition at line 156 of file LogicalDevice.cpp.
References vpr::vkQueueFamilyIndices::Compute, dataMembers, vpr::vkQueueFamilyIndices::Graphics, handle, queueFamilyIndices, vpr::DeviceDataMembers::queueInfos, and vpr::vkQueueFamilyIndices::SparseBinding.
{
         if (!dataMembers->queueInfos.count(VK_QUEUE_SPARSE_BINDING_BIT)) {
             LOG(ERROR) << "Current device does not support sparse binding queues!";
             throw std::runtime_error("Requested unsuported queue family (Sparse Binding)");
         }
         LOG_IF(queueFamilyIndices.Compute == queueFamilyIndices.Graphics, INFO) << "Retrieving queue that supports sparse binding, but isn't dedicated sparse binding queue.";
         VkQueue result;
         vkGetDeviceQueue(handle, queueFamilyIndices.SparseBinding, idx, &result);
         return result;
     }
TransferQueue()
VkQueue vpr::Device::TransferQueue (const uint32_t & idx = 0) const
Definition at line 132 of file LogicalDevice.cpp.
References vpr::vkQueueFamilyIndices::Graphics, queueFamilyIndices, vpr::vkQueueFamilyIndices::Transfer, and vkHandle().
{
         static bool logged_warning = false;
         if ((queueFamilyIndices.Transfer == queueFamilyIndices.Graphics) && !logged_warning) {
             LOG(WARNING) << "Retrieving queue that supports transfer ops, but isn't dedicated transfer queue. This warning is only issued once - but retrieval is likely occuring multiple times.";
             logged_warning = true;
         }
         VkQueue result;
         vkGetDeviceQueue(vkHandle(), queueFamilyIndices.Transfer, idx, &result);
         return result;
     }
UpdateSurface()
void vpr::Device::UpdateSurface (VkSurfaceKHR new_surface)
Definition at line 114 of file LogicalDevice.cpp.
References surface, and verifyPresentationSupport().
{
         surface = new_surface;
         verifyPresentationSupport();
     }
verifyPresentationSupport()
void vpr::Device::verifyPresentationSupport () private
Definition at line 413 of file LogicalDevice.cpp.
References parent, vpr::vkQueueFamilyIndices::Present, queueFamilyIndices, surface, and vpr::PhysicalDevice::vkHandle().
Referenced by create(), and UpdateSurface().
{
         // Check presentation support
         VkBool32 present_support = false;
         for (uint32_t i = 0; i < 3; ++i) {
             vkGetPhysicalDeviceSurfaceSupportKHR(parent->vkHandle(), i, surface, &present_support);
             if (present_support) {
                 queueFamilyIndices.Present = i;
                 break;
             }
         }
         if (!present_support) {
             LOG(ERROR) << "No queues found that support presentation to a surface.";
             throw std::runtime_error("No queues found that support presentation to a surface!");
         }
     }
vkHandle()
const VkDevice & vpr::Device::vkHandle () const
Definition at line 74 of file LogicalDevice.cpp.
References handle.
Referenced by ComputeQueue(), vpr::SwapchainImpl::create(), vpr::Image::CreateView(), vpr::Image::Destroy(), GeneralQueue(), GraphicsQueue(), and TransferQueue().
{
         return handle;
     }
Member Data Documentation
createInfo
VkDeviceCreateInfo vpr::Device::createInfo { } private
Definition at line 120 of file LogicalDevice.hpp.
Referenced by create(), setupExtensions(), and setupValidation().
dataMembers
DeviceDataMembers* vpr::Device::dataMembers mutable private
Definition at line 125 of file LogicalDevice.hpp.
Referenced by create(), DedicatedAllocationExtensionsEnabled(), GetEnabledExtensions(), HasExtension(), setupComputeQueues(), setupExtensions(), setupGraphicsQueues(), setupSparseBindingQueues(), setupTransferQueues(), SparseBindingQueue(), and ~Device().
debugUtilsHandler
VkDebugUtilsFunctions* vpr::Device::debugUtilsHandler { nullptr } private
Definition at line 121 of file LogicalDevice.hpp.
Referenced by DebugUtilsHandler(), setupDebugUtilsHandler(), and ~Device().
handle
VkDevice vpr::Device::handle { VK_NULL_HANDLE } private
Definition at line 119 of file LogicalDevice.hpp.
Referenced by create(), vpr::Image::Image(), setupDebugUtilsHandler(), SparseBindingQueue(), vkHandle(), and ~Device().
numComputeQueues
uint32_t vpr::Device::numComputeQueues { 0 } private
Definition at line 115 of file LogicalDevice.hpp.
Referenced by NumComputeQueues(), and setupComputeQueues().
numGraphicsQueues
uint32_t vpr::Device::numGraphicsQueues { 0 } private
Definition at line 114 of file LogicalDevice.hpp.
Referenced by GraphicsQueue(), NumGraphicsQueues(), setupComputeQueues(), setupGraphicsQueues(), setupSparseBindingQueues(), and setupTransferQueues().
numSparseBindingQueues
uint32_t vpr::Device::numSparseBindingQueues { 0 } private
Definition at line 117 of file LogicalDevice.hpp.
Referenced by NumSparseBindingQueues(), and setupSparseBindingQueues().
numTransferQueues
uint32_t vpr::Device::numTransferQueues { 0 } private
Definition at line 116 of file LogicalDevice.hpp.
Referenced by NumTransferQueues(), and setupTransferQueues().
parent
const PhysicalDevice* vpr::Device::parent { nullptr } private
Definition at line 122 of file LogicalDevice.hpp.
Referenced by checkSurfaceSupport(), create(), FindSupportedFormat(), GeneralQueue(), GetFormatTiling(), GetMemoryTypeIdx(), GetPhysicalDevice(), GetPhysicalDeviceMemoryProperties(), GetPhysicalDeviceProperties(), setupComputeQueues(), setupGraphicsQueues(), setupSparseBindingQueues(), setupTransferQueues(), and verifyPresentationSupport().
parentInstance
const Instance* vpr::Device::parentInstance { nullptr } private
Definition at line 123 of file LogicalDevice.hpp.
Referenced by setupDebugUtilsHandler(), and setupValidation().
queueFamilyIndices
vkQueueFamilyIndices vpr::Device::queueFamilyIndices private
Definition at line 118 of file LogicalDevice.hpp.
Referenced by checkSurfaceSupport(), ComputeQueue(), GeneralQueue(), GraphicsQueue(), HasDedicatedComputeQueues(), QueueFamilyIndices(), setupComputeQueues(), setupGraphicsQueues(), setupSparseBindingQueues(), setupTransferQueues(), SparseBindingQueue(), TransferQueue(), and verifyPresentationSupport().
surface
VkSurfaceKHR vpr::Device::surface private
Definition at line 124 of file LogicalDevice.hpp.
Referenced by create(), UpdateSurface(), and verifyPresentationSupport().
The documentation for this class was generated from the following files:
core/include/LogicalDevice.hpp
core/src/LogicalDevice.cpp