VulpesRender: el::Loggers Class Reference
el::Loggers Class Reference
Static helpers to deal with loggers and their configurations.
#include <easylogging++.h>
Classes
class ScopedAddFlag
Adds flag and removes it when scope goes out.
class ScopedRemoveFlag
Removes flag and add it when scope goes out.
Static Public Member Functions
static Logger * getLogger (const std::string &identity, bool registerIfNotAvailable=true)
Gets existing or registers new logger.
static void setDefaultLogBuilder (el::LogBuilderPtr &logBuilderPtr)
Changes default log builder for future loggers.
template<typename T >
static bool installLoggerRegistrationCallback (const std::string &id)
Installs logger registration callback, this callback is triggered when new logger is registered.
template<typename T >
static void uninstallLoggerRegistrationCallback (const std::string &id)
Uninstalls log dispatch callback.
template<typename T >
static T * loggerRegistrationCallback (const std::string &id)
static bool unregisterLogger (const std::string &identity)
Unregisters logger - use it only when you know what you are doing, you may unregister loggers initialized / used by third-party libs.
static bool hasLogger (const std::string &identity)
Whether or not logger with id is registered.
static Logger * reconfigureLogger (Logger *logger, const Configurations &configurations)
Reconfigures specified logger with new configurations.
static Logger * reconfigureLogger (const std::string &identity, const Configurations &configurations)
Reconfigures logger with new configurations after looking it up using identity.
static Logger * reconfigureLogger (const std::string &identity, ConfigurationType configurationType, const std::string &value)
Reconfigures logger's single configuration.
static void reconfigureAllLoggers (const Configurations &configurations)
Reconfigures all the existing loggers with new configurations.
static void reconfigureAllLoggers (ConfigurationType configurationType, const std::string &value)
Reconfigures single configuration for all the loggers.
static void reconfigureAllLoggers (Level level, ConfigurationType configurationType, const std::string &value)
Reconfigures single configuration for all the loggers for specified level.
static void setDefaultConfigurations (const Configurations &configurations, bool reconfigureExistingLoggers=false)
Sets default configurations. This configuration is used for future (and conditionally for existing) loggers.
static const Configurations * defaultConfigurations (void)
Returns current default.
static const base::LogStreamsReferenceMap * logStreamsReference (void)
Returns log stream reference pointer if needed by user.
static base::TypedConfigurations defaultTypedConfigurations (void)
Default typed configuration based on existing defaultConf.
static std::vector< std::string > * populateAllLoggerIds (std::vector< std::string > *targetList)
Populates all logger IDs in current repository.
static void configureFromGlobal (const char *globalConfigurationFilePath)
Sets configurations from global configuration file.
static bool configureFromArg (const char *argKey)
Configures loggers using command line arg.
static void flushAll (void)
Flushes all loggers for all levels - Be careful if you dont know how many loggers are registered.
static void addFlag (LoggingFlag flag)
Adds logging flag used internally.
static void removeFlag (LoggingFlag flag)
Removes logging flag used internally.
static bool hasFlag (LoggingFlag flag)
Determines whether or not certain flag is active.
static void setLoggingLevel (Level level)
Sets hierarchy for logging. Needs to enable logging flag (HierarchicalLogging)
static void setVerboseLevel (base::type::VerboseLevel level)
Sets verbose level on the fly.
static base::type::VerboseLevel verboseLevel (void)
Gets current verbose level.
static void setVModules (const char *modules)
Sets vmodules as specified (on the fly)
static void clearVModules (void)
Clears vmodules.
Detailed Description
Static helpers to deal with loggers and their configurations.
Definition at line 3810 of file easylogging++.h.
Member Function Documentation
addFlag()
static void el::Loggers::addFlag (LoggingFlag flag) inline static
Adds logging flag used internally.
Definition at line 3873 of file easylogging++.h.
References ELPP.
Referenced by el::Loggers::ScopedAddFlag::ScopedAddFlag(), and el::Loggers::ScopedRemoveFlag::~ScopedRemoveFlag().
{
     ELPP->addFlag(flag);
   }
clearVModules()
void el::Loggers::clearVModules (void) static
Clears vmodules.
Definition at line 2980 of file easylogging++.cc.
References ELPP.
{
   ELPP->vRegistry()->clearModules();
 }
configureFromArg()
bool el::Loggers::configureFromArg (const char * argKey) static
Configures loggers using command line arg.
Ensure you have already set command line args,
Returns
False if invalid argument or argument with no value provided, true if attempted to configure logger. If true is returned that does not mean it has been configured successfully, it only means that it has attempeted to configure logger using configuration file provided in argument
Definition at line 2950 of file easylogging++.cc.
References el::Helpers::commandLineArgs(), and ELPP_UNUSED.
{
 #if defined(ELPP_DISABLE_CONFIGURATION_FROM_PROGRAM_ARGS)
   ELPP_UNUSED(argKey);
 #else
   if (!Helpers::commandLineArgs()->hasParamWithValue(argKey)) {
     return false;
   }
   configureFromGlobal(Helpers::commandLineArgs()->getParamValue(argKey));
 #endif  // defined(ELPP_DISABLE_CONFIGURATION_FROM_PROGRAM_ARGS)
   return true;
 }
configureFromGlobal()
void el::Loggers::configureFromGlobal (const char * globalConfigurationFilePath) static
Sets configurations from global configuration file.
Definition at line 2909 of file easylogging++.cc.
References el::Logger::configure(), ELPP_ASSERT, ELPP_INTERNAL_INFO, el::Logger::id(), el::Configurations::Parser::ignoreComments(), el::Configurations::Parser::isComment(), el::base::consts::kConfigurationLoggerId, el::Configurations::parseFromText(), el::base::utils::Str::startsWith(), and el::base::utils::Str::trim().
{
   std::ifstream gcfStream(globalConfigurationFilePath, std::ifstream::in);
   ELPP_ASSERT(gcfStream.is_open(), "Unable to open global configuration file [" << globalConfigurationFilePath
               << "] for parsing.");
   std::string line = std::string();
   std::stringstream ss;
   Logger* logger = nullptr;
   auto configure = [&](void) {
     ELPP_INTERNAL_INFO(8, "Configuring logger: '" << logger->id() << "' with configurations \n" << ss.str()
                        << "\n--------------");
     Configurations c;
     c.parseFromText(ss.str());
     logger->configure(c);
   };
   while (gcfStream.good()) {
     std::getline(gcfStream, line);
     ELPP_INTERNAL_INFO(1, "Parsing line: " << line);
     base::utils::Str::trim(line);
     if (Configurations::Parser::isComment(line)) continue;
     Configurations::Parser::ignoreComments(&line);
     base::utils::Str::trim(line);
     if (line.size() > 2 && base::utils::Str::startsWith(line, std::string(base::consts::kConfigurationLoggerId))) {
       if (!ss.str().empty() && logger != nullptr) {
         configure();
       }
       ss.str(std::string(""));
       line = line.substr(2);
       base::utils::Str::trim(line);
       if (line.size() > 1) {
         ELPP_INTERNAL_INFO(1, "Getting logger: '" << line << "'");
         logger = getLogger(line);
       }
     } else {
       ss << line << "\n";
     }
   }
   if (!ss.str().empty() && logger != nullptr) {
     configure();
   }
 }
defaultConfigurations()
const Configurations * el::Loggers::defaultConfigurations (void) static
Returns current default.
Definition at line 2886 of file easylogging++.cc.
References ELPP.
{
   return ELPP->registeredLoggers()->defaultConfigurations();
 }
defaultTypedConfigurations()
base::TypedConfigurations el::Loggers::defaultTypedConfigurations (void) static
Default typed configuration based on existing defaultConf.
Definition at line 2894 of file easylogging++.cc.
References ELPP.
{
   return base::TypedConfigurations(
            ELPP->registeredLoggers()->defaultConfigurations(),
            ELPP->registeredLoggers()->logStreamsReference());
 }
flushAll()
void el::Loggers::flushAll (void) static
Flushes all loggers for all levels - Be careful if you dont know how many loggers are registered.
Definition at line 2962 of file easylogging++.cc.
References ELPP.
{
   ELPP->registeredLoggers()->flushAll();
 }
getLogger()
Logger * el::Loggers::getLogger (const std::string & identity, bool registerIfNotAvailable = true) static
Gets existing or registers new logger.
Definition at line 2822 of file easylogging++.cc.
References ELPP.
Referenced by reconfigureLogger().
{
   base::threading::ScopedLock scopedLock(ELPP->lock());
   return ELPP->registeredLoggers()->get(identity, registerIfNotAvailable);
 }
hasFlag()
static bool el::Loggers::hasFlag (LoggingFlag flag) inline static
Determines whether or not certain flag is active.
Definition at line 3881 of file easylogging++.h.
References ELPP.
{
     return ELPP->hasFlag(flag);
   }
hasLogger()
bool el::Loggers::hasLogger (const std::string & identity) static
Whether or not logger with id is registered.
Definition at line 2836 of file easylogging++.cc.
References ELPP.
{
   base::threading::ScopedLock scopedLock(ELPP->lock());
   return ELPP->registeredLoggers()->has(identity);
 }
installLoggerRegistrationCallback()
template<typename T > static bool el::Loggers::installLoggerRegistrationCallback (const std::string & id) inline static
Installs logger registration callback, this callback is triggered when new logger is registered.
Definition at line 3818 of file easylogging++.h.
References ELPP.
{
     return ELPP->registeredLoggers()->installLoggerRegistrationCallback<T>(id);
   }
loggerRegistrationCallback()
template<typename T > static T* el::Loggers::loggerRegistrationCallback (const std::string & id) inline static
Definition at line 3827 of file easylogging++.h.
References ELPP.
{
     return ELPP->registeredLoggers()->loggerRegistrationCallback<T>(id);
   }
logStreamsReference()
const base::LogStreamsReferenceMap * el::Loggers::logStreamsReference (void) static
Returns log stream reference pointer if needed by user.
Definition at line 2890 of file easylogging++.cc.
References ELPP.
{
   return ELPP->registeredLoggers()->logStreamsReference();
 }
populateAllLoggerIds()
std::vector< std::string > * el::Loggers::populateAllLoggerIds (std::vector< std::string > * targetList) static
Populates all logger IDs in current repository.
Parameters
[out] targetList List of fill up.
Definition at line 2900 of file easylogging++.cc.
References ELPP.
{
   targetList->clear();
   for (base::RegisteredLoggers::iterator it = ELPP->registeredLoggers()->list().begin();
        it != ELPP->registeredLoggers()->list().end(); ++it) {
     targetList->push_back(it->first);
   }
   return targetList;
 }
reconfigureAllLoggers() [1/3]
void el::Loggers::reconfigureAllLoggers (const Configurations & configurations) static
Reconfigures all the existing loggers with new configurations.
Definition at line 2862 of file easylogging++.cc.
References ELPP, and reconfigureLogger().
Referenced by setDefaultConfigurations().
{
   for (base::RegisteredLoggers::iterator it = ELPP->registeredLoggers()->begin();
        it != ELPP->registeredLoggers()->end(); ++it) {
     Loggers::reconfigureLogger(it->second, configurations);
   }
 }
reconfigureAllLoggers() [2/3]
static void el::Loggers::reconfigureAllLoggers (ConfigurationType configurationType, const std::string & value) inline static
Reconfigures single configuration for all the loggers.
Definition at line 3845 of file easylogging++.h.
References el::Global.
{
     reconfigureAllLoggers(Level::Global, configurationType, value);
   }
reconfigureAllLoggers() [3/3]
void el::Loggers::reconfigureAllLoggers (Level level, ConfigurationType configurationType, const std::string & value) static
Reconfigures single configuration for all the loggers for specified level.
Definition at line 2869 of file easylogging++.cc.
References el::Logger::configurations(), ELPP, el::Logger::reconfigure(), and el::Configurations::set().
{
   for (base::RegisteredLoggers::iterator it = ELPP->registeredLoggers()->begin();
        it != ELPP->registeredLoggers()->end(); ++it) {
     Logger* logger = it->second;
     logger->configurations()->set(level, configurationType, value);
     logger->reconfigure();
   }
 }
reconfigureLogger() [1/3]
Logger * el::Loggers::reconfigureLogger (Logger * logger, const Configurations & configurations) static
Reconfigures specified logger with new configurations.
Definition at line 2841 of file easylogging++.cc.
References el::Logger::configure().
Referenced by reconfigureAllLoggers(), and reconfigureLogger().
{
   if (!logger) return nullptr;
   logger->configure(configurations);
   return logger;
 }
reconfigureLogger() [2/3]
Logger * el::Loggers::reconfigureLogger (const std::string & identity, const Configurations & configurations) static
Reconfigures logger with new configurations after looking it up using identity.
Definition at line 2847 of file easylogging++.cc.
References getLogger(), and reconfigureLogger().
{
   return Loggers::reconfigureLogger(Loggers::getLogger(identity), configurations);
 }
reconfigureLogger() [3/3]
Logger * el::Loggers::reconfigureLogger (const std::string & identity, ConfigurationType configurationType, const std::string & value) static
Reconfigures logger's single configuration.
Definition at line 2851 of file easylogging++.cc.
References el::Logger::configurations(), getLogger(), el::Global, el::Logger::reconfigure(), and el::Configurations::set().
{
   Logger* logger = Loggers::getLogger(identity);
   if (logger == nullptr) {
     return nullptr;
   }
   logger->configurations()->set(Level::Global, configurationType, value);
   logger->reconfigure();
   return logger;
 }
removeFlag()
static void el::Loggers::removeFlag (LoggingFlag flag) inline static
Removes logging flag used internally.
Definition at line 3877 of file easylogging++.h.
References ELPP.
Referenced by el::Loggers::ScopedRemoveFlag::ScopedRemoveFlag(), and el::Loggers::ScopedAddFlag::~ScopedAddFlag().
{
     ELPP->removeFlag(flag);
   }
setDefaultConfigurations()
void el::Loggers::setDefaultConfigurations (const Configurations & configurations, bool reconfigureExistingLoggers = false) static
Sets default configurations. This configuration is used for future (and conditionally for existing) loggers.
Definition at line 2879 of file easylogging++.cc.
References ELPP, and reconfigureAllLoggers().
{
   ELPP->registeredLoggers()->setDefaultConfigurations(configurations);
   if (reconfigureExistingLoggers) {
     Loggers::reconfigureAllLoggers(configurations);
   }
 }
setDefaultLogBuilder()
void el::Loggers::setDefaultLogBuilder (el::LogBuilderPtr & logBuilderPtr) static
Changes default log builder for future loggers.
Definition at line 2827 of file easylogging++.cc.
References ELPP.
{
   ELPP->registeredLoggers()->setDefaultLogBuilder(logBuilderPtr);
 }
setLoggingLevel()
static void el::Loggers::setLoggingLevel (Level level) inline static
Sets hierarchy for logging. Needs to enable logging flag (HierarchicalLogging)
Definition at line 3909 of file easylogging++.h.
References ELPP.
{
     ELPP->setLoggingLevel(level);
   }
setVerboseLevel()
void el::Loggers::setVerboseLevel (base::type::VerboseLevel level) static
Sets verbose level on the fly.
Definition at line 2966 of file easylogging++.cc.
References ELPP.
{
   ELPP->vRegistry()->setLevel(level);
 }
setVModules()
void el::Loggers::setVModules (const char * modules) static
Sets vmodules as specified (on the fly)
Definition at line 2974 of file easylogging++.cc.
References ELPP.
{
   if (ELPP->vRegistry()->vModulesEnabled()) {
     ELPP->vRegistry()->setModules(modules);
   }
 }
uninstallLoggerRegistrationCallback()
template<typename T > static void el::Loggers::uninstallLoggerRegistrationCallback (const std::string & id) inline static
Uninstalls log dispatch callback.
Definition at line 3823 of file easylogging++.h.
References ELPP.
{
     ELPP->registeredLoggers()->uninstallLoggerRegistrationCallback<T>(id);
   }
unregisterLogger()
bool el::Loggers::unregisterLogger (const std::string & identity) static
Unregisters logger - use it only when you know what you are doing, you may unregister loggers initialized / used by third-party libs.
Definition at line 2831 of file easylogging++.cc.
References ELPP.
{
   base::threading::ScopedLock scopedLock(ELPP->lock());
   return ELPP->registeredLoggers()->remove(identity);
 }
verboseLevel()
base::type::VerboseLevel el::Loggers::verboseLevel (void) static
Gets current verbose level.
Definition at line 2970 of file easylogging++.cc.
References ELPP.
{
   return ELPP->vRegistry()->level();
 }
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc