VulpesRender: el::base::utils::RegistryWithPred< T_Ptr, Pred > Class Template Reference
el::base::utils::RegistryWithPred< T_Ptr, Pred > Class Template Reference abstract
A pointer registry mechanism to manage memory and provide search functionalities.
#include <easylogging++.h>
Public Types
typedef RegistryWithPred< T_Ptr, Pred >::iterator iterator
typedef RegistryWithPred< T_Ptr, Pred >::const_iterator const_iterator
Public Member Functions
RegistryWithPred (void)
virtual ~RegistryWithPred (void)
RegistryWithPred (const RegistryWithPred &sr)
Copy constructor that is useful for base classes. Try to avoid this constructor, use move constructor.
RegistryWithPred & operator= (const RegistryWithPred &sr)
Assignment operator that unregisters all the existing registeries and deeply copies each of repo element.
bool operator== (const AbstractRegistry< T_Ptr, std::vector< T_Ptr * > > &other)
bool operator!= (const AbstractRegistry< T_Ptr, std::vector< T_Ptr * > > &other)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual std::vector< T_Ptr * > & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const std::vector< T_Ptr * > & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void unregister (T_Ptr *&ptr) ELPP_FINAL
virtual void registerNew (T_Ptr *ptr) ELPP_FINAL
template<typename T , typename T2 >
T_Ptr * get (const T &arg1, const T2 arg2)
Gets pointer from repository with speicifed arguments.
virtual void deepCopy (const AbstractRegistry< T_Ptr, std::vector< T_Ptr * > > &)=0
void reinitDeepCopy (const AbstractRegistry< T_Ptr, std::vector< T_Ptr * > > &sr)
Private Member Functions
virtual void deepCopy (const AbstractRegistry< T_Ptr, std::vector< T_Ptr *>> &sr)
Friends
base::type::ostream_t & operator<< (base::type::ostream_t &os, const RegistryWithPred &sr)
Detailed Description
template<typename T_Ptr, typename Pred>
class el::base::utils::RegistryWithPred< T_Ptr, Pred >
A pointer registry mechanism to manage memory and provide search functionalities.
(predicate version)
NOTE: This is thread-unsafe implementation of AbstractRegistry<T_Ptr, Container>. Any implementation of this class should be made thread-safe explicitly
Definition at line 1501 of file easylogging++.h.
Member Typedef Documentation
const_iterator
template<typename T_Ptr, typename Pred> typedef RegistryWithPred<T_Ptr, Pred>::const_iterator el::base::utils::RegistryWithPred< T_Ptr, Pred >::const_iterator
Definition at line 1504 of file easylogging++.h.
iterator
template<typename T_Ptr, typename Pred> typedef RegistryWithPred<T_Ptr, Pred>::iterator el::base::utils::RegistryWithPred< T_Ptr, Pred >::iterator
Definition at line 1503 of file easylogging++.h.
Constructor & Destructor Documentation
RegistryWithPred() [1/2]
template<typename T_Ptr, typename Pred> el::base::utils::RegistryWithPred< T_Ptr, Pred >::RegistryWithPred (void) inline
Definition at line 1506 of file easylogging++.h.
{
   }
~RegistryWithPred()
template<typename T_Ptr, typename Pred> virtual el::base::utils::RegistryWithPred< T_Ptr, Pred >::~RegistryWithPred (void) inline virtual
Definition at line 1509 of file easylogging++.h.
{
     unregisterAll();
   }
RegistryWithPred() [2/2]
template<typename T_Ptr, typename Pred> el::base::utils::RegistryWithPred< T_Ptr, Pred >::RegistryWithPred (const RegistryWithPred< T_Ptr, Pred > & sr) inline
Copy constructor that is useful for base classes. Try to avoid this constructor, use move constructor.
Definition at line 1514 of file easylogging++.h.
                                                : AbstractRegistry<T_Ptr, std::vector<T_Ptr*>>() {
     if (this == &sr) {
       return;
     }
     this->reinitDeepCopy(sr);
   }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
begin()
virtual iterator el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::begin (void) inline virtual inherited
Returns
Iterator pointer from start of repository
Definition at line 1365 of file easylogging++.h.
{
     return m_list.begin();
   }
cbegin()
virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::cbegin (void) const inline virtual inherited
Returns
Constant iterator pointer from start of repository
Definition at line 1376 of file easylogging++.h.
{
     return m_list.cbegin();
   }
cend()
virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::cend (void) const inline virtual inherited
Returns
End of repository
Definition at line 1381 of file easylogging++.h.
{
     return m_list.cend();
   }
deepCopy() [1/2]
virtual void el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::deepCopy (const AbstractRegistry< T_Ptr, std::vector< T_Ptr *> > &) protected pure virtual inherited
deepCopy() [2/2]
template<typename T_Ptr, typename Pred> virtual void el::base::utils::RegistryWithPred< T_Ptr, Pred >::deepCopy (const AbstractRegistry< T_Ptr, std::vector< T_Ptr *>> & sr) inline private virtual
Definition at line 1580 of file easylogging++.h.
{
     for (const_iterator it = sr.list().begin(); it != sr.list().end(); ++it) {
       registerNew(new T_Ptr(**it));
     }
   }
empty()
virtual bool el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::empty (void) const inline virtual inherited
Returns
Whether or not repository is empty
Definition at line 1386 of file easylogging++.h.
{
     return m_list.empty();
   }
end()
virtual iterator el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::end (void) inline virtual inherited
Returns
Iterator pointer from end of repository
Definition at line 1370 of file easylogging++.h.
{
     return m_list.end();
   }
get()
template<typename T_Ptr, typename Pred> template<typename T , typename T2 > T_Ptr* el::base::utils::RegistryWithPred< T_Ptr, Pred >::get (const T & arg1, const T2 arg2) inline protected
Gets pointer from repository with speicifed arguments.
Arguments are passed to predicate in order to validate pointer.
Definition at line 1571 of file easylogging++.h.
{
     iterator iter = std::find_if(this->list().begin(), this->list().end(), Pred(arg1, arg2));
     if (iter != this->list().end() && *iter != nullptr) {
       return *iter;
     }
     return nullptr;
   }
list() [1/2]
virtual std::vector< T_Ptr *> & el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::list (void) inline virtual inherited
Returns underlying container by reference.
Definition at line 1396 of file easylogging++.h.
{
     return m_list;
   }
list() [2/2]
virtual const std::vector< T_Ptr *> & el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::list (void) const inline virtual inherited
Returns underlying container by constant reference.
Definition at line 1401 of file easylogging++.h.
{
     return m_list;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
operator!=()
bool el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator!= (const AbstractRegistry< T_Ptr, std::vector< T_Ptr *> > & other) inline inherited
Definition at line 1339 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list, and el::base::utils::AbstractRegistry< T_Ptr, Container >::size().
{
     if (size() != other.size()) {
       return true;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return true;
       }
     }
     return false;
   }
operator=()
template<typename T_Ptr, typename Pred> RegistryWithPred& el::base::utils::RegistryWithPred< T_Ptr, Pred >::operator= (const RegistryWithPred< T_Ptr, Pred > & sr) inline
Assignment operator that unregisters all the existing registeries and deeply copies each of repo element.
See also
unregisterAll()
deepCopy(const AbstractRegistry&)
Definition at line 1524 of file easylogging++.h.
{
     if (this == &sr) {
       return *this;
     }
     this->reinitDeepCopy(sr);
     return *this;
   }
operator==()
bool el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator== (const AbstractRegistry< T_Ptr, std::vector< T_Ptr *> > & other) inline inherited
Definition at line 1327 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list, and el::base::utils::AbstractRegistry< T_Ptr, Container >::size().
{
     if (size() != other.size()) {
       return false;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return false;
       }
     }
     return true;
   }
registerNew()
template<typename T_Ptr, typename Pred> virtual void el::base::utils::RegistryWithPred< T_Ptr, Pred >::registerNew (T_Ptr * ptr) inline protected virtual
Definition at line 1564 of file easylogging++.h.
{
     this->list().push_back(ptr);
   }
reinitDeepCopy()
void el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::reinitDeepCopy (const AbstractRegistry< T_Ptr, std::vector< T_Ptr *> > & sr) inline protected inherited
Definition at line 1410 of file easylogging++.h.
{
     unregisterAll();
     deepCopy(sr);
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
size()
virtual std::size_t el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::size (void) const inline virtual inherited
Returns
Size of repository
Definition at line 1391 of file easylogging++.h.
{
     return m_list.size();
   }
unregister()
template<typename T_Ptr, typename Pred> virtual void el::base::utils::RegistryWithPred< T_Ptr, Pred >::unregister (T_Ptr *& ptr) inline protected virtual
Definition at line 1549 of file easylogging++.h.
{
     if (ptr) {
       iterator iter = this->begin();
       for (; iter != this->end(); ++iter) {
         if (ptr == *iter) {
           break;
         }
       }
       if (iter != this->end() && *iter != nullptr) {
         this->list().erase(iter);
         base::utils::safeDelete(*iter);
       }
     }
   }
unregisterAll()
template<typename T_Ptr, typename Pred> virtual void el::base::utils::RegistryWithPred< T_Ptr, Pred >::unregisterAll (void) inline protected virtual
Unregisters all the pointers from current repository.
Implements el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >.
Definition at line 1540 of file easylogging++.h.
{
     if (!this->empty()) {
       for (auto&& curr : this->list()) {
         base::utils::safeDelete(curr);
       }
       this->list().clear();
     }
   }
Friends And Related Function Documentation
operator<<
template<typename T_Ptr, typename Pred> base::type::ostream_t& operator<< (base::type::ostream_t & os, const RegistryWithPred< T_Ptr, Pred > & sr) friend
Definition at line 1532 of file easylogging++.h.
{
     for (const_iterator it = sr.list().begin(); it != sr.list().end(); ++it) {
       os << ELPP_LITERAL("    ") << **it << ELPP_LITERAL("\n");
     }
     return os;
   }
The documentation for this class was generated from the following file:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h