VulpesRender: el::base::utils::CommandLineArgs Class Reference
el::base::utils::CommandLineArgs Class Reference
Command line arguments for application if specified using el::Helpers::setArgs(..) or START_EASYLOGGINGPP(..)
#include <easylogging++.h>
Public Member Functions
CommandLineArgs (void)
CommandLineArgs (int argc, const char **argv)
CommandLineArgs (int argc, char **argv)
virtual ~CommandLineArgs (void)
void setArgs (int argc, const char **argv)
Sets arguments and parses them.
void setArgs (int argc, char **argv)
Sets arguments and parses them.
bool hasParamWithValue (const char *paramKey) const
Returns true if arguments contain paramKey with a value (seperated by '=')
const char * getParamValue (const char *paramKey) const
Returns value of arguments.
bool hasParam (const char *paramKey) const
Return true if arguments has a param (not having a value) i,e without '='.
bool empty (void) const
Returns true if no params available. This exclude argv[0].
std::size_t size (void) const
Returns total number of arguments. This exclude argv[0].
Private Attributes
int m_argc
char ** m_argv
std::map< std::string, std::string > m_paramsWithValue
std::vector< std::string > m_params
Friends
base::type::ostream_t & operator<< (base::type::ostream_t &os, const CommandLineArgs &c)
Detailed Description
Command line arguments for application if specified using el::Helpers::setArgs(..) or START_EASYLOGGINGPP(..)
Definition at line 1266 of file easylogging++.h.
Constructor & Destructor Documentation
CommandLineArgs() [1/3]
el::base::utils::CommandLineArgs::CommandLineArgs (void) inline
Definition at line 1268 of file easylogging++.h.
{
     setArgs(0, static_cast<char**>(nullptr));
   }
CommandLineArgs() [2/3]
el::base::utils::CommandLineArgs::CommandLineArgs (int argc, const char ** argv) inline
Definition at line 1271 of file easylogging++.h.
{
     setArgs(argc, argv);
   }
CommandLineArgs() [3/3]
el::base::utils::CommandLineArgs::CommandLineArgs (int argc, char ** argv) inline
Definition at line 1274 of file easylogging++.h.
{
     setArgs(argc, argv);
   }
~CommandLineArgs()
virtual el::base::utils::CommandLineArgs::~CommandLineArgs (void) inline virtual
Definition at line 1277 of file easylogging++.h.
 {}
Member Function Documentation
empty()
bool el::base::utils::CommandLineArgs::empty (void) const
Returns true if no params available. This exclude argv[0].
Definition at line 1283 of file easylogging++.cc.
{
   return m_params.empty() && m_paramsWithValue.empty();
 }
getParamValue()
const char * el::base::utils::CommandLineArgs::getParamValue (const char * paramKey) const
Returns value of arguments.
See also
hasParamWithValue(const char*)
Definition at line 1274 of file easylogging++.cc.
Referenced by el::base::VRegistry::setFromArgs().
{
   std::map<std::string, std::string>::const_iterator iter = m_paramsWithValue.find(std::string(paramKey));
   return iter != m_paramsWithValue.end() ? iter->second.c_str() : "";
 }
hasParam()
bool el::base::utils::CommandLineArgs::hasParam (const char * paramKey) const
Return true if arguments has a param (not having a value) i,e without '='.
Definition at line 1279 of file easylogging++.cc.
Referenced by el::base::VRegistry::setFromArgs().
{
   return std::find(m_params.begin(), m_params.end(), std::string(paramKey)) != m_params.end();
 }
hasParamWithValue()
bool el::base::utils::CommandLineArgs::hasParamWithValue (const char * paramKey) const
Returns true if arguments contain paramKey with a value (seperated by '=')
Definition at line 1270 of file easylogging++.cc.
Referenced by el::base::VRegistry::setFromArgs().
{
   return m_paramsWithValue.find(std::string(paramKey)) != m_paramsWithValue.end();
 }
setArgs() [1/2]
void el::base::utils::CommandLineArgs::setArgs (int argc, const char ** argv) inline
Sets arguments and parses them.
Definition at line 1279 of file easylogging++.h.
References vpr::operator<<().
{
     setArgs(argc, const_cast<char**>(argv));
   }
setArgs() [2/2]
void el::base::utils::CommandLineArgs::setArgs (int argc, char ** argv)
Sets arguments and parses them.
Definition at line 1240 of file easylogging++.cc.
References ELPP_INTERNAL_INFO.
{
   m_params.clear();
   m_paramsWithValue.clear();
   if (argc == 0 || argv == nullptr) {
     return;
   }
   m_argc = argc;
   m_argv = argv;
   for (int i = 1; i < m_argc; ++i) {
     const char* v = (strstr(m_argv[i], "="));
     if (v != nullptr && strlen(v) > 0) {
       std::string key = std::string(m_argv[i]);
       key = key.substr(0, key.find_first_of('='));
       if (hasParamWithValue(key.c_str())) {
         ELPP_INTERNAL_INFO(1, "Skipping [" << key << "] arg since it already has value ["
                            << getParamValue(key.c_str()) << "]");
       } else {
         m_paramsWithValue.insert(std::make_pair(key, std::string(v + 1)));
       }
     }
     if (v == nullptr) {
       if (hasParam(m_argv[i])) {
         ELPP_INTERNAL_INFO(1, "Skipping [" << m_argv[i] << "] arg since it already exists");
       } else {
         m_params.push_back(std::string(m_argv[i]));
       }
     }
   }
 }
size()
std::size_t el::base::utils::CommandLineArgs::size (void) const
Returns total number of arguments. This exclude argv[0].
Definition at line 1287 of file easylogging++.cc.
{
   return m_params.size() + m_paramsWithValue.size();
 }
Friends And Related Function Documentation
operator<<
base::type::ostream_t& operator<< (base::type::ostream_t & os, const CommandLineArgs & c) friend
Definition at line 1291 of file easylogging++.cc.
{
   for (int i = 1; i < c.m_argc; ++i) {
     os << ELPP_LITERAL("[") << c.m_argv[i] << ELPP_LITERAL("]");
     if (i < c.m_argc - 1) {
       os << ELPP_LITERAL(" ");
     }
   }
   return os;
 }
Member Data Documentation
m_argc
int el::base::utils::CommandLineArgs::m_argc private
Definition at line 1298 of file easylogging++.h.
Referenced by el::base::utils::operator<<().
m_argv
char** el::base::utils::CommandLineArgs::m_argv private
Definition at line 1299 of file easylogging++.h.
Referenced by el::base::utils::operator<<().
m_params
std::vector<std::string> el::base::utils::CommandLineArgs::m_params private
Definition at line 1301 of file easylogging++.h.
m_paramsWithValue
std::map<std::string, std::string> el::base::utils::CommandLineArgs::m_paramsWithValue private
Definition at line 1300 of file easylogging++.h.
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc