VulpesRender: el::base::DefaultLogDispatchCallback Class Reference
el::base::DefaultLogDispatchCallback Class Reference
#include <easylogging++.h>
Public Member Functions
bool enabled (void) const
void setEnabled (bool enabled)
Protected Member Functions
void handle (const LogDispatchData *data)
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
void dispatch (base::type::string_t &&logLine)
Private Attributes
const LogDispatchData * m_data
Detailed Description
Definition at line 2767 of file easylogging++.h.
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
dispatch()
void el::base::DefaultLogDispatchCallback::dispatch (base::type::string_t && logLine) private
Definition at line 2108 of file easylogging++.cc.
References el::LogBuilder::build(), el::ColoredTerminalOutput, el::LogBuilder::convertToColoredOutput(), el::LevelHelper::convertToString(), el::Debug, el::LogDispatchData::dispatchAction(), ELPP, ELPP_COUT, ELPP_COUT_LINE, ELPP_INTERNAL_ERROR, ELPP_INTERNAL_INFO, el::Error, el::Fatal, el::base::TypedConfigurations::filename(), el::base::TypedConfigurations::fileStream(), el::Logger::flush(), el::Logger::id(), el::ImmediateFlush, el::Info, el::Logger::isFlushNeeded(), el::LogMessage::level(), el::Logger::logBuilder(), el::LogMessage::logger(), el::LogDispatchData::logMessage(), el::base::NormalLog, el::base::SysLog, el::base::TypedConfigurations::toFile(), el::base::TypedConfigurations::toStandardOutput(), el::Logger::typedConfigurations(), el::Warning, and el::base::utils::Str::wcharPtrToCharPtr().
{
   if (m_data->dispatchAction() == base::DispatchAction::NormalLog) {
     if (m_data->logMessage()->logger()->m_typedConfigurations->toFile(m_data->logMessage()->level())) {
       base::type::fstream_t* fs = m_data->logMessage()->logger()->m_typedConfigurations->fileStream(
                                     m_data->logMessage()->level());
       if (fs != nullptr) {
         fs->write(logLine.c_str(), logLine.size());
         if (fs->fail()) {
           ELPP_INTERNAL_ERROR("Unable to write log to file ["
                               << m_data->logMessage()->logger()->m_typedConfigurations->filename(m_data->logMessage()->level()) << "].\n"
                               << "Few possible reasons (could be something else):\n" << "      * Permission denied\n"
                               << "      * Disk full\n" << "      * Disk is not writable", true);
         } else {
           if (ELPP->hasFlag(LoggingFlag::ImmediateFlush)
               || (m_data->logMessage()->logger()->isFlushNeeded(m_data->logMessage()->level()))) {
             m_data->logMessage()->logger()->flush(m_data->logMessage()->level(), fs);
           }
         }
       } else {
         ELPP_INTERNAL_ERROR("Log file for [" << LevelHelper::convertToString(m_data->logMessage()->level()) << "] "
                             << "has not been configured but [TO_FILE] is configured to TRUE. [Logger ID: "
                             << m_data->logMessage()->logger()->id() << "]", false);
       }
     }
     if (m_data->logMessage()->logger()->m_typedConfigurations->toStandardOutput(m_data->logMessage()->level())) {
       if (ELPP->hasFlag(LoggingFlag::ColoredTerminalOutput))
         m_data->logMessage()->logger()->logBuilder()->convertToColoredOutput(&logLine, m_data->logMessage()->level());
       ELPP_COUT << ELPP_COUT_LINE(logLine);
     }
   }
 #if defined(ELPP_SYSLOG)
   else if (m_data->dispatchAction() == base::DispatchAction::SysLog) {
     // Determine syslog priority
     int sysLogPriority = 0;
     if (m_data->logMessage()->level() == Level::Fatal)
       sysLogPriority = LOG_EMERG;
     else if (m_data->logMessage()->level() == Level::Error)
       sysLogPriority = LOG_ERR;
     else if (m_data->logMessage()->level() == Level::Warning)
       sysLogPriority = LOG_WARNING;
     else if (m_data->logMessage()->level() == Level::Info)
       sysLogPriority = LOG_INFO;
     else if (m_data->logMessage()->level() == Level::Debug)
       sysLogPriority = LOG_DEBUG;
     else
       sysLogPriority = LOG_NOTICE;
 #  if defined(ELPP_UNICODE)
     char* line = base::utils::Str::wcharPtrToCharPtr(logLine.c_str());
     syslog(sysLogPriority, "%s", line);
     free(line);
 #  else
     syslog(sysLogPriority, "%s", logLine.c_str());
 #  endif
   }
 #endif  // defined(ELPP_SYSLOG)
 }
enabled()
bool el::Callback< LogDispatchData >::enabled (void) const inline inherited
Definition at line 2200 of file easylogging++.h.
{
     return m_enabled;
   }
handle()
void el::base::DefaultLogDispatchCallback::handle (const LogDispatchData * data) protected virtual
Implements el::Callback< LogDispatchData >.
Definition at line 2102 of file easylogging++.cc.
References el::base::NormalLog.
{
   m_data = data;
   dispatch(m_data->logMessage()->logger()->logBuilder()->build(m_data->logMessage(),
            m_data->dispatchAction() == base::DispatchAction::NormalLog));
 }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
setEnabled()
void el::Callback< LogDispatchData >::setEnabled (bool enabled) inline inherited
Definition at line 2203 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     m_enabled = enabled;
   }
Member Data Documentation
m_data
const LogDispatchData* el::base::DefaultLogDispatchCallback::m_data private
Definition at line 2771 of file easylogging++.h.
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc