VulpesRender: vpr::Framebuffer Class Reference
vpr::Framebuffer Class Reference
Rendering
The Framebuffer class merely handles lifetime of a VkFramebuffer object.
#include <Framebuffer.hpp>
Public Member Functions
virtual ~Framebuffer ()
Framebuffer (const Device *parent, const VkFramebufferCreateInfo &create_info)
Framebuffer & operator= (Framebuffer &&other) noexcept
Framebuffer (Framebuffer &&other) noexcept
const VkFramebuffer & vkHandle () const noexcept
void Destroy ()
Protected Attributes
const Device * parent
VkFramebuffer handle
Private Member Functions
Framebuffer (const Framebuffer &)=delete
Framebuffer & operator= (const Framebuffer &)=delete
Detailed Description
The Framebuffer class merely handles lifetime of a VkFramebuffer object.
All important information on how to setup this class is provided by the VkFramebufferCreateInfo struct in the constructor.
Definition at line 13 of file Framebuffer.hpp.
Constructor & Destructor Documentation
Framebuffer() [1/3]
vpr::Framebuffer::Framebuffer (const Framebuffer &) private delete
~Framebuffer()
vpr::Framebuffer::~Framebuffer () virtual
Definition at line 13 of file Framebuffer.cpp.
References Destroy().
{
         Destroy();
     }
Framebuffer() [2/3]
vpr::Framebuffer::Framebuffer (const Device * parent, const VkFramebufferCreateInfo & create_info)
Definition at line 7 of file Framebuffer.cpp.
References handle, parent, VkAssert, and vpr::Device::vkHandle().
                                                                                                 : parent(_parent),
         handle(VK_NULL_HANDLE) {
         VkResult result = vkCreateFramebuffer(parent->vkHandle(), &create_info, nullptr, &handle);
         VkAssert(result);
     }
Framebuffer() [3/3]
vpr::Framebuffer::Framebuffer (Framebuffer && other) noexcept
Definition at line 17 of file Framebuffer.cpp.
References vpr::Device::handle.
                                                          : handle(std::move(other.handle)), parent(std::move(other.parent)) {
         other.handle = VK_NULL_HANDLE;
     }
Member Function Documentation
Destroy()
void vpr::Framebuffer::Destroy ()
Definition at line 32 of file Framebuffer.cpp.
References handle, parent, and vpr::Device::vkHandle().
Referenced by ~Framebuffer().
{
         if (handle != VK_NULL_HANDLE) {
             vkDestroyFramebuffer(parent->vkHandle(), handle, nullptr);
         }
     }
operator=() [1/2]
Framebuffer& vpr::Framebuffer::operator= (const Framebuffer &) private delete
operator=() [2/2]
Framebuffer & vpr::Framebuffer::operator= (Framebuffer && other) noexcept
Definition at line 21 of file Framebuffer.cpp.
References handle, and parent.
{
         handle = std::move(other.handle);
         parent = std::move(other.parent);
         other.handle = VK_NULL_HANDLE;
         return *this;
     }
vkHandle()
const VkFramebuffer & vpr::Framebuffer::vkHandle () const noexcept
Definition at line 28 of file Framebuffer.cpp.
References handle.
{
         return handle;
     }
Member Data Documentation
handle
VkFramebuffer vpr::Framebuffer::handle protected
Definition at line 30 of file Framebuffer.hpp.
Referenced by Destroy(), Framebuffer(), operator=(), and vkHandle().
parent
const Device* vpr::Framebuffer::parent protected
Definition at line 29 of file Framebuffer.hpp.
Referenced by Destroy(), Framebuffer(), and operator=().
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/render/Framebuffer.hpp
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/render/Framebuffer.cpp