VulpesRender: vpr::Buffer Class Reference
vpr::Buffer Class Reference
Resources
#include <BufferDeprecated.hpp>
Public Member Functions
Buffer (const VkDevice &parent)
~Buffer ()
Buffer (Buffer &&other) noexcept
Buffer & operator= (Buffer &&other) noexcept
void CreateBuffer (const VkBufferUsageFlags &usage_flags, const VkMemoryPropertyFlags &memory_flags, const VkDeviceSize &size)
Creates underlying handles, binds a memory region from the allocator system, and prepares everything for use.
void CreateBuffer (const VkBufferCreateInfo &create_info, const VkMemoryPropertyFlags &memory_flags)
Creates underlying handles and binds a memory region from the allocator subsystem, but takes a VkBufferCreatInfo structure containing all the relevant required setup information.
void Destroy ()
Destroys handles belonging to this object and attempts to free/unbind the memory region it used.
void CopyToMapped (const void *data, const VkDeviceSize &size, const VkDeviceSize &offset)
Maps this object, copies data to this object, then ensures to unmap this object.
void CopyTo (const Buffer *other_buffer, const VkCommandBuffer &cmd, const VkDeviceSize offset)
Copies the data in the given Buffer pointer to this object.
void CopyTo (const void *data, const VkCommandBuffer &transfer_cmd, const VkDeviceSize &copy_size, const VkDeviceSize &copy_offset)
Copys the data pointed to by the relevant parameter into a staging buffer, then records commands copying data from the staging object into the destination object.
void CopyTo (const void *data, CommandPool *cmd_pool, const VkQueue &transfer_queue, const VkDeviceSize &size, const VkDeviceSize &offset)
Copies data using a single command buffer submission form the given pool to the given queue.
void Update (const VkCommandBuffer &cmd, const VkDeviceSize &data_sz, const VkDeviceSize &offset, const void *data)
Used to update a sub-region of the buffer.
void Fill (const VkCommandBuffer &cmd, const VkDeviceSize sz, const VkDeviceSize offset, const uint32_t value)
Fills buffer with given value.
VkBufferMemoryBarrier CreateMemoryBarrier (VkAccessFlags src, VkAccessFlags dst, uint32_t src_idx, uint32_t dst_idx, VkDeviceSize sz) const
void CreateView (const VkFormat format, const VkDeviceSize range, const VkDeviceSize offset)
void Map (const VkDeviceSize &offset=0)
void Unmap ()
void Flush ()
void Invalidate ()
const VkBuffer & vkHandle () const noexcept
VkBuffer & vkHandle () noexcept
const VkBufferView & View () const noexcept
const VkDescriptorBufferInfo & GetDescriptor () const noexcept
const VkMappedMemoryRange & MappedMemoryRange () const noexcept
VkDeviceSize Size () const noexcept
void SetMappedMemory (void *mapping_destination)
VkBufferUsageFlags Usage () const noexcept
Static Public Member Functions
static void CreateStagingBuffer (const Device *dvc, const VkDeviceSize &size, VkBuffer &dest, Allocation &dest_memory_range)
Creates a staging buffer of given size, using the given (hopefully not used) VkBuffer handle and updating the members of the given Allocation struct.
static std::unique_ptr< Buffer > CreateStagingBuffer (const Device *dvc, void *data, const size_t data_size)
Protected Member Functions
void createStagingBuffer (const VkDeviceSize &size, VkBuffer &staging_buffer, Allocation &dest_memory_range)
void setMappedMemoryRange () const
void setDescriptorInfo () const noexcept
Protected Attributes
VkDevice parent { VK_NULL_HANDLE }
VkBuffer handle { VK_NULL_HANDLE }
VkBufferView view { VK_NULL_HANDLE }
VkBufferCreateInfo createInfo { }
VkBufferViewCreateInfo viewCreateInfo { VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO, nullptr, 0 }
VkMappedMemoryRange mappedMemoryRange { }
Allocation memoryAllocation
VkDeviceSize size { std::numeric_limits<VkDeviceSize>::max() }
VkDeviceSize dataSize { std::numeric_limits<VkDeviceSize>::max() }
void * mappedMemory { nullptr }
bool descriptorInfoSet { false }
VkDescriptorBufferInfo descriptor { VK_NULL_HANDLE, 0, 0 }
Private Member Functions
Buffer (const Buffer &)=delete
Buffer & operator= (const Buffer &)=delete
Detailed Description
Deprecated:
{No longer recommended for use: unmaintained and not updated.
} RAII wrapper around a VkBuffer object. Can be used for anything from VBOs+EBOs to compute storage buffers to uniform buffers. No initialization or resource creation is done until the CreateBuffer method is called: at this point, the size of the object must be submitted as this size is fixed after creating the VkBuffer object.
Definition at line 23 of file BufferDeprecated.hpp.
Constructor & Destructor Documentation
Buffer() [1/3]
vpr::Buffer::Buffer (const Buffer &) private delete
Buffer() [2/3]
vpr::Buffer::Buffer (const VkDevice & parent)
Definition at line 12 of file BufferDeprecated.cpp.
                                           : parent(_parent), createInfo(vk_buffer_create_info_base), viewCreateInfo(base_view_info),
         handle(VK_NULL_HANDLE), view(VK_NULL_HANDLE) {}
~Buffer()
vpr::Buffer::~Buffer ()
Definition at line 15 of file BufferDeprecated.cpp.
References Destroy().
                    {
         Destroy();
     }
Buffer() [3/3]
vpr::Buffer::Buffer (Buffer && other) noexcept
Definition at line 19 of file BufferDeprecated.cpp.
                                            : size(std::move(other.size)), createInfo(std::move(other.createInfo)),
         handle(std::move(other.handle)), memoryAllocation(std::move(other.memoryAllocation)), parent(std::move(other.parent)),
         viewCreateInfo(std::move(other.viewCreateInfo)), view(std::move(other.view)) {
         // Make sure to nullify so destructor checks safer/more likely to succeed.
         other.handle = VK_NULL_HANDLE;
         other.view = VK_NULL_HANDLE;
     }
Member Function Documentation
CopyTo() [1/3]
void vpr::Buffer::CopyTo (const Buffer * other_buffer, const VkCommandBuffer & cmd, const VkDeviceSize offset)
Copies the data in the given Buffer pointer to this object.
Definition at line 92 of file BufferDeprecated.cpp.
References handle, Size(), and vkHandle().
{
         VkBufferCopy copy{};
         copy.size = buff->Size();
         copy.dstOffset = offset;
         vkCmdCopyBuffer(cmd, buff->vkHandle(), handle, 1, &copy);
     }
CopyTo() [2/3]
void vpr::Buffer::CopyTo (const void * data, const VkCommandBuffer & transfer_cmd, const VkDeviceSize & copy_size, const VkDeviceSize & copy_offset)
Copys the data pointed to by the relevant parameter into a staging buffer, then records commands copying data from the staging object into the destination object.
The lifetime of the staging buffer will persist after the command is submitted: make sure to call FreeStagingBuffers() somewhat frequently, in order to ensure that excess host-side memory isn't being occupied/used.
Definition at line 99 of file BufferDeprecated.cpp.
References createStagingBuffer(), handle, vpr::Allocation::Memory(), vpr::Allocation::Offset(), parent, and VkAssert.
{
         VkBuffer staging_buffer;
         Allocation staging_alloc;
         createStagingBuffer(copy_size, staging_buffer, staging_alloc);
         void* mapped;
         VkResult result = vkMapMemory(parent->vkHandle(), staging_alloc.Memory(), staging_alloc.Offset(), copy_size, 0, &mapped);
         VkAssert(result);
         memcpy(mapped, data, static_cast<size_t>(copy_size));
         vkUnmapMemory(parent->vkHandle(), staging_alloc.Memory());
         VkBufferCopy copy{};
         copy.size = copy_size;
         copy.dstOffset = copy_offset;
         vkCmdCopyBuffer(transfer_cmd, staging_buffer, handle, 1, &copy);
         stagingBuffers.emplace_back(std::make_pair(std::move(staging_buffer), std::move(staging_alloc)));
     }
CopyTo() [3/3]
void vpr::Buffer::CopyTo (const void * data, CommandPool * cmd_pool, const VkQueue & transfer_queue, const VkDeviceSize & size, const VkDeviceSize & offset)
Copies data using a single command buffer submission form the given pool to the given queue.
Attempt to use a transfer-specialized queue when available.
Deprecated:
Use the other CopyTo method that accepts a command buffer instead of this one: using a single command buffer submission like this method does is wasteful, and is not as safe as the other method: if that method is used with a TransferPool, the transfer is guarded with a VkFence (and this method is not). Additionally, the TransferPool class is thread-safe and protects access to its queue and command pool.
Definition at line 120 of file BufferDeprecated.cpp.
References createStagingBuffer(), vpr::CommandPool::EndSingleCmdBuffer(), handle, vpr::Allocation::Memory(), vpr::Allocation::Offset(), parent, vpr::CommandPool::StartSingleCmdBuffer(), and VkAssert.
{
         VkBuffer staging_buffer;
         Allocation staging_alloc;
         createStagingBuffer(copy_size, staging_buffer, staging_alloc);
         void* mapped;
         VkResult result = vkMapMemory(parent->vkHandle(), staging_alloc.Memory(), staging_alloc.Offset(), copy_size, 0, &mapped);
         VkAssert(result);
         memcpy(mapped, data, static_cast<size_t>(copy_size));
         vkUnmapMemory(parent->vkHandle(), staging_alloc.Memory());
         VkCommandBuffer copy_cmd = cmd_pool->StartSingleCmdBuffer();
             VkBufferCopy copy{};
             copy.size = copy_size;
             copy.dstOffset = copy_offset;
             vkCmdCopyBuffer(copy_cmd, staging_buffer, handle, 1, &copy);
         cmd_pool->EndSingleCmdBuffer(copy_cmd, transfer_queue);
         stagingBuffers.emplace_back(std::make_pair(std::move(staging_buffer), std::move(staging_alloc)));
     }
CopyToMapped()
void vpr::Buffer::CopyToMapped (const void * data, const VkDeviceSize & size, const VkDeviceSize & offset)
Maps this object, copies data to this object, then ensures to unmap this object.
Parameters
data whatever you intend to copy. Some objects might have to be const_cast'ed
size size of data being copied, which can be much smaller than the total size
offset destination offset, but can be set to 0 if copying to the front of the buffer or if the copy size is equivalent to the buffer's total size.
Definition at line 78 of file BufferDeprecated.cpp.
References Map(), mappedMemory, Size(), size, and Unmap().
{
         Map(offset);
         if (size == 0) {
             memcpy(mappedMemory, data, static_cast<size_t>(Size()));
         }
         else {
             memcpy(mappedMemory, data, static_cast<size_t>(copy_size));
         }
         Unmap();
     }
CreateBuffer() [1/2]
void vpr::Buffer::CreateBuffer (const VkBufferUsageFlags & usage_flags, const VkMemoryPropertyFlags & memory_flags, const VkDeviceSize & size)
Creates underlying handles, binds a memory region from the allocator system, and prepares everything for use.
Does not load data, however
Parameters
usage_flags The intended use of this buffer. If memory_flags is VK_MEMORY_PROPERTY_DEVICE_LOCAL, be sure to | your usage flag with VK_BUFFER_USAGE_TRANFER_SRC_BIT/VK_BUFFER_USAGE_TRANFER_DST_BIT based on which way you'll be passing resources
memory_flags for rendering resources larger than ~512 bytes, use VK_MEMORY_PROPERTY_DEVICE_LOCAL. Otherwise, consider using VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |'d with VK_MEMORY_PROPERTY_HOST_COHERENT bit, especially for things that are frequently updated like UBOs.
Definition at line 40 of file BufferDeprecated.cpp.
References createInfo, dataSize, handle, memoryAllocation, parent, vpr::AllocationRequirements::preferredFlags, vpr::AllocationRequirements::privateMemory, vpr::AllocationRequirements::requiredFlags, setMappedMemoryRange(), vpr::Allocation::Size, size, and VkAssert.
{
         createInfo.usage = usage_flags;
         createInfo.size = _size;
         dataSize = _size;
         createInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
         AllocationRequirements reqs;
         reqs.preferredFlags = 0;
         reqs.privateMemory = false;
         reqs.requiredFlags = memory_flags;
         VkResult result = parent->GetAllocator()->CreateBuffer(&handle, &createInfo, reqs, memoryAllocation);
         VkAssert(result);
         size = memoryAllocation.Size;
         setMappedMemoryRange();
     }
CreateBuffer() [2/2]
void vpr::Buffer::CreateBuffer (const VkBufferCreateInfo & create_info, const VkMemoryPropertyFlags & memory_flags)
Creates underlying handles and binds a memory region from the allocator subsystem, but takes a VkBufferCreatInfo structure containing all the relevant required setup information.
Definition at line 55 of file BufferDeprecated.cpp.
References createInfo, dataSize, handle, memoryAllocation, parent, vpr::AllocationRequirements::preferredFlags, vpr::AllocationRequirements::privateMemory, vpr::AllocationRequirements::requiredFlags, setMappedMemoryRange(), vpr::Allocation::Size, size, and VkAssert.
{
         createInfo = info;
         dataSize = info.size;
         AllocationRequirements reqs;
         reqs.preferredFlags = 0;
         reqs.privateMemory = false;
         reqs.requiredFlags = memory_flags;
         VkResult result = parent->GetAllocator()->CreateBuffer(&handle, &createInfo, reqs, memoryAllocation);
         VkAssert(result);
         size = memoryAllocation.Size;
         setMappedMemoryRange();
     }
CreateMemoryBarrier()
VkBufferMemoryBarrier vpr::Buffer::CreateMemoryBarrier (VkAccessFlags src, VkAccessFlags dst, uint32_t src_idx, uint32_t dst_idx, VkDeviceSize sz) const
Definition at line 160 of file BufferDeprecated.cpp.
References createInfo, handle, memoryAllocation, and vpr::Allocation::Offset().
{
         if ((src_idx != dst_idx) && (createInfo.sharingMode == VK_SHARING_MODE_EXCLUSIVE)) {
             LOG(WARNING) << "Created a memory barrier for a buffer with different source/destination queues, but the buffer has sharing mode VK_SHARING_MODE_EXCLUSIVE!";
         }
         return VkBufferMemoryBarrier{ VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER, nullptr, src, dst, src_idx, dst_idx,
             handle, memoryAllocation.Offset(), sz };
     }
CreateStagingBuffer() [1/2]
void vpr::Buffer::CreateStagingBuffer (const Device * dvc, const VkDeviceSize & size, VkBuffer & dest, Allocation & dest_memory_range) static
Creates a staging buffer of given size, using the given (hopefully not used) VkBuffer handle and updating the members of the given Allocation struct.
Adds both of those objects to a static pool, so that they can be cleaned up together independent of individual object scopes and lifetimes.
Definition at line 231 of file BufferDeprecated.cpp.
References vpr::AllocationRequirements::privateMemory, vpr::AllocationRequirements::requiredFlags, size, vpr::vk_buffer_create_info_base, and VkAssert.
{
         VkBufferCreateInfo create_info = vk_buffer_create_info_base;
         create_info.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
         create_info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
         create_info.size = size;
         AllocationRequirements alloc_reqs;
         alloc_reqs.privateMemory = false;
         alloc_reqs.requiredFlags = VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;
         VkResult result = dvc->GetAllocator()->CreateBuffer(&dest, &create_info, alloc_reqs, dest_memory_alloc);
         VkAssert(result);
     }
CreateStagingBuffer() [2/2]
std::unique_ptr< Buffer > vpr::Buffer::CreateStagingBuffer (const Device * dvc, void * data, const size_t data_size) static
Definition at line 247 of file BufferDeprecated.cpp.
References vpr::vk_buffer_create_info_base.
{
         VkBufferCreateInfo buffer_info = vk_buffer_create_info_base;
         buffer_info.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
         buffer_info.size = static_cast<VkDeviceSize>(data_size);
         buffer_info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
         std::unique_ptr<Buffer> result = std::make_unique<Buffer>(dvc);
         result->CreateBuffer(buffer_info, VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
         result->CopyToMapped(data, static_cast<VkDeviceSize>(data_size), 0);
         return std::move(result);
     }
createStagingBuffer()
void vpr::Buffer::createStagingBuffer (const VkDeviceSize & size, VkBuffer & staging_buffer, Allocation & dest_memory_range) protected
Definition at line 264 of file BufferDeprecated.cpp.
References parent, vpr::AllocationRequirements::privateMemory, vpr::AllocationRequirements::requiredFlags, size, and vpr::vk_buffer_create_info_base.
Referenced by CopyTo().
{
         VkBufferCreateInfo create_info = vk_buffer_create_info_base;
         create_info.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
         create_info.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
         create_info.size = staging_size;
         size = staging_size;
         AllocationRequirements alloc_reqs;
         alloc_reqs.privateMemory = false;
         alloc_reqs.requiredFlags = VK_MEMORY_PROPERTY_HOST_COHERENT_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;
         VkResult result = parent->GetAllocator()->CreateBuffer(&staging_buffer, &create_info, alloc_reqs, dest_memory_alloc);
     }
CreateView()
void vpr::Buffer::CreateView (const VkFormat format, const VkDeviceSize range, const VkDeviceSize offset)
Definition at line 170 of file BufferDeprecated.cpp.
References handle, parent, view, viewCreateInfo, and VkAssert.
{
         viewCreateInfo.format = format;
         viewCreateInfo.range = range;
         viewCreateInfo.offset = offset;
         viewCreateInfo.buffer = handle;
         VkResult result = vkCreateBufferView(parent->vkHandle(), &viewCreateInfo, nullptr, &view);
         VkAssert(result);
     }
Destroy()
void vpr::Buffer::Destroy ()
Destroys handles belonging to this object and attempts to free/unbind the memory region it used.
Definition at line 68 of file BufferDeprecated.cpp.
References handle, memoryAllocation, parent, and view.
Referenced by ~Buffer().
{
         if (handle != VK_NULL_HANDLE) {
             parent->GetAllocator()->DestroyBuffer(handle, memoryAllocation);
             handle = VK_NULL_HANDLE;
         }
         if (view != VK_NULL_HANDLE) {
             vkDestroyBufferView(parent->vkHandle(), view, nullptr);
         }
     }
Fill()
void vpr::Buffer::Fill (const VkCommandBuffer & cmd, const VkDeviceSize sz, const VkDeviceSize offset, const uint32_t value)
Fills buffer with given value.
Definition at line 147 of file BufferDeprecated.cpp.
References handle, and Size().
{
         #ifdef NDEBUG
         if (offset % 4 != 0) {
             LOG(ERROR) << "Supplied offset value to Buffer fill command is not a multiple of 4, and is as such not valid!";
         }
         if ((sz % 4 != 0) && (sz != Size())) {
             LOG(ERROR) << "Size of fill operation supplied to Buffer fill command is both not a multiple of 4 and wouldn't fill the whole buffer!";
         }
         #endif
         vkCmdFillBuffer(cmd, handle, offset, sz, value);
     }
Flush()
void vpr::Buffer::Flush ()
Definition at line 189 of file BufferDeprecated.cpp.
References mappedMemoryRange, parent, and VkAssert.
{
         VkResult result = vkFlushMappedMemoryRanges(parent->vkHandle(), 1, &mappedMemoryRange);
         VkAssert(result);
     }
GetDescriptor()
const VkDescriptorBufferInfo & vpr::Buffer::GetDescriptor () const noexcept
Definition at line 220 of file BufferDeprecated.cpp.
References descriptor, descriptorInfoSet, and setDescriptorInfo().
{
         if (!descriptorInfoSet) {
             setDescriptorInfo();
         }
         return descriptor;
     }
Invalidate()
void vpr::Buffer::Invalidate ()
Definition at line 194 of file BufferDeprecated.cpp.
References mappedMemoryRange, parent, and VkAssert.
{
         VkResult result = vkInvalidateMappedMemoryRanges(parent->vkHandle(), 1, &mappedMemoryRange);
         VkAssert(result);
     }
Map()
void vpr::Buffer::Map (const VkDeviceSize & offset = 0)
Definition at line 179 of file BufferDeprecated.cpp.
References mappedMemory, vpr::Allocation::Memory(), memoryAllocation, vpr::Allocation::Offset(), parent, vpr::Allocation::Size, and VkAssert.
Referenced by CopyToMapped().
{
         assert(offset < memoryAllocation.Size);
         VkResult result = vkMapMemory(parent->vkHandle(), memoryAllocation.Memory(), memoryAllocation.Offset() + offset, memoryAllocation.Size, 0, &mappedMemory);
         VkAssert(result);
     }
MappedMemoryRange()
const VkMappedMemoryRange & vpr::Buffer::MappedMemoryRange () const noexcept
Definition at line 211 of file BufferDeprecated.cpp.
References mappedMemoryRange.
{
         return mappedMemoryRange;
     }
operator=() [1/2]
Buffer& vpr::Buffer::operator= (const Buffer &) private delete
operator=() [2/2]
Buffer & vpr::Buffer::operator= (Buffer && other) noexcept
Definition at line 27 of file BufferDeprecated.cpp.
References createInfo, handle, memoryAllocation, parent, size, view, and viewCreateInfo.
{
         size = std::move(other.size);
         createInfo = std::move(other.createInfo);
         handle = std::move(other.handle);
         memoryAllocation = std::move(other.memoryAllocation);
         parent = std::move(other.parent);
         view = std::move(other.view);
         viewCreateInfo = std::move(other.viewCreateInfo);
         other.handle = VK_NULL_HANDLE;
         other.view = VK_NULL_HANDLE;
         return *this;
     }
setDescriptorInfo()
void vpr::Buffer::setDescriptorInfo () const protected noexcept
Definition at line 215 of file BufferDeprecated.cpp.
References dataSize, descriptor, descriptorInfoSet, and handle.
Referenced by GetDescriptor().
{
         descriptor = VkDescriptorBufferInfo{ handle, 0, dataSize };
         descriptorInfoSet = true;
     }
SetMappedMemory()
void vpr::Buffer::SetMappedMemory (void * mapping_destination)
Definition at line 260 of file BufferDeprecated.cpp.
References mappedMemory.
{
         mappedMemory = mapping_destination;
     }
setMappedMemoryRange()
void vpr::Buffer::setMappedMemoryRange () const protected
Definition at line 284 of file BufferDeprecated.cpp.
References mappedMemoryRange, vpr::Allocation::Memory(), memoryAllocation, vpr::Allocation::Offset(), and vpr::Allocation::Size.
Referenced by CreateBuffer().
{
         mappedMemoryRange = VkMappedMemoryRange{ VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE, nullptr,
             memoryAllocation.Memory(), memoryAllocation.Offset(), memoryAllocation.Size };
     }
Size()
VkDeviceSize vpr::Buffer::Size () const noexcept
Definition at line 227 of file BufferDeprecated.cpp.
References size.
Referenced by CopyTo(), CopyToMapped(), and Fill().
{
         return size;
     }
Unmap()
void vpr::Buffer::Unmap ()
Definition at line 185 of file BufferDeprecated.cpp.
References vpr::Allocation::Memory(), memoryAllocation, and parent.
Referenced by CopyToMapped().
{
         vkUnmapMemory(parent->vkHandle(), memoryAllocation.Memory());
     }
Update()
void vpr::Buffer::Update (const VkCommandBuffer & cmd, const VkDeviceSize & data_sz, const VkDeviceSize & offset, const void * data)
Used to update a sub-region of the buffer.
Cannot be called in an active renderpass.
Definition at line 143 of file BufferDeprecated.cpp.
References handle.
{
         vkCmdUpdateBuffer(cmd, handle, offset, data_sz, data);
     }
Usage()
VkBufferUsageFlags vpr::Buffer::Usage () const noexcept
Definition at line 280 of file BufferDeprecated.cpp.
References createInfo.
{
         return createInfo.usage;
     }
View()
const VkBufferView & vpr::Buffer::View () const noexcept
Definition at line 207 of file BufferDeprecated.cpp.
References view.
{
         return view;
     }
vkHandle() [1/2]
const VkBuffer & vpr::Buffer::vkHandle () const noexcept
Definition at line 199 of file BufferDeprecated.cpp.
References handle.
Referenced by CopyTo().
{
         return handle;
     }
vkHandle() [2/2]
VkBuffer & vpr::Buffer::vkHandle () noexcept
Definition at line 203 of file BufferDeprecated.cpp.
References handle.
{
         return handle;
     }
Member Data Documentation
createInfo
VkBufferCreateInfo vpr::Buffer::createInfo { } protected
Definition at line 115 of file BufferDeprecated.hpp.
Referenced by CreateBuffer(), CreateMemoryBarrier(), operator=(), and Usage().
dataSize
VkDeviceSize vpr::Buffer::dataSize { std::numeric_limits<VkDeviceSize>::max() } protected
Definition at line 120 of file BufferDeprecated.hpp.
Referenced by CreateBuffer(), and setDescriptorInfo().
descriptor
VkDescriptorBufferInfo vpr::Buffer::descriptor { VK_NULL_HANDLE, 0, 0 } mutable protected
Definition at line 125 of file BufferDeprecated.hpp.
Referenced by GetDescriptor(), and setDescriptorInfo().
descriptorInfoSet
bool vpr::Buffer::descriptorInfoSet { false } mutable protected
Definition at line 124 of file BufferDeprecated.hpp.
Referenced by GetDescriptor(), and setDescriptorInfo().
handle
VkBuffer vpr::Buffer::handle { VK_NULL_HANDLE } protected
Definition at line 113 of file BufferDeprecated.hpp.
Referenced by CopyTo(), CreateBuffer(), CreateMemoryBarrier(), CreateView(), Destroy(), Fill(), operator=(), setDescriptorInfo(), Update(), and vkHandle().
mappedMemory
void* vpr::Buffer::mappedMemory { nullptr } protected
Definition at line 121 of file BufferDeprecated.hpp.
Referenced by CopyToMapped(), Map(), and SetMappedMemory().
mappedMemoryRange
VkMappedMemoryRange vpr::Buffer::mappedMemoryRange { } mutable protected
Definition at line 117 of file BufferDeprecated.hpp.
Referenced by Flush(), Invalidate(), MappedMemoryRange(), and setMappedMemoryRange().
memoryAllocation
Allocation vpr::Buffer::memoryAllocation protected
Definition at line 118 of file BufferDeprecated.hpp.
Referenced by CreateBuffer(), CreateMemoryBarrier(), Destroy(), Map(), operator=(), setMappedMemoryRange(), and Unmap().
parent
VkDevice vpr::Buffer::parent { VK_NULL_HANDLE } protected
Definition at line 112 of file BufferDeprecated.hpp.
Referenced by CopyTo(), CreateBuffer(), createStagingBuffer(), CreateView(), Destroy(), Flush(), Invalidate(), Map(), operator=(), and Unmap().
size
VkDeviceSize vpr::Buffer::size { std::numeric_limits<VkDeviceSize>::max() } protected
Definition at line 119 of file BufferDeprecated.hpp.
Referenced by CopyToMapped(), CreateBuffer(), CreateStagingBuffer(), createStagingBuffer(), operator=(), and Size().
view
VkBufferView vpr::Buffer::view { VK_NULL_HANDLE } protected
Definition at line 114 of file BufferDeprecated.hpp.
Referenced by CreateView(), Destroy(), operator=(), and View().
viewCreateInfo
VkBufferViewCreateInfo vpr::Buffer::viewCreateInfo { VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO, nullptr, 0 } protected
Definition at line 116 of file BufferDeprecated.hpp.
Referenced by CreateView(), and operator=().
The documentation for this class was generated from the following files:
resource/include/BufferDeprecated.hpp
resource/src/BufferDeprecated.cpp