VulpesRender: el::base::LogDispatcher Class Reference
el::base::LogDispatcher Class Reference
Dispatches log messages.
#include <easylogging++.h>
Public Member Functions
LogDispatcher (bool proceed, LogMessage &&logMessage, base::DispatchAction dispatchAction)
void dispatch (void)
Private Attributes
bool m_proceed
LogMessage m_logMessage
base::DispatchAction m_dispatchAction
Detailed Description
Dispatches log messages.
Definition at line 2811 of file easylogging++.h.
Constructor & Destructor Documentation
LogDispatcher()
el::base::LogDispatcher::LogDispatcher (bool proceed, LogMessage && logMessage, base::DispatchAction dispatchAction) inline
Definition at line 2813 of file easylogging++.h.
                                                                                           :
     m_proceed(proceed),
     m_logMessage(std::move(logMessage)),
     m_dispatchAction(std::move(dispatchAction)) {
   }
Member Function Documentation
dispatch()
void el::base::LogDispatcher::dispatch (void)
Definition at line 2364 of file easylogging++.cc.
References ELPP, el::Callback< T >::enabled(), el::Callback< T >::handle(), el::base::None, el::LogDispatchData::setDispatchAction(), el::LogDispatchData::setLogMessage(), el::StrictLogFileSizeCheck, and el::base::TypedConfigurations::validateFileRolling().
Referenced by el::base::Writer::triggerDispatch().
{
   if (m_proceed && m_dispatchAction == base::DispatchAction::None) {
     m_proceed = false;
   }
   if (!m_proceed) {
     return;
   }
   base::threading::ScopedLock scopedLock(ELPP->lock());
   base::TypedConfigurations* tc = m_logMessage.logger()->m_typedConfigurations;
   if (ELPP->hasFlag(LoggingFlag::StrictLogFileSizeCheck)) {
     tc->validateFileRolling(m_logMessage.level(), ELPP->preRollOutCallback());
   }
   LogDispatchCallback* callback = nullptr;
   LogDispatchData data;
   for (const std::pair<std::string, base::type::LogDispatchCallbackPtr>& h
        : ELPP->m_logDispatchCallbacks) {
     callback = h.second.get();
     if (callback != nullptr && callback->enabled()) {
       data.setLogMessage(&m_logMessage);
       data.setDispatchAction(m_dispatchAction);
       callback->handle(&data);
     }
   }
 }
Member Data Documentation
m_dispatchAction
base::DispatchAction el::base::LogDispatcher::m_dispatchAction private
Definition at line 2824 of file easylogging++.h.
m_logMessage
LogMessage el::base::LogDispatcher::m_logMessage private
Definition at line 2823 of file easylogging++.h.
m_proceed
bool el::base::LogDispatcher::m_proceed private
Definition at line 2822 of file easylogging++.h.
The documentation for this class was generated from the following files:
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/include/util/easylogging++.h
C:/Users/kjones/Documents/SoftwareDev/VulpesSceneKit/third_party/vulpesrender/src/util/easylogging++.cc