VulpesRender: el::base::RegisteredHitCounters Class Reference
el::base::RegisteredHitCounters Class Reference abstract
Repository for hit counters used across the application.
#include <easylogging++.h>
Public Types
typedef RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >::iterator iterator
typedef RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >::const_iterator const_iterator
Public Member Functions
bool validateEveryN (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for every N, i.e, registers new if does not exist otherwise updates original one.
bool validateAfterN (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits >= N, i.e, registers new if does not exist otherwise updates original one.
bool validateNTimes (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits are <= n, i.e, registers new if does not exist otherwise updates original one.
const base::HitCounter * getCounter (const char *filename, base::type::LineNumber lineNumber)
Gets hit counter registered at specified position.
bool operator== (const AbstractRegistry< base::HitCounter, std::vector< base::HitCounter * > > &other)
bool operator!= (const AbstractRegistry< base::HitCounter, std::vector< base::HitCounter * > > &other)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual std::vector< base::HitCounter * > & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const std::vector< base::HitCounter * > & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void unregister (base::HitCounter *&ptr) ELPP_FINAL
virtual void registerNew (base::HitCounter *ptr) ELPP_FINAL
base::HitCounter * get (const T &arg1, const T2 arg2)
Gets pointer from repository with speicifed arguments.
virtual void deepCopy (const AbstractRegistry< base::HitCounter, std::vector< base::HitCounter * > > &)=0
void reinitDeepCopy (const AbstractRegistry< base::HitCounter, std::vector< base::HitCounter * > > &sr)
Detailed Description
Repository for hit counters used across the application.
Definition at line 2171 of file easylogging++.h.
Member Typedef Documentation
const_iterator
typedef RegistryWithPred<base::HitCounter , base::HitCounter::Predicate >::const_iterator el::base::utils::RegistryWithPred< base::HitCounter , base::HitCounter::Predicate >::const_iterator inherited
Definition at line 1504 of file easylogging++.h.
iterator
typedef RegistryWithPred<base::HitCounter , base::HitCounter::Predicate >::iterator el::base::utils::RegistryWithPred< base::HitCounter , base::HitCounter::Predicate >::iterator inherited
Definition at line 1503 of file easylogging++.h.
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
begin()
virtual iterator el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::begin (void) inline virtual inherited
Returns
Iterator pointer from start of repository
Definition at line 1365 of file easylogging++.h.
{
     return m_list.begin();
   }
cbegin()
virtual const_iterator el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::cbegin (void) const inline virtual inherited
Returns
Constant iterator pointer from start of repository
Definition at line 1376 of file easylogging++.h.
{
     return m_list.cbegin();
   }
cend()
virtual const_iterator el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::cend (void) const inline virtual inherited
Returns
End of repository
Definition at line 1381 of file easylogging++.h.
{
     return m_list.cend();
   }
deepCopy()
virtual void el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::deepCopy (const AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> > &) protected pure virtual inherited
empty()
virtual bool el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::empty (void) const inline virtual inherited
Returns
Whether or not repository is empty
Definition at line 1386 of file easylogging++.h.
{
     return m_list.empty();
   }
end()
virtual iterator el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::end (void) inline virtual inherited
Returns
Iterator pointer from end of repository
Definition at line 1370 of file easylogging++.h.
{
     return m_list.end();
   }
get()
base::HitCounter * el::base::utils::RegistryWithPred< base::HitCounter , base::HitCounter::Predicate >::get (const T & arg1, const T2 arg2) inline protected inherited
Gets pointer from repository with speicifed arguments.
Arguments are passed to predicate in order to validate pointer.
Definition at line 1571 of file easylogging++.h.
{
     iterator iter = std::find_if(this->list().begin(), this->list().end(), Pred(arg1, arg2));
     if (iter != this->list().end() && *iter != nullptr) {
       return *iter;
     }
     return nullptr;
   }
getCounter()
const base::HitCounter* el::base::RegisteredHitCounters::getCounter (const char * filename, base::type::LineNumber lineNumber) inline
Gets hit counter registered at specified position.
Definition at line 2186 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     return get(filename, lineNumber);
   }
list() [1/2]
virtual std::vector< base::HitCounter *> & el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::list (void) inline virtual inherited
Returns underlying container by reference.
Definition at line 1396 of file easylogging++.h.
{
     return m_list;
   }
list() [2/2]
virtual const std::vector< base::HitCounter *> & el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::list (void) const inline virtual inherited
Returns underlying container by constant reference.
Definition at line 1401 of file easylogging++.h.
{
     return m_list;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
operator!=()
bool el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::operator!= (const AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> > & other) inline inherited
Definition at line 1339 of file easylogging++.h.
{
     if (size() != other.size()) {
       return true;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return true;
       }
     }
     return false;
   }
operator==()
bool el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::operator== (const AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> > & other) inline inherited
Definition at line 1327 of file easylogging++.h.
{
     if (size() != other.size()) {
       return false;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return false;
       }
     }
     return true;
   }
registerNew()
virtual void el::base::utils::RegistryWithPred< base::HitCounter , base::HitCounter::Predicate >::registerNew (base::HitCounter * ptr) inline protected virtual inherited
Definition at line 1564 of file easylogging++.h.
{
     this->list().push_back(ptr);
   }
reinitDeepCopy()
void el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::reinitDeepCopy (const AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> > & sr) inline protected inherited
Definition at line 1410 of file easylogging++.h.
{
     unregisterAll();
     deepCopy(sr);
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
size()
virtual std::size_t el::base::utils::AbstractRegistry< base::HitCounter , std::vector< base::HitCounter *> >::size (void) const inline virtual inherited
Returns
Size of repository
Definition at line 1391 of file easylogging++.h.
{
     return m_list.size();
   }
unregister()
virtual void el::base::utils::RegistryWithPred< base::HitCounter , base::HitCounter::Predicate >::unregister (base::HitCounter *& ptr) inline protected virtual inherited
Definition at line 1549 of file easylogging++.h.
References el::base::utils::safeDelete().
{
     if (ptr) {
       iterator iter = this->begin();
       for (; iter != this->end(); ++iter) {
         if (ptr == *iter) {
           break;
         }
       }
       if (iter != this->end() && *iter != nullptr) {
         this->list().erase(iter);
         base::utils::safeDelete(*iter);
       }
     }
   }
unregisterAll()
virtual void el::base::utils::RegistryWithPred< base::HitCounter , base::HitCounter::Predicate >::unregisterAll (void) inline protected virtual inherited
Unregisters all the pointers from current repository.
Implements el::base::utils::AbstractRegistry< base::HitCounter, std::vector< base::HitCounter *> >.
Definition at line 1540 of file easylogging++.h.
References el::base::utils::safeDelete().
{
     if (!this->empty()) {
       for (auto&& curr : this->list()) {
         base::utils::safeDelete(curr);
       }
       this->list().clear();
     }
   }
validateAfterN()
bool el::base::RegisteredHitCounters::validateAfterN (const char * filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits >= N, i.e, registers new if does not exist otherwise updates original one.
Returns
True if validation resulted in triggering hit. Meaning logs should be written everytime true is returned
Definition at line 1777 of file easylogging++.cc.
References el::base::HitCounter::hitCounts(), and el::base::HitCounter::increment().
{
   base::threading::ScopedLock scopedLock(lock());
   base::HitCounter* counter = get(filename, lineNumber);
   if (counter == nullptr) {
     registerNew(counter = new base::HitCounter(filename, lineNumber));
   }
   // Do not use validateHitCounts here since we do not want to reset counter here
   // Note the >= instead of > because we are incrementing
   // after this check
   if (counter->hitCounts() >= n)
     return true;
   counter->increment();
   return false;
 }
validateEveryN()
bool el::base::RegisteredHitCounters::validateEveryN (const char * filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for every N, i.e, registers new if does not exist otherwise updates original one.
Returns
True if validation resulted in triggering hit. Meaning logs should be written everytime true is returned
Definition at line 1764 of file easylogging++.cc.
References el::base::HitCounter::hitCounts(), and el::base::HitCounter::validateHitCounts().
{
   base::threading::ScopedLock scopedLock(lock());
   base::HitCounter* counter = get(filename, lineNumber);
   if (counter == nullptr) {
     registerNew(counter = new base::HitCounter(filename, lineNumber));
   }
   counter->validateHitCounts(n);
   bool result = (n >= 1 && counter->hitCounts() != 0 && counter->hitCounts() % n == 0);
   return result;
 }
validateNTimes()
bool el::base::RegisteredHitCounters::validateNTimes (const char * filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits are <= n, i.e, registers new if does not exist otherwise updates original one.
Returns
True if validation resulted in triggering hit. Meaning logs should be written everytime true is returned
Definition at line 1794 of file easylogging++.cc.
References el::base::HitCounter::hitCounts(), and el::base::HitCounter::increment().
{
   base::threading::ScopedLock scopedLock(lock());
   base::HitCounter* counter = get(filename, lineNumber);
   if (counter == nullptr) {
     registerNew(counter = new base::HitCounter(filename, lineNumber));
   }
   counter->increment();
   // Do not use validateHitCounts here since we do not want to reset counter here
   if (counter->hitCounts() <= n)
     return true;
   return false;
 }
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc