VulpesRender: vpr::PipelineCache Class Reference
vpr::PipelineCache Class Reference
Resources
A PipelineCache is a wrapper around a VkPipelineCache that takes care of several important details that are otherwise difficult to handle: saving and loading pipeline cache data from a file, verifying integrity of pipeline cache files, and cleaning up / repairing old, unused, and outdated pipeline cache files.
#include <PipelineCache.hpp>
Public Member Functions
PipelineCache (const Device *parent, const size_t hash_id)
Creates a pipeline cache, or loads a pre-existing one from file.
~PipelineCache ()
PipelineCache (PipelineCache &&other) noexcept
PipelineCache & operator= (PipelineCache &&other) noexcept
bool Verify (const int8_t *cache_header) const
Takes a pipeline cache header and checks it for validity.
void LoadCacheFromFile (const char *filename)
const VkPipelineCache & vkHandle () const
Private Member Functions
PipelineCache (const PipelineCache &other)=delete
PipelineCache & operator= (const PipelineCache &other)=delete
VkResult saveToFile () const
Private Attributes
std::string filename
size_t hashID
const Device * parent
VkPipelineCache handle
VkPipelineCacheCreateInfo createInfo
Detailed Description
A PipelineCache is a wrapper around a VkPipelineCache that takes care of several important details that are otherwise difficult to handle: saving and loading pipeline cache data from a file, verifying integrity of pipeline cache files, and cleaning up / repairing old, unused, and outdated pipeline cache files.
This object can be used to increase the speed of creating graphics pipeline objects, and is especially useful for pipelines that are:
very complex and slow to create/recreate after a swapchain recreation
frequently created as part of other objects
for use with dynamic shader editing and recompiliation, which requires a pipeline recreation to propagate changes
Definition at line 19 of file PipelineCache.hpp.
Constructor & Destructor Documentation
PipelineCache() [1/3]
vpr::PipelineCache::PipelineCache (const PipelineCache & other) private delete
PipelineCache() [2/3]
vpr::PipelineCache::PipelineCache (const Device * parent, const size_t hash_id)
Creates a pipeline cache, or loads a pre-existing one from file.
Parameters
hash_id This can be nicely setting by using typeid(owning_type).hash_code(), so that types all share a pipline cache and there is still a unique identifier per type.
Definition at line 14 of file PipelineCache.cpp.
References createInfo, filename, handle, LoadCacheFromFile(), LOG, parent, VkAssert, and vpr::Device::vkHandle().
                                                                             : parent(_parent), createInfo(base_create_info),
         hashID(std::move(hash_id)), handle(VK_NULL_HANDLE) {
         std::string cache_dir = std::string("./rsrc/shader_cache/");
 #ifdef USE_EXPERIMENTAL_FILESYSTEM
         std::experimental::filesystem::path cache_path(cache_dir);
         if (!std::experimental::filesystem::exists(cache_path)) {
             LOG(INFO) << "Shader cache path didn't exist, creating...";
             std::experimental::filesystem::create_directories(cache_path);
         }
 #endif
         std::string fname = cache_dir + std::to_string(hash_id) + std::string(".vkdat");
         filename = fname;
         // Attempts to load cache from file: if failed, doesn't matter much.
         LoadCacheFromFile(fname.c_str());
         VkResult result = vkCreatePipelineCache(parent->vkHandle(), &createInfo, nullptr, &handle);
         VkAssert(result);
     }
~PipelineCache()
vpr::PipelineCache::~PipelineCache ()
Definition at line 39 of file PipelineCache.cpp.
References handle, parent, saveToFile(), VkAssert, and vpr::Device::vkHandle().
{
         if (handle != VK_NULL_HANDLE) {
             VkResult saved = saveToFile();
             VkAssert(saved);
             vkDestroyPipelineCache(parent->vkHandle(), handle, nullptr);
         }
     }
PipelineCache() [3/3]
vpr::PipelineCache::PipelineCache (PipelineCache && other) noexcept
Definition at line 47 of file PipelineCache.cpp.
                                                                : parent(std::move(other.parent)), createInfo(std::move(other.createInfo)),
         hashID(std::move(other.hashID)), handle(std::move(other.handle)), filename(std::move(other.filename)) { other.handle = VK_NULL_HANDLE; }
Member Function Documentation
LoadCacheFromFile()
void vpr::PipelineCache::LoadCacheFromFile (const char * filename)
Definition at line 137 of file PipelineCache.cpp.
References createInfo, hashID, LOG, and Verify().
Referenced by PipelineCache().
{
         /*
         check for pre-existing cache file.
         */
         std::ifstream cache(_filename, std::ios::in);
         if (cache) {
             // get header (4 uint32_t, 16 int8_t) = (32 int8_t)
             std::vector<int8_t> header(64);
             cache.get(reinterpret_cast<char*>(header.data()), 64);
             // Check to see if header data matches current device.
             if (Verify(header.data())) {
                 LOG(INFO) << "Found valid pipeline cache data with ID # " << std::to_string(hashID) << " .";
                 std::string cache_str((std::istreambuf_iterator<char>(cache)), std::istreambuf_iterator<char>());
                 uint32_t cache_size = static_cast<uint32_t>(cache_str.size() * sizeof(char));
                 createInfo.initialDataSize = cache_size;
                 createInfo.pInitialData = cache_str.data();
             }
             else {
                 LOG(INFO) << "Pre-existing cache file isn't valid: creating new pipeline cache.";
                 createInfo.initialDataSize = 0;
                 createInfo.pInitialData = nullptr;
             }
         }
     }
operator=() [1/2]
PipelineCache& vpr::PipelineCache::operator= (const PipelineCache & other) private delete
operator=() [2/2]
PipelineCache & vpr::PipelineCache::operator= (PipelineCache && other) noexcept
Definition at line 50 of file PipelineCache.cpp.
References createInfo, filename, handle, hashID, and parent.
{
         parent = std::move(other.parent);
         createInfo = std::move(other.createInfo);
         hashID = std::move(other.hashID);
         handle = std::move(other.handle);
         other.handle = VK_NULL_HANDLE;
         filename = std::move(other.filename);
         return *this;
     }
saveToFile()
VkResult vpr::PipelineCache::saveToFile () const private
Definition at line 60 of file PipelineCache.cpp.
References filename, handle, LOG, parent, VkAssert, and vpr::Device::vkHandle().
Referenced by ~PipelineCache().
{
         VkResult result = VK_SUCCESS;
         size_t cache_size;
         if (!parent) {
             LOG(ERROR) << "Attempted to delete/save a non-existent cache!";
             return VK_ERROR_DEVICE_LOST;
         }
         // works like enumerate calls: get size first, then use size to get data.
         result = vkGetPipelineCacheData(parent->vkHandle(), handle, &cache_size, nullptr);
         VkAssert(result);
         if (cache_size != 0) {
             try {
                 std::ofstream file(filename, std::ios::out | std::ios::trunc);
                 void* cache_data;
                 cache_data = malloc(cache_size);
                 result = vkGetPipelineCacheData(parent->vkHandle(), handle, &cache_size, cache_data);
                 VkAssert(result);
                 file.write(reinterpret_cast<const char*>(cache_data), cache_size);
                 file.close();
                 free(cache_data);
                 LOG(INFO) << "Saved pipeline cache data to file successfully";
                 return VK_SUCCESS;
             }
             catch (std::ofstream::failure&) {
                 LOG(WARNING) << "Saving of pipeline cache to file failed with unindentified exception in std::ofstream.";
                 return VK_ERROR_VALIDATION_FAILED_EXT;
             }
         }
         else {
             LOG(WARNING) << "Cache data was reported empty by Vulkan: errors possible.";
             return VK_SUCCESS;
         }
     }
Verify()
bool vpr::PipelineCache::Verify (const int8_t * cache_header) const
Takes a pipeline cache header and checks it for validity.
Definition at line 104 of file PipelineCache.cpp.
References vpr::Device::GetPhysicalDevice(), LOG, and parent.
Referenced by LoadCacheFromFile().
{
         const uint32_t* header = reinterpret_cast<const uint32_t*>(cache_header);
         if (header[0] != 32) {
             return false;
         }
         if (header[1] != static_cast<uint32_t>(VK_PIPELINE_CACHE_HEADER_VERSION_ONE)) {
             return false;
         }
         auto& physical_device = parent->GetPhysicalDevice();
         if (header[2] != physical_device.GetProperties().vendorID) {
             return false;
         }
         if (header[3] != physical_device.GetProperties().deviceID) {
             return false;
         }
         uint8_t cache_uuid[VK_UUID_SIZE] = {};
         memcpy(cache_uuid, cache_header + 16, VK_UUID_SIZE);
         if (memcmp(cache_uuid, physical_device.GetProperties().pipelineCacheUUID, sizeof(cache_uuid)) != 0) {
             LOG(INFO) << "Pipeline cache UUID incorrect, requires rebuilding.";
             return false;
         }
         return true;
     }
vkHandle()
const VkPipelineCache & vpr::PipelineCache::vkHandle () const
Definition at line 164 of file PipelineCache.cpp.
References handle.
{
         return handle;
     }
Member Data Documentation
createInfo
VkPipelineCacheCreateInfo vpr::PipelineCache::createInfo private
Definition at line 46 of file PipelineCache.hpp.
Referenced by LoadCacheFromFile(), operator=(), and PipelineCache().
filename
std::string vpr::PipelineCache::filename private
Definition at line 41 of file PipelineCache.hpp.
Referenced by operator=(), PipelineCache(), and saveToFile().
handle
VkPipelineCache vpr::PipelineCache::handle private
Definition at line 45 of file PipelineCache.hpp.
Referenced by operator=(), PipelineCache(), saveToFile(), vkHandle(), and ~PipelineCache().
hashID
size_t vpr::PipelineCache::hashID private
Definition at line 43 of file PipelineCache.hpp.
Referenced by LoadCacheFromFile(), and operator=().
parent
const Device* vpr::PipelineCache::parent private
Definition at line 44 of file PipelineCache.hpp.
Referenced by operator=(), PipelineCache(), saveToFile(), Verify(), and ~PipelineCache().
The documentation for this class was generated from the following files:
include/resource/PipelineCache.hpp
src/resource/PipelineCache.cpp