VulpesRender: vpr::GraphicsPipeline Class Reference
vpr::GraphicsPipeline Class Reference
Rendering
The GraphicsPipeline object is an RAII wrapper around a vkGraphicsPipeline object, handling construction and destruction alone.
#include <GraphicsPipeline.hpp>
Public Member Functions
GraphicsPipeline (const Device *parent, VkGraphicsPipelineCreateInfo create_info, VkPipeline handle)
GraphicsPipeline (const Device *parent)
~GraphicsPipeline ()
GraphicsPipeline (GraphicsPipeline &&other) noexcept
GraphicsPipeline & operator= (GraphicsPipeline &&other) noexcept
void Init (VkGraphicsPipelineCreateInfo &create_info, const VkPipelineCache &cache=VK_NULL_HANDLE)
void Destroy ()
const VkPipeline & vkHandle () const noexcept
Private Member Functions
GraphicsPipeline (const GraphicsPipeline &)=delete
GraphicsPipeline & operator= (const GraphicsPipeline &)=delete
Private Attributes
const VkAllocationCallbacks * allocators = nullptr
const Device * parent
VkPipeline handle
VkGraphicsPipelineCreateInfo createInfo
Detailed Description
The GraphicsPipeline object is an RAII wrapper around a vkGraphicsPipeline object, handling construction and destruction alone.
The GraphicsPipelineInfo structure is, truthfully, much more important and much complex than this class is.
Definition at line 59 of file GraphicsPipeline.hpp.
Constructor & Destructor Documentation
GraphicsPipeline() [1/4]
vpr::GraphicsPipeline::GraphicsPipeline (const GraphicsPipeline &) private delete
Referenced by vpr::CreateMultiple().
GraphicsPipeline() [2/4]
vpr::GraphicsPipeline::GraphicsPipeline (const Device * parent, VkGraphicsPipelineCreateInfo create_info, VkPipeline handle)
Definition at line 23 of file GraphicsPipeline.cpp.
 : parent(_d), createInfo(std::move(info)), handle(_handle) {}
GraphicsPipeline() [3/4]
vpr::GraphicsPipeline::GraphicsPipeline (const Device * parent)
Definition at line 25 of file GraphicsPipeline.cpp.
 : parent(_parent), createInfo(vk_graphics_pipeline_create_info_base) {}
~GraphicsPipeline()
vpr::GraphicsPipeline::~GraphicsPipeline ()
Definition at line 39 of file GraphicsPipeline.cpp.
References Destroy().
{
         Destroy();
     }
GraphicsPipeline() [4/4]
vpr::GraphicsPipeline::GraphicsPipeline (GraphicsPipeline && other) noexcept
Definition at line 27 of file GraphicsPipeline.cpp.
                                                                         : parent(std::move(other.parent)), createInfo(std::move(other.createInfo)), handle(std::move(other.handle)) {
         other.handle = VK_NULL_HANDLE;
     }
Member Function Documentation
Destroy()
void vpr::GraphicsPipeline::Destroy ()
Definition at line 49 of file GraphicsPipeline.cpp.
References allocators, handle, parent, and vpr::Device::vkHandle().
Referenced by ~GraphicsPipeline().
{
         if(handle != VK_NULL_HANDLE) {
             vkDestroyPipeline(parent->vkHandle(), handle, allocators);
         }
     }
Init()
void vpr::GraphicsPipeline::Init (VkGraphicsPipelineCreateInfo & create_info, const VkPipelineCache & cache = VK_NULL_HANDLE)
Definition at line 43 of file GraphicsPipeline.cpp.
References createInfo, handle, parent, VkAssert, and vpr::Device::vkHandle().
{
         VkResult result = vkCreateGraphicsPipelines(parent->vkHandle(), cache, 1, &create_info, nullptr, &handle);
         VkAssert(result);
         createInfo = std::move(create_info);
     }
operator=() [1/2]
GraphicsPipeline& vpr::GraphicsPipeline::operator= (const GraphicsPipeline &) private delete
operator=() [2/2]
GraphicsPipeline & vpr::GraphicsPipeline::operator= (GraphicsPipeline && other) noexcept
Definition at line 31 of file GraphicsPipeline.cpp.
References createInfo, handle, and parent.
{
         parent = std::move(other.parent);
         createInfo = std::move(other.createInfo);
         handle = std::move(other.handle);
         other.handle = VK_NULL_HANDLE;
         return *this;
     }
vkHandle()
const VkPipeline & vpr::GraphicsPipeline::vkHandle () const noexcept
Definition at line 55 of file GraphicsPipeline.cpp.
References handle.
{
         return handle;
     }
Member Data Documentation
allocators
const VkAllocationCallbacks* vpr::GraphicsPipeline::allocators = nullptr private
Definition at line 77 of file GraphicsPipeline.hpp.
Referenced by Destroy().
createInfo
VkGraphicsPipelineCreateInfo vpr::GraphicsPipeline::createInfo private
Definition at line 80 of file GraphicsPipeline.hpp.
Referenced by Init(), and operator=().
handle
VkPipeline vpr::GraphicsPipeline::handle private
Definition at line 79 of file GraphicsPipeline.hpp.
Referenced by Destroy(), Init(), operator=(), and vkHandle().
parent
const Device* vpr::GraphicsPipeline::parent private
Definition at line 78 of file GraphicsPipeline.hpp.
Referenced by Destroy(), Init(), and operator=().
The documentation for this class was generated from the following files:
include/render/GraphicsPipeline.hpp
src/render/GraphicsPipeline.cpp