VulpesRender: el::base::RegisteredLoggers Class Reference
el::base::RegisteredLoggers Class Reference abstract
Loggers repository.
#include <easylogging++.h>
Public Types
typedef Registry< Logger, std::string >::iterator iterator
typedef Registry< Logger, std::string >::const_iterator const_iterator
Public Member Functions
RegisteredLoggers (const LogBuilderPtr &defaultLogBuilder)
virtual ~RegisteredLoggers (void)
void setDefaultConfigurations (const Configurations &configurations)
Configurations * defaultConfigurations (void)
Logger * get (const std::string &id, bool forceCreation=true)
template<typename T >
bool installLoggerRegistrationCallback (const std::string &id)
template<typename T >
void uninstallLoggerRegistrationCallback (const std::string &id)
template<typename T >
T * loggerRegistrationCallback (const std::string &id)
bool remove (const std::string &id)
bool has (const std::string &id)
void unregister (Logger *&logger)
base::LogStreamsReferenceMap * logStreamsReference (void)
void flushAll (void)
void setDefaultLogBuilder (LogBuilderPtr &logBuilderPtr)
bool operator== (const AbstractRegistry< Logger, std::map< std::string, Logger * > > &other)
bool operator!= (const AbstractRegistry< Logger, std::map< std::string, Logger * > > &other)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual std::map< std::string, Logger * > & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const std::map< std::string, Logger * > & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void registerNew (const std::string &uniqKey, Logger *ptr) ELPP_FINAL
Registers new registry to repository.
void unregister (const std::string &uniqKey)
Unregisters single entry mapped to specified unique key.
Logger * get (const std::string &uniqKey)
Gets pointer from repository. If none found, nullptr is returned.
virtual void deepCopy (const AbstractRegistry< Logger, std::map< std::string, Logger * > > &)=0
void reinitDeepCopy (const AbstractRegistry< Logger, std::map< std::string, Logger * > > &sr)
Private Member Functions
void unsafeFlushAll (void)
Private Attributes
LogBuilderPtr m_defaultLogBuilder
Configurations m_defaultConfigurations
base::LogStreamsReferenceMap m_logStreamsReference
std::map< std::string, base::type::LoggerRegistrationCallbackPtr > m_loggerRegistrationCallbacks
Friends
class el::base::Storage
Detailed Description
Loggers repository.
Definition at line 2395 of file easylogging++.h.
Member Typedef Documentation
const_iterator
typedef Registry<Logger , std::string >::const_iterator el::base::utils::Registry< Logger , std::string >::const_iterator inherited
Definition at line 1428 of file easylogging++.h.
iterator
typedef Registry<Logger , std::string >::iterator el::base::utils::Registry< Logger , std::string >::iterator inherited
Definition at line 1427 of file easylogging++.h.
Constructor & Destructor Documentation
RegisteredLoggers()
el::base::RegisteredLoggers::RegisteredLoggers (const LogBuilderPtr & defaultLogBuilder) explicit
Definition at line 1809 of file easylogging++.cc.
References m_defaultConfigurations, and el::Configurations::setToDefault().
                                                                            :
   m_defaultLogBuilder(defaultLogBuilder) {
   m_defaultConfigurations.setToDefault();
 }
~RegisteredLoggers()
virtual el::base::RegisteredLoggers::~RegisteredLoggers (void) inline virtual
Definition at line 2399 of file easylogging++.h.
{
     unsafeFlushAll();
   }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
begin()
virtual iterator el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::begin (void) inline virtual inherited
Returns
Iterator pointer from start of repository
Definition at line 1365 of file easylogging++.h.
{
     return m_list.begin();
   }
cbegin()
virtual const_iterator el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::cbegin (void) const inline virtual inherited
Returns
Constant iterator pointer from start of repository
Definition at line 1376 of file easylogging++.h.
{
     return m_list.cbegin();
   }
cend()
virtual const_iterator el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::cend (void) const inline virtual inherited
Returns
End of repository
Definition at line 1381 of file easylogging++.h.
{
     return m_list.cend();
   }
deepCopy()
virtual void el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::deepCopy (const AbstractRegistry< Logger , std::map< std::string, Logger *> > &) protected pure virtual inherited
defaultConfigurations()
Configurations* el::base::RegisteredLoggers::defaultConfigurations (void) inline
Definition at line 2408 of file easylogging++.h.
{
     return &m_defaultConfigurations;
   }
empty()
virtual bool el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::empty (void) const inline virtual inherited
Returns
Whether or not repository is empty
Definition at line 1386 of file easylogging++.h.
{
     return m_list.empty();
   }
end()
virtual iterator el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::end (void) inline virtual inherited
Returns
Iterator pointer from end of repository
Definition at line 1370 of file easylogging++.h.
{
     return m_list.end();
   }
flushAll()
void el::base::RegisteredLoggers::flushAll (void) inline
Definition at line 2445 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     unsafeFlushAll();
   }
get() [1/2]
Logger * el::base::utils::Registry< Logger , std::string >::get (const std::string & uniqKey) inline protected inherited
Gets pointer from repository. If none found, nullptr is returned.
Definition at line 1481 of file easylogging++.h.
{
     iterator it = this->list().find(uniqKey);
     return it == this->list().end()
            ? nullptr
            : it->second;
   }
get() [2/2]
Logger * el::base::RegisteredLoggers::get (const std::string & id, bool forceCreation = true)
Definition at line 1814 of file easylogging++.cc.
References ELPP_ASSERT, el::Callback< T >::enabled(), el::base::utils::Registry< T_Ptr, T_Key >::get(), el::Callback< T >::handle(), el::Logger::isValidId(), el::base::threading::ThreadSafe::lock(), m_defaultConfigurations, m_defaultLogBuilder, el::Logger::m_logBuilder, m_loggerRegistrationCallbacks, m_logStreamsReference, and el::base::utils::Registry< Logger, std::string >::registerNew().
{
   base::threading::ScopedLock scopedLock(lock());
   Logger* logger_ = base::utils::Registry<Logger, std::string>::get(id);
   if (logger_ == nullptr && forceCreation) {
     bool validId = Logger::isValidId(id);
     if (!validId) {
       ELPP_ASSERT(validId, "Invalid logger ID [" << id << "]. Not registering this logger.");
       return nullptr;
     }
     logger_ = new Logger(id, m_defaultConfigurations, &m_logStreamsReference);
     logger_->m_logBuilder = m_defaultLogBuilder;
     registerNew(id, logger_);
     LoggerRegistrationCallback* callback = nullptr;
     for (const std::pair<std::string, base::type::LoggerRegistrationCallbackPtr>& h
          : m_loggerRegistrationCallbacks) {
       callback = h.second.get();
       if (callback != nullptr && callback->enabled()) {
         callback->handle(logger_);
       }
     }
   }
   return logger_;
 }
has()
bool el::base::RegisteredLoggers::has (const std::string & id) inline
Definition at line 2432 of file easylogging++.h.
{
     return get(id, false) != nullptr;
   }
installLoggerRegistrationCallback()
template<typename T > bool el::base::RegisteredLoggers::installLoggerRegistrationCallback (const std::string & id) inline
Definition at line 2415 of file easylogging++.h.
{
     return base::utils::Utils::installCallback<T, base::type::LoggerRegistrationCallbackPtr>(id,
            &m_loggerRegistrationCallbacks);
   }
list() [1/2]
virtual std::map< std::string, Logger *> & el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::list (void) inline virtual inherited
Returns underlying container by reference.
Definition at line 1396 of file easylogging++.h.
{
     return m_list;
   }
list() [2/2]
virtual const std::map< std::string, Logger *> & el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::list (void) const inline virtual inherited
Returns underlying container by constant reference.
Definition at line 1401 of file easylogging++.h.
{
     return m_list;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
loggerRegistrationCallback()
template<typename T > T* el::base::RegisteredLoggers::loggerRegistrationCallback (const std::string & id) inline
Definition at line 2426 of file easylogging++.h.
{
     return base::utils::Utils::callback<T, base::type::LoggerRegistrationCallbackPtr>(id, &m_loggerRegistrationCallbacks);
   }
logStreamsReference()
base::LogStreamsReferenceMap* el::base::RegisteredLoggers::logStreamsReference (void) inline
Definition at line 2441 of file easylogging++.h.
{
     return &m_logStreamsReference;
   }
operator!=()
bool el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::operator!= (const AbstractRegistry< Logger , std::map< std::string, Logger *> > & other) inline inherited
Definition at line 1339 of file easylogging++.h.
{
     if (size() != other.size()) {
       return true;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return true;
       }
     }
     return false;
   }
operator==()
bool el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::operator== (const AbstractRegistry< Logger , std::map< std::string, Logger *> > & other) inline inherited
Definition at line 1327 of file easylogging++.h.
{
     if (size() != other.size()) {
       return false;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return false;
       }
     }
     return true;
   }
registerNew()
virtual void el::base::utils::Registry< Logger , std::string >::registerNew (const std::string & uniqKey, Logger * ptr) inline protected virtual inherited
Registers new registry to repository.
Definition at line 1466 of file easylogging++.h.
Referenced by get().
{
     unregister(uniqKey);
     this->list().insert(std::make_pair(uniqKey, ptr));
   }
reinitDeepCopy()
void el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::reinitDeepCopy (const AbstractRegistry< Logger , std::map< std::string, Logger *> > & sr) inline protected inherited
Definition at line 1410 of file easylogging++.h.
{
     unregisterAll();
     deepCopy(sr);
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
remove()
bool el::base::RegisteredLoggers::remove (const std::string & id)
Definition at line 1838 of file easylogging++.cc.
References el::base::utils::Registry< T_Ptr, T_Key >::get(), el::base::consts::kDefaultLoggerId, and unregister().
{
   if (id == base::consts::kDefaultLoggerId) {
     return false;
   }
   Logger* logger = base::utils::Registry<Logger, std::string>::get(id);
   if (logger != nullptr) {
     unregister(logger);
   }
   return true;
 }
setDefaultConfigurations()
void el::base::RegisteredLoggers::setDefaultConfigurations (const Configurations & configurations) inline
Definition at line 2403 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     m_defaultConfigurations.setFromBase(const_cast<Configurations*>(&configurations));
   }
setDefaultLogBuilder()
void el::base::RegisteredLoggers::setDefaultLogBuilder (LogBuilderPtr & logBuilderPtr) inline
Definition at line 2450 of file easylogging++.h.
{
     base::threading::ScopedLock scopedLock(lock());
     m_defaultLogBuilder = logBuilderPtr;
   }
size()
virtual std::size_t el::base::utils::AbstractRegistry< Logger , std::map< std::string, Logger *> >::size (void) const inline virtual inherited
Returns
Size of repository
Definition at line 1391 of file easylogging++.h.
{
     return m_list.size();
   }
uninstallLoggerRegistrationCallback()
template<typename T > void el::base::RegisteredLoggers::uninstallLoggerRegistrationCallback (const std::string & id) inline
Definition at line 2421 of file easylogging++.h.
{
     base::utils::Utils::uninstallCallback<T, base::type::LoggerRegistrationCallbackPtr>(id, &m_loggerRegistrationCallbacks);
   }
unregister() [1/2]
void el::base::utils::Registry< Logger , std::string >::unregister (const std::string & uniqKey) inline protected inherited
Unregisters single entry mapped to specified unique key.
Definition at line 1472 of file easylogging++.h.
References el::base::utils::safeDelete().
{
     T_Ptr* existing = get(uniqKey);
     if (existing != nullptr) {
       this->list().erase(uniqKey);
       base::utils::safeDelete(existing);
     }
   }
unregister() [2/2]
void el::base::RegisteredLoggers::unregister (Logger *& logger) inline
Definition at line 2436 of file easylogging++.h.
References el::Logger::id(), and el::base::utils::Registry< T_Ptr, T_Key >::unregister().
Referenced by remove().
{
     base::threading::ScopedLock scopedLock(lock());
     base::utils::Registry<Logger, std::string>::unregister(logger->id());
   }
unregisterAll()
virtual void el::base::utils::Registry< Logger , std::string >::unregisterAll (void) inline protected virtual inherited
Unregisters all the pointers from current repository.
Implements el::base::utils::AbstractRegistry< Logger, std::map< std::string, Logger *> >.
Definition at line 1456 of file easylogging++.h.
References el::base::utils::safeDelete().
{
     if (!this->empty()) {
       for (auto&& curr : this->list()) {
         base::utils::safeDelete(curr.second);
       }
       this->list().clear();
     }
   }
unsafeFlushAll()
void el::base::RegisteredLoggers::unsafeFlushAll (void) private
Definition at line 1849 of file easylogging++.cc.
References ELPP_INTERNAL_INFO, and m_logStreamsReference.
{
   ELPP_INTERNAL_INFO(1, "Flushing all log files");
   for (base::LogStreamsReferenceMap::iterator it = m_logStreamsReference.begin();
        it != m_logStreamsReference.end(); ++it) {
     if (it->second.get() == nullptr) continue;
     it->second->flush();
   }
 }
Friends And Related Function Documentation
el::base::Storage
friend class el::base::Storage friend
Definition at line 2460 of file easylogging++.h.
Member Data Documentation
m_defaultConfigurations
Configurations el::base::RegisteredLoggers::m_defaultConfigurations private
Definition at line 2457 of file easylogging++.h.
Referenced by get(), and RegisteredLoggers().
m_defaultLogBuilder
LogBuilderPtr el::base::RegisteredLoggers::m_defaultLogBuilder private
Definition at line 2456 of file easylogging++.h.
Referenced by get().
m_loggerRegistrationCallbacks
std::map<std::string, base::type::LoggerRegistrationCallbackPtr> el::base::RegisteredLoggers::m_loggerRegistrationCallbacks private
Definition at line 2459 of file easylogging++.h.
Referenced by get().
m_logStreamsReference
base::LogStreamsReferenceMap el::base::RegisteredLoggers::m_logStreamsReference private
Definition at line 2458 of file easylogging++.h.
Referenced by get(), and unsafeFlushAll().
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc