VulpesRender: el::base::utils::AbstractRegistry< T_Ptr, Container > Class Template Reference
el::base::utils::AbstractRegistry< T_Ptr, Container > Class Template Reference abstract
Abstract registry (aka repository) that provides basic interface for pointer repository specified by T_Ptr type.
#include <easylogging++.h>
Public Types
typedef Container::iterator iterator
typedef Container::const_iterator const_iterator
Public Member Functions
AbstractRegistry (void)
Default constructor.
AbstractRegistry (AbstractRegistry &&sr)
Move constructor that is useful for base classes.
bool operator== (const AbstractRegistry< T_Ptr, Container > &other)
bool operator!= (const AbstractRegistry< T_Ptr, Container > &other)
AbstractRegistry & operator= (AbstractRegistry &&sr)
Assignment move operator.
virtual ~AbstractRegistry (void)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual Container & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const Container & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void unregisterAll (void)=0
Unregisters all the pointers from current repository.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void deepCopy (const AbstractRegistry< T_Ptr, Container > &)=0
void reinitDeepCopy (const AbstractRegistry< T_Ptr, Container > &sr)
Private Attributes
Container m_list
Detailed Description
template<typename T_Ptr, typename Container>
class el::base::utils::AbstractRegistry< T_Ptr, Container >
Abstract registry (aka repository) that provides basic interface for pointer repository specified by T_Ptr type.
Most of the functions are virtual final methods but anything implementing this abstract class should implement unregisterAll() and deepCopy(const AbstractRegistry<T_Ptr, Container>&) and write registerNew() method according to container and few more methods; get() to find element, unregister() to unregister single entry. Please note that this is thread-unsafe and should also implement thread-safety mechanisms in implementation.
Definition at line 1310 of file easylogging++.h.
Member Typedef Documentation
const_iterator
template<typename T_Ptr, typename Container> typedef Container::const_iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::const_iterator
Definition at line 1313 of file easylogging++.h.
iterator
template<typename T_Ptr, typename Container> typedef Container::iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::iterator
Definition at line 1312 of file easylogging++.h.
Constructor & Destructor Documentation
AbstractRegistry() [1/2]
template<typename T_Ptr, typename Container> el::base::utils::AbstractRegistry< T_Ptr, Container >::AbstractRegistry (void) inline
Default constructor.
Definition at line 1316 of file easylogging++.h.
 {}
AbstractRegistry() [2/2]
template<typename T_Ptr, typename Container> el::base::utils::AbstractRegistry< T_Ptr, Container >::AbstractRegistry (AbstractRegistry< T_Ptr, Container > && sr) inline
Move constructor that is useful for base classes.
Definition at line 1319 of file easylogging++.h.
{
     if (this == &sr) {
       return;
     }
     unregisterAll();
     m_list = std::move(sr.m_list);
   }
~AbstractRegistry()
template<typename T_Ptr, typename Container> virtual el::base::utils::AbstractRegistry< T_Ptr, Container >::~AbstractRegistry (void) inline virtual
Definition at line 1361 of file easylogging++.h.
{
   }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
begin()
template<typename T_Ptr, typename Container> virtual iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::begin (void) inline virtual
Returns
Iterator pointer from start of repository
Definition at line 1365 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::build().
{
     return m_list.begin();
   }
cbegin()
template<typename T_Ptr, typename Container> virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::cbegin (void) const inline virtual
Returns
Constant iterator pointer from start of repository
Definition at line 1376 of file easylogging++.h.
{
     return m_list.cbegin();
   }
cend()
template<typename T_Ptr, typename Container> virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::cend (void) const inline virtual
Returns
End of repository
Definition at line 1381 of file easylogging++.h.
{
     return m_list.cend();
   }
deepCopy()
template<typename T_Ptr, typename Container> virtual void el::base::utils::AbstractRegistry< T_Ptr, Container >::deepCopy (const AbstractRegistry< T_Ptr, Container > &) protected pure virtual
empty()
template<typename T_Ptr, typename Container> virtual bool el::base::utils::AbstractRegistry< T_Ptr, Container >::empty (void) const inline virtual
Returns
Whether or not repository is empty
Definition at line 1386 of file easylogging++.h.
{
     return m_list.empty();
   }
end()
template<typename T_Ptr, typename Container> virtual iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::end (void) inline virtual
Returns
Iterator pointer from end of repository
Definition at line 1370 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::build().
{
     return m_list.end();
   }
list() [1/2]
template<typename T_Ptr, typename Container> virtual Container& el::base::utils::AbstractRegistry< T_Ptr, Container >::list (void) inline virtual
Returns underlying container by reference.
Definition at line 1396 of file easylogging++.h.
Referenced by el::Configurations::setFromBase().
{
     return m_list;
   }
list() [2/2]
template<typename T_Ptr, typename Container> virtual const Container& el::base::utils::AbstractRegistry< T_Ptr, Container >::list (void) const inline virtual
Returns underlying container by constant reference.
Definition at line 1401 of file easylogging++.h.
{
     return m_list;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
operator!=()
template<typename T_Ptr, typename Container> bool el::base::utils::AbstractRegistry< T_Ptr, Container >::operator!= (const AbstractRegistry< T_Ptr, Container > & other) inline
Definition at line 1339 of file easylogging++.h.
{
     if (size() != other.size()) {
       return true;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return true;
       }
     }
     return false;
   }
operator=()
template<typename T_Ptr, typename Container> AbstractRegistry& el::base::utils::AbstractRegistry< T_Ptr, Container >::operator= (AbstractRegistry< T_Ptr, Container > && sr) inline
Assignment move operator.
Definition at line 1352 of file easylogging++.h.
{
     if (this == &sr) {
       return *this;
     }
     unregisterAll();
     m_list = std::move(sr.m_list);
     return *this;
   }
operator==()
template<typename T_Ptr, typename Container> bool el::base::utils::AbstractRegistry< T_Ptr, Container >::operator== (const AbstractRegistry< T_Ptr, Container > & other) inline
Definition at line 1327 of file easylogging++.h.
{
     if (size() != other.size()) {
       return false;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return false;
       }
     }
     return true;
   }
reinitDeepCopy()
template<typename T_Ptr, typename Container> void el::base::utils::AbstractRegistry< T_Ptr, Container >::reinitDeepCopy (const AbstractRegistry< T_Ptr, Container > & sr) inline protected
Definition at line 1410 of file easylogging++.h.
{
     unregisterAll();
     deepCopy(sr);
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
size()
template<typename T_Ptr, typename Container> virtual std::size_t el::base::utils::AbstractRegistry< T_Ptr, Container >::size (void) const inline virtual
Returns
Size of repository
Definition at line 1391 of file easylogging++.h.
Referenced by el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator!=(), and el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator==().
{
     return m_list.size();
   }
unregisterAll()
template<typename T_Ptr, typename Container> virtual void el::base::utils::AbstractRegistry< T_Ptr, Container >::unregisterAll (void) pure virtual
Unregisters all the pointers from current repository.
Implemented in el::base::utils::RegistryWithPred< T_Ptr, Pred >, el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >, el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >, el::base::utils::Registry< T_Ptr, T_Key >, and el::base::utils::Registry< Logger, std::string >.
Member Data Documentation
m_list
template<typename T_Ptr, typename Container> Container el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list private
Definition at line 1416 of file easylogging++.h.
Referenced by el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator!=(), and el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator==().
The documentation for this class was generated from the following file:
include/util/easylogging++.h