VulpesRender: el::base::utils::Registry< T_Ptr, T_Key > Class Template Reference
el::base::utils::Registry< T_Ptr, T_Key > Class Template Reference abstract
A pointer registry mechanism to manage memory and provide search functionalities.
#include <easylogging++.h>
Public Types
typedef Registry< T_Ptr, T_Key >::iterator iterator
typedef Registry< T_Ptr, T_Key >::const_iterator const_iterator
Public Member Functions
Registry (void)
Registry (const Registry &sr)
Copy constructor that is useful for base classes. Try to avoid this constructor, use move constructor.
Registry & operator= (const Registry &sr)
Assignment operator that unregisters all the existing registeries and deeply copies each of repo element.
virtual ~Registry (void)
bool operator== (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr * > > &other)
bool operator!= (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr * > > &other)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual std::map< T_Key, T_Ptr * > & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const std::map< T_Key, T_Ptr * > & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void registerNew (const T_Key &uniqKey, T_Ptr *ptr) ELPP_FINAL
Registers new registry to repository.
void unregister (const T_Key &uniqKey)
Unregisters single entry mapped to specified unique key.
T_Ptr * get (const T_Key &uniqKey)
Gets pointer from repository. If none found, nullptr is returned.
virtual void deepCopy (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr * > > &)=0
void reinitDeepCopy (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr * > > &sr)
Private Member Functions
virtual void deepCopy (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *>> &sr) ELPP_FINAL
Detailed Description
template<typename T_Ptr, typename T_Key = const char*>
class el::base::utils::Registry< T_Ptr, T_Key >
A pointer registry mechanism to manage memory and provide search functionalities.
(non-predicate version)
NOTE: This is thread-unsafe implementation (although it contains lock function, it does not use these functions) of AbstractRegistry<T_Ptr, Container>. Any implementation of this class should be explicitly (by using lock functions)
Definition at line 1425 of file easylogging++.h.
Member Typedef Documentation
const_iterator
template<typename T_Ptr, typename T_Key = const char*> typedef Registry<T_Ptr, T_Key>::const_iterator el::base::utils::Registry< T_Ptr, T_Key >::const_iterator
Definition at line 1428 of file easylogging++.h.
iterator
template<typename T_Ptr, typename T_Key = const char*> typedef Registry<T_Ptr, T_Key>::iterator el::base::utils::Registry< T_Ptr, T_Key >::iterator
Definition at line 1427 of file easylogging++.h.
Constructor & Destructor Documentation
Registry() [1/2]
template<typename T_Ptr, typename T_Key = const char*> el::base::utils::Registry< T_Ptr, T_Key >::Registry (void) inline
Definition at line 1430 of file easylogging++.h.
 {}
Registry() [2/2]
template<typename T_Ptr, typename T_Key = const char*> el::base::utils::Registry< T_Ptr, T_Key >::Registry (const Registry< T_Ptr, T_Key > & sr) inline
Copy constructor that is useful for base classes. Try to avoid this constructor, use move constructor.
Definition at line 1433 of file easylogging++.h.
                                : AbstractRegistry<T_Ptr, std::vector<T_Ptr*>>() {
     if (this == &sr) {
       return;
     }
     this->reinitDeepCopy(sr);
   }
~Registry()
template<typename T_Ptr, typename T_Key = const char*> virtual el::base::utils::Registry< T_Ptr, T_Key >::~Registry (void) inline virtual
Definition at line 1451 of file easylogging++.h.
{
     unregisterAll();
   }
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
begin()
virtual iterator el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::begin (void) inline virtual inherited
Returns
Iterator pointer from start of repository
Definition at line 1365 of file easylogging++.h.
{
     return m_list.begin();
   }
cbegin()
virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::cbegin (void) const inline virtual inherited
Returns
Constant iterator pointer from start of repository
Definition at line 1376 of file easylogging++.h.
{
     return m_list.cbegin();
   }
cend()
virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::cend (void) const inline virtual inherited
Returns
End of repository
Definition at line 1381 of file easylogging++.h.
{
     return m_list.cend();
   }
deepCopy() [1/2]
virtual void el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::deepCopy (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> > &) protected pure virtual inherited
deepCopy() [2/2]
template<typename T_Ptr, typename T_Key = const char*> virtual void el::base::utils::Registry< T_Ptr, T_Key >::deepCopy (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *>> & sr) inline private virtual
Definition at line 1489 of file easylogging++.h.
{
     for (const_iterator it = sr.cbegin(); it != sr.cend(); ++it) {
       registerNew(it->first, new T_Ptr(*it->second));
     }
   }
empty()
virtual bool el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::empty (void) const inline virtual inherited
Returns
Whether or not repository is empty
Definition at line 1386 of file easylogging++.h.
{
     return m_list.empty();
   }
end()
virtual iterator el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::end (void) inline virtual inherited
Returns
Iterator pointer from end of repository
Definition at line 1370 of file easylogging++.h.
{
     return m_list.end();
   }
get()
template<typename T_Ptr, typename T_Key = const char*> T_Ptr* el::base::utils::Registry< T_Ptr, T_Key >::get (const T_Key & uniqKey) inline protected
Gets pointer from repository. If none found, nullptr is returned.
Definition at line 1481 of file easylogging++.h.
Referenced by el::base::RegisteredLoggers::get(), and el::base::RegisteredLoggers::remove().
{
     iterator it = this->list().find(uniqKey);
     return it == this->list().end()
            ? nullptr
            : it->second;
   }
list() [1/2]
virtual std::map< T_Key, T_Ptr *> & el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::list (void) inline virtual inherited
Returns underlying container by reference.
Definition at line 1396 of file easylogging++.h.
{
     return m_list;
   }
list() [2/2]
virtual const std::map< T_Key, T_Ptr *> & el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::list (void) const inline virtual inherited
Returns underlying container by constant reference.
Definition at line 1401 of file easylogging++.h.
{
     return m_list;
   }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
operator!=()
bool el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::operator!= (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> > & other) inline inherited
Definition at line 1339 of file easylogging++.h.
{
     if (size() != other.size()) {
       return true;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return true;
       }
     }
     return false;
   }
operator=()
template<typename T_Ptr, typename T_Key = const char*> Registry& el::base::utils::Registry< T_Ptr, T_Key >::operator= (const Registry< T_Ptr, T_Key > & sr) inline
Assignment operator that unregisters all the existing registeries and deeply copies each of repo element.
See also
unregisterAll()
deepCopy(const AbstractRegistry&)
Definition at line 1443 of file easylogging++.h.
{
     if (this == &sr) {
       return *this;
     }
     this->reinitDeepCopy(sr);
     return *this;
   }
operator==()
bool el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::operator== (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> > & other) inline inherited
Definition at line 1327 of file easylogging++.h.
{
     if (size() != other.size()) {
       return false;
     }
     for (std::size_t i = 0; i < m_list.size(); ++i) {
       if (m_list.at(i) != other.m_list.at(i)) {
         return false;
       }
     }
     return true;
   }
registerNew()
template<typename T_Ptr, typename T_Key = const char*> virtual void el::base::utils::Registry< T_Ptr, T_Key >::registerNew (const T_Key & uniqKey, T_Ptr * ptr) inline protected virtual
Registers new registry to repository.
Definition at line 1466 of file easylogging++.h.
{
     unregister(uniqKey);
     this->list().insert(std::make_pair(uniqKey, ptr));
   }
reinitDeepCopy()
void el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::reinitDeepCopy (const AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> > & sr) inline protected inherited
Definition at line 1410 of file easylogging++.h.
{
     unregisterAll();
     deepCopy(sr);
   }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
size()
virtual std::size_t el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >::size (void) const inline virtual inherited
Returns
Size of repository
Definition at line 1391 of file easylogging++.h.
{
     return m_list.size();
   }
unregister()
template<typename T_Ptr, typename T_Key = const char*> void el::base::utils::Registry< T_Ptr, T_Key >::unregister (const T_Key & uniqKey) inline protected
Unregisters single entry mapped to specified unique key.
Definition at line 1472 of file easylogging++.h.
Referenced by el::base::RegisteredLoggers::unregister().
{
     T_Ptr* existing = get(uniqKey);
     if (existing != nullptr) {
       this->list().erase(uniqKey);
       base::utils::safeDelete(existing);
     }
   }
unregisterAll()
template<typename T_Ptr, typename T_Key = const char*> virtual void el::base::utils::Registry< T_Ptr, T_Key >::unregisterAll (void) inline protected virtual
Unregisters all the pointers from current repository.
Implements el::base::utils::AbstractRegistry< T_Ptr, std::map< T_Key, T_Ptr *> >.
Definition at line 1456 of file easylogging++.h.
{
     if (!this->empty()) {
       for (auto&& curr : this->list()) {
         base::utils::safeDelete(curr.second);
       }
       this->list().clear();
     }
   }
The documentation for this class was generated from the following file:
include/util/easylogging++.h