VulpesRender: el::Logger Class Reference
el::Logger Class Reference
Represents a logger holding ID and configurations we need to write logs.
#include <easylogging++.h>
Public Member Functions
Logger (const std::string &id, base::LogStreamsReferenceMap *logStreamsReference)
Logger (const std::string &id, const Configurations &configurations, base::LogStreamsReferenceMap *logStreamsReference)
Logger (const Logger &logger)
Logger & operator= (const Logger &logger)
virtual ~Logger (void)
virtual void log (el::base::type::ostream_t &os) const
void configure (const Configurations &configurations)
Configures the logger using specified configurations.
void reconfigure (void)
Reconfigures logger using existing configurations.
const std::string & id (void) const
const std::string & parentApplicationName (void) const
void setParentApplicationName (const std::string &parentApplicationName)
Configurations * configurations (void)
base::TypedConfigurations * typedConfigurations (void)
void flush (void)
Flushes logger to sync all log files for all levels.
void flush (Level level, base::type::fstream_t *fs)
bool isFlushNeeded (Level level)
LogBuilder * logBuilder (void) const
void setLogBuilder (const LogBuilderPtr &logBuilder)
bool enabled (Level level) const
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Static Public Member Functions
static bool isValidId (const std::string &id)
Private Member Functions
Logger (void)
void initUnflushedCount (void)
base::type::stringstream_t & stream (void)
void resolveLoggerFormatSpec (void) const
Private Attributes
std::string m_id
base::TypedConfigurations * m_typedConfigurations
base::type::stringstream_t m_stream
std::string m_parentApplicationName
bool m_isConfigured
Configurations m_configurations
std::map< Level, unsigned int > m_unflushedCount
base::LogStreamsReferenceMap * m_logStreamsReference
LogBuilderPtr m_logBuilder
Friends
class el::LogMessage
class el::Loggers
class el::Helpers
class el::base::RegisteredLoggers
class el::base::DefaultLogDispatchCallback
class el::base::MessageBuilder
class el::base::Writer
class el::base::PErrorWriter
class el::base::Storage
class el::base::PerformanceTracker
class el::base::LogDispatcher
Detailed Description
Represents a logger holding ID and configurations we need to write logs.
This class does not write logs itself instead its used by writer to read configuations from.
Definition at line 2261 of file easylogging++.h.
Constructor & Destructor Documentation
Logger() [1/4]
el::Logger::Logger (const std::string & id, base::LogStreamsReferenceMap * logStreamsReference)
Definition at line 521 of file easylogging++.cc.
References initUnflushedCount().
                                                                                    :
   m_id(id),
   m_typedConfigurations(nullptr),
   m_parentApplicationName(std::string()),
   m_isConfigured(false),
   m_logStreamsReference(logStreamsReference) {
   initUnflushedCount();
 }
Logger() [2/4]
el::Logger::Logger (const std::string & id, const Configurations & configurations, base::LogStreamsReferenceMap * logStreamsReference)
Definition at line 530 of file easylogging++.cc.
References configure(), and initUnflushedCount().
                                                                 :
   m_id(id),
   m_typedConfigurations(nullptr),
   m_parentApplicationName(std::string()),
   m_isConfigured(false),
   m_logStreamsReference(logStreamsReference) {
   initUnflushedCount();
   configure(configurations);
 }
Logger() [3/4]
el::Logger::Logger (const Logger & logger)
Definition at line 541 of file easylogging++.cc.
References m_configurations, m_id, m_isConfigured, m_logStreamsReference, m_parentApplicationName, m_typedConfigurations, m_unflushedCount, and el::base::utils::safeDelete().
{
   base::utils::safeDelete(m_typedConfigurations);
   m_id = logger.m_id;
   m_typedConfigurations = logger.m_typedConfigurations;
   m_parentApplicationName = logger.m_parentApplicationName;
   m_isConfigured = logger.m_isConfigured;
   m_configurations = logger.m_configurations;
   m_unflushedCount = logger.m_unflushedCount;
   m_logStreamsReference = logger.m_logStreamsReference;
 }
~Logger()
virtual el::Logger::~Logger (void) inline virtual
Definition at line 2268 of file easylogging++.h.
References el::base::utils::safeDelete().
{
     base::utils::safeDelete(m_typedConfigurations);
   }
Logger() [4/4]
el::Logger::Logger (void) private
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual inherited
Definition at line 1059 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.lock(); }
configurations()
Configurations* el::Logger::configurations (void) inline
Definition at line 2294 of file easylogging++.h.
Referenced by el::Loggers::reconfigureAllLoggers(), el::Loggers::reconfigureLogger(), and el::base::Storage::Storage().
{
     return &m_configurations;
   }
configure()
void el::Logger::configure (const Configurations & configurations)
Configures the logger using specified configurations.
Definition at line 566 of file easylogging++.cc.
References el::base::TypedConfigurations::configurations(), el::Filename, flush(), el::Global, el::Configurations::hasConfiguration(), initUnflushedCount(), el::base::threading::ThreadSafe::lock(), m_configurations, m_isConfigured, m_logStreamsReference, m_typedConfigurations, resolveLoggerFormatSpec(), el::base::utils::safeDelete(), and el::Configurations::setFromBase().
Referenced by el::Loggers::configureFromGlobal(), Logger(), reconfigure(), and el::Loggers::reconfigureLogger().
{
   m_isConfigured = false;  // we set it to false in case if we fail
   initUnflushedCount();
   if (m_typedConfigurations != nullptr) {
     Configurations* c = const_cast<Configurations*>(m_typedConfigurations->configurations());
     if (c->hasConfiguration(Level::Global, ConfigurationType::Filename)) {
       // This check is definitely needed for cases like ELPP_NO_DEFAULT_LOG_FILE
       flush();
     }
   }
   base::threading::ScopedLock scopedLock(lock());
   if (m_configurations != configurations) {
     m_configurations.setFromBase(const_cast<Configurations*>(&configurations));
   }
   base::utils::safeDelete(m_typedConfigurations);
   m_typedConfigurations = new base::TypedConfigurations(&m_configurations, m_logStreamsReference);
   resolveLoggerFormatSpec();
   m_isConfigured = true;
 }
enabled()
bool el::Logger::enabled (Level level) const inline
Definition at line 2321 of file easylogging++.h.
{
     return m_typedConfigurations->enabled(level);
   }
flush() [1/2]
void el::Logger::flush (void)
Flushes logger to sync all log files for all levels.
Definition at line 600 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), ELPP_INTERNAL_INFO, el::LevelHelper::forEachLevel(), el::LevelHelper::kMinValid, el::base::threading::ThreadSafe::lock(), and m_id.
Referenced by configure(), and el::base::DefaultLogDispatchCallback::dispatch().
{
   ELPP_INTERNAL_INFO(3, "Flushing logger [" << m_id << "] all levels");
   base::threading::ScopedLock scopedLock(lock());
   base::type::EnumType lIndex = LevelHelper::kMinValid;
   LevelHelper::forEachLevel(&lIndex, [&](void) -> bool {
     flush(LevelHelper::castFromInt(lIndex), nullptr);
     return false;
   });
 }
flush() [2/2]
void el::Logger::flush (Level level, base::type::fstream_t * fs)
Definition at line 610 of file easylogging++.cc.
References el::base::TypedConfigurations::fileStream(), m_typedConfigurations, m_unflushedCount, and el::base::TypedConfigurations::toFile().
{
   if (fs == nullptr && m_typedConfigurations->toFile(level)) {
     fs = m_typedConfigurations->fileStream(level);
   }
   if (fs != nullptr) {
     fs->flush();
     std::map<Level, unsigned int>::iterator iter = m_unflushedCount.find(level);
     if (iter != m_unflushedCount.end()) {
       iter->second = 0;
     }
   }
 }
id()
const std::string& el::Logger::id (void) const inline
Definition at line 2282 of file easylogging++.h.
Referenced by el::Loggers::configureFromGlobal(), el::base::Writer::construct(), el::base::DefaultLogDispatchCallback::dispatch(), and el::base::RegisteredLoggers::unregister().
{
     return m_id;
   }
initUnflushedCount()
void el::Logger::initUnflushedCount (void) private
Definition at line 623 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), el::LevelHelper::forEachLevel(), el::LevelHelper::kMinValid, and m_unflushedCount.
Referenced by configure(), and Logger().
{
   m_unflushedCount.clear();
   base::type::EnumType lIndex = LevelHelper::kMinValid;
   LevelHelper::forEachLevel(&lIndex, [&](void) -> bool {
     m_unflushedCount.insert(std::make_pair(LevelHelper::castFromInt(lIndex), 0));
     return false;
   });
 }
isFlushNeeded()
bool el::Logger::isFlushNeeded (Level level) inline
Definition at line 2309 of file easylogging++.h.
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
     return ++m_unflushedCount.find(level)->second >= m_typedConfigurations->logFlushThreshold(level);
   }
isValidId()
bool el::Logger::isValidId (const std::string & id) static
Definition at line 591 of file easylogging++.cc.
References el::base::utils::Str::contains(), and el::base::consts::kValidLoggerIdSymbols.
Referenced by el::base::RegisteredLoggers::get().
{
   for (std::string::const_iterator it = id.begin(); it != id.end(); ++it) {
     if (!base::utils::Str::contains(base::consts::kValidLoggerIdSymbols, *it)) {
       return false;
     }
   }
   return true;
 }
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual inherited
Definition at line 1061 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), configure(), flush(), el::base::RegisteredLoggers::get(), el::Configurations::hasConfiguration(), el::base::Storage::hasCustomFormatSpecifier(), el::base::Storage::installCustomFormatSpecifier(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), el::base::Storage::uninstallCustomFormatSpecifier(), and el::base::PErrorWriter::~PErrorWriter().
 { return m_mutex; }
log()
virtual void el::Logger::log (el::base::type::ostream_t & os) const inline virtual
Implements el::Loggable.
Definition at line 2272 of file easylogging++.h.
Referenced by el::base::PErrorWriter::PErrorWriter().
{
     os << m_id.c_str();
   }
logBuilder()
LogBuilder* el::Logger::logBuilder (void) const inline
Definition at line 2313 of file easylogging++.h.
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
{
     return m_logBuilder.get();
   }
operator=()
Logger & el::Logger::operator= (const Logger & logger)
Definition at line 552 of file easylogging++.cc.
References m_configurations, m_id, m_isConfigured, m_logStreamsReference, m_parentApplicationName, m_typedConfigurations, m_unflushedCount, and el::base::utils::safeDelete().
{
   if (&logger != this) {
     base::utils::safeDelete(m_typedConfigurations);
     m_id = logger.m_id;
     m_typedConfigurations = logger.m_typedConfigurations;
     m_parentApplicationName = logger.m_parentApplicationName;
     m_isConfigured = logger.m_isConfigured;
     m_configurations = logger.m_configurations;
     m_unflushedCount = logger.m_unflushedCount;
     m_logStreamsReference = logger.m_logStreamsReference;
   }
   return *this;
 }
parentApplicationName()
const std::string& el::Logger::parentApplicationName (void) const inline
Definition at line 2286 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
{
     return m_parentApplicationName;
   }
reconfigure()
void el::Logger::reconfigure (void)
Reconfigures logger using existing configurations.
Definition at line 586 of file easylogging++.cc.
References configure(), ELPP_INTERNAL_INFO, m_configurations, and m_id.
Referenced by el::Loggers::reconfigureAllLoggers(), el::Loggers::reconfigureLogger(), and el::base::Storage::Storage().
{
   ELPP_INTERNAL_INFO(1, "Reconfiguring logger [" << m_id << "]");
   configure(m_configurations);
 }
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual inherited
Definition at line 1060 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString().
 { m_mutex.unlock(); }
resolveLoggerFormatSpec()
void el::Logger::resolveLoggerFormatSpec (void) const private
Definition at line 632 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), el::LevelHelper::forEachLevel(), el::base::consts::kLoggerIdFormatSpecifier, el::LevelHelper::kMinValid, el::base::TypedConfigurations::logFormat(), el::base::LogFormat::m_format, m_id, m_typedConfigurations, and el::base::utils::Str::replaceFirstWithEscape().
Referenced by configure().
{
   base::type::EnumType lIndex = LevelHelper::kMinValid;
   LevelHelper::forEachLevel(&lIndex, [&](void) -> bool {
     base::LogFormat* logFormat =
     const_cast<base::LogFormat*>(&m_typedConfigurations->logFormat(LevelHelper::castFromInt(lIndex)));
     base::utils::Str::replaceFirstWithEscape(logFormat->m_format, base::consts::kLoggerIdFormatSpecifier, m_id);
     return false;
   });
 }
setLogBuilder()
void el::Logger::setLogBuilder (const LogBuilderPtr & logBuilder) inline
Definition at line 2317 of file easylogging++.h.
{
     m_logBuilder = logBuilder;
   }
setParentApplicationName()
void el::Logger::setParentApplicationName (const std::string & parentApplicationName) inline
Definition at line 2290 of file easylogging++.h.
{
     m_parentApplicationName = parentApplicationName;
   }
stream()
base::type::stringstream_t& el::Logger::stream (void) inline private
Definition at line 2387 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString(), and el::base::MessageBuilder::writeIterator().
{
     return m_stream;
   }
typedConfigurations()
base::TypedConfigurations* el::Logger::typedConfigurations (void) inline
Definition at line 2298 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::DefaultLogDispatchCallback::dispatch().
{
     return m_typedConfigurations;
   }
Friends And Related Function Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
Definition at line 2361 of file easylogging++.h.
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
Definition at line 2367 of file easylogging++.h.
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
Definition at line 2362 of file easylogging++.h.
el::base::PerformanceTracker
friend class el::base::PerformanceTracker friend
Definition at line 2366 of file easylogging++.h.
el::base::PErrorWriter
friend class el::base::PErrorWriter friend
Definition at line 2364 of file easylogging++.h.
el::base::RegisteredLoggers
friend class el::base::RegisteredLoggers friend
Definition at line 2360 of file easylogging++.h.
el::base::Storage
friend class el::base::Storage friend
Definition at line 2365 of file easylogging++.h.
el::base::Writer
friend class el::base::Writer friend
Definition at line 2363 of file easylogging++.h.
el::Helpers
friend class el::Helpers friend
Definition at line 2359 of file easylogging++.h.
el::Loggers
friend class el::Loggers friend
Definition at line 2358 of file easylogging++.h.
el::LogMessage
friend class el::LogMessage friend
Definition at line 2357 of file easylogging++.h.
Member Data Documentation
m_configurations
Configurations el::Logger::m_configurations private
Definition at line 2352 of file easylogging++.h.
Referenced by configure(), Logger(), operator=(), and reconfigure().
m_id
std::string el::Logger::m_id private
Definition at line 2347 of file easylogging++.h.
Referenced by flush(), Logger(), operator=(), reconfigure(), and resolveLoggerFormatSpec().
m_isConfigured
bool el::Logger::m_isConfigured private
Definition at line 2351 of file easylogging++.h.
Referenced by configure(), Logger(), and operator=().
m_logBuilder
LogBuilderPtr el::Logger::m_logBuilder private
Definition at line 2355 of file easylogging++.h.
Referenced by el::base::RegisteredLoggers::get().
m_logStreamsReference
base::LogStreamsReferenceMap* el::Logger::m_logStreamsReference private
Definition at line 2354 of file easylogging++.h.
Referenced by configure(), Logger(), and operator=().
m_parentApplicationName
std::string el::Logger::m_parentApplicationName private
Definition at line 2350 of file easylogging++.h.
Referenced by Logger(), and operator=().
m_stream
base::type::stringstream_t el::Logger::m_stream private
Definition at line 2349 of file easylogging++.h.
m_typedConfigurations
base::TypedConfigurations* el::Logger::m_typedConfigurations private
Definition at line 2348 of file easylogging++.h.
Referenced by configure(), flush(), Logger(), operator=(), resolveLoggerFormatSpec(), el::Helpers::validateFileRolling(), and el::base::PErrorWriter::~PErrorWriter().
m_unflushedCount
std::map<Level, unsigned int> el::Logger::m_unflushedCount private
Definition at line 2353 of file easylogging++.h.
Referenced by flush(), initUnflushedCount(), Logger(), and operator=().
The documentation for this class was generated from the following files:
include/util/easylogging++.h
src/util/easylogging++.cc