VulpesRender: el::base::threading Namespace Reference
el::base::threading Namespace Reference
Namespaces
internal
Classes
class ThreadSafe
Base of thread safe class, this class is inheritable-only.
Typedefs
typedef base::threading::internal::NoMutex Mutex
typedef base::threading::internal::NoScopedLock< base::threading::Mutex > ScopedLock
Functions
static std::string getCurrentThreadId (void)
Typedef Documentation
Mutex
typedef base::threading::internal::NoMutex el::base::threading::Mutex
Definition at line 1053 of file easylogging++.h.
ScopedLock
typedef base::threading::internal::NoScopedLock<base::threading::Mutex> el::base::threading::ScopedLock
Definition at line 1054 of file easylogging++.h.
Function Documentation
getCurrentThreadId()
static std::string el::base::threading::getCurrentThreadId (void) inline static
Definition at line 1088 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), el::Helpers::getThreadName(), and el::base::Storage::setThreadName().
{
   return std::string();
 }