VulpesRender: el::base::utils Namespace Reference
el::base::utils Namespace Reference
Namespace containing utility functions/static classes used internally.
Namespaces
bitwise
Bitwise operations for C++11 strong enum class.
Classes
class AbstractRegistry
Abstract registry (aka repository) that provides basic interface for pointer repository specified by T_Ptr type.
class CommandLineArgs
Command line arguments for application if specified using el::Helpers::setArgs(..) or START_EASYLOGGINGPP(..)
class DateTime
Contains utilities for cross-platform date/time. This class make use of el::base::utils::Str.
class File
class OS
Operating System helper static class used internally. You should not use it.
class Registry
A pointer registry mechanism to manage memory and provide search functionalities.
class RegistryWithPred
A pointer registry mechanism to manage memory and provide search functionalities.
class Str
String utilities helper class used internally. You should not use it.
class Utils
Functions
template<typename T >
static std::enable_if< std::is_pointer< T * >::value, void >::type safeDelete (T *&pointer)
Deletes memory safely and points to null.
template<typename Enum >
static void addFlag (Enum e, base::type::EnumType *flag)
template<typename Enum >
static void removeFlag (Enum e, base::type::EnumType *flag)
template<typename Enum >
static bool hasFlag (Enum e, base::type::EnumType flag)
static void abort (int status, const std::string &reason)
Aborts application due with user-defined status.
base::type::ostream_t & operator<< (base::type::ostream_t &os, const CommandLineArgs &c)
Detailed Description
Namespace containing utility functions/static classes used internally.
Function Documentation
abort()
static void el::base::utils::abort (int status, const std::string & reason) static
Aborts application due with user-defined status.
Definition at line 30 of file easylogging++.cc.
References ELPP_UNUSED.
Referenced by el::base::Writer::triggerDispatch(), vkErrCheck(), and el::base::PErrorWriter::~PErrorWriter().
{
   // Both status and reason params are there for debugging with tools like gdb etc
   ELPP_UNUSED(status);
   ELPP_UNUSED(reason);
 #if defined(ELPP_COMPILER_MSVC) && defined(_M_IX86) && defined(_DEBUG)
   // Ignore msvc critical error dialog - break instead (on debug mode)
   _asm int 3
 #else
   ::abort();
 #endif  // defined(ELPP_COMPILER_MSVC) && defined(_M_IX86) && defined(_DEBUG)
 }
addFlag()
template<typename Enum > static void el::base::utils::addFlag (Enum e, base::type::EnumType * flag) inline static
Definition at line 936 of file easylogging++.h.
Referenced by el::base::LogFormat::addFlag(), el::base::Storage::addFlag(), and el::base::Storage::Storage().
{
   *flag = base::utils::bitwise::Or<Enum>(e, *flag);
 }
hasFlag()
template<typename Enum > static bool el::base::utils::hasFlag (Enum e, base::type::EnumType flag) inline static
Definition at line 944 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), el::base::LogFormat::hasFlag(), el::base::Storage::hasFlag(), el::base::VRegistry::setModules(), and el::base::VRegistry::vModulesEnabled().
{
   return base::utils::bitwise::And<Enum>(e, flag) > 0x0;
 }
operator<<()
base::type::ostream_t& el::base::utils::operator<< (base::type::ostream_t & os, const CommandLineArgs & c)
Definition at line 1291 of file easylogging++.cc.
References ELPP_LITERAL, el::base::utils::CommandLineArgs::m_argc, and el::base::utils::CommandLineArgs::m_argv.
Referenced by el::base::PErrorWriter::~PErrorWriter().
{
   for (int i = 1; i < c.m_argc; ++i) {
     os << ELPP_LITERAL("[") << c.m_argv[i] << ELPP_LITERAL("]");
     if (i < c.m_argc - 1) {
       os << ELPP_LITERAL(" ");
     }
   }
   return os;
 }
removeFlag()
template<typename Enum > static void el::base::utils::removeFlag (Enum e, base::type::EnumType * flag) inline static
Definition at line 940 of file easylogging++.h.
Referenced by el::base::Storage::removeFlag().
{
   *flag = base::utils::bitwise::Not<Enum>(e, *flag);
 }
safeDelete()
template<typename T > static std::enable_if<std::is_pointer<T*>::value, void>::type el::base::utils::safeDelete (T *& pointer) static
Deletes memory safely and points to null.
Definition at line 913 of file easylogging++.h.
Referenced by el::Logger::configure(), el::Logger::Logger(), el::base::utils::File::newFileStream(), el::Logger::operator=(), el::base::utils::Registry< Logger, std::string >::unregister(), el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >::unregister(), el::base::utils::Registry< Logger, std::string >::unregisterAll(), el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >::unregisterAll(), el::Logger::~Logger(), and el::base::Storage::~Storage().
{
   if (pointer == nullptr)
     return;
   delete pointer;
   pointer = nullptr;
 }