VulpesRender: el::base::consts Namespace Reference
el::base::consts Namespace Reference
Namespace containing constants used internally.
Variables
static const base::type::char_t * kInfoLevelLogValue = ELPP_LITERAL("INFO")
static const base::type::char_t * kDebugLevelLogValue = ELPP_LITERAL("DEBUG")
static const base::type::char_t * kWarningLevelLogValue = ELPP_LITERAL("WARNING")
static const base::type::char_t * kErrorLevelLogValue = ELPP_LITERAL("ERROR")
static const base::type::char_t * kFatalLevelLogValue = ELPP_LITERAL("FATAL")
static const base::type::char_t * kVerboseLevelLogValue
static const base::type::char_t * kTraceLevelLogValue = ELPP_LITERAL("TRACE")
static const base::type::char_t * kInfoLevelShortLogValue = ELPP_LITERAL("I")
static const base::type::char_t * kDebugLevelShortLogValue = ELPP_LITERAL("D")
static const base::type::char_t * kWarningLevelShortLogValue = ELPP_LITERAL("W")
static const base::type::char_t * kErrorLevelShortLogValue = ELPP_LITERAL("E")
static const base::type::char_t * kFatalLevelShortLogValue = ELPP_LITERAL("F")
static const base::type::char_t * kVerboseLevelShortLogValue = ELPP_LITERAL("V")
static const base::type::char_t * kTraceLevelShortLogValue = ELPP_LITERAL("T")
static const base::type::char_t * kAppNameFormatSpecifier = ELPP_LITERAL("%app")
static const base::type::char_t * kLoggerIdFormatSpecifier = ELPP_LITERAL("%logger")
static const base::type::char_t * kThreadIdFormatSpecifier = ELPP_LITERAL("%thread")
static const base::type::char_t * kSeverityLevelFormatSpecifier = ELPP_LITERAL("%level")
static const base::type::char_t * kSeverityLevelShortFormatSpecifier = ELPP_LITERAL("%levshort")
static const base::type::char_t * kDateTimeFormatSpecifier = ELPP_LITERAL("%datetime")
static const base::type::char_t * kLogFileFormatSpecifier = ELPP_LITERAL("%file")
static const base::type::char_t * kLogFileBaseFormatSpecifier = ELPP_LITERAL("%fbase")
static const base::type::char_t * kLogLineFormatSpecifier = ELPP_LITERAL("%line")
static const base::type::char_t * kLogLocationFormatSpecifier = ELPP_LITERAL("%loc")
static const base::type::char_t * kLogFunctionFormatSpecifier = ELPP_LITERAL("%func")
static const base::type::char_t * kCurrentUserFormatSpecifier = ELPP_LITERAL("%user")
static const base::type::char_t * kCurrentHostFormatSpecifier = ELPP_LITERAL("%host")
static const base::type::char_t * kMessageFormatSpecifier = ELPP_LITERAL("%msg")
static const base::type::char_t * kVerboseLevelFormatSpecifier = ELPP_LITERAL("%vlevel")
static const char * kDateTimeFormatSpecifierForFilename = "%datetime"
static const char * kDays [7] = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }
static const char * kDaysAbbrev [7] = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" }
static const char * kMonths [12]
static const char * kMonthsAbbrev [12] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }
static const char * kDefaultDateTimeFormat = "%Y-%M-%d %H:%m:%s,%g"
static const char * kDefaultDateTimeFormatInFilename = "%Y-%M-%d_%H-%m"
static const int kYearBase = 1900
static const char * kAm = "AM"
static const char * kPm = "PM"
static const char * kDefaultLoggerId = "default"
static const char * kPerformanceLoggerId = "performance"
static const char * kNullPointer = "nullptr"
static const char kFormatSpecifierChar = '%'
static const unsigned int kMaxLogPerContainer = 100
static const unsigned int kMaxLogPerCounter = 100000
static const unsigned int kDefaultSubsecondPrecision = 3
static const base::type::VerboseLevel kMaxVerboseLevel = 9
static const char * kUnknownUser = "user"
static const char * kUnknownHost = "unknown-host"
static const char * kDefaultLogFileParam = "--default-log-file"
static const char * kFilePathSeperator = "/"
static const char * kValidLoggerIdSymbols
static const char * kConfigurationComment = "##"
static const char * kConfigurationLevel = "*"
static const char * kConfigurationLoggerId = "--"
static const std::size_t kSourceFilenameMaxLength = 100
static const std::size_t kSourceLineMaxLength = 10
static const Level kPerformanceTrackerDefaultLevel = Level::Info
struct {
double value
const base::type::char_t * unit
} kTimeFormats []
static const int kTimeFormatsCount = sizeof(kTimeFormats) / sizeof(kTimeFormats[0])
struct {
int numb
const char * name
const char * brief
const char * detail
} kCrashSignals []
static const int kCrashSignalsCount = sizeof(kCrashSignals) / sizeof(kCrashSignals[0])
Detailed Description
Namespace containing constants used internally.
Variable Documentation
kAm
const char* el::base::consts::kAm = "AM" static
Definition at line 758 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().
kAppNameFormatSpecifier
const base::type::char_t* el::base::consts::kAppNameFormatSpecifier = ELPP_LITERAL("%app") static
Definition at line 732 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kConfigurationComment
const char* el::base::consts::kConfigurationComment = "##" static
Definition at line 811 of file easylogging++.h.
Referenced by el::Configurations::Parser::ignoreComments(), and el::Configurations::Parser::isComment().
kConfigurationLevel
const char* el::base::consts::kConfigurationLevel = "*" static
Definition at line 812 of file easylogging++.h.
Referenced by el::Configurations::Parser::isLevel().
kConfigurationLoggerId
const char* el::base::consts::kConfigurationLoggerId = "--" static
Definition at line 813 of file easylogging++.h.
Referenced by el::Loggers::configureFromGlobal().
kCrashSignals
const { ... } el::base::consts::kCrashSignals[]
Initial value:
= {
  {
    SIGABRT, "SIGABRT", "Abnormal termination",
    "Program was abnormally terminated."
  },
  {
    SIGFPE, "SIGFPE", "Erroneous arithmetic operation",
    "Arithemetic operation issue such as division by zero or operation resulting in overflow."
  },
  {
    SIGILL, "SIGILL", "Illegal instruction",
    "Generally due to a corruption in the code or to an attempt to execute data."
  },
  {
    SIGSEGV, "SIGSEGV", "Invalid access to memory",
    "Program is trying to read an invalid (unallocated, deleted or corrupted) or inaccessible memory."
  },
  {
    SIGINT, "SIGINT", "Interactive attention signal",
    "Interruption generated (generally) by user or operating system."
  },
}
Referenced by el::base::PErrorWriter::~PErrorWriter().
kCrashSignalsCount
const int el::base::consts::kCrashSignalsCount = sizeof(kCrashSignals) / sizeof(kCrashSignals[0]) static
Definition at line 857 of file easylogging++.h.
Referenced by el::base::PErrorWriter::~PErrorWriter().
kCurrentHostFormatSpecifier
const base::type::char_t* el::base::consts::kCurrentHostFormatSpecifier = ELPP_LITERAL("%host") static
Definition at line 744 of file easylogging++.h.
Referenced by el::base::LogFormat::parseFromFormat(), and el::base::LogFormat::updateFormatSpec().
kCurrentUserFormatSpecifier
const base::type::char_t* el::base::consts::kCurrentUserFormatSpecifier = ELPP_LITERAL("%user") static
Definition at line 743 of file easylogging++.h.
Referenced by el::base::LogFormat::parseFromFormat(), and el::base::LogFormat::updateFormatSpec().
kDateTimeFormatSpecifier
const base::type::char_t* el::base::consts::kDateTimeFormatSpecifier = ELPP_LITERAL("%datetime") static
Definition at line 737 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), el::base::LogFormat::parseFromFormat(), and el::base::LogFormat::updateDateFormat().
kDateTimeFormatSpecifierForFilename
const char* el::base::consts::kDateTimeFormatSpecifierForFilename = "%datetime" static
Definition at line 747 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::resolveFilename().
kDays
const char* el::base::consts::kDays[7] = { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" } static
Definition at line 749 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().
kDaysAbbrev
const char* el::base::consts::kDaysAbbrev[7] = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" } static
Definition at line 750 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().
kDebugLevelLogValue
const base::type::char_t* el::base::consts::kDebugLevelLogValue = ELPP_LITERAL("DEBUG") static
Definition at line 717 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kDebugLevelShortLogValue
const base::type::char_t* el::base::consts::kDebugLevelShortLogValue = ELPP_LITERAL("D") static
Definition at line 725 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kDefaultDateTimeFormat
const char* el::base::consts::kDefaultDateTimeFormat = "%Y-%M-%d %H:%m:%s,%g" static
Definition at line 755 of file easylogging++.h.
Referenced by el::base::LogFormat::updateDateFormat().
kDefaultDateTimeFormatInFilename
const char* el::base::consts::kDefaultDateTimeFormatInFilename = "%Y-%M-%d_%H-%m" static
Definition at line 756 of file easylogging++.h.
Referenced by el::base::TypedConfigurations::resolveFilename().
kDefaultLogFileParam
const char* el::base::consts::kDefaultLogFileParam = "--default-log-file" static
Definition at line 799 of file easylogging++.h.
Referenced by el::base::Storage::setApplicationArguments().
kDefaultLoggerId
const char* el::base::consts::kDefaultLoggerId = "default" static
Definition at line 764 of file easylogging++.h.
Referenced by el::Helpers::convertTemplateToStdString(), el::Helpers::getThreadName(), el::base::Writer::initializeLogger(), el::base::RegisteredLoggers::remove(), el::base::Storage::Storage(), el::base::Writer::triggerDispatch(), and el::base::PErrorWriter::~PErrorWriter().
kDefaultSubsecondPrecision
const unsigned int el::base::consts::kDefaultSubsecondPrecision = 3 static
Definition at line 781 of file easylogging++.h.
Referenced by el::base::SubsecondPrecision::init(), and el::base::SubsecondPrecision::SubsecondPrecision().
kErrorLevelLogValue
const base::type::char_t* el::base::consts::kErrorLevelLogValue = ELPP_LITERAL("ERROR") static
Definition at line 719 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kErrorLevelShortLogValue
const base::type::char_t* el::base::consts::kErrorLevelShortLogValue = ELPP_LITERAL("E") static
Definition at line 727 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kFatalLevelLogValue
const base::type::char_t* el::base::consts::kFatalLevelLogValue = ELPP_LITERAL("FATAL") static
Definition at line 720 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kFatalLevelShortLogValue
const base::type::char_t* el::base::consts::kFatalLevelShortLogValue = ELPP_LITERAL("F") static
Definition at line 728 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kFilePathSeperator
const char* el::base::consts::kFilePathSeperator = "/" static
Definition at line 807 of file easylogging++.h.
Referenced by el::base::utils::File::createPath(), and el::base::TypedConfigurations::insertFile().
kFormatSpecifierChar
const char el::base::consts::kFormatSpecifierChar = '%' static
Definition at line 775 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat(), el::base::LogFormat::parseFromFormat(), el::base::PErrorWriter::PErrorWriter(), el::base::utils::Str::replaceFirstWithEscape(), and el::base::TypedConfigurations::resolveFilename().
kInfoLevelLogValue
const base::type::char_t* el::base::consts::kInfoLevelLogValue = ELPP_LITERAL("INFO") static
Definition at line 716 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kInfoLevelShortLogValue
const base::type::char_t* el::base::consts::kInfoLevelShortLogValue = ELPP_LITERAL("I") static
Definition at line 724 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kLogFileBaseFormatSpecifier
const base::type::char_t* el::base::consts::kLogFileBaseFormatSpecifier = ELPP_LITERAL("%fbase") static
Definition at line 739 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kLogFileFormatSpecifier
const base::type::char_t* el::base::consts::kLogFileFormatSpecifier = ELPP_LITERAL("%file") static
Definition at line 738 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kLogFunctionFormatSpecifier
const base::type::char_t* el::base::consts::kLogFunctionFormatSpecifier = ELPP_LITERAL("%func") static
Definition at line 742 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kLoggerIdFormatSpecifier
const base::type::char_t* el::base::consts::kLoggerIdFormatSpecifier = ELPP_LITERAL("%logger") static
Definition at line 733 of file easylogging++.h.
Referenced by el::base::LogFormat::parseFromFormat(), and el::Logger::resolveLoggerFormatSpec().
kLogLineFormatSpecifier
const base::type::char_t* el::base::consts::kLogLineFormatSpecifier = ELPP_LITERAL("%line") static
Definition at line 740 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kLogLocationFormatSpecifier
const base::type::char_t* el::base::consts::kLogLocationFormatSpecifier = ELPP_LITERAL("%loc") static
Definition at line 741 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kMaxLogPerContainer
const unsigned int el::base::consts::kMaxLogPerContainer = 100 static
Definition at line 779 of file easylogging++.h.
Referenced by el::base::MessageBuilder::writeIterator().
kMaxLogPerCounter
const unsigned int el::base::consts::kMaxLogPerCounter = 100000 static
Definition at line 780 of file easylogging++.h.
Referenced by el::base::HitCounter::validateHitCounts().
kMaxVerboseLevel
const base::type::VerboseLevel el::base::consts::kMaxVerboseLevel = 9 static
Definition at line 782 of file easylogging++.h.
Referenced by el::base::VRegistry::setFromArgs(), and el::base::VRegistry::setLevel().
kMessageFormatSpecifier
const base::type::char_t* el::base::consts::kMessageFormatSpecifier = ELPP_LITERAL("%msg") static
Definition at line 745 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kMonths
const char* el::base::consts::kMonths[12] static
Initial value:
=      { "January", "February", "March", "Apri", "May", "June", "July", "August",
                                                             "September", "October", "November", "December"
                                                           }
Definition at line 751 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().
kMonthsAbbrev
const char* el::base::consts::kMonthsAbbrev[12] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" } static
Definition at line 754 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().
kNullPointer
const char* el::base::consts::kNullPointer = "nullptr" static
Definition at line 774 of file easylogging++.h.
Referenced by el::base::MessageBuilder::operator<<().
kPerformanceLoggerId
const char* el::base::consts::kPerformanceLoggerId = "performance" static
Definition at line 769 of file easylogging++.h.
Referenced by el::base::Storage::Storage().
kPerformanceTrackerDefaultLevel
const Level el::base::consts::kPerformanceTrackerDefaultLevel = Level::Info static
Definition at line 816 of file easylogging++.h.
kPm
const char* el::base::consts::kPm = "PM" static
Definition at line 759 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().
kSeverityLevelFormatSpecifier
const base::type::char_t* el::base::consts::kSeverityLevelFormatSpecifier = ELPP_LITERAL("%level") static
Definition at line 735 of file easylogging++.h.
Referenced by el::base::LogFormat::parseFromFormat(), and el::base::LogFormat::updateFormatSpec().
kSeverityLevelShortFormatSpecifier
const base::type::char_t* el::base::consts::kSeverityLevelShortFormatSpecifier = ELPP_LITERAL("%levshort") static
Definition at line 736 of file easylogging++.h.
Referenced by el::base::LogFormat::parseFromFormat(), and el::base::LogFormat::updateFormatSpec().
kSourceFilenameMaxLength
const std::size_t el::base::consts::kSourceFilenameMaxLength = 100 static
Definition at line 814 of file easylogging++.h.
Referenced by el::base::VRegistry::allowed(), and el::base::DefaultLogBuilder::build().
kSourceLineMaxLength
const std::size_t el::base::consts::kSourceLineMaxLength = 10 static
Definition at line 815 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build().
kThreadIdFormatSpecifier
const base::type::char_t* el::base::consts::kThreadIdFormatSpecifier = ELPP_LITERAL("%thread") static
Definition at line 734 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kTimeFormats
const { ... } el::base::consts::kTimeFormats[]
Initial value:
= {
  { 1000.0f, ELPP_LITERAL("us") },
  { 1000.0f, ELPP_LITERAL("ms") },
  { 60.0f, ELPP_LITERAL("seconds") },
  { 60.0f, ELPP_LITERAL("minutes") },
  { 24.0f, ELPP_LITERAL("hours") },
  { 7.0f, ELPP_LITERAL("days") }
}
Referenced by el::base::utils::DateTime::formatTime(), and el::base::PErrorWriter::~PErrorWriter().
kTimeFormatsCount
const int el::base::consts::kTimeFormatsCount = sizeof(kTimeFormats) / sizeof(kTimeFormats[0]) static
Definition at line 828 of file easylogging++.h.
Referenced by el::base::utils::DateTime::formatTime().
kTraceLevelLogValue
const base::type::char_t* el::base::consts::kTraceLevelLogValue = ELPP_LITERAL("TRACE") static
Definition at line 723 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kTraceLevelShortLogValue
const base::type::char_t* el::base::consts::kTraceLevelShortLogValue = ELPP_LITERAL("T") static
Definition at line 730 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kUnknownHost
const char* el::base::consts::kUnknownHost = "unknown-host" static
Definition at line 784 of file easylogging++.h.
Referenced by el::base::utils::OS::currentHost().
kUnknownUser
const char* el::base::consts::kUnknownUser = "user" static
Definition at line 783 of file easylogging++.h.
Referenced by el::base::utils::OS::currentUser().
kValidLoggerIdSymbols
const char* el::base::consts::kValidLoggerIdSymbols static
Initial value:
=
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._"
Definition at line 809 of file easylogging++.h.
Referenced by el::Logger::isValidId().
kVerboseLevelFormatSpecifier
const base::type::char_t* el::base::consts::kVerboseLevelFormatSpecifier = ELPP_LITERAL("%vlevel") static
Definition at line 746 of file easylogging++.h.
Referenced by el::base::DefaultLogBuilder::build(), and el::base::LogFormat::parseFromFormat().
kVerboseLevelLogValue
const base::type::char_t* el::base::consts::kVerboseLevelLogValue static
Initial value:
=
  ELPP_LITERAL("VERBOSE")
Definition at line 721 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kVerboseLevelShortLogValue
const base::type::char_t* el::base::consts::kVerboseLevelShortLogValue = ELPP_LITERAL("V") static
Definition at line 729 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kWarningLevelLogValue
const base::type::char_t* el::base::consts::kWarningLevelLogValue = ELPP_LITERAL("WARNING") static
Definition at line 718 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kWarningLevelShortLogValue
const base::type::char_t* el::base::consts::kWarningLevelShortLogValue = ELPP_LITERAL("W") static
Definition at line 726 of file easylogging++.h.
Referenced by el::base::LogFormat::updateFormatSpec().
kYearBase
const int el::base::consts::kYearBase = 1900 static
Definition at line 757 of file easylogging++.h.
Referenced by el::base::utils::DateTime::parseFormat().