VulpesRender: vpr::Suballocation Struct Reference
vpr::Suballocation Struct Reference
Allocation
During the process of finding a suitable region to bind to, we need to store things like "SuballocationType", which helps keep track of the precise kind of memory we are looking for and lets us know if its optimally/linearly tiled.
#include <Suballocation.hpp>
Public Member Functions
bool operator< (const Suballocation &other) const noexcept
Public Attributes
VkDeviceSize Offset { std::numeric_limits<VkDeviceSize>::max() }
VkDeviceSize Size { std::numeric_limits<VkDeviceSize>::max() }
SuballocationType Type { SuballocationType::Unknown }
Detailed Description
During the process of finding a suitable region to bind to, we need to store things like "SuballocationType", which helps keep track of the precise kind of memory we are looking for and lets us know if its optimally/linearly tiled.
Definition at line 25 of file Suballocation.hpp.
Member Function Documentation
operator<()
bool vpr::Suballocation::operator< (const Suballocation & other) const inline noexcept
Definition at line 29 of file Suballocation.hpp.
{
             return Offset < other.Offset;
         }
Member Data Documentation
Offset
VkDeviceSize vpr::Suballocation::Offset { std::numeric_limits<VkDeviceSize>::max() }
Definition at line 26 of file Suballocation.hpp.
Referenced by vpr::MemoryBlock::Validate(), and vpr::MemoryBlock::VerifySuballocation().
Size
VkDeviceSize vpr::Suballocation::Size { std::numeric_limits<VkDeviceSize>::max() }
Definition at line 27 of file Suballocation.hpp.
Referenced by vpr::MemoryBlock::freeSuballocation(), vpr::MemoryBlock::Validate(), and vpr::MemoryBlock::VerifySuballocation().
Type
SuballocationType vpr::Suballocation::Type { SuballocationType::Unknown }
Definition at line 28 of file Suballocation.hpp.
Referenced by vpr::MemoryBlock::freeSuballocation(), vpr::MemoryBlock::Validate(), and vpr::MemoryBlock::VerifySuballocation().
The documentation for this struct was generated from the following file:
alloc/src/Suballocation.hpp