VulpesRender: vpr::SwapchainImpl Struct Reference
vpr::SwapchainImpl Struct Reference
Classes
struct SwapchainInfo
SwapchainInfo takes care of hiding away much of the setup work required to create a swapchain.
Public Member Functions
SwapchainImpl (const Device *device, GLFWwindow *window, VkSurfaceKHR surface, uint32_t mode)
~SwapchainImpl ()
void destroy ()
void create ()
void setParameters ()
void setupCreateInfo ()
void setupSwapImages ()
void setupImageViews ()
Public Attributes
struct vpr::SwapchainImpl::SwapchainInfo info
VkFormat colorFormat
uint32_t imageCount
VkColorSpaceKHR colorSpace
VkExtent2D extent
std::vector< VkImage > images
std::vector< VkImageView > imageViews
VkPresentModeKHR presentMode
uint32_t desiredSyncMode
VkSurfaceFormatKHR surfaceFormat
VkSwapchainCreateInfoKHR createInfo
VkSwapchainKHR handle = VK_NULL_HANDLE
VkSwapchainKHR oldHandle = VK_NULL_HANDLE
VkSurfaceKHR surface = VK_NULL_HANDLE
GLFWwindow * window
const Device * device
Detailed Description
Definition at line 21 of file Swapchain.cpp.
Constructor & Destructor Documentation
SwapchainImpl()
vpr::SwapchainImpl::SwapchainImpl (const Device * device, GLFWwindow * window, VkSurfaceKHR surface, uint32_t mode)
Definition at line 67 of file Swapchain.cpp.
References create().
                                                                                                                   :
         info(_device->GetPhysicalDevice().vkHandle(), _surface), desiredSyncMode(mode), surface(_surface), window(_window), device(_device) {
         create();
     }
~SwapchainImpl()
vpr::SwapchainImpl::~SwapchainImpl ()
Definition at line 72 of file Swapchain.cpp.
References destroy().
{
         destroy();
     }
Member Function Documentation
create()
void vpr::SwapchainImpl::create ()
Definition at line 76 of file Swapchain.cpp.
References createInfo, device, handle, setParameters(), setupCreateInfo(), setupImageViews(), setupSwapImages(), VkAssert, and vpr::Device::vkHandle().
Referenced by vpr::Swapchain::Recreate(), and SwapchainImpl().
{
         setParameters();
         setupCreateInfo();
         VkResult result = vkCreateSwapchainKHR(device->vkHandle(), &createInfo, nullptr, &handle);
         VkAssert(result);
         setupSwapImages();
         setupImageViews();
     }
destroy()
void vpr::SwapchainImpl::destroy ()
Definition at line 174 of file Swapchain.cpp.
Referenced by vpr::Swapchain::Destroy(), and ~SwapchainImpl().
{
         for (const auto& view : imageViews) {
             if (view != VK_NULL_HANDLE) {
                 vkDestroyImageView(device->vkHandle(), view, nullptr);
             }
         }
         if (handle != VK_NULL_HANDLE) {
             oldHandle = handle;
             vkDestroySwapchainKHR(device->vkHandle(), handle, nullptr);
         }
         imageViews.clear(); imageViews.shrink_to_fit();
         handle = VK_NULL_HANDLE;
     }
setParameters()
void vpr::SwapchainImpl::setParameters ()
Definition at line 209 of file Swapchain.cpp.
References vpr::getPresentModeStr(), vpr::vertical_sync_mode::None, vpr::vertical_sync_mode::VerticalSync, vpr::vertical_sync_mode::VerticalSyncMailbox, and vpr::vertical_sync_mode::VerticalSyncRelaxed.
Referenced by create().
{
         surfaceFormat = info.GetBestFormat();
         colorFormat = surfaceFormat.format;
         extent = info.ChooseSwapchainExtent(window);
         presentMode = info.GetBestPresentMode();
         VkPresentModeKHR desiredMode = VK_PRESENT_MODE_BEGIN_RANGE_KHR;
         switch (desiredSyncMode) {
         case vertical_sync_mode::None:
             desiredMode = VK_PRESENT_MODE_IMMEDIATE_KHR;
             break;
         case vertical_sync_mode::VerticalSync:
             desiredMode = VK_PRESENT_MODE_FIFO_KHR;
             break;
         case vertical_sync_mode::VerticalSyncRelaxed:
             desiredMode = VK_PRESENT_MODE_FIFO_RELAXED_KHR;
             break;
         case vertical_sync_mode::VerticalSyncMailbox:
             desiredMode = VK_PRESENT_MODE_MAILBOX_KHR;
             break;
         default:
             desiredMode = presentMode;
             break;
         }
         if (desiredMode != presentMode) {
             auto& avail_modes = info.PresentModes;
             auto iter = std::find(std::begin(avail_modes), std::end(avail_modes), desiredMode);
             if (iter == std::cend(avail_modes)) {
                 LOG(WARNING) << "Desired vertical sync mode is " << getPresentModeStr(desiredMode) << "not available on current hardware!";
                 LOG(INFO) << "Falling back to supported present mode " << getPresentModeStr(presentMode);
             }
             else {
                 presentMode = *iter;
             }
         }
         // Create one more image than minspec to implement triple buffering (in hope we got mailbox present mode)
         if (presentMode == VK_PRESENT_MODE_MAILBOX_KHR) {
             imageCount = info.Capabilities.minImageCount + 1;
             if (info.Capabilities.maxImageCount > 0 && imageCount > info.Capabilities.maxImageCount) {
                 imageCount = info.Capabilities.maxImageCount;
             }
         }
         else if (presentMode == VK_PRESENT_MODE_FIFO_KHR || presentMode ==  VK_PRESENT_MODE_FIFO_RELAXED_KHR) {
             imageCount = info.Capabilities.minImageCount + 1;
             if (info.Capabilities.maxImageCount > 0 && imageCount > info.Capabilities.maxImageCount) {
                 imageCount = info.Capabilities.maxImageCount;
             }
         }
         else {
             imageCount = info.Capabilities.minImageCount;
         }
     }
setupCreateInfo()
void vpr::SwapchainImpl::setupCreateInfo ()
Definition at line 266 of file Swapchain.cpp.
References vpr::vk_swapchain_create_info_base.
Referenced by create().
{
         createInfo = vk_swapchain_create_info_base;
         createInfo.surface = surface;
         createInfo.imageFormat = surfaceFormat.format;
         createInfo.imageColorSpace = surfaceFormat.colorSpace;
         colorSpace = surfaceFormat.colorSpace;
         createInfo.imageExtent = extent;
         createInfo.imageArrayLayers = 1;
         createInfo.minImageCount = imageCount;
         createInfo.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
         const uint32_t indices[2] = { static_cast<uint32_t>(device->QueueFamilyIndices.Present), static_cast<uint32_t>(device->QueueFamilyIndices.Graphics) };
         if ((device->QueueFamilyIndices.Present != device->QueueFamilyIndices.Graphics) && (device->QueueFamilyIndices.Present != std::numeric_limits<uint32_t>::max())) {
             createInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
             createInfo.queueFamilyIndexCount = 2;
             createInfo.pQueueFamilyIndices = indices;
         }
         else {
             createInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
             createInfo.queueFamilyIndexCount = 0;
             createInfo.pQueueFamilyIndices = nullptr;
         }
         createInfo.preTransform = info.Capabilities.currentTransform;
         createInfo.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
         createInfo.presentMode = presentMode;
         createInfo.clipped = VK_TRUE;
         createInfo.oldSwapchain = VK_NULL_HANDLE;
     }
setupImageViews()
void vpr::SwapchainImpl::setupImageViews ()
Definition at line 305 of file Swapchain.cpp.
References vpr::vk_image_view_create_info_base, and VkAssert.
Referenced by create().
{
         // Setup image views
         imageViews.resize(imageCount);
         for (uint32_t i = 0; i < imageCount; ++i) {
             VkImageViewCreateInfo iv_info = vk_image_view_create_info_base;
             iv_info.image = images[i];
             iv_info.viewType = VK_IMAGE_VIEW_TYPE_2D;
             iv_info.format = colorFormat;
             iv_info.components = { VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY };
             iv_info.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
             iv_info.subresourceRange.baseMipLevel = 0;
             iv_info.subresourceRange.levelCount = 1;
             iv_info.subresourceRange.baseArrayLayer = 0;
             iv_info.subresourceRange.layerCount = 1;
             VkResult result = vkCreateImageView(device->vkHandle(), &iv_info, nullptr, &imageViews[i]);
             VkAssert(result);
         }
     }
setupSwapImages()
void vpr::SwapchainImpl::setupSwapImages ()
Definition at line 298 of file Swapchain.cpp.
Referenced by create().
{
         // Setup swap images
         vkGetSwapchainImagesKHR(device->vkHandle(), handle, &imageCount, nullptr);
         images.resize(imageCount);
         vkGetSwapchainImagesKHR(device->vkHandle(), handle, &imageCount, images.data());
     }
Member Data Documentation
colorFormat
VkFormat vpr::SwapchainImpl::colorFormat
Definition at line 44 of file Swapchain.cpp.
Referenced by vpr::Swapchain::ColorFormat().
colorSpace
VkColorSpaceKHR vpr::SwapchainImpl::colorSpace
Definition at line 46 of file Swapchain.cpp.
Referenced by vpr::Swapchain::ColorSpace().
createInfo
VkSwapchainCreateInfoKHR vpr::SwapchainImpl::createInfo
Definition at line 59 of file Swapchain.cpp.
Referenced by create().
desiredSyncMode
uint32_t vpr::SwapchainImpl::desiredSyncMode
Definition at line 57 of file Swapchain.cpp.
device
const Device* vpr::SwapchainImpl::device
Definition at line 64 of file Swapchain.cpp.
Referenced by create(), and vpr::Swapchain::Recreate().
extent
VkExtent2D vpr::SwapchainImpl::extent
Definition at line 47 of file Swapchain.cpp.
Referenced by vpr::Swapchain::Extent().
handle
VkSwapchainKHR vpr::SwapchainImpl::handle = VK_NULL_HANDLE
Definition at line 60 of file Swapchain.cpp.
Referenced by create(), and vpr::Swapchain::vkHandle().
imageCount
uint32_t vpr::SwapchainImpl::imageCount
Definition at line 45 of file Swapchain.cpp.
Referenced by vpr::Swapchain::ImageCount(), and vpr::Swapchain::Recreate().
images
std::vector<VkImage> vpr::SwapchainImpl::images
Definition at line 49 of file Swapchain.cpp.
Referenced by vpr::Swapchain::Image().
imageViews
std::vector<VkImageView> vpr::SwapchainImpl::imageViews
Definition at line 50 of file Swapchain.cpp.
Referenced by vpr::Swapchain::ImageView().
oldHandle
VkSwapchainKHR vpr::SwapchainImpl::oldHandle = VK_NULL_HANDLE
Definition at line 61 of file Swapchain.cpp.
presentMode
VkPresentModeKHR vpr::SwapchainImpl::presentMode
Definition at line 56 of file Swapchain.cpp.
surface
VkSurfaceKHR vpr::SwapchainImpl::surface = VK_NULL_HANDLE
Definition at line 62 of file Swapchain.cpp.
Referenced by vpr::Swapchain::Recreate().
surfaceFormat
VkSurfaceFormatKHR vpr::SwapchainImpl::surfaceFormat
Definition at line 58 of file Swapchain.cpp.
window
GLFWwindow* vpr::SwapchainImpl::window
Definition at line 63 of file Swapchain.cpp.
The documentation for this struct was generated from the following file:
core/src/Swapchain.cpp